---
title: "The molecular mechanism of lipid monolayer collapse"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Svetlana Baoukina, Luca Monticelli, H. Jelger Risselada, Siewert J. Marrink, and D. Peter Tieleman"         # Paper authors (required)
year: "2008"           # Publication year (required)
publication: "Proceedings of the National Academy of Sciences"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1073/pnas.0711563105"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Vesicles
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Baoukina, S., Monticelli, L., Risselada, H. J., Marrink, S. J., & Tieleman, D. P. (2008). The molecular mechanism of lipid monolayer collapse. Proceedings of the National Academy of Sciences, 105(31), 10803-10808.

## Abstract

Lipid monolayers at an air–water interface can be compressed laterally and reach high surface density. Beyond a certain threshold, they become unstable and collapse. Lipid monolayer collapse plays an important role in the regulation of surface tension at the air–liquid interface in the lungs. Although the structures of lipid aggregates formed upon collapse can be characterized experimentally, the mechanism leading to these structures is not fully understood. We investigate the molecular mechanism of monolayer collapse using molecular dynamics simulations. Upon lateral compression, the collapse begins with buckling of the monolayer, followed by folding of the buckle into a bilayer in the water phase. Folding leads to an increase in the monolayer surface tension, which reaches the equilibrium spreading value. Immediately after their formation, the bilayer folds have a flat semielliptical shape, in agreement with theoretical predictions. The folds undergo further transformation and form either flat circular bilayers or vesicles. The transformation pathway depends on macroscopic parameters of the system: the bending modulus, the line tension at the monolayer–bilayer connection, and the line tension at the bilayer perimeter. These parameters are determined by the system composition and temperature. Coexistence of the monolayer with lipid aggregates is favorable at lower tensions of the monolayer–bilayer connection. Transformation into a vesicle reduces the energy of the fold perimeter and is facilitated for softer bilayers, e.g., those with a higher content of unsaturated lipids, or at higher temperatures.