---
title: "Structure of Spheroidal HDL Particles Revealed by Combined Atomistic and Coarse-Grained Simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Andrea Catte, James C. Patterson, Denys Bashtovyy, Martin K. Jones, Feifei Gu, Ling Li, Aldo Rampioni, Durba Sengupta, Timo Vuorela, Perttu Niemelä, Mikko Karttunen, Siewert Jan Marrink, Ilpo Vattulainen, and Jere P. Segrest"         # Paper authors (required)
year: "2008"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1529/biophysj.107.115857"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Multi-scale
  - Lipid membranes
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Catte, A., Patterson, J. C., Bashtovyy, D., Jones, M. K., Gu, F., Li, L., ... & Segrest, J. P. (2008). Structure of spheroidal HDL particles revealed by combined atomistic and coarse-grained simulations. Biophysical journal, 94(6), 2306-2319.

## Abstract

Spheroidal high-density lipoprotein (HDL) particles circulating in the blood are formed through an enzymatic process activated by apoA-I, leading to the esterification of cholesterol, which creates a hydrophobic core of cholesteryl ester molecules in the middle of the discoidal phospholipid bilayer. In this study, we investigated the conformation of apoA-I in model spheroidal HDL (ms-HDL) particles using both atomistic and coarse-grained molecular dynamics simulations, which are found to provide consistent results for all HDL properties we studied. The observed small contribution of cholesteryl oleate molecules to the solvent-accessible surface area of the entire ms-HDL particle indicates that palmitoyloleoylphosphatidylcholines and apoA-I molecules cover the hydrophobic core comprised of cholesteryl esters particularly well. The ms-HDL particles are found to form a prolate ellipsoidal shape, with sizes consistent with experimental results. Large rigid domains and low mobility of the protein are seen in all the simulations. Additionally, the average number of contacts of cholesteryl ester molecules with apoA-I residues indicates that cholesteryl esters interact with protein residues mainly through their cholesterol moiety. We propose that the interaction of annular cholesteryl oleate molecules contributes to apoA-I rigidity stabilizing and regulating the structure and function of the ms-HDL particle.