---
title: "Cholesterol Shows Preference for the Interior of Polyunsaturated Lipid Membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Siewert J. Marrink, Alex H. de Vries, Thad. A. Harroun, John Katsaras, and Stephen R. Wassall"         # Paper authors (required)
year: "2008"           # Publication year (required)
publication: "Journal of the American Chemical Society"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/ja076641c"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Sterols
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Marrink, S. J., de Vries, A. H., Harroun, T. A., Katsaras, J., & Wassall, S. R. (2008). Cholesterol shows preference for the interior of polyunsaturated lipid membranes. Journal of the American chemical society, 130(1), 10-11.

## Abstract

Recent neutron scattering experiments showed a striking manifestation of the aversion between polyunsaturated fatty acid (PUFA)-containing lipids and cholesterol. Selectively deuterated cholesterol/ 1,2-diarachidonylphosphatidylcholine (DAPC) samples revealed that the hydroxyl of the sterol resides at the center of the bilayer. Here we use a recently parametrized coarse grain simulation model to shed light on these puzzling experimental observations. Using a simulation setup in close correspondence to the experimental conditions, we reproduce the experimental neutron scattering profiles to a large extent. The simulations allow us to analyze the behavior of cholesterol in detail; we show that the interaction of cholesterol with the PUFA chains of DAPC leads to a fast flip-flop rate for the sterol and an increased preference of the sterol for the unusual location embedded between the monolayer leaflets.