---
title: "The molecular face of lipid rafts in model membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "H. Jelger Risselada and Siewert J. Marrink"         # Paper authors (required)
year: "2008"           # Publication year (required)
publication: "Proceedings of the National Academy of Sciences"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1073/pnas.0807527105"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Sterols
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Risselada, H. J., & Marrink, S. J. (2008). The molecular face of lipid rafts in model membranes. Proceedings of the National Academy of Sciences, 105(45), 17367-17372.

## Abstract

Cell membranes contain a large number of different lipid species. Such a multicomponent mixture exhibits a complex phase behavior with regions of structural and compositional heterogeneity. Especially domains formed in ternary mixtures, composed of saturated and unsaturated lipids together with cholesterol, have received a lot of attention as they may resemble raft formation in real cells. Here we apply a simulation model to assess the molecular nature of these domains at the nanoscale, information that has thus far eluded experimental determination. We are able to show the spontaneous separation of a saturated phosphatidylcholine (PC)/unsaturated PC/cholesterol mixture into a liquid-ordered and a liquid-disordered phase with structural and dynamic properties closely matching experimental data. The near-atomic resolution of the simulations reveals remarkable features of both domains and the boundary domain interface. Furthermore, we predict the existence of a small surface tension between the monolayer leaflets that drives registration of the domains. At the level of molecular detail, raft-like lipid mixtures show a surprising face with possible implications for many cell membrane processes.