---
title: "Application of Mean Field Boundary Potentials in Simulations of Lipid Vesicles"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "H. Jelger Risselada, Alan E. Mark, and Siewert J. Marrink"         # Paper authors (required)
year: "2008"           # Publication year (required)
publication: "The Journal of Physical Chemistry B"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jp0758519"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Vesicles
  - Enhanced sampling
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Risselada, H. J., Mark, A. E., & Marrink, S. J. (2008). Application of mean field boundary potentials in simulations of lipid vesicles. The Journal of Physical Chemistry B, 112(25), 7438-7447.

## Abstract

A method is presented to enhance the efficiency of simulations of lipid vesicles. The method increases computational speed by eliminating water molecules that either surround the vesicle or reside in the interior of the vesicle, without altering the properties of the water at the membrane interface. Specifically, mean field force approximation (MFFA) boundary potentials are used to replace both the internal and external excess bulk solvent. In addition to reducing the cost of simulating preformed vesicles, the molding effect of the boundary potentials also enhances the formation and equilibration of vesicles from random solutions of lipid in water. Vesicles with diameters in the range from 20 to 60 nm were obtained on a nanosecond time scale, without any noticeable effect of the boundary potentials on their structure.