---
title: "Gating Motions in Voltage-Gated Potassium Channels Revealed by Coarse-Grained Molecular Dynamics Simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Werner Treptow, Siewert-J Marrink, and Mounir Tarek"         # Paper authors (required)
year: "2008"           # Publication year (required)
publication: "The Journal of Physical Chemistry B"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jp709675e"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Treptow, W., Marrink, S. J., & Tarek, M. (2008). Gating motions in voltage-gated potassium channels revealed by coarse-grained molecular dynamics simulations. The Journal of Physical Chemistry B, 112(11), 3277-3282.

## Abstract

Voltage-gated potassium (Kv) channels are ubiquitous transmembrane proteins involved in electric signaling of excitable tissues. A fundamental property of these channels is the ability to open or close in response to changes in the membrane potential. To date, their structure-based activation mechanism remains unclear, and there is a large controversy on how these gates function at the molecular level, in particular, how movements of the voltage sensor domain are coupled to channel gating. So far, all mechanisms proposed for this coupling are based on the crystal structure of the open voltage-gated Kv1.2 channel and structural models of the closed form based on electrophysiology experiments. Here, we use coarse-grain (CG) molecular dynamics simulations that allow conformational changes from the open to the closed form of the channel (embedded in its membrane environment) to be followed. Despite the low specificity of the CG force field, the obtained closed structure satisfies several experimental constraints. The overall results suggest a gating mechanism in which a lateral displacement the S4−S5 linker leads to a closing of the gate. Only a small up−down movement of the S4 helices is noticed. Additionally, the study suggests a peculiar upward motion of the intracellular tetramerization domain of the channel, hence providing a molecular view on how this domain may further regulate conduction in Kv channels.