---
title: "Mechanosensitive Membrane Channels in Action"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Serge Yefimov, Erik van der Giessen, Patrick R. Onck, and Siewert J. Marrink"         # Paper authors (required)
year: "2008"           # Publication year (required)
publication: "Biophysical Journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1529/biophysj.107.119966"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Solvents
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Yefimov, S., Van der Giessen, E., Onck, P. R., & Marrink, S. J. (2008). Mechanosensitive membrane channels in action. Biophysical journal, 94(8), 2994-3002.

## Abstract

The tension-driven gating process of MscL from Mycobacterium tuberculosis, Tb-MscL, has been addressed at near-atomic detail using coarse-grained molecular dynamics simulations. To perform the simulations, a novel coarse-grained peptide model based on a thermodynamic parameterization of the amino-acid side chains has been applied. Both the wild-type Tb-MscL and its gain-of-function mutant V21D embedded in a solvated lipid bilayer have been studied. To mimic hypoosmotic shock conditions, simulations were performed at increasing levels of membrane tension approaching the rupture threshold of the lipid bilayer. Both the wild-type and the mutant channel are found to undergo significant conformational changes in accordance with an irislike expansion mechanism, reaching a conducting state on a microsecond timescale. The most pronounced expansion of the pore has been observed for the V21D mutant, which is consistent with the experimentally shown gain-of-function phenotype of the V21D mutant.