---
title: <i class="fa-solid fa-cheese"></i> Lipidome
format: html
---

Available Martini lipid topologies are listed below according to their major category. Additional information for each lipid, other topologies (e.g. Dry Martini, alternative, old), and supporting files can be found on the subpage of each lipid. Collections of lipid topologies can be found at the bottom of this page for ease of download. For explanation of the lipid naming schema and the Martini lipid parameterization philosophy see the [Martini lipid details](http://cgmartini.nl/index.php/force-field-parameters/lipids2/350-lipid-details) page. For further background reading on the Martini lipidome, see:

- T.A. Wassenaar, H.I. Ingólfsson, R.A. Böckmann, D.P. Tieleman, S.J. Marrink. Computational lipidomics with insane: a versatile tool for generating custom membranes for molecular simulations. JCTC, 11:2144–2155, 2015. [abstract](http://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b00209)

If you have developed additional Martini lipid topologies and would like to post them here please contact Siewert J. Marrink [s.j.marrink@rug.nl](mailto: s.j.marrink@rug.nl) or Helgi I. Ingolfsson [h.i.ingolfsson@rug.nl](mailto: h.i.ingolfsson@rug.nl).

### Phosphatidylcholine (PC)
<hr>

|       |                                       |        |
|-------|---------------------------------------|--------|
|[DTPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DTPC)  |	di-C08:0-C10:0 PC (DTPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DTPC/martini_v2.0_DTPC_01.itp)   |
|[DLPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DLPC)  |	di-C12:0-C14:0 PC (DLPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DLPC/martini_v2.0_DLPC_01.itp)   |
|[DPPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DPPC)  |	di-C16:0-C18:0 PC (DPPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DPPC/martini_v2.0_DPPC_01.itp)   |
|[DBPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DBPC)  |	di-C20:0-C22:0 PC (DBPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DBPC/martini_v2.0_DBPC_01.itp)   |
|[DXPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DXPC)  |	di-C24:0-C26:0 PC (DXPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DXPC/martini_v2.0_DXPC_01.itp)   |
|[DYPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DYPC)  |	di-C12:1-C14:1 PC (DYPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DYPC/martini_v2.0_DYPC_01.itp)   |
|[DVPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DVPC)  |	di-C16:1-C18:1 PC (DVPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DVPC/martini_v2.0_DVPC_01.itp)   |
|[DOPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DOPC)  |	di-C16:1-C18:1 PC (DOPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DOPC/martini_v2.0_DOPC_02.itp)   |
|[DIPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DIPC)  |	di-C16:2-C18:2 PC (DIPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DIPC/martini_v2.0_DIPC_01.itp)   |
|[DFPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DFPC)  |	di-C16:3-C18:3 PC (DFPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DFPC/martini_v2.0_DFPC_01.itp)   |
|[DGPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DGPC)  |	di-C20:1-C22:1 PC (DGPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DGPC/martini_v2.0_DGPC_01.itp)   |
|[DAPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DAPC)  |	di-C20:4-C22:5 PC (DAPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DAPC/martini_v2.0_DAPC_02.itp)   |
|[DRPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DRPC)  |	di-C24:6-C26:6 PC (DRPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DRPC/martini_v2.0_DRPC_01.itp)   |
|[DNPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=DNPC)  |	di-C24:1-C26:1 PC (DNPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/DNPC/martini_v2.0_DNPC_01.itp)   |
|[LPPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=LPPC)  |	C12:0/16:0 PC (LPPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/LPPC/martini_v2.0_LPPC_01.itp)   |
|[POPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=POPC)  |	C16:0/18:1 PC (POPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/POPC/martini_v2.0_POPC_02.itp)   |
|[PGPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=PGPC)  |	C16:0/20:1 PC (PGPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/PGPC/martini_v2.0_PGPC_01.itp)   |
|[PEPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=PEPC)  |	C16:0/20:2 PC (PEPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/PEPC/martini_v2.0_PEPC_01.itp)   |
|[PIPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=PIPC)  |	C16:0/18:2 PC (PIPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/PIPC/martini_v2.0_PIPC_01.itp)   |
|[PAPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=PAPC)  |	C16:0/20:4 PC (PAPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/PAPC/martini_v2.0_PAPC_01.itp)   |
|[PUPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=PUPC)  |	C16:0/22:6 PC (PUPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/PUPC/martini_v2.0_PUPC_01.itp)   |
|[PRPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PC&lipid=PRPC)  |	C16:0/24:6 PC (PRPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PC/PRPC/martini_v2.0_PRPC_01.itp)   |

### Phosphatidylethanolamine (PE)
<hr>

|       |                                       |        |
|-------|---------------------------------------|--------|
|[DTPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DTPE)  |	di-C08:0-C10:0 PE (DTPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DTPE/martini_v2.0_DTPE_01.itp)   |
|[DLPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DLPE)  |	di-C12:0-C14:0 PE (DLPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DLPE/martini_v2.0_DLPE_01.itp)   |
|[DPPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DPPE)  |	di-C16:0-C18:0 PE (DPPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DPPE/martini_v2.0_DPPE_01.itp)   |
|[DBPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DBPE)  |	di-C20:0-C22:0 PE (DBPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DBPE/martini_v2.0_DBPE_01.itp)   |
|[DXPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DXPE)  |	di-C24:0-C26:0 PE (DXPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DXPE/martini_v2.0_DXPE_01.itp)   |
|[DYPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DYPE)  |	di-C12:1-C14:1 PE (DYPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DYPE/martini_v2.0_DYPE_01.itp)   |
|[DVPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DVPE)  |	di-C16:1-C18:1 PE (DVPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DVPE/martini_v2.0_DVPE_01.itp)   |
|[DOPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DOPE)  |	di-C16:1-C18:1 PE (DOPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DOPE/martini_v2.0_DOPE_02.itp)   |
|[DIPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DIPE)  |	di-C16:2-C18:2 PE (DIPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DIPE/martini_v2.0_DIPE_01.itp)   |
|[DFPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DFPE)  |	di-C16:3-C18:3 PE (DFPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DFPE/martini_v2.0_DFPE_01.itp)   |
|[DGPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DGPE)  |	di-C20:1-C22:1 PE (DGPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DGPE/martini_v2.0_DGPE_01.itp)   |
|[DAPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DAPE)  |	di-C20:4-C22:5 PE (DAPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DAPE/martini_v2.0_DAPE_01.itp)   |
|[DUPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DUPE)  |	di-C20:5-C22:6 PE (DUPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DUPE/martini_v2.0_DUPE_01.itp)   |
|[DRPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DRPE)  |	di-C24:6-C26:6 PE (DRPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DRPE/martini_v2.0_DRPE_01.itp)   |
|[DNPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=DNPE)  |	di-C24:1-C26:1 PE (DNPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/DNPE/martini_v2.0_DNPE_01.itp)   |
|[LPPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=LPPE)  |	C12:0/16:0 PE (LPPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/LPPE/martini_v2.0_LPPE_01.itp)   |
|[POPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=POPE)  |	C16:0/18:1 PE (POPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/POPE/martini_v2.0_POPE_02.itp)   |
|[PGPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=PGPE)  |	C16:0/20:1 PE (PGPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/PGPE/martini_v2.0_PGPE_01.itp)   |
|[PQPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=PQPE)  |	C16:0/20:3 PE (PQPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/PQPE/martini_v2.0_PQPE_01.itp)   |
|[PIPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=PIPE)  |	C16:0/18:2 PE (PIPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/PIPE/martini_v2.0_PIPE_01.itp)   |
|[PAPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=PAPE)  |	C16:0/20:4 PE (PAPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/PAPE/martini_v2.0_PAPE_01.itp)   |
|[PUPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=PUPE)  |	C16:0/22:6 PE (PUPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/PUPE/martini_v2.0_PUPE_01.itp)   |
|[PRPE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PE&lipid=PRPE)  |	C16:0/24:6 PE (PRPE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PE/PRPE/martini_v2.0_PRPE_01.itp)   |

### Phosphatidylserine (PS)
<hr>

|       |                                       |        |
|-------|---------------------------------------|--------|
|[DTPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DTPS)  | di-C08:0-C10:0 PS (DTPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DTPS/martini_v2.0_DTPS_01.itp)   |
|[DLPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DLPS)  | di-C12:0-C14:0 PS (DLPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DLPS/martini_v2.0_DLPS_01.itp)   |
|[DPPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DPPS)  | di-C16:0-C18:0 PS (DPPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DPPS/martini_v2.0_DPPS_01.itp)   |
|[DBPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DBPS)  | di-C20:0-C22:0 PS (DBPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DBPS/martini_v2.0_DBPS_01.itp)   |
|[DXPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DXPS)  | di-C24:0-C26:0 PS (DXPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DXPS/martini_v2.0_DXPS_01.itp)   |
|[DYPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DYPS)  | di-C12:1-C14:1 PS (DYPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DYPS/martini_v2.0_DYPS_01.itp)   |
|[DVPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DVPS)  | di-C16:1-C18:1 PS (DVPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DVPS/martini_v2.0_DVPS_01.itp)   |
|[DOPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DOPS)  | di-C16:1-C18:1 PS (DOPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DOPS/martini_v2.0_DOPS_02.itp)   |
|[DIPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DIPS)  | di-C16:2-C18:2 PS (DIPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DIPS/martini_v2.0_DIPS_01.itp)   |
|[DFPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DFPS)  | di-C16:3-C18:3 PS (DFPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DFPS/martini_v2.0_DFPS_01.itp)   |
|[DGPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DGPS)  | di-C20:1-C22:1 PS (DGPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DGPS/martini_v2.0_DGPS_01.itp)   |
|[DAPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DAPS)  | di-C20:4-C22:5 PS (DAPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DAPS/martini_v2.0_DAPS_01.itp)   |
|[DUPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DUPS)  | di-C20:5-C22:6 PS (DUPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DUPS/martini_v2.0_DUPS_01.itp)   |
|[DRPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DRPS)  | di-C24:6-C26:6 PS (DRPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DRPS/martini_v2.0_DRPS_01.itp)   |
|[DNPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=DNPS)  | di-C24:1-C26:1 PS (DNPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/DNPS/martini_v2.0_DNPS_01.itp)   |
|[LPPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=LPPS)  | C12:0/16:0 PS (LPPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/LPPS/martini_v2.0_LPPS_01.itp)   |
|[POPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=POPS)  | C16:0/18:1 PS (POPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/POPS/martini_v2.0_POPS_02.itp)   |
|[PGPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=PGPS)  | C16:0/20:1 PS (PGPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/PGPS/martini_v2.0_PGPS_01.itp)   |
|[PQPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=PQPS)  | C16:0/20:3 PS (PQPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/PQPS/martini_v2.0_PQPS_01.itp)   |
|[PIPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=PIPS)  | C16:0/18:2 PS (PIPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/PIPS/martini_v2.0_PIPS_01.itp)   |
|[PAPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=PAPS)  | C16:0/20:4 PS (PAPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/PAPS/martini_v2.0_PAPS_01.itp)   |
|[PUPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=PUPS)  | C16:0/22:6 PS (PUPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/PUPS/martini_v2.0_PUPS_01.itp)   |
|[PRPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PS&lipid=PRPS)  | C16:0/24:6 PS (PRPS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PS/PRPS/martini_v2.0_PRPS_01.itp)   |


### Phosphatidylglycerol (PG)
<hr>

|       |                                       |        |
|-------|---------------------------------------|--------|
|[DTPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DTPG)  | di-C08:0-C10:0 PG (DTPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DTPG/martini_v2.0_DTPG_01.itp)   |
|[DLPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DLPG)  | di-C12:0-C14:0 PG (DLPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DLPG/martini_v2.0_DLPG_01.itp)   |
|[DPPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DPPG)  | di-C16:0-C18:0 PG (DPPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DPPG/martini_v2.0_DPPG_01.itp)   |
|[DBPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DBPG)  | di-C20:0-C22:0 PG (DBPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DBPG/martini_v2.0_DBPG_01.itp)   |
|[DXPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DXPG)  | di-C24:0-C26:0 PG (DXPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DXPG/martini_v2.0_DXPG_01.itp)   |
|[DYPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DYPG)  | di-C12:1-C14:1 PG (DYPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DYPG/martini_v2.0_DYPG_01.itp)   |
|[DVPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DVPG)  | di-C16:1-C18:1 PG (DVPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DVPG/martini_v2.0_DVPG_01.itp)   |
|[DOPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DOPG)  | di-C16:1-C18:1 PG (DOPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DOPG/martini_v2.0_DOPG_02.itp)   |
|[DIPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DIPG)  | di-C16:2-C18:2 PG (DIPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DIPG/martini_v2.0_DIPG_01.itp)   |
|[DFPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DFPG)  | di-C16:3-C18:3 PG (DFPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DFPG/martini_v2.0_DFPG_01.itp)   |
|[DGPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DGPG)  | di-C20:1-C22:1 PG (DGPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DGPG/martini_v2.0_DGPG_01.itp)   |
|[DAPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DAPG)  | di-C20:4-C22:5 PG (DAPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DAPG/martini_v2.0_DAPG_01.itp)   |
|[DRPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DRPG)  | di-C24:6-C26:6 PG (DRPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DRPG/martini_v2.0_DRPG_01.itp)   |
|[DNPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=DNPG)  | di-C24:1-C26:1 PG (DNPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/DNPG/martini_v2.0_DNPG_01.itp)   |
|[LPPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=LPPG)  | C12:0/16:0 PG (LPPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/LPPG/martini_v2.0_LPPG_01.itp)   |
|[POPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=POPG)  | C16:0/18:1 PG (POPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/POPG/martini_v2.0_POPG_02.itp)   |
|[PGPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=PGPG)  | C16:0/20:1 PG (PGPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/PGPG/martini_v2.0_PGPG_01.itp)   |
|[PIPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=PIPG)  | C16:0/18:2 PG (PIPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/PIPG/martini_v2.0_PIPG_01.itp)   |
|[PAPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=PAPG)  | C16:0/20:4 PG (PAPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/PAPG/martini_v2.0_PAPG_01.itp)   |
|[PRPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=PRPG)  | C16:0/24:6 PG (PRPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/PRPG/martini_v2.0_PRPG_01.itp)   |
|[OPPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=OPPG)  | C18:1/16:0 PG (OPPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/OPPG/martini_v2.0_OPPG_01.itp)   |
|[JPPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=JPPG)  | C16:1(3t)/16:0 PG (JPPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/JPPG/martini_v2.0_JPPG_01.itp)   |
|[JFPG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PG&lipid=JFPG)  | C16:1(3t)/18:3 PG (JFPG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PG/JFPG/martini_v2.0_JFPG_01.itp)   |

### Phosphatidic acid (PA)
<hr>

|       |                                       |        |
|-------|---------------------------------------|--------|
|[DTPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DTPA)  | di-C08:0-C10:0 PA (DTPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DTPA/martini_v2.0_DTPA_01.itp)   |
|[DLPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DLPA)  | di-C12:0-C14:0 PA (DLPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DLPA/martini_v2.0_DLPA_01.itp)   |
|[DPPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DPPA)  | di-C16:0-C18:0 PA (DPPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DPPA/martini_v2.0_DPPA_01.itp)   |
|[DBPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DBPA)  | di-C20:0-C22:0 PA (DBPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DBPA/martini_v2.0_DBPA_01.itp)   |
|[DXPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DXPA)  | di-C24:0-C26:0 PA (DXPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DXPA/martini_v2.0_DXPA_01.itp)   |
|[DYPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DYPA)  | di-C12:1-C14:1 PA (DYPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DYPA/martini_v2.0_DYPA_01.itp)   |
|[DVPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DVPA)  | di-C16:1-C18:1 PA (DVPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DVPA/martini_v2.0_DVPA_01.itp)   |
|[DOPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DOPA)  | di-C16:1-C18:1 PA (DOPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DOPA/martini_v2.0_DOPA_01.itp)   |
|[DIPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DIPA)  | di-C16:2-C18:2 PA (DIPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DIPA/martini_v2.0_DIPA_01.itp)   |
|[DFPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DFPA)  | di-C16:3-C18:3 PA (DFPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DFPA/martini_v2.0_DFPA_01.itp)   |
|[DGPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DGPA)  | di-C20:1-C22:1 PA (DGPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DGPA/martini_v2.0_DGPA_01.itp)   |
|[DAPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DAPA)  | di-C20:4-C22:5 PA (DAPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DAPA/martini_v2.0_DAPA_01.itp)   |
|[DRPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DRPA)  | di-C24:6-C26:6 PA (DRPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DRPA/martini_v2.0_DRPA_01.itp)   |
|[DNPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=DNPA)  | di-C24:1-C26:1 PA (DNPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/DNPA/martini_v2.0_DNPA_01.itp)   |
|[LPPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=LPPA)  | C12:0/16:0 PA (LPPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/LPPA/martini_v2.0_LPPA_01.itp)   |
|[POPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=POPA)  | C16:0/18:1 PA (POPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/POPA/martini_v2.0_POPA_01.itp)   |
|[PGPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=PGPA)  | C16:0/20:1 PA (PGPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/PGPA/martini_v2.0_PGPA_01.itp)   |
|[PIPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=PIPA)  | C16:0/18:2 PA (PIPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/PIPA/martini_v2.0_PIPA_01.itp)   |
|[PAPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=PAPA)  | C16:0/20:4 PA (PAPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/PAPA/martini_v2.0_PAPA_01.itp)   |
|[PUPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=PUPA)  | C16:0/22:6 PA (PUPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/PUPA/martini_v2.0_PUPA_01.itp)   |
|[PRPA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=PA&lipid=PRPA)  | C16:0/24:6 PA (PRPA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/PA/PRPA/martini_v2.0_PRPA_01.itp)   |

### Phosphatidylinositols
<hr>

#### Phosphatidylinositol (PI)
|       |                                       |        |
|-------|---------------------------------------|--------|
|[DPPI](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=DPPI)  | di-C16:0-C18:0 PI (DPPI)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/DPPI/martini_v2.0_DPPI_01.itp)   |
|[PVPI](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=PVPI)  | C16:0/18:1 (PVPI)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/PVPI/martini_v2.0_PVPI_01.itp)   |
|[POPI](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=POPI)  | C16:0/18:1 PI (POPI)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/POPI/martini_v2.0_POPI_01.itp)   |
|[PIPI](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=PIPI)  | C16:0/18:2 PI (PIPI)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/PIPI/martini_v2.0_PIPI_01.itp)   |
|[PAPI](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=PAPI)  | C16:0/20:4 PI (PAPI)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/PAPI/martini_v2.0_PAPI_01.itp)   |
|[PUPI](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=PUPI)  | C16:0/22:6 PI (PUPI)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/PUPI/martini_v2.0_PUPI_01.itp)   |


#### Phosphatidylinositol phosphate (PIP1)
|       |                                       |        |
|-------|---------------------------------------|--------|
|[DPP1](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=DPP1)  | di-C16:0-C18:0 PIP (DPP1)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/DPP1/martini_v2.0_DPP1_01.itp)   |
|[PVP1](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=PVP1)  | C16:0/18:1 PIP (PVP1)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/PVP1/martini_v2.0_PVP1_01.itp)   |
|[POP1](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=POP1)  | C16:0/18:1 PIP (POP1)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/POP1/martini_v2.0_POP1_01.itp)   |


#### Phosphatidylinositol bisphosphate (PIP2)
|       |                                       |        |
|-------|---------------------------------------|--------|
|[DPP2](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=DPP2)  | di-C16:0-C18:0 PIP2 (DPP2)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/DPP2/martini_v2.0_DPP2_01.itp)   |
|[PVP2](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=PVP2)  | C16:0/18:1 PIP2 (PVP2)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/PVP2/martini_v2.0_PVP2_01.itp)   |
|[POP2](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=POP2)  | C16:0/18:1 PIP2 (POP2)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/POP2/martini_v2.0_POP2_01.itp)   |


#### Phosphatidylinositol trisphosphate (PIP3)
|       |                                       |        |
|-------|---------------------------------------|--------|
|[PVP3](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=PVP3)  | C16:0/18:1 PIP3 (PVP3)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/PVP3/martini_v2.0_PVP3_01.itp)   |
|[POP3](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Phosphatidylinositols&lipid=POP3)  | C16:0/18:1 PIP3 (POP3)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Phosphatidylinositols/POP3/martini_v2.0_POP3_01.itp)   |


### Glycerols
<hr>

#### Diacylglycerol (DAG)
|       |                                       |        |
|-------|---------------------------------------|--------|
|[PVDG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycerols&lipid=PVDG)  | C16:0/18:1 DAG (PVDG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycerols/PVDG/martini_v2.0_PVDG_01.itp)   |
|[PODG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycerols&lipid=PODG)  | C16:0/18:1 DAG (PODG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycerols/PODG/martini_v2.0_PODG_01.itp)   |
|[PIDG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycerols&lipid=PIDG)  | C16:0/18:2 DAG (PIDG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycerols/PIDG/martini_v2.0_PIDG_01.itp)   |
|[PADG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycerols&lipid=PADG)  | C16:0/20:4 DAG (PADG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycerols/PADG/martini_v2.0_PADG_01.itp)   |
|[PUDG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycerols&lipid=PUDG)  | C16:0/22:6 DAG (PUDG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycerols/PUDG/martini_v2.0_PUDG_01.itp)   |

#### Triacylglycerol (TAG)
|       |                                       |        |
|-------|---------------------------------------|--------|
|[TOG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycerols&lipid=TOG)  | Glyceryl trioleate	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycerols/TOG/martini_v2.0_TOG_01.itp)   |


### Lysophosphatidylcholine (LPC)
<hr>

|       |                                       |        |
|-------|---------------------------------------|--------|
|[CPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=LPC&lipid=CPC)  | C04:0-C06:0 LPC (CPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/LPC/CPC/martini_v2.0_CPC_01.itp)   |
|[TPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=LPC&lipid=TPC)  | C08:0-C10:0 LPC (TPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/LPC/TPC/martini_v2.0_TPC_01.itp)   |
|[LPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=LPC&lipid=LPC)  | C12:0-C14:0 LPC (LPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/LPC/LPC/martini_v2.0_LPC_01.itp)   |
|[PPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=LPC&lipid=PPC)  | C16:0-C18:0 LPC (PPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/LPC/PPC/martini_v2.0_PPC_02.itp)   |
|[VPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=LPC&lipid=VPC)  | C16:1-C18:1 LPC (VPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/LPC/VPC/martini_v2.0_VPC_01.itp)   |
|[OPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=LPC&lipid=OPC)  | C16:1-C18:1 LPC (OPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/LPC/OPC/martini_v2.0_OPC_01.itp)   |
|[IPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=LPC&lipid=IPC)  | C16:2-C18:2 LPC (IPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/LPC/IPC/martini_v2.0_IPC_01.itp)   |
|[APC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=LPC&lipid=APC)  | C20:4-C22:5 LPC (APC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/LPC/APC/martini_v2.0_APC_01.itp)   |
|[UPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=LPC&lipid=UPC)  | C20:5-C22:6 LPC (UPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/LPC/UPC/martini_v2.0_UPC_01.itp)   |


### Sphingomyelin (SM)
<hr>

|       |                                       |        |
|-------|---------------------------------------|--------|
|[DPSM](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=SM&lipid=DPSM)  | C(d18:1/18:0) SM (DPSM)	|  [itp](http://cgmartini.nl/images/parameters/lipids/SM/DPSM/martini_v2.0_DPSM_01.itp)   |
|[DBSM](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=SM&lipid=DBSM)  | C(d20:1/20:0) SM (DBSM)	|  [itp](http://cgmartini.nl/images/parameters/lipids/SM/DBSM/martini_v2.0_DBSM_01.itp)   |
|[DXSM](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=SM&lipid=DXSM)  | C(d24:1/24:0) SM (DXSM)	|  [itp](http://cgmartini.nl/images/parameters/lipids/SM/DXSM/martini_v2.0_DXSM_01.itp)   |
|[PVSM](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=SM&lipid=PVSM)  | C(d18:1/18:1) SM (PVSM)	|  [itp](http://cgmartini.nl/images/parameters/lipids/SM/PVSM/martini_v2.0_PVSM_01.itp)   |
|[POSM](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=SM&lipid=POSM)  | C(d18:1/18:1) SM (POSM)	|  [itp](http://cgmartini.nl/images/parameters/lipids/SM/POSM/martini_v2.0_POSM_01.itp)   |
|[PGSM](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=SM&lipid=PGSM)  | C(d18:1/22:1) SM (PGSM)	|  [itp](http://cgmartini.nl/images/parameters/lipids/SM/PGSM/martini_v2.0_PGSM_01.itp)   |
|[PNSM](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=SM&lipid=PNSM)  | C(d18:1/24:1) SM (PNSM)	|  [itp](http://cgmartini.nl/images/parameters/lipids/SM/PNSM/martini_v2.0_PNSM_01.itp)   |
|[BNSM](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=SM&lipid=BNSM)  | C(d20:1/24:1) SM (BNSM)	|  [itp](http://cgmartini.nl/images/parameters/lipids/SM/BNSM/martini_v2.0_BNSM_01.itp)   |
|[XNSM](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=SM&lipid=XNSM)  | C(d24:1/24:1) SM (XNSM)	|  [itp](http://cgmartini.nl/images/parameters/lipids/SM/XNSM/martini_v2.0_XNSM_01.itp)   |


### Ceramide (CER)
<hr>

|       |                                       |        |
|-------|---------------------------------------|--------|
|[DPCE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=CER&lipid=DPCE)  | C(d18:1/18:0) CER (DPCE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/CER/DPCE/martini_v2.0_DPCE_01.itp)   |
|[DXCE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=CER&lipid=DXCE)  | C(d24:1/24:0) CER (DXCE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/CER/DXCE/martini_v2.0_DXCE_01.itp)   |
|[PNCE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=CER&lipid=PNCE)  | C(d18:1/24:1) CER (PNCE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/CER/PNCE/martini_v2.0_PNCE_01.itp)   |
|[XNCE](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=CER&lipid=XNCE)  | C(d24:1/24:1) CER (XNCE)	|  [itp](http://cgmartini.nl/images/parameters/lipids/CER/XNCE/martini_v2.0_XNCE_01.itp)   |


### Glycosphingolipids
<hr>

#### Glucosylceramide (GS)
|       |                                       |        |
|-------|---------------------------------------|--------|
|[DPGS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycosphingolipids&lipid=DPGS)  | C(d16:1/16:0) GS (DPGS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycosphingolipids/DPGS/martini_v2.0_DPGS_01.itp)   |


#### Monosialotetrahexosylganglioside (GM1)
|       |                                       |        |
|-------|---------------------------------------|--------|
|[DPG1](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycosphingolipids&lipid=DPG1)  | C(d18:1/18:0) GM1 (DPG1)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycosphingolipids/DPG1/martini_v2.0_DPG1_02.itp)   |
|[DBG1](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycosphingolipids&lipid=DBG1)  | C(d20:1/20:0) GM1 (DBG1)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycosphingolipids/DBG1/martini_v2.0_DBG1_02.itp)   |
|[DXG1](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycosphingolipids&lipid=DXG1)  | C(d24:1/24:0) GM1 (DXG1)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycosphingolipids/DXG1/martini_v2.0_DXG1_02.itp)   |
|[PNG1](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycosphingolipids&lipid=PNG1)  | C(d18:1/24:1) GM1 (PNG1)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycosphingolipids/PNG1/martini_v2.0_PNG1_02.itp)   |
|[XNG1](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycosphingolipids&lipid=XNG1)  | C(d24:1/24:1) GM1 (XNG1)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycosphingolipids/XNG1/martini_v2.0_XNG1_02.itp)   |


#### Monosialodihexosylganglioside (GM3)
|       |                                       |        |
|-------|---------------------------------------|--------|
|[DPG3](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycosphingolipids&lipid=DPG3)  | C(d18:1/18:0) GM3 (DPG3)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycosphingolipids/DPG3/martini_v2.0_DPG3_02.itp)   |
|[DBG3](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycosphingolipids&lipid=DBG3)  | C(d20:1/20:0) GM3 (DBG3)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycosphingolipids/DBG3/martini_v2.0_DBG3_02.itp)   |
|[DXG3](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycosphingolipids&lipid=DXG3)  | C(d24:1/24:0) GM3 (DXG3)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycosphingolipids/DXG3/martini_v2.0_DXG3_02.itp)   |
|[PNG3](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycosphingolipids&lipid=PNG3)  | C(d18:1/24:1) GM3 (PNG3)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycosphingolipids/PNG3/martini_v2.0_PNG3_02.itp)   |
|[XNG3](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycosphingolipids&lipid=XNG3)  | C(d24:1/24:1) GM3 (XNG3)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycosphingolipids/XNG3/martini_v2.0_XNG3_02.itp)   |


### Glycoglycerolipids
<hr>

#### Glucosylceramide (GS)
|       |                                       |        |
|-------|---------------------------------------|--------|
|[DPMG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycoglycerolipids&lipid=DPMG)  | di-C16:0-C18:0 MGDG (DPMG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycoglycerolipids/DPMG/martini_v2.0_DPMG_02.itp)   |
|[OPMG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycoglycerolipids&lipid=OPMG)  | C18:1/16:0 MGDG (OPMG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycoglycerolipids/OPMG/martini_v2.0_OPMG_01.itp)   |
|[DFMG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycoglycerolipids&lipid=DFMG)  | di-C18:3 MGDG (DFMG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycoglycerolipids/DFMG/martini_v2.0_DFMG_01.itp)   |
|[FPMG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycoglycerolipids&lipid=FPMG)  | C18:3/16:0 MGDG (FPMG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycoglycerolipids/FPMG/martini_v2.0_FPMG_01.itp)   |


#### Sulfoquinovosyl diacylglycerol (SQDG)
|       |                                       |        |
|-------|---------------------------------------|--------|
|[DPSG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycoglycerolipids&lipid=DPSG)  | di-C16:0-C18:0 SQDG (DPSG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycoglycerolipids/DPSG/martini_v2.0_DPSG_03.itp)   |
|[OPSG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycoglycerolipids&lipid=OPSG)  | C18:1/16:0 SQDG (OPSG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycoglycerolipids/OPSG/martini_v2.0_OPSG_01.itp)   |
|[FPSG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycoglycerolipids&lipid=FPSG)  | C18:3/16:0 SQDG (FPSG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycoglycerolipids/FPSG/martini_v2.0_FPSG_01.itp)   |


#### Digalactosyl diacylglycerol (DGDG)
|       |                                       |        |
|-------|---------------------------------------|--------|
|[DPGG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycoglycerolipids&lipid=DPGG)  | di-C16:0-C18:0 DGDG (OPGG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycoglycerolipids/DPGG/martini_v2.0_DPGG_02.itp)   |
|[OPGG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycoglycerolipids&lipid=OPGG)  | C18:1/16:0 DGDG (OPGG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycoglycerolipids/OPGG/martini_v2.0_OPGG_01.itp)   |
|[DFGG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycoglycerolipids&lipid=DFGG)  | di-C18:3 DGDG (DFGG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycoglycerolipids/DFGG/martini_v2.0_DFGG_01.itp)   |
|[FPGG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Glycoglycerolipids&lipid=FPGG)  | C18:3/16:0 DGDG (FPGG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Glycoglycerolipids/FPGG/martini_v2.0_FPGG_01.itp)   |


### Sterols
<hr>

|       |                                       |        |
|-------|---------------------------------------|--------|
|[CHOL](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Sterols&lipid=CHOL)  | cholesterol	|  [itp](http://cgmartini.nl/images/parameters/lipids/Sterols/CHOL/martini_v2.0_CHOL_02.itp)   |
|[CHOA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Sterols&lipid=CHOA)  | cholate	|  [itp](http://cgmartini.nl/images/parameters/lipids/Sterols/CHOA/martini_v2.0_CHOA_02.itp)   |
|[CHYO](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Sterols&lipid=CHYO)  | cholesteryl oleate	|  [itp](http://cgmartini.nl/images/parameters/lipids/Sterols/CHYO/martini_v2.0_CHYO_02.itp)   |
|[ERGO](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Sterols&lipid=ERGO)  | ergosterol	|  [itp](http://cgmartini.nl/images/parameters/lipids/Sterols/ERGO/martini_v2.0_ERGO_01.itp)   |
|[HBHT](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Sterols&lipid=HBHT)  | bacteriohopanetetrol	|  [itp](http://cgmartini.nl/images/parameters/lipids/Sterols/HBHT/martini_v2.0_HBHT_01.itp)   |
|[HDPT](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Sterols&lipid=HDPT)  | diploptene	|  [itp](http://cgmartini.nl/images/parameters/lipids/Sterols/HDPT/martini_v2.0_HDPT_01.itp)   |
|[HHOP](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Sterols&lipid=HHOP)  | hopane	|  [itp](http://cgmartini.nl/images/parameters/lipids/Sterols/HHOP/martini_v2.0_HHOP_01.itp)   |
|[HOPR](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Sterols&lipid=HOPR)  | hopanoid polycyclic group	|  [itp](http://cgmartini.nl/images/parameters/lipids/Sterols/HOPR/martini_v2.0_HOPR_01.itp)   |


### Surfactants
<hr>

|       |                                       |        |
|-------|---------------------------------------|--------|
|[BOG](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Surfactants&lipid=BOG)  | beta-octylglucoside (beta-OG)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Surfactants/BOG/martini_v2.0_BOG_01.itp)   |
|[C12E2](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Surfactants&lipid=C12E2)  | alkyl-PEG C12E2	|  [itp](http://cgmartini.nl/images/parameters/lipids/Surfactants/C12E2/martini_v2.0_C12E2.itp)   |
|[C12E4](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Surfactants&lipid=C12E4)  | alkyl-PEG C12E4	|  [itp](http://cgmartini.nl/images/parameters/lipids/Surfactants/C12E4/martini_v2.0_C12E4.itp)   |
|[C12E6](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Surfactants&lipid=C12E6)  | alkyl-PEG C12E6	|  [itp](http://cgmartini.nl/images/parameters/lipids/Surfactants/C12E6/martini_v2.0_C12E6.itp)   |
|[C12E5_old](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Surfactants&lipid=C12E5_old)  | alkyl-PEG C12E5	|  [itp](http://cgmartini.nl/images/parameters/lipids/Surfactants/C12E5_old/martini_v2.0_EO5_01.itp)   |
|[DDM](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Surfactants&lipid=DDM)  | dodecylmaltoside (DDM)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Surfactants/DDM/martini_v2.0_DDM_01.itp)   |
|[DPC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Surfactants&lipid=DPC)  | dodecylphosphocholine (DPC)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Surfactants/DPC/martini_v2.0_DPC_01.itp)   |
|[SDS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Surfactants&lipid=SDS)  | sodium dodecyl sulfate (SDS)	|  [itp](http://cgmartini.nl/images/parameters/lipids/Surfactants/SDS/martini_v2.0_SDS_01.itp)   |


### Fatty acids (FA)
<hr>

|       |                                       |        |
|-------|---------------------------------------|--------|
|[LCA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=FA&lipid=LCA)  | lauric (C12:0) / myristic (C14:0) acid	|  [itp](http://cgmartini.nl/images/parameters/lipids/FA/LCA/martini_v2.0_LCN_01.itp)   |
|[PCA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=FA&lipid=PCA)  | palmitic (C16:0) / stearic (C18:0)	|  [itp](http://cgmartini.nl/images/parameters/lipids/FA/PCA/martini_v2.0_PCN_01.itp)   |
|[BCA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=FA&lipid=BCA)  | arachidic (C20:0) / behenic (C22:0) acid	|  [itp](http://cgmartini.nl/images/parameters/lipids/FA/BCA/martini_v2.0_BCN_01.itp)   |
|[XCA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=FA&lipid=XCA)  | lignoceroyl (C24:0) / hexacosanoic (C26:0) acid	|  [itp](http://cgmartini.nl/images/parameters/lipids/FA/XCA/martini_v2.0_XCN_01.itp)   |
|[ACA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=FA&lipid=ACA)  | arachidonic (C20:4) / docosapentaenoic (C22:5) acid	|  [itp](http://cgmartini.nl/images/parameters/lipids/FA/ACA/martini_v2.0_ACN_01.itp)   |
|[UCA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=FA&lipid=UCA)  | docosahexaenoic (C22:6) acid (DHA)	|  [itp](http://cgmartini.nl/images/parameters/lipids/FA/UCA/martini_v2.0_UCN_01.itp)   |


### Other
<hr>

|       |                                       |        |
|-------|---------------------------------------|--------|
|[BOLA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=BOLA)  | cyclic di-DPPC Bolalipid	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/BOLA/martini_v2.0_BOLA_01.itp)   |
|[BOLB](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=BOLB)  | acyclic di-DPPC Bolalipid	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/BOLB/martini_v2.0_BOLB_01.itp)   |
|[CDL0](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=CDL0)  | cardiolipin (CL) 0-	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/CDL0/martini_v2.0_CDL0_01.itp)   |
|[CDL1](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=CDL1)  | cardiolipin (CL) 1-	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/CDL1/martini_v2.0_CDL1_01.itp)   |
|[CDL2](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=CDL2)  | cardiolipin (CL) 2-	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/CDL2/martini_v2.0_CDL2_01.itp)   |
|[LPS](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=LPS)  | Lipopolysaccharide	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/LPS/martini_v2.0_LPS_01.itp)   |
|[BFRA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=BFRA)  | Lipid A - Bacteroides fragilis	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/BFRA/Bfragilis_v1.itp)   |
|[BPER](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=BPER)  | Lipid A - Bordetella pertussis	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/BPER/Bpertussis_v1.itp)   |
|[CJEJ](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=CJEJ)  | Lipid A - Campylobacter jejuni	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/CJEJ/Cjejuni_v1.itp)   |
|[CTRA](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=CTRA)  | Lipid A - Chlamydia trachomatis	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/CTRA/Ctrachomatis_v1.itp)   |
|[HPYL](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=HPYL)  | Lipid A - Helicobacter pylori |  [itp](http://cgmartini.nl/images/parameters/lipids/Other/HPYL/Hpylori_v1.itp)   |
|[NMEN](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=NMEN)  | Lipid A - Neisseria meningitidis	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/NMEN/Nmeningitidis_v1.itp)   |
|[PGIN](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=PGIN)  | Lipid A - Porphyromonas gingivalis	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/PGIN/Pgingivalis_v1.itp)   |
|[PARU](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=PARU)  | Lipid A - Pseudomonas aeruginosa	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/PARU/Paeruginosa_LPA_v1.itp)   |
|[PARC](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=PARC)  | Lipid A+core - Pseudomonas aeruginosa	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/PARC/Paeruginosa_LPC_v1.itp)   |
|[SMIN](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=SMIN)  | Lipid A - Salmonella minnesota	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/SMIN/Sminnesota_v1.itp)   |
|[DPTAP](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=DPTAP)  | di-C16:0-C18:0 TAP	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/DPTAP/martini_v2.0_DPTAP_01.itp)   |
|[DOTAP](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=DOTAP)  | di-C16:1-C18:1 TAP	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/DOTAP/martini_v2.0_DOTAP_01.itp)   |
|[DITAP](http://cgmartini.nl/index.php/force-field-parameters/lipids2/351-lipid.html?dir=Other&lipid=DITAP)  | di-C16:1-C18:1 TAP	|  [itp](http://cgmartini.nl/images/parameters/lipids/Other/DITAP/martini_v2.0_DITAP_01.itp)   |



### Collections
<hr>

|                                                 |                                   |
|-------------------------------------------------|-----------------------------------|
| Martini 2.0 lipids, all | 	[martini_v2.0_lipids_all_201506.itp]() |
| Phosphatidylcholines (PC) |	[martini_v2.0_lipids_phosphatidylcholines_201504.itp]() |
| Phosphatidylethanolamines (PE) |	[martini_v2.0_lipids_phosphatidylethanolamines_201504.itp]() |
| Phosphatidylserines (PS) |	[martini_v2.0_lipids_phosphatidylserines_201504.itp]() |
| Phosphatidylglycerols (PG) |	[martini_v2.0_lipids_phosphatidylglycerols_201504.itp]() |
| Phosphatidic acid lipids (PA) |	[martini_v2.0_lipids_phosphatidic_acid_201504.itp]() |
| Phosphatidylinositols |	[martini_v2.0_lipids_phosphatidylinositols_201512.itp]() |
| Glycerols |	[martini_v2.0_lipids_glycerols_201609.itp]() |
| Lysophosphatidylcholines (LPC) |	[martini_v2.0_lipids_lysophosphatidylcholines_201504.itp]() |
| Sphingomyelins (SM) |	[martini_v2.0_lipids_sphingomyelins_201504.itp]() |
| Ceramides (CER) |	[martini_v2.0_lipids_ceramides_201504.itp]() |
| Glycosphingolipids |	[martini_v2.0_lipids_glycosphingolipids_201609.itp]() |
| Glycoglycerolipids |	[martini_v2.0_lipids_glycoglycerolipids_201504.itp]() |
| Sterols |	[martini_v2.0_lipids_sterols_201504.itp]() |
| Surfactants |	[martini_v2.0_lipids_surfactants_201504.itp]() |
| Fatty acids (FA) |	[martini_v2.0_lipids_fatty_acids_201512.itp]() |
| Other lipids |	[martini_v2.0_lipids_other_201504.itp]() |
| Plasma membrane lipid collection |	[martini_v2.0_lipids_plasma_201503.itp]() |
| Thylakoid cyano bact. lipid collection |	[martini_v2.0_lipids_thylakoid_cyano_201505.itp]() |
| Thylakoid plant lipid collection |	[martini_v2.0_lipids_thylakoid_plant_201505.itp]() |
| Dry Martini lipids, all |	[dry_martini_v2.0_lipids_all_201502.itp]() | 
| Old glycolipid collection (fix 10 Oct 2013) |	[martini_v2.0_glycolipids_old3.itp]() |
| Old glycolipid collection (fix 13 Sep 2013) |	[martini_v2.0_glycolipids_old2.itp]() |
| Old glycolipid collection |	[martini_v2.0_glycolipids_old.itp]() |
| Old surfactants collection |	[martini_v2.0_surfactants_old.itp]() |
| Old cholesterol with virtual sites |	[martini_v2.0_cholesterol_old.itp]() |
| Old cholesterol, cholesteryl oleate and cholate |	[martini_v2.0_cholesterol_old2.itp]() |
| Old Martini 2.0 lipid collection |	[martini_v2.0_lipids_old.itp]() |
| From 2015.06, Martini 2.0 lipids, all |	[martini_v2.0_lipids_all_201506.itp]() |
| From 2015.04, Glycosphingolipids |	[martini_v2.0_lipids_glycosphingolipids_201504.itp]() |
| From 2015.04, Glycerols |	[martini_v2.0_lipids_glycerols_201504.itp]() |