---
title: <i class="fa-solid fa-dice-d20"></i> Particle definitions
format: html
---
<hr>

The particle definition file is required for all simulations and specifies the coarse-grained particle types and interaction matrix in Martini 3. In the file below you will find the particle definitions in Martini 3, as well as the topology of proteins, solvents, ions, lipids, nucleobases, carbohydrates, and small molecules, as defined in its original release. [Here](https://github.com/ricalessandri/Martini3-small-molecules/blob/main/tutorials/building_block_table.pdf)'s a table (in continuous expansion) to help with understanding Martini 3's bead types. 

<hr>

- [martini_v300.zip](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/ff_parameters/martini3/martini_v300.zip)

<hr>

In addition to this centralized folder, individual `.itp` files will be provided in the respective sections for each molecule type, including further extensions and refinements. 

**Please read and cite the associated publication when using it: [PCT Souza, et al., Nat. Methods, 2021](https://www.nature.com/articles/s41592-021-01098-3#Sec13). And enjoy Martini 3 responsibly!**

<hr>
