---
title: "Molecular insights into the effects of focused ultrasound mechanotherapy on lipid bilayers: Unlocking the keys to design effective treatment"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Alexandre Blanco-González, Siewert J. Marrink, Ángel Piñeiro, Rebeca García-Fandiño"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "Journal of Colloid and Interface Science"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.jcis.2023.07.077"            # URL of DOI (required)  
materials: "https://www.sciencedirect.com/science/article/pii/S0021979723013267#s0045"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Multi-scale
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Blanco-González, A., Marrink, S. J., Piñeiro, Á., & García-Fandiño, R. (2023). Molecular insights into the effects of focused ultrasound mechanotherapy on lipid bilayers: Unlocking the keys to design effective treatments. Journal of Colloid and Interface Science, 650, 1201-1210.

## Abstract

Administration of focused ultrasounds (US) represents an attractive complement to classical therapies for a wide range of maladies, from cancer to neurological pathologies, as they are non-invasive, easily targeted, their dosage is easy to control, and they involve low risks. Different mechanisms have been proposed for their activity but the direct effect of their interaction with cell membranes is not well understood at the molecular level. This is in part due to the difficulty of designing experiments able to probe the required spatio-temporal resolutions. Here we use Molecular Dynamics (MD) simulations at two resolution levels and machine learning (ML) classification tools to shed light on the effects that focused US mechanotherapy methods have over a range of lipid bilayers. Our results indicate that the dynamic-structural response of the membrane models to the mechanical perturbations caused by the sound waves strongly depends on the lipid composition. The analyses performed on the MD trajectories contribute to a better understanding of the behavior of lipid membranes, and to open up a path for the rational design of new therapies for the long list of diseases characterized by specific lipid profiles of pathological membrane cells.