---
title: "Martini 3 Coarse-Grained Force Field for Cholesterol"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Luís Borges-Araújo, Ana C. Borges-Araújo, Tugba Nur Ozturk, Daniel P. Ramirez-Echemendia, Balázs Fábián, Timothy S. Carpenter, Sebastian Thallmair, Jonathan Barnoud, Helgi I. Ingólfsson, Gerhard Hummer, D. Peter Tieleman, Siewert J. Marrink, Paulo C. T. Souza, and Manuel N. Melo"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "Journal of Chemical Theory and Computation"    # Journal or similar (required)
preprint: "https://chemrxiv.org/engage/chemrxiv/article-details/650c59f060c37f4f76332ea7"       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jctc.3c00547"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/acs.jctc.3c00547?goto=supporting-info"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Lipid membranes
  - Journal article
  - Parametrization
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Borges-Araújo, L., Borges-Araújo, A. C., Ozturk, T. N., Ramirez-Echemendia, D. P., Fábián, B., Carpenter, T. S., ... & Melo, M. N. (2023). Martini 3 Coarse-Grained Force Field for Cholesterol. Journal of Chemical Theory and Computation, 19(20), 7387-7404.

## Abstract

Cholesterol plays a crucial role in biomembranes by regulating various properties, such as fluidity, rigidity, permeability, and organization of lipid bilayers. The latest version of the Martini model, Martini 3, offers significant improvements in interaction balance, molecular packing, and inclusion of new bead types and sizes. However, the release of the new model resulted in the need to reparameterize many core molecules, including cholesterol. Here, we describe the development and validation of a Martini 3 cholesterol model, addressing issues related to its bonded setup, shape, volume, and hydrophobicity. The proposed model mitigates some limitations of its Martini 2 predecessor while maintaining or improving the overall behavior.