---
title: "Pragmatic Coarse-Graining of Proteins: Models and Applications"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Luís Borges-Araújo, Ilias Patmanidis, Akhil P. Singh, Lucianna H. S. Santos, Adam K. Sieradzan, Stefano Vanni, Cezary Czaplewski, Sergio Pantano, Wataru Shinoda, Luca Monticelli, Adam Liwo, Siewert J. Marrink, and Paulo C. T. Souza"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "Journal of Chemical Theory and Computation"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jctc.3c00733"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Proteins
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Borges-Araújo, L., Patmanidis, I., Singh, A. P., Santos, L. H., Sieradzan, A. K., Vanni, S., ... & Souza, P. C. (2023). Pragmatic coarse-graining of proteins: models and applications. Journal of Chemical Theory and Computation, 19(20), 7112-7135.

## Abstract

The molecular details involved in the folding, dynamics, organization, and interaction of proteins with other molecules are often difficult to assess by experimental techniques. Consequently, computational models play an ever-increasing role in the field. However, biological processes involving large-scale protein assemblies or long time scale dynamics are still computationally expensive to study in atomistic detail. For these applications, employing coarse-grained (CG) modeling approaches has become a key strategy. In this Review, we provide an overview of what we call pragmatic CG protein models, which are strategies combining, at least in part, a physics-based implementation and a top-down experimental approach to their parametrization. In particular, we focus on CG models in which most protein residues are represented by at least two beads, allowing these models to retain some degree of chemical specificity. A description of the main modern pragmatic protein CG models is provided, including a review of the most recent applications and an outlook on future perspectives in the field.