---
title: "pH-Dependent Conformational Switch Impacts Stability of the PsbS Dimer"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Maria Gabriella Chiariello, Fabian Grünewald, Rubi Zarmiento-Garcia, and Siewert J. Marrink"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "The Journal of Physical Chemistry Letters"    # Journal or similar (required)
preprint: "https://chemrxiv.org/engage/chemrxiv/article-details/638cd9a4cfb5ff7f435cb762"       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jpclett.2c03760"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/acs.jpclett.2c03760?goto=supporting-info"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - pH
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Chiariello, M. G., Grünewald, F., Zarmiento-Garcia, R., & Marrink, S. J. (2023). pH-Dependent Conformational Switch Impacts Stability of the PsbS Dimer. The Journal of Physical Chemistry Letters, 14(4), 905-911.

## Abstract

The photosystem II PsbS protein triggers the photoprotective mechanism of plants by sensing the acidification of the thylakoid lumen. Despite the mechanism of action of PsbS would require a pH-dependent monomerization of the dimeric form, a clear connection between the pH-induced structural changes and the dimer stability is missing. Here, by applying constant pH coarse-grained and all-atom molecular dynamics simulations, we investigate the pH-dependent structural response of the PsbS dimer. We find that the pH variation leads to structural changes in the lumen-exposed helices, located at the dimeric interface, providing an effective switch between PsbS inactive and active form. Moreover, the monomerization free energies reveal that in the neutral pH conformation, where the network of H-bond interactions at the dimeric interface is destroyed, the protein–protein interaction is weaker. Our results show how the pH-dependent conformations of PsbS affect their dimerization propensity, which is at the basis of the photoprotective mechanism.