---
title: "Synthetic Membrane Shaper for Controlled Liposome Deformation"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Nicola De Franceschi, Weria Pezeshkian, Alessio Fragasso, Bart M. H. Bruininks, Sean Tsai, Siewert J. Marrink, and Cees Dekker"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "ACS nano"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acsnano.2c06125"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/acsnano.2c06125?goto=supporting-info"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Multi-scale
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> De Franceschi, N., Pezeshkian, W., Fragasso, A., Bruininks, B. M., Tsai, S., Marrink, S. J., & Dekker, C. (2022). Synthetic membrane shaper for controlled liposome deformation. ACS nano, 17(2), 966-978.

## Abstract

Shape defines the structure and function of cellular membranes. In cell division, the cell membrane deforms into a “dumbbell” shape, while organelles such as the autophagosome exhibit “stomatocyte” shapes. Bottom-up in vitro reconstitution of protein machineries that stabilize or resolve the membrane necks in such deformed liposome structures is of considerable interest to characterize their function. Here we develop a DNA-nanotechnology-based approach that we call the synthetic membrane shaper (SMS), where cholesterol-linked DNA structures attach to the liposome membrane to reproducibly generate high yields of stomatocytes and dumbbells. In silico simulations confirm the shape-stabilizing role of the SMS. We show that the SMS is fully compatible with protein reconstitution by assembling bacterial divisome proteins (DynaminA, FtsZ:ZipA) at the catenoidal neck of these membrane structures. The SMS approach provides a general tool for studying protein binding to complex membrane geometries that will greatly benefit synthetic cell research.