---
title: "Identification of inhibitors targeting the energy-coupling factor (ECF) transporters"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Eleonora Diamanti, Paulo C. T. Souza, Inda Setyawati, Spyridon Bousis, Leticia Monjas, Lotteke J.Y.M. Swier, Atanaz Shams, Aleksei Tsarenko, Weronika K. Stanek, Manuel Jäger, Siewert J. Marrink, Dirk J. Slotboom & Anna K. H. Hirsch"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "Communications biology"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s42003-023-05555-x"            # URL of DOI (required)  
materials: "https://static-content.springer.com/esm/art%3A10.1038%2Fs42003-023-05555-x/MediaObjects/42003_2023_5555_MOESM1_ESM.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Drug design
  - Small molecules
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Diamanti, E., Souza, P. C., Setyawati, I., Bousis, S., Monjas, L., Swier, L. J., ... & Hirsch, A. K. (2023). Identification of inhibitors targeting the energy-coupling factor (ECF) transporters. Communications biology, 6(1), 1182.

## Abstract

The energy-coupling factor (ECF) transporters are a family of transmembrane proteins involved in the uptake of vitamins in a wide range of bacteria. Inhibition of the activity of these proteins could reduce the viability of pathogens that depend on vitamin uptake. The central role of vitamin transport in the metabolism of bacteria and absence from humans make the ECF transporters an attractive target for inhibition with selective chemical probes. Here, we report on the identification of a promising class of inhibitors of the ECF transporters. We used coarse-grained molecular dynamics simulations on Lactobacillus delbrueckii ECF-FolT2 and ECF-PanT to profile the binding mode and mechanism of inhibition of this novel chemotype. The results corroborate the postulated mechanism of transport and pave the way for further drug-discovery efforts.