---
title: "Curvature-induced lipid sorting beyond the critical packing parameter"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Melanie Konig, Reinier de Vries, Fabian Grunewald, Siewert-Jan Marrink, and Weria Pezeshkian"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "bioRxiv"    # Journal or similar (required)
preprint: "https://www.biorxiv.org/content/10.1101/2023.12.15.571845v1"       # URL to prepint page (optional)  
doi: "https://doi.org/10.1101/2023.12.15.571845"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Pre-print
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Konig, M., de Vries, R., Grunewald, F., Marrink, S. J., & Pezeshkian, W. (2023). Curvature-induced lipid sorting beyond the critical packing parameter. bioRxiv, 2023-12.

## Abstract

Over the last few decades, the spatial organization of biomembranes has received a lot of attention. With the fluid mosaic model, Singer and Nicolson proposed that biomembranes behave as two-dimensional fluids, allowing proteins and lipids to diffuse freely and thus react to external stimuli. Biological functionality and membrane organization are intricately linked to each other, however, how these organizations emerge is yet to be established. Here we use coarse-grained molecular dynamics simulations to explore the relationship between membrane shape and lateral organization at the nanoscale for a broad range of lipid mixtures. Our results illustrate that membrane curvature and lateral organization are intimately linked at the nanoscale and the relationship is much more complicated compared to the traditional views, in particular the lipid shape concept. Furthermore, we show that large membrane curvature can disrupt phase separation, line tension, and interleaflet coupling leading to non-intuitive lipid sorting. Our findings highlight how curvature-driven sorting can alter the phase behavior of lipid mixtures, which could be crucial for cellular functionality.