---
title: "Watching Molecular Nanotubes Self-Assemble in Real Time"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Marìck Manrho, Sundar Raj Krishnaswamy, Björn Kriete, Ilias Patmanidis, Alex H. de Vries, Siewert J. Marrink, Thomas L. C. Jansen, Jasper Knoester, and Maxim S. Pshenichnikov"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "Journal of the American Chemical Society"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jacs.3c07103"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/jacs.3c07103?goto=supporting-info"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Self-assembly
  - Journal article
  - Polymers
  - pH
  - Multi-scale
  - Nanoparticles
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Manrho, M., Krishnaswamy, S. R., Kriete, B., Patmanidis, I., de Vries, A. H., Marrink, S. J., ... & Pshenichnikov, M. S. (2023). Watching molecular nanotubes self-assemble in real time. Journal of the American Chemical Society, 145(41), 22494-22503.

## Abstract

Molecular self-assembly is a fundamental process in nature that can be used to develop novel functional materials for medical and engineering applications. However, their complex mechanisms make the short-lived stages of self-assembly processes extremely hard to reveal. In this article, we track the self-assembly process of a benchmark system, double-walled molecular nanotubes, whose structure is similar to that found in biological and synthetic systems. We selectively dissolved the outer wall of the double-walled system and used the inner wall as a template for the self-reassembly of the outer wall. The reassembly kinetics were followed in real time using a combination of microfluidics, spectroscopy, cryogenic transmission electron microscopy, molecular dynamics simulations, and exciton modeling. We found that the outer wall self-assembles through a transient disordered patchwork structure: first, several patches of different orientations are formed, and only on a longer time scale will the patches interact with each other and assume their final preferred global orientation. The understanding of patch formation and patch reorientation marks a crucial step toward steering self-assembly processes and subsequent material engineering.