---
title: "Lateral membrane organization as target of an antimicrobial peptidomimetic compound"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Adéla Melcrová, Sourav Maity, Josef Melcr, Niels A. W. de Kok, Mariella Gabler, Jonne van der Eyden, Wenche Stensen, John S. M. Svendsen, Arnold J. M. Driessen, Siewert J. Marrink & Wouter H. Roos"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "Nature Communications"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s41467-023-39726-5"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/s41467-023-39726-5#Sec20"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Drug design
  - Lipid membranes
  - Small molecules
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Melcrová, A., Maity, S., Melcr, J., de Kok, N. A., Gabler, M., van der Eyden, J., ... & Roos, W. H. (2023). Lateral membrane organization as target of an antimicrobial peptidomimetic compound. Nature Communications, 14(1), 4038.

## Abstract

Antimicrobial resistance is one of the leading concerns in medical care. Here we study the mechanism of action of an antimicrobial cationic tripeptide, AMC-109, by combining high speed-atomic force microscopy, molecular dynamics, fluorescence assays, and lipidomic analysis. We show that AMC-109 activity on negatively charged membranes derived from Staphylococcus aureus consists of two crucial steps. First, AMC-109 self-assembles into stable aggregates consisting of a hydrophobic core and a cationic surface, with specificity for negatively charged membranes. Second, upon incorporation into the membrane, individual peptides insert into the outer monolayer, affecting lateral membrane organization and dissolving membrane nanodomains, without forming pores. We propose that membrane domain dissolution triggered by AMC-109 may affect crucial functions such as protein sorting and cell wall synthesis. Our results indicate that the AMC-109 mode of action resembles that of the disinfectant benzalkonium chloride (BAK), but with enhanced selectivity for bacterial membranes.