---
title: "Molecular architecture and dynamics of SARS-CoV-2 envelope by integrative modeling"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Weria Pezeshkian, Fabian Grünewald, Oleksandr Narykov, Senbao Lu, Valeria Arkhipova, Alexey Solodovnikov, Tsjerk A. Wassenaar, Siewert J. Marrink and Dmitry Korkin"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "Structure"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.str.2023.02.006"            # URL of DOI (required)  
materials: "https://www.cell.com/structure/fulltext/S0969-2126(23)00040-0#supplementaryMaterial"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Glycans
  - Proteins
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Pezeshkian, W., Grünewald, F., Narykov, O., Lu, S., Arkhipova, V., Solodovnikov, A., ... & Korkin, D. (2023). Molecular architecture and dynamics of SARS-CoV-2 envelope by integrative modeling. Structure, 31(4), 492-503.

## Abstract

Despite tremendous efforts, the exact structure of SARS-CoV-2 and related betacoronaviruses remains elusive. SARS-CoV-2 envelope is a key structural component of the virion that encapsulates viral RNA. It is composed of three structural proteins, spike, membrane (M), and envelope, which interact with each other and with the lipids acquired from the host membranes. Here, we developed and applied an integrative multi-scale computational approach to model the envelope structure of SARS-CoV-2 with near atomistic detail, focusing on studying the dynamic nature and molecular interactions of its most abundant, but largely understudied, M protein. The molecular dynamics simulations allowed us to test the envelope stability under different configurations and revealed that the M dimers agglomerated into large, filament-like, macromolecular assemblies with distinct molecular patterns. These results are in good agreement with current experimental data, demonstrating a generic and versatile approach to model the structure of a virus de novo.