---
title: "Molecular basis of PIP2-dependent conformational switching of phosphorylated CD44 in binding FERM"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Meina Ren, Lina Zhao, Ziyi Ma, Hailong An, Siewert Jan Marrink and Fude Sun"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "Biophysical Journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2023.05.021"            # URL of DOI (required)  
materials: "https://www.cell.com/biophysj/fulltext/S0006-3495(23)00333-8#secsectitle0085"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Phopholipids
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Ren, M., Zhao, L., Ma, Z., An, H., Marrink, S. J., & Sun, F. (2023). Molecular basis of PIP2-dependent conformational switching of phosphorylated CD44 in binding FERM. Biophysical Journal, 122(13), 2675-2685.

## Abstract

Association of the cellular adhesive protein CD44 and the N-terminal (FERM) domain of cytoskeleton adaptors is critical for cell proliferation, migration, and signaling. Phosphorylation of the cytoplasmic domain (CTD) of CD44 acts as an important regulator of the protein association, but the structural transformation and dynamics mechanism remain enigmatic. In this study, extensive coarse-grained simulations were employed to explore the molecular details in the formation of CD44-FERM complex under S291 and S325 phosphorylation, a modification path known to exert reciprocal effects on the protein association. We find that phosphorylation of S291 inhibits complexation by causing the CTD of CD44 to adopt a more closed structure. In contrast, S325 phosphorylation liberates the CD44-CTD from the membrane surface and promotes the linkage with FERM. The phosphorylation-driven transformation is found to occur in a PIP2-dependent manner, with PIP2 effecting the relative stability of the closed and open conformation, and a replacement of PIP2 by POPS greatly abrogates this effect. The revealed interdependent regulation mechanism by phosphorylation and PIP2 in the association of CD44 and FERM further strengthens our understanding of the molecular basis of cellular signaling and migration.