---
title: "CRAFTing Delivery of Membrane Proteins into Protocells using Nanodiscs"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Piotr Stępień, Sylwia Świątek, Manuel Yamil Yusef Robles, Joanna Markiewicz-Mizera, Dhanasekaran Balakrishnan, Satomi Inaba-Inoue, Alex H De Vries, Konstantinos Beis, Siewert J Marrink, and Jonathan G Heddle"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "ACS Applied Materials & Interfaces"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acsami.3c11894"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/acsami.3c11894?goto=supporting-info"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Stępień, P., Świątek, S., Robles, M. Y. Y., Markiewicz-Mizera, J., Balakrishnan, D., Inaba-Inoue, S., ... & Heddle, J. G. (2023). CRAFTing Delivery of Membrane Proteins into Protocells using Nanodiscs. ACS Applied Materials & Interfaces, 15(49), 56689-56701.

## Abstract

For the successful generative engineering of functional artificial cells, a convenient and controllable means of delivering membrane proteins into membrane lipid bilayers is necessary. Here we report a delivery system that achieves this by employing membrane protein-carrying nanodiscs and the calcium-dependent fusion of phosphatidylserine lipid membranes. We show that lipid nanodiscs can fuse a transported lipid bilayer with the lipid bilayers of small unilamellar vesicles (SUVs) or giant unilamellar vesicles (GUVs) while avoiding recipient vesicles aggregation. This is triggered by a simple, transient increase in calcium concentration, which results in efficient and rapid fusion in a one-pot reaction. Furthermore, nanodiscs can be loaded with membrane proteins that can be delivered into target SUV or GUV membranes in a detergent-independent fashion while retaining their functionality. Nanodiscs have a proven ability to carry a wide range of membrane proteins, control their oligomeric state, and are highly adaptable. Given this, our approach may be the basis for the development of useful tools that will allow bespoke delivery of membrane proteins to protocells, equipping them with the cell-like ability to exchange material across outer/subcellular membranes.