---
title: "Expulsion mechanism of the substrate-translocating subunit in ECF transporters"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Chancievan Thangaratnarajah, Mark Nijland, Luís Borges-Araújo, Aike Jeucken, Jan Rheinberger, Siewert J. Marrink, Paulo C. T. Souza, Cristina Paulino & Dirk J. Slotboom"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "Nature Communications"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s41467-023-40266-1"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/s41467-023-40266-1#Sec28"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Thangaratnarajah, C., Nijland, M., Borges-Araújo, L., Jeucken, A., Rheinberger, J., Marrink, S. J., ... & Slotboom, D. J. (2023). Expulsion mechanism of the substrate-translocating subunit in ECF transporters. Nature Communications, 14(1), 4484.

## Abstract

Energy-coupling factor (ECF)-type transporters mediate the uptake of micronutrients in many bacteria. They consist of a substrate-translocating subunit (S-component) and an ATP-hydrolysing motor (ECF module) Previous data indicate that the S-component topples within the membrane to alternately expose the binding site to either side of the membrane. In many ECF transporters, the substrate-free S-component can be expelled from the ECF module. Here we study this enigmatic expulsion step by cryogenic electron microscopy and reveal that ATP induces a concave-to-convex shape change of two long helices in the motor, thereby destroying the S-component’s docking site and allowing for its dissociation. We show that adaptation of the membrane morphology to the conformational state of the motor may favour expulsion of the substrate-free S-component when ATP is bound and docking of the substrate-loaded S-component after hydrolysis. Our work provides a picture of bilayer-assisted chemo-mechanical coupling in the transport cycle of ECF transporters.