---
title: "Membrane manipulation by free fatty acids improves microbial plant polyphenol synthesis"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Apilaasha Tharmasothirajan, Josef Melcr, John Linney, Thomas Gensch, Karin Krumbach, Karla Marlen Ernst, Christopher Brasnett, Paola Poggi, Andrew R. Pitt, Alan D. Goddard, Alexandros Chatgilialoglu, Siewert J. Marrink & Jan Marienhagen"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "Nature Communications"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s41467-023-40947-x"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/s41467-023-40947-x#Sec20"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Tharmasothirajan, A., Melcr, J., Linney, J., Gensch, T., Krumbach, K., Ernst, K. M., ... & Marienhagen, J. (2023). Membrane manipulation by free fatty acids improves microbial plant polyphenol synthesis. Nature Communications, 14(1), 5619.

## Abstract

Microbial synthesis of nutraceutically and pharmaceutically interesting plant polyphenols represents a more environmentally friendly alternative to chemical synthesis or plant extraction. However, most polyphenols are cytotoxic for microorganisms as they are believed to negatively affect cell integrity and transport processes. To increase the production performance of engineered cell factories, strategies have to be developed to mitigate these detrimental effects. Here, we examine the accumulation of the stilbenoid resveratrol in the cell membrane and cell wall during its production using Corynebacterium glutamicum and uncover the membrane rigidifying effect of this stilbenoid experimentally and with molecular dynamics simulations. A screen of free fatty acid supplements identifies palmitelaidic acid and linoleic acid as suitable additives to attenuate resveratrol’s cytotoxic effects resulting in a three-fold higher product titer. This cost-effective approach to counteract membrane-damaging effects of product accumulation is transferable to the microbial production of other polyphenols and may represent an engineering target for other membrane-active bioproducts.