---
title: "Martini 3 Coarse-Grained Model for Second-Generation Unidirectional Molecular Motors and Switches"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Petteri Vainikka and Siewert J. Marrink"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "Journal of Chemical Theory and Computation"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jctc.2c00796"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/acs.jctc.2c00796?goto=supporting-info"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Small molecules
  - Parametrization
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Vainikka, P., & Marrink, S. J. (2023). Martini 3 Coarse-Grained Model for Second-Generation Unidirectional Molecular Motors and Switches. Journal of Chemical Theory and Computation, 19(2), 596-604.

## Abstract

Artificial molecular motors (MMs) and switches (MSs), capable of undergoing unidirectional rotation or switching under the appropriate stimuli, are being utilized in multiple complex and chemically diverse environments. Although thorough theoretical work utilizing QM and QM/MM methods have mapped out many of the critical properties of MSs and MMs, as the experimental setups become more complex and ambitious, there is an ever increasing need to study the behavior and dynamics of these molecules as they interact with their environment. To this end, we have parametrized two coarse-grained (CG) models of commonly used MMs and a model for an oxindole-based MS, which can be used to study the ground state behavior of MMs and MSs in large simulations for significantly longer periods of time. We also propose methods to perturb these systems which can allow users to approximate how such systems would respond to MMs rotating or the MSs switching.