---
title: "Potential binding modes of the gut bacterial metabolite, 5-hydroxyindole, to the intestinal L-type calcium channels and its impact on the microbiota in rats"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Barbora Waclawiková, Paulo Cesar Telles de Souza, Markus Schwalbe, Constantinos G. Neochoritis, Warner Hoornenborg, Sieger A. Nelemans, Siewert J. Marrink & Sahar El Aidy"         # Paper authors (required)
year: "2023"           # Publication year (required)
publication: "Gut microbes"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1080/19490976.2022.2154544"            # URL of DOI (required)  
materials: "https://www.tandfonline.com/doi/suppl/10.1080/19490976.2022.2154544?scroll=top"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Small molecules
  - Proteins
  - Drug design
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Waclawiková, B., Cesar Telles de Souza, P., Schwalbe, M., Neochoritis, C. G., Hoornenborg, W., Nelemans, S. A., ... & El Aidy, S. (2023). Potential binding modes of the gut bacterial metabolite, 5-hydroxyindole, to the intestinal L-type calcium channels and its impact on the microbiota in rats. Gut microbes, 15(1), 2154544.

## Abstract

Intestinal microbiota and microbiota-derived metabolites play a key role in regulating the host physiology. Recently, we have identified a gut-bacterial metabolite, namely 5-hydroxyindole, as a potent stimulant of intestinal motility via its modulation of L-type voltage-gated calcium channels located on the intestinal smooth muscle cells. Dysregulation of L-type voltage-gated calcium channels is associated with various gastrointestinal motility disorders, including constipation, making L-type voltage-gated calcium channels an important target for drug development. Nonetheless, the majority of currently available drugs are associated with alteration of the gut microbiota. Using 16S rRNA sequencing this study shows that, when administered orally, 5-hydroxyindole has only marginal effects on the rat cecal microbiota. Molecular dynamics simulations propose potential-binding pockets of 5-hydroxyindole in the α1 subunit of the L-type voltage-gated calcium channels and when its stimulatory effect on the rat colonic contractility was compared to 16 different analogues, ex-vivo, 5-hydroxyindole stood as the most potent enhancer of the intestinal contractility. Overall, the present findings imply a potential role of microbiota-derived metabolites as candidate therapeutics for targeted treatment of slow intestinal motility-related disorders including constipation.