---
title: "Molecular View of Cholesterol Flip-Flop and Chemical Potential in Different Membrane Environments"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "W. F. Drew Bennett, Justin L. MacCallum, Marlon J. Hinner, Siewert J. Marrink, and D. Peter Tieleman"         # Paper authors (required)
year: "2009"           # Publication year (required)
publication: "Journal of the American Chemical Society"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/ja903529f"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Sterols
  - Vesicles
  - Multi-scale
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Marrink, S. J., & Mark, A. E. (2003). The Mechanism of Vesicle Fusion as Revealed by Molecular Dynamics Simulations. Journal of the American Chemical Society, 125(37), 11144–11145. https://doi.org/10.1021/ja036138+

## Abstract

The relative stability of cholesterol in cellular membranes and the thermodynamics of fluctuations from equilibrium have important consequences for sterol trafficking and lateral domain formation. We used molecular dynamics computer simulations to investigate the partitioning of cholesterol in a systematic set of lipid bilayers. In addition to atomistic simulations, we undertook a large set of coarse grained simulations, which allowed longer time and length scales to be sampled. Our results agree with recent experiments (Steck, T. L.; et al. Biophys. J.2002, 83, 2118−2125) that the rate of cholesterol flip-flop can be fast on physiological time scales, while extending our understanding of this process to a range of lipids. We predicted that the rate of flip-flop is strongly dependent on the composition of the bilayer. In polyunsaturated bilayers, cholesterol undergoes flip-flop on a submicrosecond time scale, while flip-flop occurs in the second range in saturated bilayers with high cholesterol content. We also calculated the free energy of cholesterol desorption, which can be equated to the excess chemical potential of cholesterol in the bilayer compared to water. The free energy of cholesterol desorption from a DPPC bilayer is 80 kJ/mol, compared to 67 kJ/mol for a DAPC bilayer. In general, cholesterol prefers more ordered and rigid bilayers and has the lowest affinity for bilayers with two polyunsaturated chains. Overall, the simulations provide a detailed molecular level thermodynamic description of cholesterol interactions with lipid bilayers, of fundamental importance to eukaryotic life.