---
title: "The structural basis for peptide selection by the transport receptor OppA"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Ronnie P‐A Berntsson, Mark K Doeven, Fabrizia Fusetti, Ria H Duurkens, Durba Sengupta, Siewert‐Jan Marrink, Andy‐Mark W H Thunnissen, Bert Poolman, and Dirk‐Jan Slotboom"         # Paper authors (required)
year: "2009"           # Publication year (required)
publication: "The EMBO Journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/emboj.2009.65"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Berntsson, R. P. A., Doeven, M. K., Fusetti, F., Duurkens, R. H., Sengupta, D., Marrink, S. J., ... & Slotboom, D. J. (2009). The structural basis for peptide selection by the transport receptor OppA. The EMBO journal, 28(9), 1332-1340.

## Abstract

Oligopeptide‐binding protein A (OppA) from Lactococcus lactis binds peptides of an exceptionally wide range of lengths (4–35 residues), with no apparent sequence preference. Here, we present the crystal structures of OppA in the open‐ and closed‐liganded conformations. The structures directly explain the protein's phenomenal promiscuity. A huge cavity allows binding of very long peptides, and a lack of constraints for the position of the N and C termini of the ligand is compatible with binding of peptides with varying lengths. Unexpectedly, the peptide's amino‐acid composition (but not the exact sequence) appears to have a function in selection, with a preference for proline‐rich peptides containing at least one isoleucine. These properties can be related to the physiology of the organism: L. lactis is auxotrophic for branched chain amino acids and favours proline‐rich caseins as a source of amino acids. We propose a new mechanism for peptide selection based on amino‐acid composition rather than sequence.