---
title: "Location, Tilt, and Binding: A Molecular Dynamics Study of Voltage-Sensitive Dyes in Biomembranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Marlon J. Hinner, Siewert-J. Marrink, and Alex H. de Vries"         # Paper authors (required)
year: "2009"           # Publication year (required)
publication: "The Journal of Physical Chemistry B"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jp907981y"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Small molecules
  - Enhanced sampling
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Hinner, M. J., Marrink, S. J., & de Vries, A. H. (2009). Location, tilt, and binding: a molecular dynamics study of voltage-sensitive dyes in biomembranes. The Journal of Physical Chemistry B, 113(48), 15807-15819.

## Abstract

We present a molecular dynamics study on the interaction of styryl-type voltage-sensitive dyes with a lipid membrane. In this work, voltage-sensitive dyes are proposed as interesting model amphiphiles for biomolecular simulation, due to the wealth of biophysical and thermodynamical data available on their behavior and their binding to lipid membranes. Taking this data as a basis, we tested the recently developed MARTINI coarse-grained model (J. Phys. Chem. B2007, 111, 7812). The focus was on the fast computation of the free energy of membrane binding. As a first step, we investigated the tilt and location of a coarse-grained representation of the dye Di-4-ASPBS in a lipid membrane, and found good agreement with atomistic simulations and experimental data. Then, we performed umbrella sampling to obtain the theoretical binding free energy for a number of Di-4-ASPBS derivates. In most cases, simulation and experimental binding data were in good agreement regarding the impact of structural changes in the amphiphile on binding. The work yields a general molecular picture of how such structural variations lead to changes of the binding mode and binding strength of amphiphiles to lipid membranes. Further, it provides insights into the possibilities and current limitations of rapid free energy computation for membrane binding with the coarse-grained MARTINI model. The results suggest that the MARTINI model may be a generally useful tool for the study and optimization of molecules interacting with membranes, such as biophysical probes or pharmaceutical compounds.