---
title: "Areas of Monounsaturated Diacylphosphatidylcholines"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Norbert Kučerka, Jana Gallová, Daniela Uhríková, Pavol Balgavý, Monica Bulacu, Siewert-Jan Marrink, and John Katsaras"         # Paper authors (required)
year: "2009"           # Publication year (required)
publication: "Biophysical Journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2009.06.050"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Kučerka, N., Gallová, J., Uhríková, D., Balgavý, P., Bulacu, M., Marrink, S. J., & Katsaras, J. (2009). Areas of monounsaturated diacylphosphatidylcholines. Biophysical Journal, 97(7), 1926-1932.

## Abstract

We have studied the structural properties of monounsaturated diacylphosphatidylcholine lipid bilayers (i.e., diCn:1PC, where n = 14, 16, 18, 20, 22, and 24 is the number of acyl chain carbons). High-resolution x-ray scattering data were analyzed in conjunction with contrast-varied neutron scattering data using a technique we recently developed. Analyses of the data show that the manner by which bilayer thickness increases with increasing n in monounsaturated diacylphosphatidylcholines is dependent on the double bond's position. For commonly available monounsaturated diacylphosphatidylcholines, this results in the nonlinear behavior of both bilayer thickness and lipid area, whereas for diC18:1PC bilayers, lipid area assumes a maximum value. It is worthwhile to note that compared to previous data, our results indicate that lipid areas are smaller by ∼10%. This observation highlights the need to revisit lipid areas, as they are often used in comparisons with molecular dynamics simulations. Moreover, simulators are encouraged to compare their results not only to x-ray scattering data, but to neutron data as well.