---
title: "A Coarse-Grained Model for Polyethylene Oxide and Polyethylene Glycol: Conformation and Hydrodynamics"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Hwankyu Lee, Alex H. de Vries, Siewert-Jan Marrink, and Richard W. Pastor"         # Paper authors (required)
year: "2009"           # Publication year (required)
publication: "The Journal of Physical Chemistry B"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jp9058966"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Parametrization
  - Polymers
  - Multi-scale
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Lee, H., de Vries, A. H., Marrink, S. J., & Pastor, R. W. (2009). A coarse-grained model for polyethylene oxide and polyethylene glycol: conformation and hydrodynamics. The journal of physical chemistry B, 113(40), 13186-13194.

## Abstract

A coarse-grained (CG) model for polyethylene oxide (PEO) and polyethylene glycol (PEG) developed within the framework of the MARTINI CG force field (FF) using the distributions of bonds, angles, and dihedrals from the CHARMM all-atom FF is presented. Densities of neat low molecular weight PEO agree with experiment, and the radius of gyration Rg = 19.1 Å ± 0.7 for 76-mers of PEO (Mw ≈ 3400), in excellent agreement with neutron scattering results for an equal sized PEG. Simulations of 9, 18, 27, 36, 44, 67, 76, 90, 112, 135, and 158-mers of the CG PEO (442 < Mw < 6998) at low concentration in water show the experimentally observed transition from ideal chain to real chain behavior at 1600 < Mw < 2000, in excellent agreement with the dependence of experimentally observed hydrodynamic radii of PEG. Hydrodynamic radii of PEO calculated from diffusion coefficients of the higher Mw PEO also agree well with experiment. Rg calculated from both all-atom and CG simulations of PEO76 at 21 and 148 mg/cm3 are found to be nearly equal. This lack of concentration dependence implies that apparent Rg from scattering experiments at high concentration should not be taken to be the chain dimension. Simulations of PEO grafted to a nonadsorbing surface yield a mushroom to brush transition that is well described by the Alexander−de Gennes formalism.