---
title: "3D Pressure Field in Lipid Membranes and Membrane-Protein Complexes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "O. H. Samuli Ollila, H. Jelger Risselada, Martti Louhivuori, Erik Lindahl, Ilpo Vattulainen, and Siewert J. Marrink"         # Paper authors (required)
year: "2009"           # Publication year (required)
publication: "Physical review letters"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1103/PhysRevLett.102.078101"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Vesicles
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Ollila, O. S., Risselada, H. J., Louhivuori, M., Lindahl, E., Vattulainen, F. I., & Marrink, S. J. (2009). 3D pressure field in lipid membranes and membrane-protein complexes. Physical review letters, 102(7), 078101.

## Abstract

We calculate full 3D pressure fields for inhomogeneous nanoscale systems using molecular dynamics simulation data. The fields represent systems with increasing level of complexity, ranging from semivesicles and vesicles to membranes characterized by coexistence of two phases, including also a protein-membrane complex. We show that the 3D pressure field is distinctly different for curved and planar bilayers, the pressure field depends strongly on the phase of the membrane, and that an integral protein modulates the tension and elastic properties of the membrane.