---
title: "Curvature effects on lipid packing and dynamics in liposomes revealed by coarse grained molecular dynamics simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "H. Jelger Risselada and Siewert J. Marrink"         # Paper authors (required)
year: "2009"           # Publication year (required)
publication: "Physical Chemistry Chemical Physics"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/B818782G"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Vesicles
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Risselada, H. J., & Marrink, S. J. (2009). Curvature effects on lipid packing and dynamics in liposomes revealed by coarse grained molecular dynamics simulations. Physical Chemistry Chemical Physics, 11(12), 2056-2067.

## Abstract

The molecular packing details of lipids in planar bilayers are well characterized. For curved bilayers, however, little data is available. In this paper we study the effect of temperature and membrane composition on the structural and dynamical properties of a liposomal membrane in the limit of high curvature (liposomal diameter of 15–20 nm), using coarse grained molecular dynamics simulations. Both pure dipalmitoyl phosphatidylcholine (DPPC) liposomes and binary mixtures of DPPC and either dipalmitoylphosphatidylethanolamine (DPPE) or polyunsaturated dilinoleylphosphatidylcholine (DLiPC) lipids are modeled. We take special care in the equilibration of the liposomes requiring lipid flip-flopping, which can be facilitated by the temporary insertion of artificial pores. The equilibrated liposomes show some remarkable properties. Curvature induces membrane thinning and reduces the thermal expansivity of the membrane. In the inner monolayer the lipid head groups are very closely packed and dehydrated, and the lipids tails relatively disordered. The opposite packing effects are seen in the outer monolayer. In addition, we noticed an increased tendency of the lipid tails to backfold toward the interface in the outer monolayer. The distribution of lipids over the monolayers was found to be strongly temperature dependent. Higher temperatures favor more equally populated monolayers. Relaxation times of the lipid tails were found to increase with increasing curvature, with the lipid tails in the outer monolayer showing a significant slower dynamics compared to the lipid tails in the inner monolayer. In the binary systems there is a clear tendency toward partial transversal demixing of the two components, with especially DPPE enriched in the inner monolayer. This observation is in line with a static shape concept which dictates that inverted-cone shaped lipids such as DPPE and DLiPC would prefer the concave volume of the inner monolayer. However, our results for DLiPC show that another effect comes into play that is almost equally strong and provides a counter-acting driving force toward the outer, rather than the inner monolayer. This effect is the ability of the polyunsaturated tails of DLiPC to backfold, which is advantageous in the outer monolayer. We speculate that polyunsaturated lipids in biological membranes may play an important role in stabilizing both positive and negative regions of curvature.