---
title: "The freezing process of small lipid vesicles at molecular resolution"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "H. Jelger Risselada and Siewert J. Marrink"         # Paper authors (required)
year: "2009"           # Publication year (required)
publication: "Soft Matter"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/B913210D"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Vesicles
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Risselada, H. J., & Marrink, S. J. (2009). The freezing process of small lipid vesicles at molecular resolution. Soft Matter, 5(22), 4531-4541.

## Abstract

At present very little is known about the kinetic barriers which a small vesicle will face during the transformation from the liquid-crystalline to the gel phase, and what the structure of frozen vesicles looks like at the molecular level. The formation of gel domains in the strongly curved bilayer of a small vesicle seems almost paradoxical and is expected to involve large structural reorganizations. In this work we use coarse-grained molecular dynamics simulations to study the kinetic and structural aspects of gel domain formation in small lipid vesicles, specifically dipalmitoylphosphatidylcholine (DPPC) vesicles with a diameter range of 20–40 nm. We observe that cooling of such vesicles below the phase transition temperature does not result in gel phase formation on a microsecond time scale, which we attribute to the presence of an effective area constraint. This area constraint is due to the strongly reduced membrane permeability at lower temperatures, preventing the rapid efflux of water and the required decrease in membrane area to form a gel phase. Control simulations with lamellar bilayers, simulated at fixed area, show that gel phase formation is indeed only possible below a certain threshold area. The effect of lipid asymmetry was also studied with the lamellar setup, and found to be of less importance. To circumvent the kinetic barrier imposed by the effective area constraint of the liposomes, i.e. to mimic the long time behavior, we introduce artificial pores in the membrane facilitating the solvent efflux. In this case, spontaneous gel domains are formed. We identify several stages during the microsecond-long transformation, finally resulting in strongly deformed or ruptured vesicles entirely in the gel state.