---
title: "Simulations of the c-subunit of ATP-synthase reveal helix rearrangements"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Durba Sengupta, Aldo Rampioni & Siewert-Jan Marrink"         # Paper authors (required)
year: "2009"           # Publication year (required)
publication: "Molecular Membrane Biology"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.3109/09687680903321073"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Sengupta, D., Rampioni, A., & Marrink, S. J. (2009). Simulations of the c-subunit of ATP-synthase reveal helix rearrangements. Molecular Membrane Biology, 26(8), 422-434.

## Abstract

The c-subunit of the enzyme, ATP synthase couples the proton movement through the a-subunit with its own rotation and subsequent rotation of the F1 ring to drive ATP synthesis. Here, we perform μs time-scale coarse-grained molecular dynamics simulations of the c-subunit to characterize its structure and dynamics. Two different helix-helix interfaces, albeit with similar interfacial characteristics, are sampled in the simulations. The helix-2 of the c-subunit monomer rotates around the axis of helix-1 bringing about a change in the interface. Previous models have also proposed such a change in the helix interface but postulated that helix-2 swivels around its own axis. Such large-scale changes in helix packing motifs have not been observed before. The helix-swirling persists even in the c-subunit ring but the dynamics is much slower. The cooperative behavior in the ring appears to stabilize a conformation less-populated in the monomer. Analyzing the stability of the c-subunit ring, it was found that six lipid molecules are necessary to fill the central cavity of the ring. These lipid molecules were not aligned with the surrounding bilayer but protruded towards the periplasmic side. The characterization of the monomer and ring presented in this work sheds light into the structural dynamics of the c-subunit and its functional relevance.