---
title: "Hydrophobic Compounds Reshape Membrane Domains"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Jonathan Barnoud, Giulia Rossi, Siewert J. Marrink, and Luca Monticelli"         # Paper authors (required)
year: "2014"           # Publication year (required)
publication: "PLoS Computational Biology"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1371/journal.pcbi.1003873"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Small molecules
  - Solvents
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Barnoud, J., Rossi, G., Marrink, S. J., & Monticelli, L. (2014). Hydrophobic compounds reshape membrane domains. PLoS Computational Biology, 10(10), e1003873.

## Abstract

Cell membranes have a complex lateral organization featuring domains with distinct composition, also known as rafts, which play an essential role in cellular processes such as signal transduction and protein trafficking. In vivo, perturbations of membrane domains (e.g., by drugs or lipophilic compounds) have major effects on the activity of raft-associated proteins and on signaling pathways, but they are difficult to characterize because of the small size of the domains, typically below optical resolution. Model membranes, instead, can show macroscopic phase separation between liquid-ordered and liquid-disordered domains, and they are often used to investigate the driving forces of membrane lateral organization. Studies in model membranes have shown that some lipophilic compounds perturb membrane domains, but it is not clear which chemical and physical properties determine domain perturbation. The mechanisms of domain stabilization and destabilization are also unknown. Here we describe the effect of six simple hydrophobic compounds on the lateral organization of phase-separated model membranes consisting of saturated and unsaturated phospholipids and cholesterol. Using molecular simulations, we identify two groups of molecules with distinct behavior: aliphatic compounds promote lipid mixing by distributing at the interface between liquid-ordered and liquid-disordered domains; aromatic compounds, instead, stabilize phase separation by partitioning into liquid-disordered domains and excluding cholesterol from the disordered domains. We predict that relatively small concentrations of hydrophobic species can have a broad impact on domain stability in model systems, which suggests possible mechanisms of action for hydrophobic compounds in vivo.