---
title: "Helfrich model of membrane bending: From Gibbs theory of liquid interfaces to membranes as thick anisotropic elastic layers"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Felix Campelo, Clement Arnarez, Siewert J. Marrink, and Michael M. Kozlov"         # Paper authors (required)
year: "2014"           # Publication year (required)
publication: "Advances in colloid and interface science"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.cis.2014.01.018"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Solvents
  - Phopholipids
  - Methods
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Marrink, S. J., & Mark, A. E. (2003). The Mechanism of Vesicle Fusion as Revealed by Molecular Dynamics Simulations. Journal of the American Chemical Society, 125(37), 11144–11145. https://doi.org/10.1021/ja036138+

## Abstract

Helfrich model of membrane bending elasticity has been most influential in establishment and development of Soft-Matter Physics of lipid bilayers and biological membranes. Recently, Helfrich theory has been extensively used in Cell Biology to understand the phenomena of shaping, fusion and fission of cellular membranes. The general background of Helfrich theory on the one hand, and the ways of specifying the model parameters on the other, are important for quantitative treatment of particular biologically relevant membrane phenomena. Here we present the origin of Helfrich model within the context of the general Gibbs theory of capillary interfaces, and review the strategies of computing the membrane elastic moduli based on considering a lipid monolayer as a three-dimensional thick layer characterized by trans-monolayer profiles of elastic parameters. We present the results of original computations of these profiles by a state-of-the-art numerical approach.