---
title: "Phytochemicals Perturb Membranes and Promiscuously Alter Protein Function"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Helgi I. Ingólfsson, Pratima Thakur, Karl F. Herold, E. Ashley Hobart, Nicole B. Ramsey, Xavier Periole, Djurre H. de Jong, Martijn Zwama, Duygu Yilmaz, Katherine Hall, Thorsten Maretzky, Hugh C. Hemmings, Jr., Carl Blobel, Siewert J. Marrink, Armağan Koçer, Jon T. Sack, and Olaf S. Andersen"         # Paper authors (required)
year: "2014"           # Publication year (required)
publication: "ACS Chemical Biology"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/cb500086e"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Small molecules
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Ingólfsson, H. I., Thakur, P., Herold, K. F., Hobart, E. A., Ramsey, N. B., Periole, X., ... & Andersen, O. S. (2014). Phytochemicals perturb membranes and promiscuously alter protein function. ACS chemical biology, 9(8), 1788-1798.

## Abstract

A wide variety of phytochemicals are consumed for their perceived health benefits. Many of these phytochemicals have been found to alter numerous cell functions, but the mechanisms underlying their biological activity tend to be poorly understood. Phenolic phytochemicals are particularly promiscuous modifiers of membrane protein function, suggesting that some of their actions may be due to a common, membrane bilayer-mediated mechanism. To test whether bilayer perturbation may underlie this diversity of actions, we examined five bioactive phenols reported to have medicinal value: capsaicin from chili peppers, curcumin from turmeric, EGCG from green tea, genistein from soybeans, and resveratrol from grapes. We find that each of these widely consumed phytochemicals alters lipid bilayer properties and the function of diverse membrane proteins. Molecular dynamics simulations show that these phytochemicals modify bilayer properties by localizing to the bilayer/solution interface. Bilayer-modifying propensity was verified using a gramicidin-based assay, and indiscriminate modulation of membrane protein function was demonstrated using four proteins: membrane-anchored metalloproteases, mechanosensitive ion channels, and voltage-dependent potassium and sodium channels. Each protein exhibited similar responses to multiple phytochemicals, consistent with a common, bilayer-mediated mechanism. Our results suggest that many effects of amphiphilic phytochemicals are due to cell membrane perturbations, rather than specific protein binding.