---
title: "Lipid Organization of the Plasma Membrane"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Helgi I. Ingólfsson, Manuel N. Melo, Floris J. van Eerden, Clément Arnarez, Cesar A. Lopez, Tsjerk A. Wassenaar, Xavier Periole, Alex H. de Vries, D. Peter Tieleman, and Siewert J. Marrink"         # Paper authors (required)
year: "2014"           # Publication year (required)
publication: "Journal of the American Chemical Society"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/ja507832e"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Ingólfsson, H. I., Melo, M. N., Van Eerden, F. J., Arnarez, C., Lopez, C. A., Wassenaar, T. A., ... & Marrink, S. J. (2014). Lipid organization of the plasma membrane. Journal of the american chemical society, 136(41), 14554-14559.

## Abstract

The detailed organization of cellular membranes remains rather elusive. Based on large-scale molecular dynamics simulations, we provide a high-resolution view of the lipid organization of a plasma membrane at an unprecedented level of complexity. Our plasma membrane model consists of 63 different lipid species, combining 14 types of headgroups and 11 types of tails asymmetrically distributed across the two leaflets, closely mimicking an idealized mammalian plasma membrane. We observe an enrichment of cholesterol in the outer leaflet and a general non-ideal lateral mixing of the different lipid species. Transient domains with liquid-ordered character form and disappear on the microsecond time scale. These domains are coupled across the two membrane leaflets. In the outer leaflet, distinct nanodomains consisting of gangliosides are observed. Phosphoinositides show preferential clustering in the inner leaflet. Our data provide a key view on the lateral organization of lipids in one of life’s fundamental structures, the cell membrane.