---
title: "The power of coarse graining in biomolecular simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Helgi I. Ingólfsson, Cesar A. Lopez, Jaakko J. Uusitalo, Djurre H. de Jong, Srinivasa M. Gopal, Xavier Periole, and Siewert J. Marrink"         # Paper authors (required)
year: "2014"           # Publication year (required)
publication: "Wiley Interdisciplinary Reviews: Computational Molecular Science"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1002/wcms.1169"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Lipid membranes
  - Proteins
  - Self-assembly
  - DNA
  - Small molecules
  - Glycans
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Ingólfsson, H. I., Lopez, C. A., Uusitalo, J. J., de Jong, D. H., Gopal, S. M., Periole, X., & Marrink, S. J. (2014). The power of coarse graining in biomolecular simulations. Wiley Interdisciplinary Reviews: Computational Molecular Science, 4(3), 225-248.

## Abstract

Computational modeling of biological systems is challenging because of the multitude of spatial and temporal scales involved. Replacing atomistic detail with lower resolution, coarse grained (CG), beads has opened the way to simulate large-scale biomolecular processes on time scales inaccessible to all-atom models. We provide an overview of some of the more popular CG models used in biomolecular applications to date, focusing on models that retain chemical specificity. A few state-of-the-art examples of protein folding, membrane protein gating and self-assembly, DNA hybridization, and modeling of carbohydrate fibers are used to illustrate the power and diversity of current CG modeling.