---
title: "Global structural changes of an ion channel during its gating are followed by ion mobility mass spectrometry"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Albert Konijnenberg, Duygu Yilmaz, Helgi I. Ingólfsson, Anna Dimitrova, Siewert J. Marrink, Zhuolun Li, Catherine Vénien-Bryan, Frank Sobott, and Armağan Koçer"         # Paper authors (required)
year: "2014"           # Publication year (required)
publication: "Proceedings of the National Academy of Sciences"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1073/pnas.1413118111"            # URL of DOI (required)  
materials: "https://www.pnas.org/doi/abs/10.1073/pnas.1413118111#supplementary-materials"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Konijnenberg, A., Yilmaz, D., Ingólfsson, H. I., Dimitrova, A., Marrink, S. J., Li, Z., ... & Koçer, A. (2014). Global structural changes of an ion channel during its gating are followed by ion mobility mass spectrometry. Proceedings of the National Academy of Sciences, 111(48), 17170-17175.

## Abstract

Mechanosensitive ion channels are sensors probing membrane tension in all species; despite their importance and vital role in many cell functions, their gating mechanism remains to be elucidated. Here, we determined the conditions for releasing intact mechanosensitive channel of large conductance (MscL) proteins from their detergents in the gas phase using native ion mobility–mass spectrometry (IM-MS). By using IM-MS, we could detect the native mass of MscL from Escherichia coli, determine various global structural changes during its gating by measuring the rotationally averaged collision cross-sections, and show that it can function in the absence of a lipid bilayer. We could detect global conformational changes during MscL gating as small as 3%. Our findings will allow studying native structure of many other membrane proteins.