---
title: "MARTINI Coarse-Grained Model for Crystalline Cellulose Microfibers"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "César A. López, Giovanni Bellesia, Antonio Redondo, Paul Langan, Shishir P. S. Chundawat, Bruce E. Dale, Siewert J. Marrink, and S. Gnanakaran"         # Paper authors (required)
year: "2014"           # Publication year (required)
publication: "The Journal of Physical Chemistry B"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jp5105938"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Parametrization
  - Glycans
  - Polymers
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> López, C. A., Bellesia, G., Redondo, A., Langan, P., Chundawat, S. P., Dale, B. E., ... & Gnanakaran, S. (2015). MARTINI coarse-grained model for crystalline cellulose microfibers. The Journal of Physical Chemistry B, 119(2), 465-473.

## Abstract

Commercial-scale biofuel production requires a deep understanding of the structure and dynamics of its principal target: cellulose. However, an accurate description and modeling of this carbohydrate structure at the mesoscale remains elusive, particularly because of its overwhelming length scale and configurational complexity. We have derived a set of MARTINI coarse-grained force field parameters for the simulation of crystalline cellulose fibers. The model is adapted to reproduce different physicochemical and mechanical properties of native cellulose Iβ. The model is able not only to handle a transition from cellulose Iβ to another cellulose allomorph, cellulose IIII, but also to capture the physical response to temperature and mechanical bending of longer cellulose nanofibers. By developing the MARTINI model of a solid cellulose crystalline fiber from the building blocks of a soluble cellobiose coarse-grained model, we have provided a systematic way to build MARTINI models for other crystalline biopolymers.