---
title: "Disaccharides Impact the Lateral Organization of Lipid Membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Gemma Moiset, Cesar A. López, Rianne Bartelds, Lukasz Syga, Egon Rijpkema, Abhishek Cukkemane, Marc Baldus, Bert Poolman, and Siewert J. Marrink"         # Paper authors (required)
year: "2014"           # Publication year (required)
publication: "Journal of the American Chemical Society"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/ja505476c"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Glycans
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Moiset, G., López, C. A., Bartelds, R., Syga, L., Rijpkema, E., Cukkemane, A., ... & Marrink, S. J. (2014). Disaccharides impact the lateral organization of lipid membranes. Journal of the American Chemical Society, 136(46), 16167-16175.

## Abstract

Disaccharides are well-known for their membrane protective ability. Interaction between sugars and multicomponent membranes, however, remains largely unexplored. Here, we combine molecular dynamics simulations and fluorescence microscopy to study the effect of mono- and disaccharides on membranes that phase separate into Lo and Ld domains. We find that nonreducing disaccharides, sucrose and trehalose, strongly destabilize the phase separation leading to uniformly mixed membranes as opposed to monosaccharides and reducing disaccharides. To unveil the driving force for this process, simulations were performed in which the sugar linkage was artificially modified. The availability of accessible interfacial binding sites that can accommodate the nonreducing disaccharides is key for their strong impact on lateral membrane organization. These exclusive interactions between the nonreducing sugars and the membranes may rationalize why organisms such as yeasts, tardigrades, nematodes, bacteria, and plants accumulate sucrose and trehalose, offering cell protection under anhydrobiotic conditions. The proposed mechanism might prove to be a more generic way by which surface bound agents could affect membranes.