---
title: "The activation mode of the mechanosensitive ion channel, MscL, by lysophosphatidylcholine differs from tension-induced gating"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Nobina Mukherjee, Mac Donald Jose, Jan Peter Birkner, Martin Walko, Helgi I. Ingólfsson, Anna Dimitrova, Clément Arnarez, Siewert J. Marrink, and Armağan Koçer"         # Paper authors (required)
year: "2014"           # Publication year (required)
publication: "The FASEB Journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1096/fj.14-251579"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Mukherjee, N., Birkner, J. P., Walko, M., Ingólfsson, H. I., Dimitrova, A., Arnarez, C., ... & Koçer, A. (2014). The activation mode of the mechanosensitive ion channel, MscL, by lysophosphatidylcholine differs from tension-induced gating. The FASEB Journal, 28(10), 4292.

## Abstract

One of the best-studied mechanosensitive channels is the mechanosensitive channel of large conductance (MscL). MscL senses tension in the membrane evoked by an osmotic down shock and directly couples it to large conformational changes leading to the opening of the channel. Spectroscopic techniques offer unique possibilities to monitor these conformational changes if it were possible to generate tension in the lipid bilayer, the native environment of MscL, during the measurements. To this end, asymmetric insertion of L-α-lysophosphatidylcholine (LPC) into the lipid bilayer has been effective; however, how LPC activates MscL is not fully understood. Here, the effects of LPC on tension-sensitive mutants of a bacterial MscL and on MscL homologs with different tension sensitivities are reported, leading to the conclusion that the mode of action of LPC is different from that of applied tension. Our results imply that LPC shifts the free energy of gating by interfering with MscL-membrane coupling. Furthermore, we demonstrate that the fine-tuned addition of LPC can be used for controlled activation of MscL in spectroscopic studies.