---
title: "Simulation of polyethylene glycol and calcium-mediated membrane fusion"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Martina Pannuzzo, Djurre H. De Jong, Antonio Raudino, and Siewert J. Marrink"         # Paper authors (required)
year: "2014"           # Publication year (required)
publication: "The Journal of Chemical Physics"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1063/1.4869176"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Polymers
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Pannuzzo, M., De Jong, D. H., Raudino, A., & Marrink, S. J. (2014). Simulation of polyethylene glycol and calcium-mediated membrane fusion. The Journal of Chemical Physics, 140(12).

## Abstract

We report on the mechanism of membrane fusion mediated by polyethylene glycol (PEG) and Ca2+ by means of a coarse-grained molecular dynamics simulation approach. Our data provide a detailed view on the role of cations and polymer in modulating the interaction between negatively charged apposed membranes. The PEG chains cause a reduction of the inter-lamellar distance and cause an increase in concentration of divalent cations. When thermally driven fluctuations bring the membranes at close contact, a switch from cis to trans Ca2+-lipid complexes stabilizes a focal contact acting as a nucleation site for further expansion of the adhesion region. Flipping of lipid tails induces subsequent stalk formation. Together, our results provide a molecular explanation for the synergistic effect of Ca2+ and PEG on membrane fusion.