---
title: "About the Martini FF Initiative"
subtitle: "General Purpose Coarse-Grained Force Field"
toc: true
---

<hr>

The Martini force field is a coarse-grain (CG) force field suited for molecular dynamics simulations of biomolecular systems. The force field has been parametrized in a systematic way, combining top-down and bottum-up strategies: Non-bonded interactions are based on the reproduction of experimental partitioning free energies between polar and apolar phases of a large number of chemical compounds, whereas bonded interactions are derived from reference all-atom simulations.

The model uses a four-to-one mapping, i.e. on average four heavy atoms and associated hydrogens are represented by a single interaction center. In order to keep the model simple, only four main types of interaction sites are defined: polar, non-polar, apolar, and charged. Each particle type has a number of subtypes, which allow for an accurate representation of the chemical nature of the underlying atomistic structure.

![Martini mapping examples of selected molecules: (A) Standard water particle representing four water molecules, (B) Polarizable water molecule with embedded charges, (C) DMPC lipid, (D) Polysaccharide fragment, (E) Peptide, (F) DNA fragment, (G) Polystyrene fragment, (H) Fullerene molecule. In all cases Martini CG beads are shown as cyan transparent beads overlaying the atomistic structure.](images/banner1.gif)

Currently topologies are available for many lipids and surfactant molecules, including cholesterol, and for all amino acids and nucleotides as well as for a variety of sugars, polymers, and nanoparticles. Scripts are furthermore available to build topologies for arbitrary peptides, proteins, polynucleotides, to add elastic networks, and to move between coarse-grained and atomistic representations.

## Key Martini papers
-  **C. Hilpert, L. Beranger, P.C.T. Souza, P.A. Vainikka, V. Nieto, S.J. Marrink, L. Monticelli, G. Launay.** Facilitating CG Simulations with MAD: The MArtini Database Server. J. Chem. Inf. Model., 2023, online. [doi:10.1021/acs.jcim.2c01375](https://doi.org/10.1021/acs.jcim.2c01375)
-  **S.J. Marrink, L. Monticelli, M.N. Melo, R. Alessandri, D.P. Tieleman, P.C.T. Souza.** Two decades of Martini: Better beads, broader scope. Wires Computational Molecular Science, 13(1), e1620, 2023. [https://wires.onlinelibrary.wiley.com/doi/full/10.1002/wcms.1620](https://wires.onlinelibrary.wiley.com/doi/full/10.1002/wcms.1620)
-  **R. Alessandri, J. Barnoud, A.S. Gertsen, I. Patmanidis, A.H. de Vries, P.C.T. Souza, S.J. Marrink.** Martini 3 Coarse-Grained Force Field: Small Molecules. Advanced Theory and Simulations 5, 2100391, 2022. [https://onlinelibrary.wiley.com/doi/full/10.1002/adts.202100391](https://onlinelibrary.wiley.com/doi/full/10.1002/adts.202100391)
-  **R. Alessandri, F. Grünewald, S.J. Marrink.** The Martini Model in Materials Science, Adv. Materials 33:2008635, 2021. [https://doi.org/10.1002/adma.202008635](https://onlinelibrary.wiley.com/doi/10.1002/adma.202008635)
-  **P.C.T. Souza, R. Alessandri, J. Barnoud, S. Thallmair, I. Faustino, ... S.J. Marrink.** Martini 3: a general purpose force field for coarse-grained molecular dynamics. Nature Methods 18:382–388, 2021. [doi:org/10.1038/s41592-021-01098-3](https://www.nature.com/articles/s41592-021-01098-3)
-  **B.M.H. Bruininks, P.C.T. Souza, S.J. Marrink.** A Practical View of the Martini Force Field. Biomolecular Simulations, 105-127, 2019. [doi:10.1007/978-1-4939-9608-7_5](https://link.springer.com/protocol/10.1007/978-1-4939-9608-7_5), [pdf-reprint](http://cgmartini.nl/images/practical-view-Martini-biomolsim19.pdf).
-  **S.J. Marrink, D.P. Tieleman.** Perspective on the Martini model. Chem. Soc. Rev., 42:6801-6822, 2013. [open access](http://pubs.rsc.org/en/Content/ArticleLanding/2013/CS/C3CS60093A)
-  **D.H. de Jong, G. Singh, W.F.D. Bennett, C. Arnarez, T.A. Wassenaar, L.V. Schäfer, X. Periole, D.P. Tieleman, S.J. Marrink.** Improved parameters for the Martini coarse-grained protein force field, JCTC, 9:687–697, 2013. [open access](http://pubs.acs.org.proxy-ub.rug.nl/doi/abs/10.1021/ct300646g)
-  **L. Monticelli, S.K. Kandasamy, X. Periole, R.G. Larson, D.P. Tieleman, S.J. Marrink.** The MARTINI coarse grained forcefield: extension to proteins. JCTC, 4:819-834, 2008. [abstract](http://pubs.acs.org/doi/abs/10.1021/ct700324x).
-  **S.J. Marrink, H.J. Risselada, S. Yefimov, D.P. Tieleman, A.H. de Vries.** The MARTINI forcefield: coarse grained model for biomolecular simulations. JPC-B, 111:7812-7824, 2007. [abstract](http://pubs.acs.org/doi/abs/10.1021/jp071097f).

More details about the Martini model can be found in the publications listed on [Google Scholar's MARTINI page](https://scholar.google.com/citations?hl=en&user=N71qbKgAAAAJ&authuser=1&scilu=&scisig=AMD79ooAAAAAXYhf6q67IkURG2cS-8dBePGULFimfV6R&gmla=AJsN-F4gekbhRj5jGDDQ-2ZezpCQFFcUJelbtNJUbwGvBhAhGP1CZFpHTbOfMLkdQORvZEsOBhwJHTBz7JR1ycxFpMUFLPfx20u2RsKTZcY07yFCgWomRtk&sciund=17182581380692271779&gmla=AJsN-F7zwshWPn3qWJvj5WMNIKTZcSlCVsjcuN8H-d89y5sMvGqCRn4Zf6INruiC1hmr0REahmpk_ZyW-LfP0LclQU1rHY3AZSDiSUzqSQqZKzG3zi2kWfg&sciund=7904069873642454661&gmla=AJsN-F7QJXiZtQm3yGuJW0aIcGL0j-afJhdWYjVd-lynBhHDC8E_gIAjywxCR0-RSHW7BDE_CzMyZeft1Yqyc-V7qAO_g7IJf3MkOhtq7nX1KyXqkD2yfc0&sciund=8022746687600405948&gmla=AJsN-F7gjKKlV_3BhuUvAFAGgT0xI49NgVhjFj3Uc76PXK000c0vy6Myq1s7MDc1pNnkCQJlvE9u8smPVdIqDl_IymPTwnY12gZHcy6woofAuJ1q1ZpCg4w&sciund=16674144928985563961&gmla=AJsN-F6leNqa65j_ogNMGt0rgI6aqp6_ObIyx3TIXwFdIN8TvVDbIqJ7RUnoc8UGnQRsicpp_-1GxFrayMAcL3h3UQhuJ2R0NJ6hvL0n-0BFdxHOUIv2sYg&sciund=5409462464681415128&gmla=AJsN-F7t8Tt0qwjc3qVwmyz8ly4PUg0SHlPiarAvi1Cg5LVDI0g1KhBO2A4SxWuGtWWdUNreT3PnVKTbky0lCKJOAPnD_cWOUFRxljMNqpdeWtg7wuJrKZs&sciund=7673021604821726893&gmla=AJsN-F5K2ep_mOwJvwA9LSOEUi0Rlaixki1X4dZOjdJ3W6Ao_e2jeJg7D4lzDt0kCWjMYQ7MXQWY0HVKDwNujcrN7xtjlvp5mCNi28V1p_oqpDIGJqC5nwY&sciund=2588055821420545806&gmla=AJsN-F7mHWJbhrnqQVDslEbjQydP5zrClGb41SpF8MjQBBgkjWBBjM56lDjhZdsTgZYGqyxs7B02lGG7QeZsnODY9esS9aswGmw6xZGpG6qwBQ_QkvyxfIA&sciund=14925947861697387916&gmla=AJsN-F7UfQxIKnZLYq-bu_X4bINT2PW5Ow8kvy5qLSn0Nd8-XrzxVxFjycOYMYLQhbpfIhsUl_17Kxh8_nKaJabNUrI02EGOa96VoA6JJntBTy7Nr6262RI&sciund=590521644600298237&gmla=AJsN-F5Mi_hQwDCyIc4vZk8aghpPviy5aggjCrzBOXblsAldPRV-mCv2mKZ5o-V6T_L9_4f7H-l7YIvoEPnXJy4Hibdu3BDKGQB381_NtgozcOAXIWWPSF8&sciund=710238946039875334&gmla=AJsN-F7x70lj78XeS3dMFI0yWxcJpkpZVdGraXIViNReo0aguCEvCx3Qbxm0N8cMGKmsp9D2Pn-syPfhefUjkHe3Vo3O4h8Jwr12nJh-Sw9M7nFGa18ecg4&sciund=4096334398360942426&gmla=AJsN-F4euJP7V9-9E0HiW4H8PkikG5Keo-C_oZHk2QKpbhMFvTzuj3sdx3j1CG2kwRpOygN4-BBAzbRzzpZQt4IDMkttiRoWMf8ihQT03rXZiS74377Y7AA&sciund=6160224723761174820&gmla=AJsN-F7hBvHJmAeLcqYU4-_7yAvti1qt9rQy101yJOfEfjp3q86WcLQaeEmTdxojuzxBcZodiPSAN_SyY0LKjkhEodHn56lrhaVUFQPkqG7Jprkff&gmla=AJsN-F7e1R281klhwqPdyzRD33Kq86GWCOXPJQBjFnWa57ozGm81gisglyk1TGfkkgvVRKUp6xgmXHexni4p2weKhg0-v-4wUulw4MEMgHInWfM3T-TGLSs&sciund=12676941147796706303).