---
pagetitle: "Martini CG Force-Field"
page-layout: custom
section-divs: false
toc: false
css: index.css
editor: source
execute:
  echo: false
description: | 
  A General Purpose Coarse-Grained Force Field.
hide-description: true
resources: 
  - images/martini.gif
---

::: {.hero-banner}


::: {.content-block}

::: {.hero-text}
<font size="6">  
    <font color="#39729e"> **Welcome to the Martini FF Initiative** </font>
</font>  <font size="5">  
    <font color="#363a3e"> A General Purpose Coarse-Grained Force Field </font>
</font> 

<font size="4">  
    <font color="#363a3e"> Simplify your simulations and unlock new insights into complex biomolecular systems by joining the Martini community &#128640;&#128640;  </font>
</font> 


::: {.hero-buttons}
[Downloads](docs/downloads/index.qmd){.btn-action-primary .btn-action .btn .btn-success .btn-lg role="button"}
[Publications](docs/publications/index.qmd){.btn-action-primary .btn-action .btn .btn-info .btn-lg role="button"}
::: 
:::

::: {.hero-animation}

```{r}
source("carousel.R")
carousel("gallery-carousel", 5000, 
         yaml.load_file("carousel.yml"))
```
:::

:::
:::

::: {.content-block}
::: {.features}

::: {.feature}
### Visualizing Martini (using VMD)
Some of the VMD commands that can be used to visualize Martini CG systems.

::: {.learn-more}
[Learn more »](docs/tutorials/martini2/visualizing_martini.qmd)
:::
:::

::: {.feature}
### Simulating lipid bilayers
Studying membrane properties through molucular dynamics simulations with Martini CG lipid models.

::: {.learn-more}
[Learn more »](docs/tutorials/martini2/lipids_and_lipidome.qmd)
:::
:::

::: {.feature}
### Parametrizing new molecules
How to build a Martini topology for new molecules.

::: {.learn-more}
[Learn more »](docs/tutorials/martini2/parametrizing.qmd)
:::
:::

::: {.feature}
### Simulating soluble and membrane proteins
Regular workflow and protocols to set up Martini CG simulations of proteins.

::: {.learn-more}
[Learn more »](docs/tutorials/martini2/proteins.qmd)
:::
:::

::: {.feature}
### Setting up double-stranded DNA
How to set up and try out DNA Martini simulations. 

::: {.learn-more}
[Learn more »](docs/tutorials/martini2/dna.qmd)
:::
:::

::: {.feature}
### Simulating polymers
Parametrization and simulation of polymers.

::: {.learn-more}
[Learn more »](docs/tutorials/martini2/polymers.qmd)
:::
:::

:::
:::


::: {.get-started .alt-background}
::: {.content-block}

[Tutorials](docs/tutorials/index.qmd){.btn-action-primary  .btn-action .btn .btn-success .btn-lg role="button" style="margin-top: 1em;"}

:::
:::


