---
title: "Resolving Donor–Acceptor Interfaces and Charge Carrier Energy Levels of Organic Semiconductors with Polar Side Chains"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Riccardo Alessandri, Selim Sami, Jonathan Barnoud, Alex H. de Vries, Siewert J. Marrink and Remco W. A. Havenith"         # Paper authors (required)
year: "2020"           # Publication year (required)
publication: "Advanced Functional Materials"    # Journal or similar (required)
preprint: "https://chemrxiv.org/engage/chemrxiv/article-details/60c74b9abb8c1a44713db259"       # URL to prepint page (optional)  
doi: "https://doi.org/10.1002/adfm.202004799"            # URL of DOI (required)  
materials: "https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fadfm.202004799&file=adfm202004799-sup-0001-SuppMat.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Materials science
  - Polymers
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Alessandri, R., Sami, S., Barnoud, J., de Vries, A. H., Marrink, S. J., & Havenith, R. W. (2020). Resolving donor–acceptor interfaces and charge carrier energy levels of organic semiconductors with polar side chains. Advanced Functional Materials, 30(46), 2004799.

## Abstract

Organic semiconductors consisting of molecules bearing polar side chains have been proposed as potential candidates to overcome the limitations of organic photovoltaics owing to their enhanced dielectric constant. However, introducing such polar molecules in photovoltaic devices has not yet resulted in higher efficiencies. A microscopic understanding of the impact of polar side chains on electronic and structural properties of organic semiconductors is paramount to rationalize their effect. Here, the impact of such side chains on bulk heterojunction overall morphology, molecular configurations at donor–acceptor (DA) interfaces, and charge carrier energy levels is investigated. The multiscale modeling approach used allows to resolve DA interfaces with atomistic resolution while taking into account the large-scale self-organization process which takes place during the processing of an organic thin film. The polar fullerene-based blends are compared to the well-studied reference system, poly(3-hexyl-thiophene) (P3HT):phenyl-C61-butyric acid methyl ester (PCBM). Introduction of polar side chains on a similar molecular scaffold does not affect molecular orientations at the DA interfaces; such orientations are, however, found to be affected by processing conditions and polymer molecular weight. Polar side chains, instead, are found to impact considerably the charge carrier energy levels of the organic blend, causing electrostatic-induced broadening of these levels.