---
title: "A molecular view on the escape of lipoplexed DNA from the endosome"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Bart MH Bruininks, Paulo CT Souza, Helgi Ingolfsson and Siewert J Marrink"         # Paper authors (required)
year: "2020"           # Publication year (required)
publication: "Elife"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.7554/eLife.52012"            # URL of DOI (required)  
materials: "https://datadryad.org/stash/dataset/doi:10.5061/dryad.fqz612jq4"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - DNA
  - Lipid membranes
  - Vesicles
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Bruininks, B. M., Souza, P. C., Ingolfsson, H., & Marrink, S. J. (2020). A molecular view on the escape of lipoplexed DNA from the endosome. Elife, 9, e52012.

## Abstract

The use of non-viral vectors for in vivo gene therapy could drastically increase safety, whilst reducing the cost of preparing the vectors. A promising approach to non-viral vectors makes use of DNA/cationic liposome complexes (lipoplexes) to deliver the genetic material. Here we use coarse-grained molecular dynamics simulations to investigate the molecular mechanism underlying efficient DNA transfer from lipoplexes. Our computational fusion experiments of lipoplexes with endosomal membrane models show two distinct modes of transfection: parallel and perpendicular. In the parallel fusion pathway, DNA aligns with the membrane surface, showing very quick release of genetic material shortly after the initial fusion pore is formed. The perpendicular pathway also leads to transfection, but release is slower. We further show that the composition and size of the lipoplex, as well as the lipid composition of the endosomal membrane, have a significant impact on fusion efficiency in our models.