---
title: "Piezo1 Forms Specific, Functionally Important Interactions with Phosphoinositides and Cholesterol"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Amanda Buyan, Charles D. Cox, Jonathan Barnoud, Jinyuan Li, Hannah S.M. Chan, Boris Martinac, Siewert J. Marrink, Ben Corry"         # Paper authors (required)
year: "2020"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2020.07.043"            # URL of DOI (required)  
materials: "https://www.sciencedirect.com/science/article/pii/S0006349520306809#app2"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Buyan, A., Cox, C. D., Barnoud, J., Li, J., Chan, H. S., Martinac, B., ... & Corry, B. (2020). Piezo1 forms specific, functionally important interactions with phosphoinositides and cholesterol. Biophysical journal, 119(8), 1683-1697.

## Abstract

Touch, hearing, and blood pressure regulation require mechanically gated ion channels that convert mechanical stimuli into electrical currents. One such channel is Piezo1, which plays a key role in the transduction of mechanical stimuli in humans and is implicated in diseases, such as xerocytosis and lymphatic dysplasia. There is building evidence that suggests Piezo1 can be regulated by the membrane environment, with the activity of the channel determined by the local concentration of lipids, such as cholesterol and phosphoinositides. To better understand the interaction of Piezo1 with its environment, we conduct simulations of the protein in a complex mammalian bilayer containing more than 60 different lipid types together with electrophysiology and mutagenesis experiments. We find that the protein alters its local membrane composition, enriching specific lipids and forming essential binding sites for phosphoinositides and cholesterol that are functionally relevant and often related to Piezo1-mediated pathologies. We also identify a number of key structural connections between the propeller and pore domains located close to lipid-binding sites.