---
title: "Membrane mediated toppling mechanism of the folate energy coupling factor transporter"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Ignacio Faustino, Haleh Abdizadeh, Paulo C. T. Souza, Aike Jeucken, Weronika K. Stanek, Albert Guskov, Dirk J. Slotboom & Siewert J. Marrink"         # Paper authors (required)
year: "2020"           # Publication year (required)
publication: "Nature Communications"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s41467-020-15554-9"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/s41467-020-15554-9#Sec16"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
  - Multi-scale
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Faustino, I., Abdizadeh, H., Souza, P. C., Jeucken, A., Stanek, W. K., Guskov, A., ... & Marrink, S. J. (2020). Membrane mediated toppling mechanism of the folate energy coupling factor transporter. Nature Communications, 11(1), 1763.

## Abstract

Energy coupling factor (ECF) transporters are responsible for the uptake of micronutrients in bacteria and archaea. They consist of an integral membrane unit, the S-component, and a tripartite ECF module. It has been proposed that the S-component mediates the substrate transport by toppling over in the membrane when docking onto an ECF module. Here, we present multi-scale molecular dynamics simulations and in vitro experiments to study the molecular toppling mechanism of the S-component of a folate-specific ECF transporter. Simulations reveal a strong bending of the membrane around the ECF module that provides a driving force for toppling of the S-component. The stability of the toppled state depends on the presence of non-bilayer forming lipids, as confirmed by folate transport activity measurements. Together, our data provide evidence for a lipid-dependent toppling-based mechanism for the folate-specific ECF transporter, a mechanism that might apply to other ECF transporters.