---
title: "Molecular dynamics simulations in photosynthesis"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Nicoletta Liguori, Roberta Croce, Siewert J. Marrink and Sebastian Thallmair"         # Paper authors (required)
year: "2020"           # Publication year (required)
publication: "Photosynthesis research"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1007/s11120-020-00741-y"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Proteins
  - Enhanced sampling
  - Cofactors
  - Lipid membranes
  - Multi-scale
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Liguori, N., Croce, R., Marrink, S. J., & Thallmair, S. (2020). Molecular dynamics simulations in photosynthesis. Photosynthesis research, 144(2), 273-295.

## Abstract

Photosynthesis is regulated by a dynamic interplay between proteins, enzymes, pigments, lipids, and cofactors that takes place on a large spatio-temporal scale. Molecular dynamics (MD) simulations provide a powerful toolkit to investigate dynamical processes in (bio)molecular ensembles from the (sub)picosecond to the (sub)millisecond regime and from the Å to hundreds of nm length scale. Therefore, MD is well suited to address a variety of questions arising in the field of photosynthesis research. In this review, we provide an introduction to the basic concepts of MD simulations, at atomistic and coarse-grained level of resolution. Furthermore, we discuss applications of MD simulations to model photosynthetic systems of different sizes and complexity and their connection to experimental observables. Finally, we provide a brief glance on which methods provide opportunities to capture phenomena beyond the applicability of classical MD.