---
title: "Caught in the Act: Mechanistic Insight into Supramolecular Polymerization-Driven Self-Replication from Real-Time Visualization"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Sourav Maity, Jim Ottelé, Guillermo Monreal Santiago, Pim W. J. M. Frederix, Peter Kroon, Omer Markovitch, Marc C. A. Stuart, Siewert J. Marrink, Sijbren Otto, and Wouter H. Roos"         # Paper authors (required)
year: "2020"           # Publication year (required)
publication: "Journal of the American Chemical Society"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jacs.0c02635"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/jacs.0c02635?goto=supporting-info"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Multi-scale
  - Polymers
  - Small molecules
  - Self-assembly
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Maity, S., Ottelé, J., Santiago, G. M., Frederix, P. W., Kroon, P., Markovitch, O., ... & Roos, W. H. (2020). Caught in the act: mechanistic insight into supramolecular polymerization-driven self-replication from real-time visualization. Journal of the American Chemical Society, 142(32), 13709-13717.

## Abstract

Self-assembly features prominently in fields ranging from materials science to biophysical chemistry. Assembly pathways, often passing through transient intermediates, can control the outcome of assembly processes. Yet, the mechanisms of self-assembly remain largely obscure due to a lack of experimental tools for probing these pathways at the molecular level. Here, the self-assembly of self-replicators into fibers is visualized in real-time by high-speed atomic force microscopy (HS-AFM). Fiber growth requires the conversion of precursor molecules into six-membered macrocycles, which constitute the fibers. HS-AFM experiments, supported by molecular dynamics simulations, revealed that aggregates of precursor molecules accumulate at the sides of the fibers, which then diffuse to the fiber ends where growth takes place. This mechanism of precursor reservoir formation, followed by one-dimensional diffusion, which guides the precursor molecules to the sites of growth, reduces the entropic penalty associated with colocalizing precursors and growth sites and constitutes a new mechanism for supramolecular polymerization.