---
title: "Charge-dependent interactions of monomeric and filamentous actin with lipid bilayers"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Carsten F. E. Schroer, Lucia Baldauf, Lennard van Buren, Tsjerk A. Wassenaar, Manuel N. Melo, Gijsje H. Koenderink, and Siewert J. Marrink"         # Paper authors (required)
year: "2020"           # Publication year (required)
publication: "Proceedings of the National Academy of Sciences"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1073/pnas.1914884117"            # URL of DOI (required)  
materials: "https://www.pnas.org/doi/abs/10.1073/pnas.1914884117#supplementary-materials"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Polymers
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Schroer, C. F., Baldauf, L., van Buren, L., Wassenaar, T. A., Melo, M. N., Koenderink, G. H., & Marrink, S. J. (2020). Charge-dependent interactions of monomeric and filamentous actin with lipid bilayers. Proceedings of the National Academy of Sciences, 117(11), 5861-5872.

## Abstract

The cytoskeletal protein actin polymerizes into filaments that are essential for the mechanical stability of mammalian cells. In vitro experiments showed that direct interactions between actin filaments and lipid bilayers are possible and that the net charge of the bilayer as well as the presence of divalent ions in the buffer play an important role. In vivo, colocalization of actin filaments and divalent ions are suppressed, and cells rely on linker proteins to connect the plasma membrane to the actin network. Little is known, however, about why this is the case and what microscopic interactions are important. A deeper understanding is highly beneficial, first, to obtain understanding in the biological design of cells and, second, as a possible basis for the building of artificial cortices for the stabilization of synthetic cells. Here, we report the results of coarse-grained molecular dynamics simulations of monomeric and filamentous actin in the vicinity of differently charged lipid bilayers. We observe that charges on the lipid head groups strongly determine the ability of actin to adsorb to the bilayer. The inclusion of divalent ions leads to a reversal of the binding affinity. Our in silico results are validated experimentally by reconstitution assays with actin on lipid bilayer membranes and provide a molecular-level understanding of the actin–membrane interaction.