---
title: "Localization Preference of Antimicrobial Peptides on Liquid-Disordered Membrane Domains"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Juanjuan Su, Siewert J. Marrink and Manuel N. Melo"         # Paper authors (required)
year: "2020"           # Publication year (required)
publication: "Frontiers in cell and developmental biology"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.3389/fcell.2020.00350"            # URL of DOI (required)  
materials: "https://www.frontiersin.org/articles/10.3389/fcell.2020.00350/full#h9"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Polymers
  - Lipid membranes
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Su, J., Marrink, S. J., & Melo, M. N. (2020). Localization preference of antimicrobial peptides on liquid-disordered membrane domains. Frontiers in cell and developmental biology, 8, 350.

## Abstract

We performed coarse-grained simulations of the antimicrobial peptides Magainin-2, BP100, MSI-103, and MSI-78 on a phase-separated membrane to study their preference for the different domains. All the peptides displayed a clear preference for the liquid-disordered (Ld) phase over the liquid-ordered (Lo) one. For BP100, MSI-103, and MSI-78 there was a further preference of the peptides for the domain interface. The peptides’ preference toward the disordered phase was shown to reflect a penalization of lipid–lipid interaction enthalpy in the Lo phase, when in the vicinity of peptides. Similar results were observed at the two studied concentrations, although Ld phase saturation at the higher concentration drove some of the peptide excess to the Lo phase. Magainin-2 and MSI-103 were found to dimerize, in agreement with available experimental data. Interestingly, at high concentrations of Magainin-2 toroidal pores spontaneously formed in the Ld phase. We performed additional simulations to characterize this phenomenon, which is likely related to Magainin-2’s membranolytic action.