---
title: "Molecular mechanism for bidirectional regulation of CD44 for lipid raft affiliation by palmitoylations and PIP2"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Fude Sun, Carsten F. E. Schroer, Carlos R. Palacios, Lida Xu, Shi-Zhong Luo and Siewert J. Marrink"         # Paper authors (required)
year: "2020"           # Publication year (required)
publication: "PLoS Computational Biology"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1371/journal.pcbi.1007777"            # URL of DOI (required)  
materials: "https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007777#sec012"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Sun, F., Schroer, C. F., Palacios, C. R., Xu, L., Luo, S. Z., & Marrink, S. J. (2020). Molecular mechanism for bidirectional regulation of CD44 for lipid raft affiliation by palmitoylations and PIP2. PLoS Computational Biology, 16(4), e1007777.

## Abstract

The co-localization of Cluster-of-Differentiation-44 protein (CD44) and cytoplasmic adaptors in specific membrane environments is crucial for cell adhesion and migration. The process is controlled by two different pathways: On the one hand palmitoylation keeps CD44 in lipid raft domains and disables the linking to the cytoplasmic adaptor, whereas on the other hand, the presence of phosphatidylinositol-4,5-biphosphate (PIP2) lipids accelerates the formation of the CD44-adaptor complex. The molecular mechanism explaining how CD44 is migrating into and out of the lipid raft domains and its dependence on both palmitoylations and the presence of PIP2 remains, however, elusive. In this study, we performed extensive molecular dynamics simulations to study the raft affinity and translocation of CD44 in phase separated model membranes as well as more realistic plasma membrane environments. We observe a delicate balance between the influence of the palmitoylations and the presence of PIP2 lipids: whereas the palmitoylations of CD44 increases the affinity for raft domains, PIP2 lipids have the opposite effect. Additionally, we studied the association between CD44 and the membrane adaptor FERM in dependence of these factors. We find that the presence of PIP2 lipids allows CD44 and FERM to associate in an experimentally observed binding mode whereas the highly palmitoylated species shows no binding affinity. Together, our results shed light on the sophisticated mechanism on how membrane translocation and peripheral protein association can be controlled by both protein modifications and membrane composition.