---
title: "Martini coarse-grained models of imidazolium-based ionic liquids: from nanostructural organization to liquid-liquid extraction"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Luis Itza Vazquez-Salazar, Michele Selle, Alex H De Vries, Siewert-Jan Marrink, Paulo CT Souza"         # Paper authors (required)
year: "2020"           # Publication year (required)
publication: "Green Chemistry"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "DOI https://doi.org/10.1039/D0GC01823F"            # URL of DOI (required)  
materials: "https://www.rsc.org/suppdata/d0/gc/d0gc01823f/d0gc01823f1.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Solvents
  - Journal article
  - Parametrization
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Vazquez-Salazar, L. I., Selle, M., De Vries, A. H., Marrink, S. J., & Souza, P. C. (2020). Martini coarse-grained models of imidazolium-based ionic liquids: from nanostructural organization to liquid–liquid extraction. Green Chemistry, 22(21), 7376-7386.

## Abstract

Ionic liquids (ILs) are remarkable green solvents, which find applications in many areas of nano- and biotechnology including extraction and purification of value-added compounds or fine chemicals. These liquid salts possess versatile solvation properties that can be tuned by modifications in the cation or anion structure. So far, in contrast to the great success of theoretical and computational methodologies applied to other fields, only a few IL models have been able to bring insights towards the rational design of such solvents. In this work, we develop coarse-grained (CG) models for imidazolium-based ILs using a new version of the Martini force field. The model is able to reproduce the main structural properties of pure ILs, including spatial heterogeneity and global densities over a wide range of temperatures. More importantly, given the high intermolecular compatibility of the Martini force field, this new IL CG model opens the possibility of large-scale simulations of liquid–liquid extraction experiments. As examples, we show two applications, namely the extraction of aromatic molecules from a petroleum oil model and the extraction of omega-3 polyunsaturated fatty acids from a fish oil model. In semi-quantitative agreement with the experiments, we show how the extraction capacity and selectivity of the IL could be affected by the cation chain length or addition of co-solvents.