---
title: "Evidence for Cardiolipin Binding Sites on the Membrane-Exposed Surface of the Cytochrome bc1"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Clement Arnarez, Jean-Pierre Mazat, Juan Elezgaray, Siewert-J Marrink, and Xavier Periole"         # Paper authors (required)
year: "2013"           # Publication year (required)
publication: "Journal of the American Chemical Society"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/ja310577u"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Arnarez, C., Mazat, J. P., Elezgaray, J., Marrink, S. J., & Periole, X. (2013). Evidence for cardiolipin binding sites on the membrane-exposed surface of the cytochrome bc 1. Journal of the American Chemical Society, 135(8), 3112-3120.

## Abstract

The respiratory chain is located in the inner membrane of mitochondria and produces the major part of the ATP used by a cell. Cardiolipin (CL), a double charged phospholipid composing ∼10–20% of the mitochondrial membrane, plays an important role in the function and supramolecular organization of the respiratory chain complexes. We present an extensive set of coarse-grain molecular dynamics (CGMD) simulations aiming at the determination of the preferential interfaces of CLs on the respiratory chain complex III (cytochrome bc1, CIII). Six CL binding sites are identified, including the CL binding sites known from earlier structural studies and buried into protein cavities. The simulations revealed the importance of two subunits of CIII (G and K in bovine heart) for the structural integrity of these internal CL binding sites. In addition, new binding sites are found on the membrane-exposed protein surface. The reproducibility of these binding sites over two species (bovine heart and yeast mitochondria) points to an important role for the function of the respiratory chain. Interestingly the membrane-exposed CL binding sites are located on the matrix side of CIII in the inner membrane and thus may provide localized sources of proton ready for uptake by CIII. Furthermore, we found that CLs bound to those membrane-exposed sites bridge the proteins during their assembly into supercomplexes by sharing the binding sites.