---
title: "Identification of cardiolipin binding sites on cytochrome c oxidase at the entrance of proton channels"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Clement Arnarez, Siewert-J Marrink, and Xavier Periole"         # Paper authors (required)
year: "2013"           # Publication year (required)
publication: "Scientific Reports"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/srep01263"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Arnarez, C., Marrink, S. J., & Periole, X. (2013). Identification of cardiolipin binding sites on cytochrome c oxidase at the entrance of proton channels. Scientific reports, 3(1), 1263.

## Abstract

The respiratory chain or oxidative phosphorylation system (OxPhos) generates most of the chemical energy (ATP) used by our cells. The cytochrome c oxidase (CcO) is one of three protein complexes of OxPhos building up a proton gradient across the inner mitochondrial membrane, which is ultimately used by the ATP synthase to produce ATP. We present molecular dynamic simulations of CcO in a mimic of the mitochondrial membrane and identify precise binding sites of cardiolipin (CL, signature phospholipid of mitochondria) on the protein surface. Two of these CL binding sites reveal pathways linking CLs to the entrance of the D and H proton channels across CcO. CLs being able to carry protons our results strongly support an involvement of CLs in the proton delivery machinery to CcO. The ubiquitous nature of CL interactions with the components of the OxPhos suggests that this delivery mechanism might extend to the other respiratory complexes.