---
title: "Coarse-grain modelling of protein–protein interactions"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Marc Baaden, Siewert J Marrink"         # Paper authors (required)
year: "2013"           # Publication year (required)
publication: "Current Opinion in Structural Biology"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.sbi.2013.09.004"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Proteins
  - Self-assembly
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Baaden, M., & Marrink, S. J. (2013). Coarse-grain modelling of protein–protein interactions. Current opinion in structural biology, 23(6), 878-886.

## Abstract

Here, we review recent advances towards the modelling of protein–protein interactions (PPI) at the coarse-grained (CG) level, a technique that is now widely used to understand protein affinity, aggregation and self-assembly behaviour. PPI models of soluble proteins and membrane proteins are separately described, but we note the parallel development that is present in both research fields with three important themes: firstly, combining CG modelling with knowledge-based approaches to predict and refine protein–protein complexes; secondly, using physics-based CG models for de novo prediction of protein–protein complexes; and thirdly modelling of large scale protein aggregates.