---
title: "Molecular view on protein sorting into liquid-ordered membrane domains mediated by gangliosides and lipid anchors"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Djurre H. de Jong, Cesar A. Lopez and Siewert J. Marrink"         # Paper authors (required)
year: "2013"           # Publication year (required)
publication: "Faraday Discussions"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/C2FD20086D"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Post-translational modifications
  - Sterols
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> de Jong, D. H., Lopez, C. A., & Marrink, S. J. (2013). Molecular view on protein sorting into liquid-ordered membrane domains mediated by gangliosides and lipid anchors. Faraday discussions, 161, 347-363.

## Abstract

We present results from coarse grain molecular dynamics simulations of mixed model membranes consisting of saturated and unsaturated lipids together with cholesterol, in which lipid-anchored membrane proteins are embedded. The membrane proteins studied are the peripherally bound H-Ras, N-Ras, and Hedgehog, and the transmembrane peptides WALP and LAT. We provide a molecular view on how the presence and nature of these lipid anchors affects partitioning of the proteins between liquid-ordered and liquid-disordered domains. In addition, we probed the role of the ganglioside lipid GM1 on the protein sorting, showing formation of GM1-protein nano-domains that act as shuttles between the differently ordered membrane regions.