---
title: "MARTINI Model for Physisorption of Organic Molecules on Graphite"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Cristian Gobbo, Isabelle Beurroies, David de Ridder, Rienk Eelkema, Siewert J. Marrink, Steven De Feyter, Jan H. van Esch, and Alex H. de Vries"         # Paper authors (required)
year: "2013"           # Publication year (required)
publication: "The Journal of Physical Chemistry C"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jp402615p"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Materials science
  - Self-assembly
  - Small molecules
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Gobbo, C., Beurroies, I., de Ridder, D., Eelkema, R., Marrink, S. J., De Feyter, S., ... & de Vries, A. H. (2013). MARTINI model for physisorption of organic molecules on graphite. The Journal of Physical Chemistry C, 117(30), 15623-15631.

## Abstract

An extension to the MARTINI coarse-grained model is presented to describe the adsorption of organic molecules on graphite surfaces. The model allows the study of the dynamics of the preferential adsorption of long-chain organic molecules from solvent and the formation of ordered structures on the surface through self-assembly on the microsecond time scale. It was found that the MARTINI model, developed for self-assembling biomolecular systems in solution, could be extended to include two-dimensional self-assembly on a solid surface using a single recipe to determine the interactions of the existing bead-types with the new representation of graphite. The model was parametrized on adsorption enthalpies of small molecules from the gas phase and on wetting enthalpies of pure compounds. Three wetting enthalpies were determined experimentally to extend the range of chemical functionalities parametrized against. The model reproduces order–disorder transitions of hexadecane and hexadecanol and preferential adsorption of long-chain organic compounds from organic solvents, including the formation of lamellar arrangements on the surface.