---
title: "Gaussian curvature elasticity determined from global shape transformations and local stress distributions: a comparative study using the MARTINI model"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Mingyang Hu, Djurre H. de Jong, Siewert J. Marrink and Markus Deserno"         # Paper authors (required)
year: "2013"           # Publication year (required)
publication: "Faraday Discussions"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/C2FD20087B"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Hu, M., de Jong, D. H., Marrink, S. J., & Deserno, M. (2013). Gaussian curvature elasticity determined from global shape transformations and local stress distributions: a comparative study using the MARTINI model. Faraday discussions, 161, 365-382.

## Abstract

We calculate the Gaussian curvature modulus [small kappa, Greek, macron] of a systematically coarse-grained (CG) one-component lipid membrane by applying the method recently proposed by Hu et al. [Biophys. J., 2012, 102, 1403] to the MARTINI representation of 1,2-dimyristoyl-sn-glycero-3-phosphocholine (DMPC). We find the value [small kappa, Greek, macron]/κ = −1.04 ± 0.03 for the elastic ratio between the Gaussian and the mean curvature modulus and deduce [small kappa, Greek, macron]m/κm ≈ −0.98 ± 0.09 for the monolayer elastic ratio, where the latter is based on plausible assumptions for the distance z0 of the monolayer neutral surface from the bilayer midplane and the spontaneous lipid curvature K0m. By also analyzing the lateral stress profile σ0(z) of our system, two other lipid types and pertinent data from the literature, we show that determining K0m and [small kappa, Greek, macron] through the first and second moment of σ0(z) gives rise to physically implausible values for these observables. This discrepancy, which we previously observed for a much simpler CG model, suggests that the moment conditions derived from simple continuum assumptions miss the effect of physically important correlations in the lipid bilayer.