---
title: "Computational microscopy of cyclodextrin mediated cholesterol extraction from lipid model membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Cesar A. López, Alex H. de Vries & Siewert J. Marrink"         # Paper authors (required)
year: "2013"           # Publication year (required)
publication: "Scientific reports"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/srep02071"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Small molecules
  - Sterols
  - Glycans
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> López, C. A., de Vries, A. H., & Marrink, S. J. (2013). Computational microscopy of cyclodextrin mediated cholesterol extraction from lipid model membranes. Scientific reports, 3(1), 2071.

## Abstract

Beta-cyclodextrins (β-CDs) can form inclusion complexes with cholesterol and are commonly used to manipulate cholesterol levels of biomembranes. In this work, we have used multiscale molecular dynamics simulations to provide a detailed view on the interaction between β-CDs and lipid model membranes. We show that cholesterol can be extracted efficiently upon adsorption of β-CD dimers at the membrane/water interface. However, extraction is only observed to occur spontaneously in membranes with high cholesterol levels. Free energy calculations reveal the presence of a kinetic barrier for cholesterol extraction in the case of low cholesterol content. Cholesterol uptake is facilitated in case of (poly)unsaturated lipid membranes, which increases the free energy of the membrane bound state of cholesterol. Comparing lipid/cholesterol compositions typical of liquid-disordered (Ld) and liquid-order (Lo) domains, we furthermore show that cholesterol is preferentially extracted from the disordered regions, in line with recent experimental data.