---
title: "The Martini Coarse-Grained Force Field"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Xavier Periole & Siewert-Jan Marrink"         # Paper authors (required)
year: "2013"           # Publication year (required)
publication: "Biomolecular simulations: Methods and protocols"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1007/978-1-62703-017-5_20"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Book chapter
  - Protocol
  - Forcefield
  - Parametrization
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Periole, X., & Marrink, S. J. (2013). The Martini coarse-grained force field. Biomolecular simulations: Methods and protocols, 533-565.

## Abstract

The Martini force field is a coarse-grained force field suited for molecular dynamics simulations of biomolecular systems. The force field has been parameterized in a systematic way, based on the reproduction of partitioning free energies between polar and apolar phases of a large number of chemical compounds. In this chapter the methodology underlying the force field is presented together with details of its parameterization and limitations. Then currently available topologies are described with a short overview of the key elements of their parameterization. These include the new polarizable Martini water model. A set of three selected ongoing studies using the Martini force field is presented. Finally the latest lines of development are discussed.