---
title: "Anomalous viscosity effect in the early stages of the ion-assisted adhesion/fusion event between lipid bilayers: A theoretical and computational study"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: Antonio Raudino, Siewert J. Marrink, and Martina Pannuzzo""         # Paper authors (required)
year: "2013"           # Publication year (required)
publication: "The Journal of Chemical Physics"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1063/1.4809993"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
  - Polymers
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Raudino, A., Marrink, S. J., & Pannuzzo, M. (2013). Anomalous viscosity effect in the early stages of the ion-assisted adhesion/fusion event between lipid bilayers: A theoretical and computational study. The Journal of Chemical Physics, 138(23).

## Abstract

The effect of viscosity on the encounter rate of two interacting membranes was investigated by combining a non-equilibrium Fokker-Planck model together with extensive Molecular Dynamics (MD) calculations. The encounter probability and stabilization of transient contact points represent the preliminary steps toward short-range adhesion and fusion of lipid leaflets. To strengthen our analytical model, we used a Coarse Grained MD method to follow the behavior of two charged palmitoyl oleoyl phosphatidylglycerol membranes embedded in a electrolyte-containing box at different viscosity regimes. Solvent friction was modulated by varying the concentration of a neutral, water-soluble polymer, polyethylene glycol, while contact points were stabilized by divalent ions that form bridges among juxtaposed membranes. While a naïve picture foresees a monotonous decrease of the membranes encounter rate with solvent viscosity, both the analytical model and MD simulations show a complex behavior. Under particular conditions, the encounter rate could exhibit a maximum at a critical viscosity value or for a critical concentration of bridging ions. These results seem to be confirmed by experimental observations taken from the literature.