---
title: "Interbilayer repulsion forces between tension-free lipid bilayers from simulation"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Yuliya G. Smirnova, Sebastian Aeffner, Herre Jelger Risselada, Tim Salditt, Siewert-Jan Marrink, Marcus Müller, and Volker Knecht"         # Paper authors (required)
year: "2013"           # Publication year (required)
publication: "Soft Matter"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/C3SM51771C"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Solvents
  - Enhanced sampling
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Smirnova, Y. G., Aeffner, S., Risselada, H. J., Salditt, T., Marrink, S. J., Müller, M., & Knecht, V. (2013). Interbilayer repulsion forces between tension-free lipid bilayers from simulation. Soft Matter, 9(45), 10705-10718.

## Abstract

Here we report studies on biologically important intermembrane repulsion forces using molecular dynamics (MD) simulations and experimental (osmotic stress) investigations of repulsion forces between 1-palmitoyl-2-oleyl-sn-glycero-3-phosphocholine bilayers. We show that the repulsion between tension-free membranes can be determined from MD simulations by either (i) simulating membrane stacks under different hydration conditions (unrestrained setup) and monitoring the change in the area per lipid upon dehydration or (ii) simulating two single punctured membranes immersed in a water reservoir and controlling the center-of-mass distance between the bilayers using an external potential (umbrella sampling setup). Despite the coarse-grained nature of the (MARTINI) model employed, the disjoining pressure profiles obtained from the simulations are in good agreement with our experiments. Remarkably, the two setups behave very differently in terms of membrane structure, as explained by considerations using elasticity theory, and the balance of interactions. In the unrestrained setup, dehydration decreases the area per lipid and lipid entropy. Dehydration in the umbrella sampling setup, in contrast, leads to an increase in area per lipid and lipid entropy. Hence, in the latter case, entropic effects from protrusion and zippering forces appear to be overcompensated by the entropy gain due to the disorder emerging from the expansion of the bilayers. The balance of interactions involves near cancellation of large opposing terms, for which also intramembrane and water–water interactions are important, and which appears to be largely a consequence, rather than the cause, of the intermembrane repulsion. Hence, care must be taken when drawing conclusions on the origin of intermembrane repulsion from thermodynamic analyses.