---
title: "Computational ‘microscopy’ of cellular membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Helgi I. Ingólfsson, Clément Arnarez, Xavier Periole, and Siewert J. Marrink"         # Paper authors (required)
year: "2016"           # Publication year (required)
publication: "Journal of cell science"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1242/jcs.176040"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Proteins
  - Lipid membranes
  - Multi-scale
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Ingólfsson, H. I., Arnarez, C., Periole, X., & Marrink, S. J. (2016). Computational ‘microscopy’of cellular membranes. Journal of cell science, 129(2), 257-268.

## Abstract

Computational ‘microscopy’ refers to the use of computational resources to simulate the dynamics of a molecular system. Tuned to cell membranes, this computational ‘microscopy’ technique is able to capture the interplay between lipids and proteins at a spatio-temporal resolution that is unmatched by other methods. Recent advances allow us to zoom out from individual atoms and molecules to supramolecular complexes and subcellular compartments that contain tens of millions of particles, and to capture the complexity of the crowded environment of real cell membranes. This Commentary gives an overview of the main concepts of computational ‘microscopy’ and describes the state-of-the-art methods used to model cell membrane processes. We illustrate the power of computational modelling approaches by providing a few in-depth examples of large-scale simulations that move up from molecular descriptions into the subcellular arena. We end with an outlook towards modelling a complete cell in silico.