---
title: "Simulation of gel phase formation and melting in lipid bilayers using a coarse grained model"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Siewert J. Marrink, Jelger Risselada, and Alan E. Mark"         # Paper authors (required)
year: "2005"           # Publication year (required)
publication: "Chemistry and Physics of Lipids"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.chemphyslip.2005.03.001"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Marrink, S. J., Risselada, J., & Mark, A. E. (2005). Simulation of gel phase formation and melting in lipid bilayers using a coarse grained model. Chemistry and physics of lipids, 135(2), 223-244.

## Abstract

The transformation between a gel and a fluid phase in dipalmitoyl-phosphatidylcholine (DPPC) bilayers has been simulated using a coarse grained (CG) model by cooling bilayer patches composed of up to 8000 lipids. The critical step in the transformation process is the nucleation of a gel cluster consisting of 20–80 lipids, spanning both monolayers. After the formation of the critical cluster, a fast growth regime is entered. Growth slows when multiple gel domains start interacting, forming a percolating network. Long-lived fluid domains remain trapped and can be metastable on a microsecond time scale. From the temperature dependence of the rate of cluster growth, the line tension of the fluid–gel interface was estimated to be  pN. The reverse process is observed when heating the gel phase. No evidence is found for a hexatic phase as an intermediate stage of melting. The hysteresis observed in the freezing and melting transformation is found to depend both on the system size and on the time scale of the simulation. Extrapolating to macroscopic length and time scales, the transition temperature for heating and cooling converges to  K, in semi-quantitative agreement with the experimental value for DPPC (315 K). The phase transformation is associated with a drop in lateral mobility of the lipids by two orders of magnitude, and an increase in the rotational correlation time of the same order of magnitude. The lipid headgroups, however, remain fluid. These observations are in agreement with experimental findings, and show that the nature of the ordered phase obtained with the CG model is indeed a gel rather than a crystalline phase. Simulations performed at different levels of hydration furthermore show that the gel phase is stabilized at low hydration. A simulation of a small DPPC vesicle reveals that curvature has the opposite effect.