---
title: Tutorials 
subtitle: "Martini lectures, hands-on tutorials, and legacy materials"
page-layout: full
title-block-banner: "#EDF3F9"
---

The material offered here aims to help you familiarize yourself with some of the basic and more advanced aspects of performing Martini 3 coarse-grained simulations.  The material follows a historical track, starting with the MARTINI model for lipids. It goes on to describe how to set up simulations with proteins (and peptides), and then continues with more advanced topics, like backmapping (i.e. fine graining from a coarse-grained structure), parameterization of new molecules, and more. 

[Lectures](Martini3/lectures.qmd) by several Martini developers describing some of the most important model features and tools are available, alongside a set of [hands-on tutorials](Martini3/tutorials.qmd) showing users how to set up a variety of Martini systems.

For the tutorials, familiarity with GROMACS is assumed; for an explanation of how to work with GROMACS and the specification of force field and run parameters we refer to the [GROMACS user manual](https://www.gromacs.org). There is also an excellent collection of GROMACS tutorials available [here](http://www.mdtutorials.com/gmx/). The material can be covered in as much time as you like, and the speed at which you go through this material depends on the computational facilities available, your GROMACS skills, and the time you take to consider what you’re doing. The set-up is modular, however, and depending on you particular interest, you may change the order of the exercises. You could either leave long runs overnight to return to them the next day, or use ”pre-prepared” intermediate and result files that will be provided.

Finally, a set of [legacy tutorials](Legacy/index.qmd) pertaining to older iterations of Martini is also available.

::: callout-note
## Note from the Martini Developers Team

This material was originally written for the 2008 MARTINI winterschool in Helsinki, and has since been updated for numerous other workshops by several Martini developers (in no particular order): Lars Schäfer, Andrzej Rzepiela, Martti Louhivuori, Clement Arnarez, Alex de Vries, Djurre de Jong, Helgi Ingólfsson, Manuel Nuno Melo and Jaakko Uusitalo, Pim Frederix, Ignacio Faustino Paulo C. T. Souza, Siewert-Jan Marrink, Tsjerk Wassenaar, Luca Monticelli, Riccardo Alessandri, Raul Mera A., Sebastian Thallmair, Fabian Grünewald, Weria Pezeshkian, Peter Tieleman, Besian I. Sejdiu, Luís Borges-Araújo, Melanie König, Selim Sami, Liu Y., Daniel P. Ramirez-Echemendia, Chris Brasnett, Martin Calvelo.

Last updated: October 2024
:::

