## Martini 2 Tutorials
<hr>

The tutorial exercises described here aim to help you familiarize yourself with some of the basic and more advanced aspects of using GROMACS to perform coarse-grained simulations. The main focus is on the semi-empirical MARTINI model. Familiarity with GROMACS is assumed; for explanation of how to work with GROMACS and the specification of force field and run parameters we refer to the GROMACS user manual and web-pages (www.gromacs.org). There is an excellent GROMACS tutorial taking you through atomistic simulation of a small peptide, available at: [http://md.chem.rug.nl/~mdcourse/pepmd/index.html](http://md.chem.rug.nl/~mdcourse/pepmd/index.html)

The tutorials are currently not presented in a particular logical order. However, beginners are advised to   start with the MARTINI model for LIPIDS, because in this tutorial both gromacs commands and Martini files are shown and discussed in most detail. A logical next step is to discover how to set up simulations with PROTEINS (and peptides) from a PDB file, combine an elastic network with MARTINI, or use the alternative ElNeDyn model. The protein tutorial also covers more advanced topics, like embedding peptides in a lipid bilayer, and reverse mapping (i.e. fine graining from a coarse-grained structure). Further experience with the protein model can be gained with the High throughput peptide self assembly tutorial, which also shows how many tasks can be automated by using clever scripting. Next in the MARTINI zoo are DNA and RNA, which also introduces third-party websites for building initial structures and a DNA-protein complex. Moving away from biomolecules, the POLYMERS tutorial lets you explore refining a model for PEO/PEG, discussing tools and strategies to develop your own MARTINI model(s); PARAMETRIZING your own molecule also covers this topic, but in a more general way. Finally, there is cutting-edge technology in the HYBRID model using virtual sites. 

 

The material can be covered in as much time as you like, and the speed at which you go through this material depends on the computational facilities available, your GROMACS skills, and the time you take to consider what you’re doing. The set-up is modular, however, and depending on you particular interest, you may change the order of the exercises. You could either leave long runs overnight to return to them the next day, or use ”pre-prepared” intermediate and result files that can be downloaded.

*These tutorials were originally written for the MARTINI winterschool 2008 in Helsinki by Lars Schäfer, Andrzej Rzepiela, and Martti Louhivuori, subsequently updated by Clement Arnarez, Alex de Vries and Djurre de Jong for the CECAM Coarse grain workshop 2011 and further updated by Clement Arnarez, Helgi Ingólfsson, Manuel Nuno Melo and Jaakko Uusitalo for the 2nd Molecular Simulation Summer School at the University of Calgary. Further updates and contributions were added for the Martini Workshops 2015 and 2017, adding to the contributors Pim Frederix and Ignacio Faustino.*