---
title: "Atomistic and Coarse Grain Topologies for the Cofactors Associated with the Photosystem II Core Complex"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Djurre H. de Jong, Nicoletta Liguori, Tom van den Berg, Clement Arnarez, Xavier Periole, and Siewert J. Marrink"         # Paper authors (required)
year: "2015"           # Publication year (required)
publication: "The Journal of Physical Chemistry B"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jpcb.5b00809"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/abs/10.1021/acs.jpcb.5b00809"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Cofactors
  - Small molecules
  - Multi-scale
  - Parametrization
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> De Jong, D. H., Liguori, N., Van Den Berg, T., Arnarez, C., Periole, X., & Marrink, S. J. (2015). Atomistic and coarse grain topologies for the cofactors associated with the photosystem II core complex. The Journal of Physical Chemistry B, 119(25), 7791-7803.

## Abstract

Electron transfers within and between protein complexes are core processes of the electron transport chains occurring in thylakoid (chloroplast), mitochondrial, and bacterial membranes. These electron transfers involve a number of cofactors. Here we describe the derivation of molecular mechanics parameters for the cofactors associated with the function of the photosystem II core complex: plastoquinone, plastoquinol, heme b, chlorophyll A, pheophytin, and β-carotene. Parameters were also obtained for ubiquinol and ubiquinone, related cofactors involved in the respiratory chain. Parameters were derived at both atomistic and coarse grain (CG) resolutions, compatible with the building blocks of the GROMOS united-atom and Martini CG force fields, respectively. Structural and thermodynamic properties of the cofactors were compared to experimental values when available. The topologies were further tested in molecular dynamics simulations of the cofactors in their physiological environment, e.g., either in a lipid membrane environment or in complex with the heme binding protein bacterioferritin.