---
title: "Parameters for MARTINI sterols and hopanoids based on a virtual-site description"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "MN Melo, HI Ingólfsson, SJ Marrink"         # Paper authors (required)
year: "2015"           # Publication year (required)
publication: "The Journal of Chemical Physics"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1063/1.4937783"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Parametrization
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Melo, M. N., Ingólfsson, H. I., & Marrink, S. J. (2015). Parameters for Martini sterols and hopanoids based on a virtual-site description. The Journal of chemical physics, 143(24).

## Abstract

Sterols play an essential role in modulating bilayer structure and dynamics. Coarse-grained molecular dynamics parameters for cholesterol and related molecules are available for the Martini force field and have been successfully used in multiple lipid bilayer studies. In this work, we focus on the use of virtual sites as a means of increasing the stability of cholesterol and cholesterol-like structures. We improve and extend the Martini parameterization of sterols in four different ways: 1—the cholesterol parameters were adapted to make use of virtual interaction sites, which markedly improves numerical stability; 2—cholesterol parameters were also modified to address reported shortcomings in reproducing correct lipid phase behavior in mixed membranes; 3—parameters for ergosterol were created and adapted from cholesterols; and 4—parameters for the hopanoid class of bacterial polycyclic molecules were created, namely, for hopane, diploptene, bacteriohopanetetrol, and for their polycyclic base structure.