---
title: "CHARMM-GUI Martini Maker for Coarse-Grained Simulations with the Martini Force Field"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Yifei Qi, Helgi I. Ingólfsson, Xi Cheng, Jumin Lee, Siewert J. Marrink, and Wonpil Im"         # Paper authors (required)
year: "2015"           # Publication year (required)
publication: "Journal of Chemical Theory and Computation"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jctc.5b00513"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b00513"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Methods
  - Proteins
  - Lipid membranes
  - Micelles
  - Vesicles
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Qi, Y., Ingólfsson, H. I., Cheng, X., Lee, J., Marrink, S. J., & Im, W. (2015). CHARMM-GUI martini maker for coarse-grained simulations with the martini force field. Journal of chemical theory and computation, 11(9), 4486-4494.

## Abstract

Coarse-grained simulations are widely used to study large biological systems. Nonetheless, building such simulation systems becomes nontrivial, especially when membranes with various lipid types are involved. Taking advantage of the frameworks in all-atom CHARMM-GUI modules, we have developed CHARMM-GUI Martini Maker for building solution, micelle, bilayer, and vesicle systems as well as systems with randomly distributed lipids using the Martini force field. Martini Maker supports 82 lipid types and different flavors of the Martini force field, including polar and nonpolar Martini, Dry Martini, and ElNeDyn (an elastic network model for proteins). The qualities of the systems generated by Martini Maker are validated by simulations of various examples involving proteins and lipids. We expect Martini Maker to be a useful tool for modeling large, complicated biomolecular systems in a user-friendly way.