---
title: "Characterization of thylakoid lipid membranes from cyanobacteria and higher plants by molecular dynamics simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Floris J. van Eerden, Djurre H. de Jong, Alex H. de Vries, Tsjerk A. Wassenaar, and Siewert J. Marrink"         # Paper authors (required)
year: "2015"           # Publication year (required)
publication: "Biochimica et Biophysica Acta (BBA)-Biomembranes"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bbamem.2015.02.025"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Multi-scale
  - Cofactors
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> van Eerden, F. J., de Jong, D. H., de Vries, A. H., Wassenaar, T. A., & Marrink, S. J. (2015). Characterization of thylakoid lipid membranes from cyanobacteria and higher plants by molecular dynamics simulations. Biochimica et Biophysica Acta (BBA)-Biomembranes, 1848(6), 1319-1330.

## Abstract

The thylakoid membrane is mainly composed of non-common lipids, so called galactolipids. Despite the importance of these lipids for the function of the photosynthetic reaction centers, the molecular organization of these membranes is largely unexplored. Here we use multiscale molecular dynamics simulations to characterize the thylakoid membrane of both cyanobacteria and higher plants. We consider mixtures of up to five different galactolipids plus phosphatidylglycerol to represent these complex membranes. We find that the different lipids generally mix well, although nanoscale heterogeneities are observed especially in case of the plant membrane. The fluidity of the cyanobacterial membrane is markedly reduced compared to the plant membrane, even considering elevated temperatures at which thermophilic cyanobacteria are found. We also find that the plant membrane more readily undergoes a phase transformation to an inverted hexagonal phase. We furthermore characterized the conformation and dynamics of the cofactors plastoquinone and plastoquinol, revealing of the fast flip-flop rates for the non-reduced form. Together, our results provide a molecular view on the dynamical organization of the thylakoid membrane.