---
title: Resolution transformation
format: html
---
<hr>

### TS2CG: Triangulated Surfaces to Coarse Grain
<hr>

TS2CG is an algorithm to backmap a triangulated surface to a corresponding coarse-grained model.
 
The software can be downloaded from this [link](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/tools/resolution_transformation/TS2CG-master.zip), or by visiting [https://github.com/marrink-lab/TS2CG](https://github.com/marrink-lab/TS2CG).

### Backward
<hr>

Backward is a tool to convert a coarse-grained system to united-atom or all-atom resolution. The mapping is done using a library of mapping definitions, which encode the geometric reconstruction.

In most cases, the backmapping is performed using the wrapper initram.sh, which calls backward.py and subsequently relaxes the resulting structure through energy minimization and molecular dynamics based relaxation.

When using this method, please cite:

**Going Backward: A Flexible Geometric Approach to Reverse Transformation from Coarse Grained to Atomistic Models** *Tsjerk A. Wassenaar, Kristyna Pluhackova, Rainer A. Böckmann, Siewert J. Marrink, and D. Peter Tieleman* J. Chem. Theory Comput., 10:676-690, 2014. [DOI: 10.1021/ct400617g](http://pubs.acs.org/doi/abs/10.1021/ct400617g)

More extensive information and a tutorial can be found [[here]](../../tutorials/Martini3/Backward/index.qmd). 

[The scripts and mapping definitions for gromacs versions 4 and 5-bead oleoyl lipid chains are combined into a single zip file, which can be downloaded here.](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/tools/resolution_transformation/backward.zip)

[The initram.sh script for version 5 can be downloaded here.](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/tools/resolution_transformation/initram-v5.sh)

[The script for gromacs versions 5 and higher and the mapping files for the amino acid residues and nucleobases are combined into a single zip file, which can be downloaded here.](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/tools/resolution_transformation/backward-v5.zip)

### Convert Martini water to polarizable water
<hr>

- [triple-w.py](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/tools/resolution_transformation/triple-w.pyhttps://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/tools/resolution_transformation/triple-w.py)

Script to convert the water in CG Martini system to polarizable water. For an example how to use this script, click [here](../../tutorials/Legacy/martini2/others.qmd#polarizable-water).

### Resolution transformation
<hr>

Custom version of Gromacs to reintroduce atomistic details to CG structures [gmx_rev.tar.gz](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/tools/resolution_transformation/gmx_rev.tar).

If you use the code, please cite:

- [Rzepiela et al. Reconstruction of atomistic details from coarse grained structures J. Comp. Chem, 31-1333-1343, 2010.](http://www3.interscience.wiley.com/journal/123244279/abstract) 

We recommend you use Backward instead of this tool. For details about this tool please contact Andrzej Rzepiela ([Andrzej.Rzepiela@physik.uni-freiburg.de](mailto: Andrzej.Rzepiela@physik.uni-freiburg.de))

You may also try an automized resolution transformation provided by Angel Pineiro, see [http://smmb.usc.es/sugarpie/sugarpie.php](http://smmb.usc.es/sugarpie/sugarpie.php).

<hr>
