---
title: <i class="fas fa-project-diagram"></i>  Topology/Structure Generation
format: html
---

::: software-card
### Martinize2/Vermouth

`Martinize2` is a rewrite of [Martinize](./legacy.qmd#martinize). It is aimed at producing coarse-grained structures and topologies from an atomistic structure. `Martinize2` is primarily developed for the Martini coarse-grained force field and the `Gromacs` simulation engine. 

`Vermouth` (for VERsatile, MOdular, and Universal Tranformation Helper) is the python library that powers `Martinize2`. It allows to describe and apply transformation on molecular structures and topologies using graph algorithms.

For more details and to download the latest version, visit the [[GitHub repository]](https://github.com/marrink-lab/vermouth-martinize).

:::

::: software-card
### Polyply

`Polyply` is a python suite designed to facilitate the generation of input files and system coordinates for simulating (bio)macromolecules such as synthetic polymers or polysaccharides. Input files can be generated either from user specified building blocks or by using the polymers available in the library. The library currently includes polymer definitions for the GROMOS (2016H66 & 54A6), OPLS, Parmbsc1, and Martini (2 & 3) force-fields. Coordinates are generated by a multiscale random-walk protocol that is able to generate condensed phase systems at target density, as well as more heterogeneous systems such as aqueous two phase systems. In addition, `polyply` allows to tailor initial chain conformations by providing a build file.

For more details and to download the latest version, visit the [[GitHub repository]](https://github.com/marrink-lab/polyply_1.0).
:::

::: software-card
### Insane

`Insane` (INSert membrANE) is a versatile tool to build coarse-grained simulation systems containing solutes, lipid bilayers, and/or solvents. It handles a broad range of different lipid types, is very flexible with respect to box types and can insert a (CG) protein structure in the bilayer if one is given. It can write PDB or gromacs files.

For more details and to download the latest version, visit the [[GitHub repository]](https://github.com/Tsjerk/Insane).
:::

::: software-card
### COBY

`COBY` is a Python-based software tool for building flat membranes at a coarse-grained resolution. It supports asymmetric membranes, phase-separated systems, multiple bilayers, protein insertion, solvation, and flooding with one or multiple solute molecules of choice.

For more details and to download the latest version, visit the [[GitHub repository]](https://github.com/MikkelDA/COBY).
:::

::: software-card
### Go-Martini

For ongoing development of `Go-Martini`, see the [[webpage of Adolfo Poma]](http://pomalab.ippt.pan.pl/web/index.html).
:::

