---
title: "2008"
format: html
---

- **H.J. Risselada, S.J. Marrink.** The molecular face of lipid rafts in model membranes. PNAS, 105:17367-17372, 2008. [open access](http://www.pnas.org/content/105/45/17367.full?sid=f7746017-6149-4d49-9aca-5878575bab5f)
- **S. Baoukina, L. Monticelli, H.J. Risselada, S.J. Marrink, D.P. Tieleman.** The molecular mechanism of lipid monolayer collapse. PNAS, 105:10803-10808, 2008. [open access](http://www.pnas.org/content/105/31/10803.full?sid=f7746017-6149-4d49-9aca-5878575bab5f)
- **H.J. Risselada, A.E. Mark, S.J. Marrink.** The application of mean field boundary potentials in simulations of lipid vesicles. JPC-B, 112:7438-7447, 2008. [abstract](http://pubs.acs.org/doi/abs/10.1021/jp0758519)
- **W. Treptow, S.J. Marrink, M. Tarek.** Gating motions in voltage-gated potassium channels revealed by coarse-grained molecular dynamics simulations. JPC-B, 112:3277-3282, 2008. [abstract](http://pubs.acs.org/doi/abs/10.1021/jp709675e)
- **S.J. Marrink, A.H. de Vries, T.A. Harroun, J. Katsaras, S.R. Wassall.** Cholesterol shows preference for the interior of polyunsaturated lipid membranes. JACS, 130:10-11, 2008. [abstract](http://pubs.acs.org/doi/abs/10.1021/ja076641c)
- **A. Catte, J.C. Patterson, D. Bashtovyy, M.K. Jones, F. Gu, L. Li, A. Rampioni, D. Sengupta, T. Vuorela, P. Niemela, M. Karttunen, S.J. Marrink, I. Vattulainen, J.P. Segrest.** Structure of spheroidal HDL particles revealed by combined atomistic and coarse grained simulations. Biophys. J., 94:2306-2319, 2008. [abstract](http://www.cell.com/biophysj/abstract/S0006-3495%2808%2970575-7)
- **S.J. Marrink, M. Fuhrmans, H.J. Risselada, X. Periole.** The MARTINI force field. In "Coarse graining of condensed phase and biomolecular systems", G. Voth ed., CRC press, Chapter 2, 2008. [pdf reprint](http://cgmartini.nl/~marrink/chapter2-voth08.pdf)
- **L. Monticelli, S.K. Kandasamy, X. Periole, R.G. Larson, D.P. Tieleman, S.J. Marrink.** The MARTINI coarse grained forcefield: extension to proteins. JCTC, 4:819-834, 2008. [abstract](http://pubs.acs.org/doi/abs/10.1021/ct700324x)
- **S. Yefimov, E. van der Giessen, P.R. Onck, S.J. Marrink.** Mechanosensitive membrane channels in action. Biophys. J., 94:2994-3002, 2008. [abstract](http://www.cell.com/biophysj/abstract/S0006-3495%2808%2970457-0)
