---
title: "2009"
format: html
---

- **M.J. Hinner, S.J. Marrink, A.H. de Vries.** Location, tilt, and binding: a molecular dynamics study of voltage sensitve dyes in biomembranes. J. Phys. Chem. B, 113:15807-15819, 2009. [abstract](http://pubs.acs.org/doi/abs/10.1021/jp907981y)
- **C.A. Lopez, A. Rzepiela, A.H. de Vries, L. Dijkhuizen, P.H. Huenenberger, S.J. Marrink.** The Martini coarse grained force field: extension to carbohydrates. J. Chem. Th. Comp., 5:3195-3210, 2009. [abstract](http://pubs.acs.org/doi/abs/10.1021/ct900313w)
- **D. Sengupta, A. Rampioni, S.J. Marrink.** Simulations of the C-subunit of ATP-synthase reveal helix rearrangements. Mol. Membr. Biol., 26:422-434, 2009. [abstract](http://cgmartini.nl/index.php/2009?id=140)
- **H.J. Risselada, S.J. Marrink.** The freezing process of small lipid vesicles at molecular resolution. Soft Matter, 5:4531-4541, 2009. [abstract](http://pubs.rsc.org/en/Content/ArticleLanding/2009/SM/b913210d)
- **H. Lee, A.H. de Vries, S.J. Marrink, R.W. Pastor.** A coarse-grained model for polyethylene oxide: conformation and hydrodynamics. J. Phys. Chem. B, 113:13186-13194, 2009. [abstract](http://pubs.acs.org/doi/abs/10.1021/jp9058966)
- **X. Periole, M. Cavalli, S.J. Marrink, M. Ceruso.** Combining an elastic network with a coarse-grained molecular force field: structure, dynamics and intermolecular recognition. J. Chem. Th. Comp., 5:2531-2543, 2009. [abstract](http://pubs.acs.org/doi/abs/10.1021/ct9002114)
- **W.F.D. Bennett, J.L. MacCallum, M.J. Hinner, S.J. Marrink, D.P. Tieleman.** A molecular view of cholesterol flip-flop and chemical potential in different membrane environments. JACS, 131:12714-12720, 2009. [abstract](http://pubs.acs.org/doi/abs/10.1021/ja903529f)
- **N. Kucerka, J. Gallova, D. Uhrikova, P. Balgavy, M. Bulacu, S.J. Marrink, J. Katsaras.** Areas of monounsaturated diacylphosphatidylcholines. Biophys. J., 97:1926-1932, 2009. [abstract](http://www.cell.com/biophysj/abstract/S0006-3495%2809%2901242-9)
- **M. Fuhrmans, V. Knecht, S.J. Marrink.** A single bicontinuous cubic phase induced by fusion peptides. JACS, 131:9166-9167, 2009. [abstract](http://pubs.acs.org/doi/abs/10.1021/ja903224q)
- **R.P.A. Berntsson, M.K. Doeven, F. Fusetti, R.H. Duurkens, D. Sengupta, S.J. Marrink, A.M.W.H. Thunnissen, B. Poolman, D.J. Slotboom.** The structural basis for peptide selection by the transport receptor OppA. EMBO J., 28:1332-1340, 2009. [open access](http://www.nature.com/emboj/journal/v28/n9/full/emboj200965a.html)
- **H.J. Risselada, S.J. Marrink.** Curvature effects on lipid packing and dynamics in liposomes revealed by coarse grained molecular dynamics simulations. Phys. Chem. Chem. Phys., 11:2056-2067, 2009. [abstract](http://pubs.rsc.org/en/Content/ArticleLanding/2009/CP/b818782g)
- **O.H.S. Ollila, H.J. Risselada, M. Louhivuori, E. Lindahl, I. Vattulainen, S.J. Marrink.** 3D Pressure distribution in lipid membranes and membrane-protein complexes. Phys. Rev. Lett., 102:078101, 2009. [abstract](http://prl.aps.org/abstract/PRL/v102/i7/e078101)
 