---
title: "2010"
format: html
---

- **M. Louhivuori, H.J. Risselada, E. van der Giessen, S.J. Marrink.** Release of content through mechano-sensitive gates in pressurized liposomes. PNAS, 107:19856-19860, 2010.  [open access](http://www.pnas.org/content/107/46/19856.full)
- **A.A. Polyansky, R. Ramaswarny, P.E. Volynsky, I.F. Sbalzarini, S.J. Marrink, R.G. Efremov.** Antimicrobial peptides induce growth of phosphatidylglycerol domains in a model bacterial membrane. J. Phys. Chem. Letters, 1:3108–3111, 2010. [abstract](http://pubs.acs.org/doi/abs/10.1021/jz101163e)
- **L.V. Schäfer, S.J. Marrink.** Partitioning of lipids at domain boundaries in model membranes. Biophys. J., 99:L91-L93, 2010. [open access](http://www.cell.com/biophysj/abstract/S0006-3495%2810%2901102-1)
- **T.A. Vuorela, A. Catte, P.S. Niemela, A. Hall, M.T. Hyvonen, S.J. Marrink, M. Karttunen, I. Vattulainen.** Role of lipids in spheroidal high density lipoproteins. PLoS Comp. Biol., 6:e1000964, 2010. [open access](http://www.ploscompbiol.org/article/info:doi/10.1371/journal.pcbi.1000964)
- **D. Sengupta, S.J. Marrink.** Lipid mediated Interactions tune the association of Glycophorin A helix and its disruptive mutants in membranes. Phys. Chem. Chem. Phys., 12:12987-12996, 2010. [abstract](http://pubs.rsc.org/en/Content/ArticleLanding/2010/CP/c0cp00101e)
- **N. Kucerka, D. Marquardt, T.A. Harroun, M.P. Nieh, S.R. Wassall, D.H. de Jong, L.V. Schäfer, S.J. Marrink, J. Katsaras.** Cholesterol in bilayers with PUFA chains: Doping with DMPC or POPC results in sterol reorientation and membrane-domain formation. Biochemistry, 49:7485-7493, 2010. [abstract](http://pubs.acs.org/doi/abs/10.1021/bi100891z)
- **S. Ramadurai, A. Holt, L.V. Schäfer, V.V. Krasnikov, D.T.S. Rijkers, S.J. Marrink, J.A. Killian, B. Poolman.** Influence of hydrophobic mismatch and amino acid composition on the lateral diffusion of transmembrane peptides. Biophys. J.,99:1447-1454, 2010. [abstract](http://www.cell.com/biophysj/abstract/S0006-3495%2810%2900724-1)
- **J.A. Lycklama a Nijeholt, M. Bulacu, S.J. Marrink, A.J.M. Driessen.** Immobilization of the plug domain inside the SecY channel allows unrestricted protein translocation. J. Biol. Chem., 285:23747-23754, 2010. [abstract](http://www.jbc.org/content/285/31/23747.abstract?sid=63e92203-fc4c-460a-be3a-20dc6a981ce2)
- **Y.G. Smirnova, S.J. Marrink, R. Lipowsky, V. Knecht.** Solvent-exposed tails as prestalk transition states for membrane fusion at low hydration. JACS, 132:6710-6718, 2010. [abstract](http://pubs.acs.org/doi/abs/10.1021/ja910050x)
- **S.O. Yesylevskyy, L.V. Schäfer, D. Sengupta, S.J. Marrink.** Polarizable water model for the coarse-grained Martini force field. PLoS Comp. Biol, 6:e1000810, 2010. [open access](http://www.ploscompbiol.org/article/info:doi/10.1371/journal.pcbi.1000810)
- **A.J. Rzepiela, L.V. Schäfer, N. Goga, H.J. Risselada, A.H. de Vries, S.J. Marrink.** Reconstruction of atomistic details from coarse grained structures. J. Comp. Chem., 31:1333-1343, 2010. [abstract](http://www3.interscience.wiley.com/journal/123244279/abstract)
- **S.J. Marrink, X. Periole, D.P. Tieleman, A.H. de Vries.** Comment on using a too large integration time step in molecular dynamics simulations of coarse-grained molecular models. Phys. Chem. Chem. Phys., 12:2254-2256, 2010. [abstract](http://www.rsc.org/Publishing/Journals/CP/article.asp?doi=b915293h)
- **M. Fuhrmans, B.P. Sanders, S.J. Marrink, A.H. de Vries.** Effects of bundling on the properties of the SPC water model. Theor. Chem. Accounts, 125:335-344, 2010. [open access](http://springerlink.com/content/0153522rq70j70g2/)
- **S. Baoukina, S.J. Marrink, D.P. Tieleman.** Lateral pressure profiles in lipid monolayers. Farad. Discuss., 144:393-409, 2010. [abstract](http://pubs.rsc.org/en/Content/ArticleLanding/2010/FD/b905647e)
- **T. Apajalahti, P. Niemela, P.N. Govindan, M. Miettinen, E. Salonen, S.J. Marrink, I. Vattulainen.** Concerted diffusion of lipids in raft-like membranes. Farad. Discuss., 144:411-430, 2010. [abstract](http://pubs.rsc.org/en/Content/ArticleLanding/2010/FD/b901487j)
- **A. Rzepiela, D. Sengupta, N. Goga, S.J. Marrink.** Membrane poration by antimicrobial peptides combining atomistic and coarse grained descriptions. Farad. Discuss., 144:431-443, 2010. [abstract](http://pubs.rsc.org/en/Content/ArticleLanding/2010/FD/b901615e)