---
title: "2011"
format: html
---

- **M. Velinova, D. Sengupta, A. Tadjer, S.J. Marrink.** Sphere-to-rod transitions of nonionic surfactant micelles in aqueous solution modeled by molecular dynamics simulations, Langmuir, 27:14071–14077, 2011. [abstract](http://pubs.acs.org/doi/abs/10.1021/la203055t)
- **J. Sørensen, X. Periole, K.K. Skeby, S.J. Marrink, B. Schiøtt.** Protofibrillar assembly toward the formation of amyloid fibrils, J. Phys. Chem. Lett., 2:2385–2390, 2011. [abstract](http://pubs.acs.org/doi/abs/10.1021/jz2010094?prevSearch=%255BContrib%253A%2Bmarrink%255D&searchHistoryKey=)
- **A.J. Markvoort, S.J. Marrink.** Lipid acrobatics in the membrane fusion arena, Curr. Top. Membr., 68:259−294, 2011. [abstract](http://www.sciencedirect.com/science/article/pii/B9780123858917000118), [reprint](http://cgmartini.nl/images/stories/fusion-review_ctm11.pdf)
- **T. Murtola, T.A. Vuorela, M.T. Hyvonen, S.J. Marrink, M. Karttunen, I. Vattulainen.** Low density lipoprotein: Structure, dynamics, and interactions of ApoB-100 with lipids. Soft Matter, 7:8135-8141, 2011. [abstract](http://pubs.rsc.org/en/Content/ArticleLanding/2011/SM/C1SM05367A)
- **M. Klacsová,  M. Bulacu, N. Kučerka, D. Uhríková, J. Teixeirad, S.J. Marrink, P. Balgavý.** The effect of aliphatic alcohols on fluid bilayers in unilamellar DOPC vesicles – a small-angle neutron scattering and molecular dynamics study. BBA Biomembr., 808:2136-2146, 2011. [abstract](http://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T1T-52RHTF2-2&_user=10&_coverDate=04%2F29%2F2011&_rdoc=8&_fmt=high&_orig=browse&_origin=browse&_zone=rslt_list_item&_srch=doc-info%28%23toc%234899%239999%23999999999%2399999%23FLA%23display%23Articles%29&_cdi=4899&_sort=d&_docanchor=&_ct=41&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=3aaff0c3d56fc1c5e99129bea564446f&searchtype=a)
- **A.J. Rzepiela, M. Louhivuori, C. Peter, S.J. Marrink.** Hybrid simulations: combining atomistic and coarse-grained force fields using virtual sites. Phys. Chem. Chem. Phys., 13:10437-10448, 2011. [abstract](http://pubs.rsc.org/en/Content/ArticleLanding/2011/CP/C0CP02981E)
- **H.J. Risselada, S.J. Marrink, M. Muller.** Curvature-dependent elastic properties of liquid-ordered domains result in inverted domain sorting on uniaxially compressed vesicles. Phys. Rev. Lett., 106:148102, 2011. [abstract](http://prl.aps.org/abstract/PRL/v106/i14/e148102)
- **O.H.S. Ollila, M. Louhivuori, S.J. Marrink, I. Vattulainen.** Protein shape change has a major effect on the gating energy of a mechanosensitive channel. Biophys. J., 100:1651-1659, 2011. [abstract](http://www.cell.com/biophysj/abstract/S0006-3495%2811%2900245-1)
- **L.V. Schafer, D.H. de Jong, A. Holt, A.J. Rzepiela, A.H. de Vries, B. Poolman, J.A. Killian, S.J. Marrink.** Lipid packing drives the segregation of transmembrane helices into disordered lipid domains in model biomembranes. PNAS, 108:1343-1348, 2011. [open access](http://www.pnas.org/content/108/4/1343.full)