---
title: "2012"
format: html
---

- **E. Deplazes, M. Louhivuori, D. Jayatilaka, S.J. Marrink, B. Corry.** Structural investigation of MscL gating using experimental data and coarse grained MD simulations. PLoS Comp. Biol. 8:e1002683, 2012. [open access](http://www.ploscompbiol.org/article/info%3Adoi%2F10.1371%2Fjournal.pcbi.1002683)
- **X. Periole, A.M. Knepp, T.P. Sakmar, S.J. Marrink, T. Huber.** Structural determinants of the supra-molecular organization of G protein-coupled receptors in bilayers. JACS, 134:10959–10965, 2012. [abstract](http://pubs.acs.org.proxy-ub.rug.nl/doi/abs/10.1021/ja303286e)
- **H.J. Risselada, G. Marelli, M. Fuhrmans, Y.G. Smirnova, H. Grubmüller, S.J. Marrink, M. Muller.** Line-tension controlled mechanism for influenza fusion. PLoS ONE 7:e38302, 2012. [open access](http://www.plosone.org/article/fetchArticle.action?utm_medium=feed&utm_source=feedburner&utm_campaign=Feed%3A+plosone%2FPLoSONE+%28PLoS+ONE+Alerts%3A+New+Articles%29&articleURI=info%3Adoi%2F10.1371%2Fjournal.pone.0038302)
- **S. Baoukina, S.J. Marrink, D.P. Tieleman.** Molecular structure of membrane tethers. Biophys. J., 102:1866-1871, 2012. [open access](http://www.cell.com/biophysj/fulltext/S0006-3495%2812%2900389-X)
- **D.H. de Jong, X. Periole, S.J. Marrink.** Dimerization of amino acid side chains: lessons from the comparison of different force fields. JCTC, 8:1003–1014, 2012. [abstract](http://pubs.acs.org/doi/abs/10.1021/ct200599d)
- **M. Fuhrmans, S.J. Marrink.** Molecular view of the role of fusion peptides in promoting positive membrane curvature. JACS, 134:1543–1552, 2012. [abstract](http://pubs.acs.org/doi/abs/10.1021/ja207290b)
- **J. Domanski, S.J. Marrink, L.V. Schaefer.** Transmembrane helices can induce domain formation in crowded model biomembranes. BBA Biomembr., 1818:984-994, 2012. [abstract](http://www.sciencedirect.com/science/article/pii/S0005273611002835)
- **M. Bulacu, X. Periole, S.J. Marrink.** In-silico design of robust bolalipid membranes, Biomacromol., 13:196–205, 2012. [abstract](http://pubs.acs.org/doi/abs/10.1021/bm201454j)


