---
title: "2013"
format: html
---

- **M. Baaden, S.J. Marrink.** Coarse-grain modelling of protein–protein interactions. Curr. Opin. Struct. Biol., 23:878-886, 2013. [open access](http://www.sciencedirect.com/science/article/pii/S0959440X13001735)
- **Y.G. Smirnova, S. Aeffner, H.J. Risselada, T. Salditt, S.J. Marrink, R. Lipowsky, M. Mueller, V. Knecht.** Interbilayer repulsion forces between tension-free lipid bilayers from simulation. Soft Matter, 9:10705-10718, 2013. [abstract](http://pubs.rsc.org/en/content/articlelanding/2013/sm/c3sm51771c)
- **M. Bulacu, N. Goga, W. Zhao, G. Rossi, L. Monticelli, X. Periole, D.P. Tieleman, S.J. Marrink.** Improved angle potentials for coarse-grained molecular dynamics simulations. JCTC, 9:3282–3292, 2013. [abstract](http://pubs.acs.org/doi/abs/10.1021/ct400219n)
- **C. Gobbo, I. Beurroies, D. de Ridder, R. Eelkema, S.J. Marrink, S. De Feyter, J.H. van Esch, A.H. de Vries.** MARTINI model for physisorption of organic molecules on graphite. J. Phys. Chem. C, 117:15623–15631, 2013. [abstract](http://pubs.acs.org/doi/abs/10.1021/jp402615p)
- **S.J. Marrink, D.P. Tieleman.** Perspective on the Martini model. Chem. Soc. Rev., 42:6801-6822, 2013. [open access](http://pubs.rsc.org/en/Content/ArticleLanding/2013/CS/C3CS60093A)
- **A. Raudino, S.J. Marrink, M. Pannuzzo.** Anomalous viscosity effect in the early stages of the ion-assisted adhesion/fusion event between lipid bilayers: A theoretical and computational study. J. Chem. Phys., 138:234901, 2013. [abstract](http://jcp.aip.org/resource/1/jcpsa6/v138/i23/p234901_s1?bypassSSO=1)
- **C.A. Lopez, A.H. de Vries, S.J. Marrink.** Computational microscopy of cyclodextrin mediated cholesterol extraction from lipid model membranes. Sci. Rep., 3:2071, 2013. [open access](http://www.nature.com/srep/2013/130625/srep02071/full/srep02071.html)
- **T.A. Wassenaar, H.I. Ingólfsson, M. Prieß, S.J. Marrink, L.V. Schäfer.** Mixing Martini: electrostatic coupling in hybrid atomistic – coarse-grained biomolecular simulations. J. Phys. Chem. B, 117:3516–3530, 2013. [open access](http://pubs.acs.org/doi/abs/10.1021/jp311533p)
- **C.A. Lopez, Z. Sovova, F.J. van Eerden, A.H. de Vries, S.J. Marrink.** Martini force field parameters for glycolipids. JCTC, 9:1694–1708, 2013. [abstract](http://pubs.acs.org/doi/abs/10.1021/ct3009655)
- **C. Arnarez, J.P. Mazat, J. Elezgaray, S.J. Marrink, X. Periole.** Evidence for cardiolipin binding sites on the membrane-exposed surface of the cytochrome bc1. JACS, 135:3112–3120, 2013. [open access](http://pubs.acs.org/doi/abs/10.1021/ja310577u)
- **C. Arnarez, S.J. Marrink, X. Periole.** Identification of cardiolipin binding sites on cytochrome c oxidase at the entrance of proton channels. Sci. Rep., 3:1263, 2013. [open access](http://www.nature.com/srep/2013/130212/srep01263/full/srep01263.html)
- M**. Hu, D.H. de Jong, S.J. Marrink, M. Deserno.** Gaussian curvature elasticity determined from global shape transformations and local stress distributions: A comparative study using the MARTINI model. Farad. Discuss., 161:365-382, 2013. [abstract](http://pubs.rsc.org/en/Content/ArticleLanding/2012/FD/C2FD20087B)
- **D.H. de Jong, C.A. Lopez, S.J. Marrink.** Molecular view on protein sorting into liquid-ordered membrane domains mediated by gangliosides and lipid anchors. Farad. Discuss., 161:347-363, 2013. [abstract](http://pubs.rsc.org/en/content/articlelanding/2012/fd/c2fd20086d)
- **D.H. de Jong, G. Singh, W.F.D. Bennett, C. Arnarez, T.A. Wassenaar, L.V. Schäfer, X. Periole, D.P. Tieleman, S.J. Marrink.** Improved parameters for the Martini coarse-grained protein force field, JCTC, 9:687–697, 2013. [open access](http://pubs.acs.org.proxy-ub.rug.nl/doi/abs/10.1021/ct300646g)
- **X. Periole, S.J. Marrink.** The Martini coarse-grained force field. In "Methods in molecular biology", Vol 924,  L. Monticelli & E. Salonen Eds., Springer, 2013, pp 533-565. [abstract](http://www.springerprotocols.com/Abstract/doi/10.1007/978-1-62703-017-5_20), [reprint](http://cgmartini.nl/images/stories/martini-chapter.pdf)
