---
title: "2014"
format: html
---

- **A. Konijnenberg, D. Yilmaz, H.I. Ingólfsson, A. Dimitrova, S.J. Marrink, Z. Li, C. Vénien-­‐Bryan, F. Sobott, A. Koçer.** Global structural changes of an ion channel during its gating are followed by ion mobility mass spectrometry. PNAS, 111:17170-17175, 2014. [abstract](http://www.pnas.org/content/early/2014/11/12/1413118111.abstract)
- **G. Moiset, C.A. López, R. Bartelds, L. Syga, E. Rijpkema, A. Cukkemane, M. Baldus, B. Poolman, S.J. Marrink.** Disaccharides impact the lateral organization of lipid membranes. JACS, 136:16167-16175, 2014. [open access](http://pubs.acs.org/doi/abs/10.1021/ja505476c?journalCode=jacsat)
- **N. Mukherjee, M.D. Jose, J.P. Birkner, M. Walko, H.I. Ingólfsson, A. Dimitrova, C. Arnarez, S.J. Marrink, A. Koçer.** The activation mode of the mechanosensitive ion channel, MscL, by lysophosphatidylcholine differs from tension-induced gating. FASEB J., 28:4292-4302, 2014. [abstract](http://www.fasebj.org/content/early/2014/06/20/fj.14-251579.abstract)
- **H.I. Ingólfsson, M.N. Melo, F.J. van Eerden, C. Arnarez, C.A. López, T.A. Wassenaar, X. Periole, A.H. De Vries, D.P. Tieleman, S.J. Marrink.** Lipid organization of the plasma membrane. JACS, 136:14554-14559, 2014. [open access](http://pubs.acs.org/doi/abs/10.1021/ja507832e?journalCode=jacsat)
- **J. Barnoud, G. Rossi, S.J. Marrink, L. Monticelli.** Hydrophobic compounds reshape membrane domains. PLoS Comp. Biol., 10: e1003873, 2014. [open access](http://www.ploscompbiol.org/article/info:doi/10.1371/journal.pcbi.1003873)
- **H.I. Ingólfsson, P. Thakur, K.F. Herold, E.A. Hobart, N.B. Ramsey, X. Periole, D.H. de Jong, M. Zwama, D. Yilmaz, K. Hall, T. Maretzky, H.C. Hemmings, C. Blobel, S.J. Marrink, A. Kocer, J.T. Sack, O.S. Andersen.** Phytochemicals perturb membranes and promiscuously alter protein function. ACS Chem. Biol., 9:1788–1798, 2014. [abstract](http://pubs.acs.org/doi/abs/10.1021/cb500086e)
- **J. Zavadlav, M.N. Melo, A.V. Cunha, A.H. De Vries, S.J. Marrink, M. Praprotnik.** Adaptive resolution simulation of MARTINI solvents. JCTC, 10:2591–2598, 2014. [open access](http://pubs.acs.org.proxy-ub.rug.nl/doi/abs/10.1021/ct5001523)
- **F. Campelo, C. Arnarez, S.J. Marrink, M.M. Kozlov.** Helfrich model of membrane bending: from Gibbs theory of liquid interfaces to membranes as thick anisotropic elastic layers. Adv. Colloid Interf. Sci., 208:25-33, 2014. [abstract](http://www.sciencedirect.com/science/article/pii/S000186861400030X)
- **H.I. Ingólfsson, C.A. Lopez, J.J. Uusitalo, D.H. de Jong, S. Gopal, X. Periole, S.J. Marrink.** The power of coarse-graining in biomolecular simulations. WIREs Comput. Mol. Sci., 4:225–248, 2014. [open access](http://onlinelibrary.wiley.com/doi/10.1002/wcms.1169/full)
- **M. Pannuzzo, D.H. de Jong, A. Raudino, S.J. Marrink.** Simulation of polyethylene glycol and calcium-mediated membrane fusion. J. Chem. Phys., 140:124905, 2014. [abstract](http://scitation.aip.org/content/aip/journal/jcp/140/12/10.1063/1.4869176)
- **T.A. Wassenaar, K. Pluhackova, R.A. Böckmann, S.J. Marrink, D.P. Tieleman.** Going backward:A flexible geometric approach to reverse transformation from coarse grained to atomistic models. JCTC, 10:676-690, 2014. [abstract](http://pubs.acs.org/doi/abs/10.1021/ct400617g)
- **J. Zavadlav, M.N. Melo, S.J. Marrink, M. Praprotnik.** Adaptive resolution simulation of an atomistic protein in MARTINI water. J. Chem. Phys., 140:054114, 2014. [open access](http://scitation.aip.org/content/aip/journal/jcp/140/5/10.1063/1.4863329)