---
title: "2015"
format: html
---

- **M.N. Melo, H.I. Ingólfsson, S.J. Marrink.** Parameters for Martini sterols and hopanoids based on a virtual-site description. JCP, 143: 243152, 2015. [abstract](http://dx.doi.org/10.1063/1.4937783)
- **Y. Qi, H.I. Ingólfsson, X. Cheng, J. Lee, S.J. Marrink, W. Im.** CHARMM-GUI Martini Maker for coarse-grained simulations with the Martini force field. JCTC, 11:4486–4494, 2015. [abstract](http://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b00513?src=recsys)
- **J.J. Uusitalo, H.I. Ingólfsson, P. Akhshi, D.P. Tieleman, S.J. Marrink.** Martini coarse-grained force field: extension to DNA. JCTC 11:3932-3945, 2015. [open access](http://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b00286)
- **J. Zavadlav, M.N. Melo, S.J. Marrink, M. Praprotnik.** Adaptive resolution simulation of polarizable supramolecular coarse-grained water models. J. Chem. Phys, 142:244118, 2015. [abstract](http://dx.doi.org/10.1063/1.4923008)
- **D.H. de Jong, N. Liguori, T. van den Berg, C. Arnarez, X. Periole, S.J. Marrink.** Atomistic and coarse grain topologies for the cofactors associated with the photosystem II core complex. JPCB, 119:7791–7803, 2015. [abstract](http://pubs.acs.org/doi/abs/10.1021/acs.jpcb.5b00809)
- **T.A. Wassenaar, H.I. Ingólfsson, R.A. Böckmann, D.P. Tieleman, S.J. Marrink.** Computational lipidomics with insane: a versatile tool for generating custom membranes for molecular simulations. JCTC, 11:2144–2155, 2015. [abstract](http://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b00209)
- **T.A. Wassenaar, K. Pluhackova, A. Moussatova, D. Sengupta, S.J. Marrink, D.P. Tieleman, R.A. Böckmann.** High-throughput simulations of dimer and trimer assembly of membrane proteins. The DAFT approach. JCTC, 11:2278–2291, 2015. [abstract](http://pubs.acs.org/doi/abs/10.1021/ct5010092?src=recsys)
- **N. Goga, M.N. Melo, A.J. Rzepiela, A.H. De Vries, A. Hadar, S.J. Marrink, H.J.C. Berendsen.** Benchmark of schemes for multiscale molecular dynamics simulations. JCTC, 11:1389–1398, 2015.  [open access](http://pubs.acs.org/doi/abs/10.1021/ct501102b)
- **F.J. van Eerden, D.H. de Jong, A.H de Vries, T.A. Wassenaar, S.J. Marrink.** Characterization of thylakoid lipid membranes from cyanobacteria and higher plants by molecular dynamics simulations. BBA Biomembranes, 1848:1319–1330, 2015. [abstract](http://dx.doi.org/10.1016/j.bbamem.2015.02.025)
- **C. Arnarez, J.J. Uusitalo, M.F. Masman, H.I. Ingólfsson, D.H. de Jong, M.N. Melo, X. Periole, A.H. De Vries, S.J. Marrink.** Dry Martini, a coarse-grained force field for lipid membrane simulations with implicit solvent. JCTC, 11:260–275, 2015. [abstract](http://pubs.acs.org/doi/abs/10.1021/ct500477k?journalCode=jctcce)
- **C.A. López, G. Bellesia, A. Redondo, P. Langan, S.P.S. Chundawat, B.E. Dale, S.J. Marrink, S. Gnanakaran.** MARTINI coarse-grained model for crystalline cellulose microfibers. JPCB, 119:465–473, 2015. [abstract](http://pubs.acs.org/doi/abs/10.1021/jp5105938?journalCode=jpcbfk)