---
title: "2016"
format: html
---

- **J. Zavadlav, R. Podgornik, M.N. Melo, S.J. Marrink, M. Praprotnik.** Adaptive resolution simulation of an atomistic DNA molecule in MARTINI salt solution. Eur. Phys. J. Special Topics 225:1595-1607, 2016. [abstract](http://epjst.epj.org/articles/epjst/abs/first/epjst160117/epjst160117.html)
- **J. Zavadlav, S.J. Marrink, M. Praprotnik.** Adaptive resolution simulation of supramolecular water: The concurrent making, breaking, and remaking of water bundles. JCTC, 12:4138–4145, 2016. [open access](http://pubs.acs.org/doi/abs/10.1021/acs.jctc.6b00536)
- **C. Arnarez, S.J. Marrink, X. Periole.** Molecular mechanism of cardiolipin-mediated assembly of respiratory chain supercomplexes. Chem. Sci., 7:4435-4443, 2016. [open access](http://pubs.rsc.org/en/content/articlelanding/2016/sc/c5sc04664e#!divAbstract)
- **H.I. Ingólfsson, C. Arnarez, X. Periole, S.J. Marrink.** Computational 'microscopy' of cellular membranes. J. Cell Science, 129:257-268, 2016. [abstract](http://jcs.biologists.org/content/129/2/257)
- **D.H. de Jong, S. Baoukina, H.I. Ingólfsson, S.J. Marrink.** Martini straight: boosting performance using a shorter cutoff and GPUs. Comp. Phys. Comm., 199:1-7, 2016. [abstract](http://www.sciencedirect.com/science/article/pii/S0010465515003628)