---
title: "2017"
format: html
---

- **F.J. van Eerden, M.N. Melo, P.W.J.M. Frederix, S.J. Marrink.** Prediction of thylakoid lipid binding sites on photosystem II. Biophys. J. 113:2669-2681, 2017. [open access](http://www.cell.com/biophysj/abstract/S0006-3495(17)31120-7)
- **H.I. Ingólfsson, T.S. Carpenter, H. Bhatia, P.T. Bremer, S.J. Marrink, F.C. Lightstone.** Computational Lipidomics of the Neuronal Plasma Membrane. Biophys. J. 113:2271–2280, 2017. [open access](http://www.cell.com/biophysj/abstract/S0006-3495(17)31132-3)
- **T. Kondela, J. Gallová, T. Hauß, J. Barnoud, S.J. Marrink, N. Kučerka.** Alcohol interactions with lipid bilayers. Molecules, 22:2078, 2017. [abstract](http://www.mdpi.com/1420-3049/22/12/2078)
- **L. Qiu, J. Liu, R. Alessandri, X. Qiu, M. Koopmans, R.W.A. Havenith, S.J. Marrink, R.C. Chiechi, L.J.A. Koster, J.C. Hummelen.** Enhancing doping efficiency by improving host-dopant miscibility for fullerene-based n-type thermoelectrics. Journal of Material Chemistry A, 5:21234-2124, 2017. [abstract](http://pubs.rsc.org/en/content/articlelanding/2017/ta/c7ta06609k#!divAbstract)
- **P.C. Hsu, B.M.H. Bruininks, D. Jefferies, P.C. Telles de Souza, J. Lee, D.S. Patel, S.J .Marrink, Y. Qi, S. Khalid, W. Im.** CHARMM‐GUI Martini Maker for modeling and simulation of complex bacterial membranes with lipopolysaccharides. J. Comput. Chem., 38:2354–2363, 2017. [abstract](http://onlinelibrary.wiley.com/doi/10.1002/jcc.24895/full)
- **J.J. Uusitalo, H.I. Ingólfsson, S.J. Marrink, I. Faustino.** Martini coarse-grained force field: extension to RNA. Biophys. J., 113:246-256, 2017. [abstract](http://dx.doi.org/10.1016/j.bpj.2017.05.043)
- **F.J. van Eerden, M.N. Melo, P.W.J.M. Frederix, X. Periole, S.J. Marrink.** Exchange pathways of plastoquinone and plastoquinol in the photosystem II complex. Nature Commun. 8:15214, 2017. [open access](http://em.rdcu.be/wf/click?upn=KP7O1RED-2BlD0F9LDqGVeSNZPI4HSNgs5ujz0ebLhZ5E-3D_FVeFEq-2F4ZCAsRdiSmPWemcCJ1bLWlEnb-2Bn6YCusRM0dF-2FoAaGCoQGfj2KfdzbmbKuB-2Bq-2BVvWl6psnviI-2BBQy6U37hrPOleNfO8DRcMKI0cM-2FAsAUvzJDwG33-2F7vu4qOYF-2BShaq7ap7X-2FlOsNV62OzqJKyoKU-2Bs-2BOuXus2nL1u9mCsdHVb5ZJv8hWqZbj9W3If92HbBVzWkt-2FRKGkY6hYfw-3D-3D)
- **B. Liu, C. Åberg, F.J. van Eerden, S.J. Marrink, B. Poolman, A.J. Boersma.** Design and properties of genetically encoded probes for sensing macromolecular crowding. Biophys. J.  112:1929–1939, 2017. [abstract](http://www.cell.com/biophysj/fulltext/S0006-3495(17)30391-0)
- **V. Maingi, J.R. Burns, J.J. Uusitalo, S. Howorka, S.J. Marrink, M.S.P. Sansom.** Stability and dynamics of membrane-spanning DNA nanopores. Nature Comm. 8:14784, 2017. [open access](http://www.nature.com/articles/ncomms14784)
- **R. Alessandri, J.J. Uusitalo, A.H. De Vries, R.W.A. Havenith, S.J. Marrink.** Bulk heterojunction morphologies with atomistic resolution from coarse-grain solvent evaporation simulations. JACS, 139:3697–3705, 2017. [open access](http://pubs.acs.org/doi/abs/10.1021/jacs.6b11717)
- **M.N. Melo, C. Arnarez, H. Sikkema, N. Kumar, M. Walko, H.J.C. Berendsen, A. Kocer, S.J. Marrink, H.I. Ingólfsson.** High-throughput simulations reveal membrane-mediated effects of alcohols on MscL gating. JACS, 139:2664–2671, 2017. [open access](http://pubs.acs.org/doi/abs/10.1021/jacs.6b11091)
- **R.M. Venable, H.I. Ingólfsson, M.G. Lerner, B.S. Perrin, Jr., B.A. Camley, S.J. Marrink, F.L.H. Brown, R.W. Pastor.** Lipid and peptide diffusion in bilayers: The Saffman-Delbrück model and periodic boundary conditions. JPCB, 121:3443–3457, 2017. [abstract](http://pubs.acs.org/doi/abs/10.1021/acs.jpcb.6b09111)
- **F.J. van Eerden, T. van den Berg, P.W.J.M. Frederix, D.H. de Jong, X. Periole, S.J. Marrink.** Molecular dynamics of photosystem II embedded in the thylakoid membrane. JPCB, 121:3237–3249, 2017. [open access](http://pubs.acs.org/doi/abs/10.1021/acs.jpcb.6b06865)
- **R.X. Gu, H.I. Ingólfsson, A.H. de Vries, S.J. Marrink, D.P. Tieleman.** Ganglioside-lipid and ganglioside-protein interactions revealed by coarse-grained and atomistic molecular dynamics simulations. JPCB, 121:3262–3275, 2017. [open access](http://pubs.acs.org/doi/abs/10.1021/acs.jpcb.6b07142)
- **I. Faustino, S.J. Marrink.** cgHeliParm: analysis of dsDNA helical parameters for coarse-grained MARTINI molecular dynamics simulations. Bioinformatics, 33:3813-3815, 2017. [abstract](https://doi.org/10.1093/bioinformatics/btx444)