---
title: "2018"
format: html
---

- **S. Thallmair, H.I. Ingólfsson, S.J. Marrink.** Cholesterol Flip-Flop Impacts Domain Registration in Plasma Membrane Models. J. Phys. Chem. Lett. 9:5527–5533, 2018. [doi:10.1021/acs.jpclett.8b01877](https://pubs.acs.org/doi/abs/10.1021/acs.jpclett.8b01877)
- **V. Corradi, E. Mendez-Villuendas, H.I. Ingólfsson, R.X. Gu, I. Siuda, M.N. Melo, A. Moussatova, L.J. DeGagné, B.I. Sejdiu, G. Singh, T.A. Wassenaar, K. Delgado Magnero, S.J. Marrink, D.P. Tieleman.** Lipid–Protein Interactions Are Unique Fingerprints for Membrane Proteins. ACS Central Science 4:709–717, 2018. [doi:10.1021/acscentsci.8b00143](https://pubs.acs.org/doi/abs/10.1021/acscentsci.8b00143)
- **S. Baoukina, H.I. Ingólfsson, S.J. Marrink, D.P. Tieleman.** Curvature‐Induced Sorting of Lipids in Plasma Membrane Tethers. Advanced Theory Simul., 1:1800034, 2018. [doi:10.1002/adts.201800034](https://doi.org/10.1002/adts.201800034)
- **F. Grunewald, G. Rossi, A.H. De Vries, S.J. Marrink, L. Monticelli.** A Transferable MARTINI Model of Polyethylene Oxide. JPCB, 122:7436–7449, 2018. [doi:10.1021/acs.jpcb.8b04760](https://pubs.acs.org/doi/10.1021/acs.jpcb.8b04760)
- **M. Xue, L. Cheng, I. Faustino, W. Guo, S.J. Marrink.** Molecular Mechanism of Lipid Nanodisk Formation by Styrene-Maleic Acid Copolymers. Biophys. J., 115:494-502, 2018. [doi:10.1016/j.bpj.2018.06.018](https://www.cell.com/biophysj/abstract/S0006-3495(18)30721-5).
- **F. Sun, C.F.E. Schroer, L. Xu, H. Yin, S.J. Marrink, S.Z. Luo.** Molecular Dynamics of the Association of L-Selectin and FERM Regulated by PIP2. Biophys. J., 114:1858–1868, 2018. [doi:10.1016/j.bpj.2018.02.034](https://www.sciencedirect.com/science/article/pii/S0006349518302947)
- **P.W.J.M. Frederix, I. Patmanidis, S.J. Marrink.** Molecular simulations of self-assembling bio-inspired supramolecular systems and their connection to experiments. Chem. Soc. Review, 47:3470 - 3489, 2018. [doi:10.1039/C8CS00040A](http://pubs.rsc.org/en/content/articlelanding/2018/cs/c8cs00040a#!divAbstract)
- **J. Liu, L. Qiu, R. Alessandri, X. Qiu, G. Portale, J. Dong, W. Talsma, G. Ye, A.A. Sengrian, P.C.T. Souza, M.A. Loi, R.C. Chiechi, S.J. Marrink, J.C. Hummelen, L.J.A. Koster.** Enhancing Molecular n-Type Doping of Donor–Acceptor Copolymers by Tailoring Side Chains. Advanced Materials, 30:1704630, 2018. [doi:10.1002/adma.201704630](http://onlinelibrary.wiley.com/doi/10.1002/adma.201704630/full)
- **J. Su, A.S. Thomas, T. Grabietz, C. Landgraf, R. Volkmer, S.J. Marrink, C. Williams,  M.N. Melo.** The N-terminal amphipathic helix of Pex11p self-interacts to induce membrane remodelling during peroxisome fission. BBA Biomembr., 1860, 6:1292-1300, 2018. [doi:10.1016/j.bbamem.2018.02.029](https://www.sciencedirect.com/science/article/pii/S0005273618300701)
- **J.N. Pedersen, P.W.J.M. Frederix, J.S. Pedersen, S.J. Marrink, D. Otzen.** Role of charge and hydrophobicity in liprotide formation: a molecular dynamics study with experimental constraints. ChemBioChem, 19:263–271, 2018. [doi:10.1002/cbic.201700496](http://onlinelibrary.wiley.com/doi/10.1002/cbic.201700496/full)
- **J. Zavadlav, S.J. Marrink, M. Praprotnik.** Multiscale simulation of protein hydration using the SWINGER dynamical clustering algorithm. J. Chem. Theory Comput., 14:1754-1761, 2018. [doi:10.1021/acs.jctc.7b01129](https://pubs.acs.org/doi/abs/10.1021/acs.jctc.7b01129)