---
title: "2019"
format: html
---

- **P.C.T. Souza, S. Thallmair, S.J. Marrink, R. Mera-Adasme.** An Allosteric Pathway in SOD1 Unravels the Molecular Mechanism of the G93A ALS-Linked Mutation. J. Phys. Chem. Letters, 10:7740-7744, 2019. [doi.org/10.1021/acs.jpclett.9b02868](https://doi.org/10.1021/acs.jpclett.9b02868)
- **Y. Liu, J. Barnoud, S.J. Marrink.** Gangliosides Destabilize Lipid Phase Separation in Multicomponent Membranes. Biophys. J. 117: 1215-1223, 2019. [doi.org/10.1016/j.bpj.2019.08.037](https://doi.org/10.1016/j.bpj.2019.08.037)
- **B.M.H. Bruininks, P.C.T. Souza, S.J. Marrink.** A Practical View of the Martini Force Field. Biomolecular Simulations, 105-127, 2019. [doi:10.1007/978-1-4939-9608-7_5](https://link.springer.com/protocol/10.1007/978-1-4939-9608-7_5) , [pdf-reprint](http://cgmartini.nl/images/practical-view-Martini-biomolsim19.pdf).
- **R. Alessandri, P.C.T. Souza, S. Thallmair, M.N. Melo, A.H. De Vries, S.J. Marrink,** Pitfalls of the MARTINI model. JCTC, 15:5448-5460, 2019. [doi.org/10.1021/acs.jctc.9b00473](https://pubs.acs.org/doi/abs/10.1021/acs.jctc.9b00473)
- **A. Newe, K. Rzeniewicz, M. König, C.F.E. Schroer, J. Joachim, A. Rey-Gallardo, S.J Marrink, J. Deka, M. Parsons, A. Ivetic.** Serine phosphorylation of the L-selectin tail regulates ERM binding, clustering, and monocyte protrusion in transendothelial migration. Front. Immunol. 10, 2227, 2019. [doi:10.3389/fimmu.2019.02227](https://doi.org/10.3389/fimmu.2019.02227)
- **W. Pezeshkian, M. König, S.J. Marrink, J.H. Ipsen.** A multi-scale approach to membrane remodeling processes. Front. Mol. Biosci. 6, 59, 2019. [doi:10.3389/fmolb.2019.00059](https://doi.org/10.3389/fmolb.2019.00059)
- **S. Koch, `M. Exterkate, C.A. López, M. Patro, S.J. Marrink, A.J.M. Driessen** Two distinct anionic phospholipid-dependent events involved in SecA-mediated protein translocation. BBA-Biomembr. 1861, 183035, 2019. [doi.10.1016/j.bbamem.2019.183035](https://doi.org/10.1016/j.bbamem.2019.183035)
- **T.K. Piskorz, C. Gobbo, S.J. Marrink, S. De Feyter, A.H. De Vries, J.H. van Esch.** Nucleation Mechanisms of Self-Assembled Physisorbed Monolayers on Graphite. J. Phys. Chem. C 123, 17510, 2019. [doi:10.1021/acs.jpcc.9b01234](https://pubs.acs.org/doi/pdf/10.1021/acs.jpcc.9b01234)
- **S. Dadsena, S. Bockelmann, J.G.M. Mina, D.G. Hassan, S. Korneev, G. Razzera, H. Jahn, P. Niekamp, D. Müller, M. Schneider, F.G. Tafesse, S.J. Marrink, M.N. Melo, J.C.M. Holthuis,** Ceramides bind VDAC2 to trigger mitochondrial apoptosis. Nature Commun. 10:1832, 2019. [doi:10.1038/s41467-019-09654](https://www.nature.com/articles/s41467-019-09654-4#article-info)
- **J. Zavadlav, S.J. Marrink M. Praprotnik,** SWINGER: a clustering algorithm for concurrent coupling of atomistic and supramolecular liquids. Interface Focus 9:20180075, 2019. [doi.org/10.1098/rsfs.2018.0075](https://royalsocietypublishing.org/doi/10.1098/rsfs.2018.0075)
- **S. Thallmair, P.A. Vainikka, S.J. Marrink.** Lipid Fingerprints and Cofactor Dynamics of Light-Harvesting Complex II in Different Membranes. Biophys. J., 116:1446-1455, 2019. [doi:10.1016/j.bpj.2019.03.009](https://www.cell.com/biophysj/fulltext/S0006-3495(19)30195-X)
- **S.J. Marrink, V. Corradi, P.C.T. Souza, H.I. Ingolfsson, D.P. Tieleman, M.S.P. Sansom.** Computational Modeling of Realistic Cell Membranes. Chem. Review, 119:6184–6226, 2019. [doi:10.1021/acs.chemrev.8b00460](https://pubs.acs.org/doi/abs/10.1021/acs.chemrev.8b00460)
- **V. Corradi, B.I. Sejdiu, H. Mesa-Galloso, H. Abdizadeh, S.Y. Noskov, S.J. Marrink, D.P. Tieleman.** Emerging Diversity in Lipid–Protein Interactions, Chem. Review, 119:5775–5848, 2019. [doi:10.1021/acs.chemrev.8b00451](https://pubs.acs.org/doi/10.1021/acs.chemrev.8b00451)