---
title: "2020"
format: html
---

- **L.I. Vazquez-Salazar, M. Selle, A.H. de Vries, S.J. Marrink, P.C.T. Souza.** Martini coarse-grained models of imidazolium-based ionic liquids: from nanostructural organization to liquid-liquid extraction. Green Chemistry, 22:7376-7386, 2020. [doi:10.1039/D0GC01823F](https://doi.org/10.1039/D0GC01823F)
- **R. Alessandri, S. Sami, J. Barnoud, A.H. de Vries, S.J. Marrink, R.W.A. Havenith.** Resolving donor–acceptor interfaces and charge carrier energy levels of organic semiconductors with polar side chains. Advanced Funct. Materials, 2004799, 2020 .[doi:10.1002/adfm.202004799](https://doi.org/10.1002/adfm.202004799)
- **A. Buyan, C.D. Cox, J. Barnoud, J. Li, H.S.M. Chan, B. Martinac, S.J. Marrink, B. Corry.** Piezo1 forms specific, functionally important interactions with phosphoinositides and cholesterol. Biophys. J. 119:1683-1697, 2020. [doi.10.1016/j.bpj.2020.07.043](https://doi.org/10.1016/j.bpj.2020.07.043)
- S**. Maity, J. Ottelé, G.M. Santiago, P.W.J.M. Frederix, P. Kroon, O. Markovitch, M.C.A. Stuart, S.J. Marrink, S. Otto, W.H Roos.** Caught in the act: mechanistic insight into supramolecular polymerization-driven self-replication from real-time visualization. J. Amer. Chem. Soci. 142:13709–13717, 2020. [doi:org/10.1021/jacs.0c02635](https://doi.org/10.1021/jacs.0c02635)
- **P.C.T. Souza, S. Thallmair, P. Conflitti, C. Ramírez-Palacios, R. Alessandri, S. Raniolo, V. Limongelli,  S.J. Marrink.** Protein–ligand binding with the coarse-grained Martini model. Nature Commun. 11:3714, 2020. [doi:10.1038/s41467-020-17437-5](https://doi.org/10.1038/s41467-020-17437-5)
- **F. Grunewald, P.C.T. Souza, H. Abdizadeh, J. Barnoud, A.H. de Vries, S.J. Marrink.** Titratable Martini model for constant pH simulations. J. Chem. Phys, 153:024118, 2020. [doi:10.1063/5.0014258](https://doi.org/10.1063/5.0014258)
- **Y. Liu, W. Pezeshkian, J. Barnoud, A.H. de Vries, S.J. Marrink.** Coupling coarse-grained to fine-grained models via Hamiltonian replica exchange. JCTC, 2020. [doi.org/10.1021/acs.jctc.0c00429](https://doi.org/10.1021/acs.jctc.0c00429)
- **W. Pezeshkian, M. Konig, T.A. Wassenaar, S.J. Marrink.** Backmapping triangulated surfaces to coarse-grained membrane models. Nature Commun. 11:2296, 2020. [doi.org/10.1038/s41467-020-16094-y](https://doi.org/10.1038/s41467-020-16094-y)
- **Y. Liu, A.H. de Vries, J. Barnoud, W. Pezeshkian, J. Melcr, S.J. Marrink.** Dual resolution membrane simulations using virtual sites. JPCB 124:3944, 2020. [doi.org/10.1021/acs.jpcb.0c01842](https://doi.org/10.1021/acs.jpcb.0c01842)
- **J. Su, S.J. Marrink, M.N. Melo.** Localization Preference of Antimicrobial Peptides on Liquid-Disordered Membrane Domains. Front. Cell Dev. Biol., 8:350, 2020. [doi.org/10.3389/fcell.2020.00350](https://doi.org/10.3389/fcell.2020.00350)
- **B.M.H. Bruininks, P.C.T. Souza, H. Ingolfsson, S.J. Marrink.**  A molecular view on the escape of lipoplexed DNA from the endosome. eLife,  9:e52012, 2020. [doi.org/10.7554/eLife.52012](https://doi.org/10.7554/eLife.52012)
- **F. Sun, C.F.E. Schroer, C.R. Palacios, L. Xu, S.Z. Luo, S.J. Marrink.** Molecular mechanism for bidirectional regulation of CD44 for lipid raft affiliation by palmitoylations and PIP2. PLoS Comput. Biol. 16:e1007777, 2020. [doi.org/10.1371/journal.pcbi.1007777](https://doi.org/10.1371/journal.pcbi.1007777)
- **I. Faustino, H. Abdizadeh, P.C.T. Souza, A. Jeucken, W.K. Stanek, A. Guskov, D.J. Slotboom, S.J. Marrink.** Membrane mediated toppling mechanism of the folate energy coupling factor transporter. Nature Commun. 11:1763, 2020. [doi.org/10.1038/s41467-020-15554-9](https://doi.org/10.1038/s41467-020-15554-9)
- **N. Liguori, R. Croce, S.J. Marrink, S. Thallmair.** Molecular dynamics simulations in photosynthesis. Photosynth Res. 144:273–295, 2020. [doi.org/10.1007/s11120-020-00741-y](https://doi.org/10.1007/s11120-020-00741-y)
- **C.F.E. Schroer, L. Baldauf, L. van Buren, T.A. Wassenaar, M.N. Melo, G. Koenderink, S.J. Marrink.** Charge-dependent interactions of monomeric and filamentous actin with lipid bilayers. PNAS, 117: 5861-5872, 2020. [doi.org/10.1073/pnas.1914884117](https://doi.org/10.1073/pnas.1914884117)
- **H.M. Khan, P.C.T. Souza, S. Thallmair, J. Barnoud, A.H. De Vries, S.J. Marrink, N. Reuter.** Capturing choline-aromatics cation-π interactions in the MARTINI force field. JCTC, 16:2550-2560, 2020. [doi.org/10.1021/acs.jctc.9b01194](https://doi.org/10.1021/acs.jctc.9b01194)