---
title: "2021"
format: html
---

- **P. Vainikka, S. Thallmair, P.C.T. Souza, S.J. Marrink.** Martini 3 Coarse-Grained Model for Type III Deep Eutectic Solvents: Thermodynamic, Structural, and Extraction Properties. ACS Sustainable Chemistry & Engineering 9 (51), 17338–17350, 2021. [https://pubs.acs.org/doi/full/10.1021/acssuschemeng.1c06521](https://pubs.acs.org/doi/full/10.1021/acssuschemeng.1c06521)
- **S. Zhang, G. Huang, R.C.A. Versloot, B.M.H. Bruininks, P.C.T. de Souza, S.J. Marrink, G. Maglia.** Bottom-up fabrication of a proteasome–nanopore that unravels and processes single proteins. Nature Chemistry, 1-8, 2021. [https://www.nature.com/articles/s41557-021-00824-w](https://www.nature.com/articles/s41557-021-00824-w)
- **A.M. Liaci, ..., S.J.Marrink, R.A.Scheltema, F. Förster.** Structure of the human signal peptidase complex reveals the determinants for signal peptide cleavage. Mol. Cell. 81, 3934-3948, 2021. [https://doi.org/10.1016/j.molcel.2021.07.031](https://doi.org/10.1016/j.molcel.2021.07.031)
- **B.M.H. Bruininks, A.S. Thie, P.C.T. Souza, T.A. Wassenaar, S. Faraji, S.J. Marrink.** Sequential Voxel-Based Leaflet Segmentation of Complex Lipid Morphologies. J. Chem. Theory Comput., 17:7873–7885, 2021. [doi.org/10.1021/acs.jctc.1c00446](https://doi.org/10.1021/acs.jctc.1c00446)
- **Y. Liu, A.H. de Vries, W. Pezeshkian, S.J. Marrink.** Capturing Membrane Phase Separation by Dual Resolution Molecular Dynamics Simulations. J. Chem. Theory Comput. 17:5876–5884, 2021. [https://doi.org/10.1021/acs.jctc.1c00151](https://doi.org/10.1021/acs.jctc.1c00151)
- **S. Thallmair, M. Javanainen, B. Fábián, H. Martinez-Seara, S.J. Marrink.** Nonconverged Constraints Cause Artificial Temperature Gradients in Lipid Bilayer Simulations. J. Phys. Chem. B 125 (33), 9537–9546, 2021. [https://doi.org/10.1021/acs.jpcb.1c03665](https://doi.org/10.1021/acs.jpcb.1c03665)
- **R. Alessandri, F. Grünewald, S.J. Marrink.** The Martini Model in Materials Science, Adv. Materials 33:2008635, 2021. [https://doi.org/10.1002/adma.202008635](https://onlinelibrary.wiley.com/doi/10.1002/adma.202008635)
- **M. Tsanai, P.W.J.M. Frederix, C.F.E. Schroer, P.C.T. Souza, S.J. Marrink.** Coacervate formation studied by explicit solvent coarse-grain molecular dynamics with the Martini model. Chem. Sci.12:8521-8530, 2021. [https://doi.org/10.1039/D1SC00374G](https://doi.org/10.1039/D1SC00374G)
- **M. Nemchinova, J. Melcr, T.A. Wassenaar, S.J. Marrink, A. Guskov.** Asymmetric CorA Gating Mechanism as Observed by Molecular Dynamics Simulations. J. Chem. Inf. Model. 61:2407–2417, 2021. [doi.10.1021/acs.jcim.1c00261](https://pubs.acs.org/doi/10.1021/acs.jcim.1c00261)
- **P.C.T. Souza, R. Alessandri, J. Barnoud, S. Thallmair, I. Faustino, ... S.J. Marrink.** Martini 3: a general purpose force field for coarse-grained molecular dynamics. Nature Methods 18:382–388, 2021. [doi:org/10.1038/s41592-021-01098-3](https://www.nature.com/articles/s41592-021-01098-3)
- **P.C.T. Souza, V. Limongelli, S. Wu, S.J. Marrink, L. Monticelli.** Perspectives on High-Throughput Ligand/Protein Docking With Martini MD Simulations. Front. Mol. Biosciences 8:657222, 2021. [doi:10.3389/fmolb.2021.657222](https://doi.org/10.3389/fmolb.2021.657222)
- **W. Pezeshkian, S.J. Marrink.** Simulating Realistic Membrane Shapes. Curr. Opin. Cell Biol. 71:103-111, 2021. [doi:10.1016/j.ceb.2021.02.009](https://doi.org/10.1016/j.ceb.2021.02.009)
- **F. Grünewald, P.C. Kroon, P.C.T. Souza, S.J. Marrink.** Protocol for Simulations of PEGylated Proteins with Martini 3. Structural Genomics: Methods in Molecular Biology 2199:315-335, 2021. [reprint](http://cgmartini.nl/images/structural-genomics-chap18.pdf)