---
title: "2022"
format: html
---

- **V. Thallmair, L. Schultz, W. Zhao, S.J. Marrink, D. Oliver, S. Thallmair.** Two cooperative binding sites sensitize PI(4,5)P2 recognition by the tubby domain. Science Advances 8 (36), eabp9471, 2022. [DOI: 10.1126/sciadv.abp9471](https://doi.org/10.1126/sciadv.abp9471)
- **F. Grünewald, M.H. Punt, E.E. Jefferys, P.A. Vainikka, M. König, V. Virtanen, T.A. Meyer, W. Pezeshkian, A.J. Gormley, M. Karonen, M.S.P. Sansom, P.C.T. Souza, S.J. Marrink.** Martini 3 Coarse-Grained Force Field for Carbohydrates. Journal of Chemical Theory and Computation, 18 (12), 7555–7569, 2022. [https://pubs.acs.org/doi/10.1021/acs.jctc.2c00757](https://pubs.acs.org/doi/10.1021/acs.jctc.2c00757)
- **I. Patmanidis, P.C.T. Souza, S. Sami, R.W.A. Havenith, A.H. de Vries, S.J. Marrink.** Modelling structural properties of cyanine dye nanotubes at coarse-grained level. Nanoscale Advances 4, 3033 - 3042, 2022. [https://pubs.rsc.org/en/content/articlelanding/2022/na/d2na00158f](https://pubs.rsc.org/en/content/articlelanding/2022/na/d2na00158f)
- **J. Frallicciardi, J. Melcr, P. Siginou, S.J. Marrink, B. Poolman.** Membrane thickness, lipid phase and sterol type are determining factors in the permeability of membranes to small solutes. Nature Communications 13, 1605, 2022. [https://www.nature.com/articles/s41467-022-29272-x](https://www.nature.com/articles/s41467-022-29272-x)
- **F. Azadi-Chegeni, S. Thallmair, M.E. Ward, G. Perin, S.J. Marrink, M. Baldus, T. Morosinotto, A. Pandit.** Protein dynamics and lipid affinity of monomeric, zeaxanthin-binding LHCII in thylakoid membranes. Biophysical Journal 121 (3), 396-409, 2022. [https://www.sciencedirect.com/science/article/abs/pii/S0006349521039631](https://www.sciencedirect.com/science/article/abs/pii/S0006349521039631)
- **F. Grünewald, R. Alessandri, P.C. Kroon, L. Monticelli, P.C.T. Souza, S.J. Marrink.** Polyply; a python suite for facilitating simulations of macromolecules and nanomaterials. Nature Communications 13, 68, 2022. [https://www.nature.com/articles/s41467-021-27627-4](https://www.nature.com/articles/s41467-021-27627-4)
- **R. Alessandri, J. Barnoud, A.S. Gertsen, I. Patmanidis, A.H. de Vries, P.C.T. Souza, S.J. Marrink.** Martini 3 Coarse-Grained Force Field: Small Molecules. Advanced Theory and Simulations 5, 2100391, 2022. [https://onlinelibrary.wiley.com/doi/full/10.1002/adts.202100391](https://onlinelibrary.wiley.com/doi/full/10.1002/adts.202100391)
- **N. Machado, B.M.H. Bruininks, ..., S.J. Marrink, P.C.T. Souza, P.P. Favero.** Complex nanoemulsion for vitamin delivery: droplet organization and interaction with skin membranes. Nanoscale 14, 506 - 514, 2022. [https://doi.org/10.1039/D1NR04610A](https://doi.org/10.1039/D1NR04610A)