---
title: "2023"
format: html
---

- **C. Thangaratnarajah, M. Nijland, L. Borges-Araújo, A. Jeucken, J. Rheinberger, S.J. Marrink, P.C.T. Souza, C. Paulino, D.J. Slotboom.** Expulsion mechanism of the substrate-translocating subunit in ECF transporters. Nature Commun. 14, 4484, 2023. [doi:10.1038/s41467-023-40266-1](https://www.nature.com/articles/s41467-023-40266-1)
- **A. Blanco-González, S.J. Marrink, Á. Piñeiro, R. García-Fandiño.** Molecular insights into the effects of focused ultrasound mechanotherapy on lipid bilayers: unlocking the keys to design effective treatments. J. Colloid Interf. Sci. 650 (B), 1201-1210, 2023. [doi:10.1016/j.jcis.2023.07.077](https://doi.org/10.1016/j.jcis.2023.07.077)
- **B.R. Gilbert, Z.R. Thornburg, T.A. Brier, J.A. Stevens, F. Grunewald, J.E. Stone, S.J. Marrink, Z.A. Luthey-Schulten.** Dynamics of Chromosome Organization in a Minimal Bacterial Cell. Front. Cell Dev. Biol., 2023, online. [doi:10.3389/fcell.2023.1214962](https://www.frontiersin.org/articles/10.3389/fcell.2023.1214962/abstract)
- **A. Melcrova, S. Maity, J. Melcr, N.A.W. de Kok, M. Gabler, J. van der Eyden, W. Stensen, J.S M. Svendsen, A.J.M. Driessen, S.J. Marrink, W.H. Roos.** Lateral membrane organization as target of an antimicrobial peptidomimetic compound. Nature Commun. 4, 4038, 2023. [doi:10.1038/s41467-023-39726-5](https://doi.org/10.1038/s41467-023-39726-5)
- **S. Sami, S.J. Marrink.** Reactive Martini: Chemical Reactions in Coarse-Grained Molecular Dynamics Simulations. J. Chem. Theory Comput., 2023, online. [doi:10.1021/acs.jctc.2c01186](https://doi.org/10.1021/acs.jctc.2c01186)
- **M. Ren, L. Zhao, Z. Ma, H. An, S.J. Marrink, F. Sun.** Molecular basis of PIP2-dependent conformational switching of phosphorylated CD44 in binding FERM. Biophys. J., 122 (13), 2675-2685, 2023. [doi:10.1016/j.bpj.2023.05.021](https://doi.org/10.1016/j.bpj.2023.05.021)
- **C. Empereur-Mot, K.B. Pedersen, C. Caruso, M. Perrone, M. Crippa, P.C.T. Souza, S.J. Marrink, G.M. Pavan.** On the Automatic Optimization of Lipid Models in the Martini Force Field using SwarmCG. J. Chem. Inf. Model. 63 (12), 3827–3838, 2023. [doi:10.1021/acs.jcim.3c00530](https://doi.org/10.1021/acs.jcim.3c00530)
- **W. Pezeshkian, F. Grünewald, O. Narykov, S. Lu, T.A. Wassenaar, S.J. Marrink, D. Korkin.** Molecular architecture of SARS-CoV-2 envelope by integrative modeling. Structure 31 (4), 492-503, 2023. [doi:10.1016/j.str.2023.02.006](https://doi.org/10.1016/j.str.2023.02.006)
- **S. Sami, F. Grünewald, P.C.T. Souza, S.J. Marrink,** A Guide to Titratable Martini Simulations, in A Practical Guide to Recent Advances in Multiscale Modeling and Simulation of Biomolecules [AIP Publishing (online), Melville, New York, 2023], available at: [doi:10.1063/9780735425279_004](https://doi.org/10.1063/9780735425279_004).
- **R. Alessandri, S. Thallmair, C.G. Herrero, R. Mera- Adasme, S.J. Marrink, P.C.T. Souza,** A Practical Introduction to Martini 3 and its Application to Protein-Ligand Binding Simulations, in A Practical Guide to Recent Advances in Multiscale Modeling and Simulation of Biomolecules [AIP Publishing (online), Melville, New York, 2023]. [doi:10.1063/9780735425279_001](https://doi.org/10.1063/9780735425279_001)
- **C. Hilpert, L. Beranger, P.C.T. Souza, P.A. Vainikka, V. Nieto, S.J. Marrink, L. Monticelli, G. Launay.** Facilitating CG Simulations with MAD: The MArtini Database Server. J. Chem. Inf. Model., 63 (3), 702–710, 2023. [doi:10.1021/acs.jcim.2c01375](https://doi.org/10.1021/acs.jcim.2c01375)
- **M.G. Chiariello, F. Grünewald, R. Zarmiento-Garcia, S.J. Marrink.** pH-Dependent Conformational Switch Impacts Stability of the PsbS Dimer. J. Phys. Chem. Lett. 14, 905-911, 2023. [doi:10.1021/acs.jpclett.2c03760](https://doi.org/10.1021/acs.jpclett.2c03760)
- **J.A. Stevens, F. Grünewald, P.A.M. van Tilburg, M. König, B.R. Gilbert, T.A. Brier, Z.R. Thornburg, Z. Luthey-Schulten, S.J. Marrink.** Molecular dynamics simulation of an entire cell. Frontiers in Chemistry 11, 2023. [doi:10.3389/fchem.2023.1106495](https://doi.org/10.3389/fchem.2023.1106495)
- **P. Vainikka, S.J. Marrink.** Martini 3 Coarse-Grained Model for Second-Generation Unidirectional Molecular Motors and Switches. J. Chem. Theory Comput., 2023, online. [doi:org/10.1021/acs.jctc.2c00796](https://doi.org/10.1021/acs.jctc.2c00796)
- **B. Waclawiková, P.C.T. Souza, M. Schwalbe, C.G. Neochoritis, W. Hoornenborg, S.A. Nelemans, S.J. Marrink, S. El Aidy.** Potential binding modes of the gut bacterial metabolite, 5-hydroxyindole, to the intestinal L-type calcium channels and its impact on the microbiota in rats. Gut Microbes 15 (1), 2154544, 2023. [doi:10.1080/19490976.2022.2154544](https://doi.org/10.1080/19490976.2022.2154544)
- **S.J. Marrink, L. Monticelli, M.N. Melo, R. Alessandri, D.P. Tieleman, P.C.T. Souza.** Two decades of Martini: Better beads, broader scope. Wires Computational Molecular Science, 13(1), e1620, 2023. [https://wires.onlinelibrary.wiley.com/doi/full/10.1002/wcms.1620](https://wires.onlinelibrary.wiley.com/doi/full/10.1002/wcms.1620)
- **N. De Franceschi, W. Pezeshkian, A. Fragasso, B.M.H. Bruininks, S. Tsai, S.J. Marrink, C. Dekker.** Synthetic Membrane Shaper for Controlled Liposome Deformation. ACS Nano, online, 2023. [doi:10.1021/acsnano.2c06125](https://doi.org/10.1021/acsnano.2c06125)