---
title: ""          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: ""         # Paper authors (required)
year: ""           # Publication year (required)
publication: ""    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: ""            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - keyword 1
  - keyword 2
  - Use as many as you think appropiate
  - And try to use consistency accross the entire library
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Marrink, S. J., & Mark, A. E. (2003). The Mechanism of Vesicle Fusion as Revealed by Molecular Dynamics Simulations. Journal of the American Chemical Society, 125(37), 11144–11145. https://doi.org/10.1021/ja036138+

## Abstract

We describe molecular dynamics simulations elucidating the molecular details of the process of fusion for small lipid vesicles. The simulations are based on a coarse grained (CG) lipid model that accurately represents the lamellar state of a variety of phospholipids and enables us to observe intermediate stages during fusion at near atomic detail. Simulations were conducted on a variety of systems containing common phospholipids such as phosphatidylcholine (PC), phosphatidylethanolamine (PE), lysoPC, and mixtures of the above. The fusion intermediates found are in general agreement with the stalk−pore mechanism. Transient pores sometimes form adjacent to the stalk, however, resulting in the mixing of lipids from the outer and inner monolayers. The speed of stalk formation and the opening of the fusion pore can be modulated by altering the lipid composition in qualitative agreement with experimental observations.