---
title: "Comparison of Atomic-Level and Coarse-Grained Models for Liquid Hydrocarbons from Molecular Dynamics Configurational Entropy Estimates"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Riccardo Baron, Alex H. de Vries, Philippe H. Hünenberger, and Wilfred F. van Gunsteren"         # Paper authors (required)
year: "2006"           # Publication year (required)
publication: "The Journal of Physical Chemistry B"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jp055888y"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Small molecules
  - Solvents
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Marrink, S. J., & Mark, A. E. (2003). The Mechanism of Vesicle Fusion as Revealed by Molecular Dynamics Simulations. Journal of the American Chemical Society, 125(37), 11144–11145. https://doi.org/10.1021/ja036138+

## Abstract

Molecular liquids can be modeled at different levels of spatial resolution. In atomic-level (AL) models, all (heavy) atoms can be explicitly simulated. In coarse-grained (CG) models, particles (beads) that represent groups of covalently bound atoms are used as elementary units. Ideally, a CG model should reproduce the thermodynamic and structural properties of the corresponding AL model after mapping to the lower-resolution scale. In the present work, two such models are investigated:  (i) the classical GROMOS atomic-level model; (ii) a CG model recently proposed by Marrink et al., which maps approximately four non-hydrogen atoms to one bead [J. Phys. Chem. B2004, 108, 750]. The study is restricted to n-alkanes whose aliphatic fragments are abundantly found in lipids of biological interest. Additionally, cis-9-octadecene is included, as a template chain of the lipid dioleoylphosphatidylcholine (DOPC). The two representations of molecules in the liquid phase are compared in terms of average molecular structures, extent of configurational space sampled, and single-molecule entropies. An approximate method is used to estimate the rotational contributions to the absolute configurational entropy. Good correspondence between the AL and CG representations is found. The loss in configurational entropy due to the reduction in degrees of freedom upon coarse-graining of the model is estimated.