---
title: Input parameters
format: html
---

Example of a general input parameter files for Gromacs 5. For comparison of the different .mdp options see:

- **D.H. de Jong, S. Baoukina, H.I. Ingólfsson, Marrink S.J.** Martini straight: boosting performance using a shorter cutoff and GPUs. Comput. Phys. Commun., 199:1-7, 2016. [doi:10.1016/j.cpc.2015.09.014](http://www.sciencedirect.com/science/article/pii/S0010465515003628)

Based on the extensive testing, we recommend the new-rf.mdp parameters for most cases. However not all systems have been tested and we recommend you do your own tests. In addition, for consistency within a project the same .mdp options should always be used.

- [martini_v3.x_example.mdp](http://cgmartini.nl/images/parameters/exampleMDP/martini_v3.x_example.mdp)

- [martini_v2.x_new-rf.mdp](http://cgmartini.nl/images/parameters/exampleMDP/martini_v2.x_new-rf.mdp)

- [martini_v2.x_new.mdp](http://cgmartini.nl/images/parameters/exampleMDP/martini_v2.x_new.mdp)

- [martini_v2.x_forcemod.mdp](http://cgmartini.nl/images/parameters/exampleMDP/martini_v2.x_forcemod.mdp)

- [martini_v2.x_common.mdp](http://cgmartini.nl/images/parameters/exampleMDP/martini_v2.x_common.mdp)

 

Example of a general input parameter files (Gromacs 4). Explanations on the various options and which options to change for the use with polarizable water are given inside the file.

- [martini_v2.x_example.mdp](http://cgmartini.nl/images/parameters/exampleMDP/martini_v2.x_example.mdp)

<font color="gray">Older mdp-files (gromacs 3) for reference purpose only. Version 2.x. is for version 2.0, 2.1 and 2.2, 2.P is for use with polarizable water (2.P and 2.2P).</font>

- [martini_v2.x_example.mdp](http://cgmartini.nl/images/parameters/exampleMDP/old/martini_v2.x_example.mdp)
- [martini_v2.P_example.mdp](http://cgmartini.nl/images/parameters/exampleMDP/old/martini_v2.P_example.mdp)