---
title: Particle definitions
format: html
---
<hr>

### We are glad to announce the release and publication of MARTINI 3!

Please read and cite the associated publication when using the new version: [PCT Souza, et al., Nat. Methods, 2021](https://www.nature.com/articles/s41592-021-01098-3#Sec13).

The parameters are available for download [here](http://cgmartini.nl/images/martini_v300.zip).

An extended collection of Martini 3 models for small molecules is now available [here](https://github.com/ricalessandri/Martini3-small-molecules/blob/main/models/martini_v3.0.0_small_molecules_v1.itp) [(R. Alessandri, et al., Adv. Theory Simul., 2022](https://doi.org/10.1002/adts.202100391)).

And [here](https://github.com/ricalessandri/Martini3-small-molecules/blob/main/tutorials/building_block_table.pdf)'s a table (in continuous expansion) to help with choosing bead types.

Please enjoy Martini 3 responsibly! Make sure to <u>read the publication with the supplementary information</u>, and stay tuned for new and improved Martini 3 [tutorials](http://cgmartini.nl/index.php/martini-3-tutorials).

### Martini 2

The definition of all CG particle types plus the interaction matrix. It also contains the topology for water particles. This file is required for all simulations. Version 2.1 or 2.2 are required for peptides & proteins, and version 2.P, 2.2P and 2.2refP (RF, PME) for use in combination with the polarizable water model. References can be found in the headers of the corresponding ITP files. (updated: dd-mm-yyyy)

- [martini_v2.0.itp](http://cgmartini.nl/images/parameters/ITP/martini_v2.0.itp)
- [martini_v2.1.itp](http://cgmartini.nl/images/parameters/ITP/martini_v2.1.itp)
- [martini_v2.2.itp](http://cgmartini.nl/images/parameters/ITP/martini_v2.2.itp) (updated: 05-12-2012)
- [martini_v2.P.itp](http://cgmartini.nl/images/parameters/ITP/martini_v2.P.itp)
- [martini_v2.2P.itp](http://cgmartini.nl/images/parameters/ITP/martini_v2.2P.itp) (updated: 05-12-2012)
- [martini_v2.2refP.itp](http://cgmartini.nl/images/parameters/ITP/martini_v2.2refP.itp) (updated: 06-02-2017)
- [martini_v2.2polIon.tar.gz](http://cgmartini.nl/images/parameters/ITP/PolIon/martini_v2.2polIon.tar.gz) (updated: 06-08-2018) Contains martini_v2.2refP.itp + NaCl
- [martini_v2.3P.itp](http://cgmartini.nl/images/martini_v2.3P.itp) (updated 09-03-2020)