---
title: "Allosteric pathway connects Zn (II) loss from SOD1 to known pathogenic mechanisms"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Rocío Araya-Osorio, Moisés Dominguez, Sebastian Thallmair, Siewert J Marrink, Paulo CT Souza, and Raúl Mera-Adasme"         # Paper authors (required)
year: "2025"           # Publication year (required)
publication: "International Journal of Biological Macromolecules"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.ijbiomac.2025.148349"            # URL of DOI (required)  
materials: "https://ars.els-cdn.com/content/image/1-s2.0-S0141813025089068-mmc1.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Araya-Osorio, R., Dominguez, M., Thallmair, S., Marrink, S. J., Souza, P. C., & Mera-Adasme, R. (2025). Allosteric pathway connects Zn (II) loss from SOD1 to known pathogenic mechanisms. International Journal of Biological Macromolecules, 148349.

## Abstract

Cu,Zn superoxide dismutase (SOD1) is one of the proteins with mutations linked to hereditary forms of the amyotrophic lateral sclerosis neurodegenerative disorder. The protein is known for its enzymatic activity, but it has been shown to also have regulatory functions, which could be related to its pathogenic potential. Seemingly unrelated to its regulatory roles, the most important hypothesis on SOD1 pathogenicity is related to misfolding of the protein, specifically centered on the region corresponding to its residues 28–38. The present work explores the structural and dynamical effect of Zn(II) removal from SOD1, which is known to influence its regulatory roles, with coarse-grained simulations of 450 µs per system. In agreement with experiment, we see an increased solvent exposure of the regulatory region (residues 5–18). We also see an increased solvent exposure of the misfolding-critical 28–38 region. We unveil the mechanism and interactions connecting Zn(II) loss, and solvent exposure of both regions. The present work allows for an unified understanding of two different pathogenic mechanisms of SOD1.