---
title: "Hexokinase-I directly binds to a charged membrane-buried glutamate of mitochondrial VDAC1 and VDAC2"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Sebastian Bieker, Michael Timme, Nils Woge, Dina G Hassan, Chelsea M Brown, Siewert J Marrink, Manuel N Melo, and Joost CM Holthuis"         # Paper authors (required)
year: "2025"           # Publication year (required)
publication: "Communications Biology"    # Journal or similar (required)
preprint: "https://doi.org/10.1101/2024.07.22.604557"       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s42003-025-07551-9"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/s42003-025-07551-9#Sec29"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - pH
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Bieker, S., Timme, M., Woge, N., Hassan, D. G., Brown, C. M., Marrink, S. J., ... & Holthuis, J. C. (2025). Hexokinase-I directly binds to a charged membrane-buried glutamate of mitochondrial VDAC1 and VDAC2. Communications biology, 8(1), 212.

## Abstract

Binding of hexokinase HKI to mitochondrial voltage-dependent anion channels (VDACs) has far-reaching physiological implications. However, the structural basis of this interaction is unclear. Combining computer simulations with experiments in cells, we here show that complex assembly relies on intimate contacts between the N-terminal α-helix of HKI and a charged membrane-buried glutamate on the outer wall of VDAC1 and VDAC2. Protonation of this residue blocks complex formation in silico while acidification of the cytosol causes a reversable release of HKI from mitochondria. Membrane insertion of HKI occurs adjacent to the bilayer-facing glutamate where a pair of polar channel residues mediates a marked thinning of the cytosolic leaflet. Disrupting the membrane thinning capacity of VDAC1 dramatically impairs its ability to bind HKI in silico and in cells. Our data reveal key topological and mechanistic insights into HKI-VDAC complex assembly that may benefit the development of therapeutics to counter pathogenic imbalances in this process.