---
title: "An integrative modelling approach to the mitochondrial cristae"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Chelsea M. Brown, Marieke S. S. Westendorp, Rubi Zarmiento-Garcia, Jan A. Stevens, Bart M. H. Bruininks, Sarah L. Rouse, Siewert J. Marrink & Tsjerk A. Wassenaar "         # Paper authors (required)
year: "2025"           # Publication year (required)
publication: "Communications Biology"    # Journal or similar (required)
preprint: "https://www.biorxiv.org/content/10.1101/2024.09.23.613389v1"       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s42003-025-08381-5"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/s42003-025-08381-5#Sec24"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Methods
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Brown, C. M., Westendorp, M. S., Zarmiento-Garcia, R., Stevens, J. A., Bruininks, B. M., Rouse, S. L., Marrink, S.J. & Wassenaar, T. A. (2025). An integrative modelling approach to the mitochondrial cristae. Communications Biology, 8(1), 972.

## Abstract

Mitochondria are implicated in many cellular functions such as energy production and apoptosis but also disease pathogenesis. To effectively perform these roles, the mitochondrial inner membrane has invaginations known as cristae that dramatically increase the surface area. This works to provide more space for membrane proteins that are essential to the roles of mitochondria. While separate components of this have been studied computationally, it remains a challenge to combine elements into an overall model. Here, we present a comprehensive model of a crista junction from a human mitochondrion and the accompanying workflow to construct it. Our coarse-grained representation of a crista shows how various experimentally determined features of organelles can be combined with molecular modelling to give insights into the interactions and dynamics of complicated biological systems. This work is presented as an initial ‘living’ model for this system, intended to be built upon and improved as our understanding, methodology and resources develop.