---
title: "A Comparative Nanomechanical Study of Antibody and Nanobody Binding to SARS-CoV-2 Variants"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Luis F Cofas-Vargas, Gustavo E Olivos-Ramirez, Siewert-Jan Marrink, and Adolfo B Poma"         # Paper authors (required)
year: "2025"           # Publication year (required)
publication: "bioRxiv"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1101/2025.09.26.672567"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Pre-print
  - Proteins
  - Enhanced sampling
  - Drug design
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Cofas-Vargas, L. F., Olivos-Ramirez, G. E., Marrink, S. J., & Poma, A. B. (2025). A Comparative Nanomechanical Study of Antibody and Nanobody Binding to SARS-CoV-2 Variants. bioRxiv, 2025-09.

## Abstract

The receptor-binding domain of the SARS-CoV-2 spike protein is the principal target of neutralizing antibodies (Abs) and nanobodies (Nbs). Although their thermodynamic binding properties have been extensively characterized, their stability under mechanical force remains less understood. Here, we perform a comparative nanomechanical analysis of three Abs (PDI-231, S2X259, and R1-32) and three Nbs (R14, C1, and n3113.1) bound to the RBD from the WT strain and the Omicron BA.4 and JN.1 variants. Using coarse-grained steered molecular dynamics within the GōMartini 3 framework, we identified distinct force–response behaviors shaped by epitope topology, binding architecture, and variant-specific mutations. Ab/RBD dissociation was characterized by asymmetric rupture events, variant-dependent unfolding of RBD segments, and occasional deformation of antibody constant domains. Analysis of single-chain systems revealed that the heavy chain acts as the main load-bearing element, while the light chain sustains a consistent but weaker mechanical response. For the two-chain Ab system, the cooperative action of both chains enhances stability, enabling complexes to withstand rupture forces in the range of 500 pN. By contrast, Nb/RBD complexes dissociated primarily through rigid-body mechanisms, transmitting force more directly to the RBD interface with minimal structural disruption. Together, these results demonstrate that mechanical resilience emerges from immune complex topology and inter-chain cooperation, providing complementary insights beyond affinity into the design of therapeutics resilient to viral evolution.