---
title: "Phase separation of protein kinase A regulatory subunits is driven by similar inter- and intra-molecular interactions involving the inhibitory segment"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Malyasree Giri, Christopher S Brasnett, Kubra F Eroglu, Julie Maiboll Kaasen, Alain AM Andre, Siewert-Jan Marrink, Frans AA Mulder, and Magnus Kjaergaard"         # Paper authors (required)
year: "2025"           # Publication year (required)
publication: "bioRxiv"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1101/2025.08.07.669161"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Pre-print
  - Biomolecular condensates
  - Coacervate
  - Multi-scale
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Giri, M., Brasnett, C. S., Eroglu, K. F., Kaasen, J. M., Andre, A. A., Marrink, S. J., ... & Kjaergaard, M. (2025). Phase separation of protein kinase A regulatory subunits is driven by similar inter-and intra-molecular interactions involving the inhibitory segment. bioRxiv, 2025-08.

## Abstract

Phase separation of biological macromolecules has emerged as a widespread mechanism for cellular organization, governing the spatiotemporal regulation of biochemical processes including signaling pathways. The regulatory subunit of the cAMP-dependent protein kinase A (PKA) RIα phase separates following cAMP-induced kinase activation, thereby restricting and enhancing PKA activity in space and time. The N-terminal dimerization/docking (D/D) domain and the linker region of RIα have been identified as necessary and sufficient for phase separation, but their interactions at atomic resolution have remained elusive. We report here a structural investigation of the minimal phase-separating region of RIα by nuclear magnetic resonance spectroscopy (NMR) and molecular dynamics (MD) simulations. The intrinsically disordered regions of RIα cause broadening of NMR signals throughout the protein indicative of widespread dynamic interactions. Mutation of arginine residues in the RIα inhibitory sequence leads to a reduction in signal broadening accompanied by loss of phase separation. Independently, binding of RIα to an A-kinase anchoring protein (AKAP) leads to spectral changes that are indicative of a loss of interactions between the D/D domain and the linker region, suggestive of a competition between intramolecular interactions and partner binding. Corroborating the experimental observations, multiscale MD simulations detect pervasive interactions of the folded D/D domain of RIα with the intrinsically disordered linker, and the intermolecular interactions in the condensate mirror those found internally in RIα dimers. Our results support the view that for PKA RIα, homotypic phase separation is underpinned by intermolecular interactions that are similar to intramolecular interactions.