---
title: "Martini 3 building blocks for Lipid Nanoparticle design"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Lisbeth R. Kjølbye, Mariana Valério, Markéta Paloncýová, Luís Borges-Araújo, Roberto Pestana-Nobles, Fabian Grünewald, Bart M. H. Bruininks, Rocío Araya-Osorio, Martin Šrejber, Raul Mera-Adasme, Luca Monticelli, Siewert J. Marrink, Michal Otyepka, Sangwook Wu, and Paulo C. T. Souza"         # Paper authors (required)
year: "2025"           # Publication year (required)
publication: "Journal of Chemical Theory and Computation"    # Journal or similar (required)
preprint: "https://doi.org/10.26434/chemrxiv-2024-bf4n8-v2"       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jctc.5c01207"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/suppl/10.1021/acs.jctc.5c01207/suppl_file/ct5c01207_si_001.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Nanoparticles
  - Lipid membranes
  - Parametrization
  - Vesicles
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Kjølbye, L. R., Valério, M., Paloncýová, M., Borges-Araújo, L., Pestana-Nobles, R., Grünewald, F., ... & Souza, P. C. (2025). Martini 3 building blocks for lipid nanoparticle design. Journal of Chemical Theory and Computation, 22(2), 1069-1091.

## Abstract

Lipid nanoparticles (LNPs) represent a promising platform for advanced drug and gene delivery, yet optimizing these particles for specific cargos and cell targets poses a complex multifaceted challenge. Furthermore, there is a pressing need for a more comprehensive understanding of the underlying technology. Experimental studies are costly and often provide low-resolution information. Molecular dynamics (MD) simulations allow us to study these particles at a higher resolution, enhancing our understanding. However, studying these systems at atomic resolutions is both challenging and computationally expensive as well as time-consuming. Coarse-grained (CG) models, such as Martini 3, are positioned as promising tools for studying LNPs. To enable CG-MD studies of LNPs, accurate and validated models of their components are needed. Here, we present a substantial extension of the Martini 3 lipid library, introducing over one hundred ionizable lipid models, natural sterols, and PEGylated lipids, covering the key components of LNP formulations. This expanded library brings an essential toolset to simulate LNPs at Martini coarse-grained resolution. We furthermore introduce initial protocols for screening fusion efficacy across lipid formulations and for constructing full LNPs and show how these tools can provide new insights into the LNP structure, dynamics, and efficiency. Altogether, this work introduces a practical and scalable approach for advancing the mechanistic understanding of LNPs and guiding their future development.