---
title: "The Martini 3 lipidome: expanded and refined parameters improve lipid phase behavior"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Kasper B. Pedersen, Helgi I. Ing칩lfsson, Daniel P. Ramirez-Echemendia, Lu칤s Borges-Ara칰jo, Mikkel D. Andreasen, Charly Empereur-mot, Josef Melcr, Tugba N. Ozturk, W. F. Drew Bennett, Lisbeth R. Kj칮lbye, Christopher Brasnett, Valentina Corradi, Hanif M. Khan, Elio A. Cino, Jackson Crowley, Hyuntae Kim, Bal치zs F치bi치n, Ana C. Borges-Ara칰jo, Giovanni M. Pavan, Guillaume Launay, Fabio Lolicato, Tsjerk A. Wassenaar, Manuel N. Melo, Sebastian Thallmair, Timothy S. Carpenter, Luca Monticelli, D. Peter Tieleman, Birgit Schi칮tt, Paulo C. T. Souza, and Siewert J. Marrink"         # Paper authors (required)
year: "2025"           # Publication year (required)
publication: "ACS Central Science"    # Journal or similar (required)
preprint: "https://chemrxiv.org/engage/chemrxiv/article-details/67652de681d2151a02594f8d"       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acscentsci.5c00755"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/acscentsci.5c00755#_i23"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Parametrization
  - Lipid membranes
  - Phopholipids
  - '!游꽂Core papers'
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Pedersen, K. B., Ing칩lfsson, H. I., Ramirez-Echemendia, D. P., Borges-Ara칰jo, L., Andreasen, M. D., Empereur-Mot, C., ... & Marrink, S. J. (2025). The Martini 3 lipidome: expanded and refined parameters improve lipid phase behavior. ACS Central Science.

## Abstract

Lipid membranes are central to cellular life. Complementing experiments, computational modeling has been essential in unraveling complex lipid-biomolecule interactions, crucial in both academia and industry. The Martini model, a coarse-grained force field for efficient molecular dynamics simulations, is widely used to study membrane phenomena but has faced limitations, particularly in capturing realistic lipid phase behavior. Here, we present refined Martini 3 lipid models with a mapping scheme that distinguishes lipid tails that differ by just two carbon atoms, enhancing the structural resolution and thermodynamic accuracy of model membrane systems including ternary mixtures. The expanded Martini lipid library includes thousands of models, enabling simulations of complex and biologically relevant systems. These advancements establish Martini as a robust platform for lipid-based simulations across diverse fields.