---
title: "Peptide Electrostatic Modulation Directs Human Neural Cell Fate"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Laura Perez-Chirinos, Xavier Barceló, M Gabriella Chiariello, Irene Sanz, Amaia Iturrospe, Arantxa Arbe, J Alberto Ortega, Siewert J Marrink, Aitziber L Cortajarena, Zaida Álvarez, and Ivan R Sasselli"         # Paper authors (required)
year: "2025"           # Publication year (required)
publication: "Advanced Science"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1002/advs.202507946"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Self-assembly
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Perez‐Chirinos, L., Barceló, X., Chiariello, M. G., Sanz, I., Iturrospe, A., Arbe, A., ... & Sasselli, I. R. (2025). Peptide Electrostatic Modulation Directs Human Neural Cell Fate. Advanced Science, e07946.

## Abstract

Supramolecular self-assembled systems have emerged as versatile platforms for engineering biomimetic environments that precisely regulate cellular behavior. These materials have tunable properties such as stiffness, hydrophobicity, and molecular composition, allowing for customization of their structure and function. Despite significant advances, the specific role of electrostatic properties in modulating cellular responses within supramolecular assemblies remains poorly understood. Here, a peptide library with diverse electrostatic profiles is designed to systematically investigate their influence on the bioactivity of supramolecular assemblies for neural regeneration. Combining computational and experimental methods, the self-assembly conditions of these peptides are optimized to create stable, biologically relevant architectures. Using human neural progenitor cell (hNPC) cultures, it is demonstrated that negatively charged environments enhance cell survival and promote neuronal differentiation. Specifically, high negative charges activate critical signaling pathways, including the mitogen-activated protein kinase (MAPK) cascade and cell adhesion mechanisms, leading to neuronal lineage commitment. This study establishes a novel framework for the design of supramolecular systems, offering an unprecedented ability to analyze specific parameters in cell behavior. By achieving control beyond conventional biomaterials, this work provides valuable insights into the complex interplay of biophysical and biochemical cues in the native neural microenvironment, with implications for regenerative medicine and biomaterial design.