---
title: "Molecular Dynamics Simulation of Fatty Acid Extraction Using a Type V Deep Eutectic Solvent with Tunable Hydrophobicity"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Petteri A Vainikka, Matthijs J Tadema, and Siewert J Marrink"         # Paper authors (required)
year: "2025"           # Publication year (required)
publication: "The Journal of Physical Chemistry B"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jpcb.4c08261"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/suppl/10.1021/acs.jpcb.4c08261/suppl_file/jp4c08261_si_001.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Solvents
  - Small molecules
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Vainikka, P. A., Tadema, M. J., & Marrink, S. J. (2025). Molecular Dynamics Simulation of Fatty Acid Extraction Using a Type V Deep Eutectic Solvent with Tunable Hydrophobicity. The Journal of Physical Chemistry B, 129(34), 8754-8763.

## Abstract

Deep eutectic solvents (DESs) are often promoted as a more environmentally friendly alternative for ionic liquids and other ionic solvents. Like ionic liquids, DESs can be designed for specific tasks in various chemical environments, but their usage in extraction processes is often significantly hampered by difficulties in recovering the extraction product. To remedy this, various tactics are being employed, which often decrease or completely remove the recyclability of the solvent. An experimental study from 2021 proposed a strategy to counter this issue, demonstrating how a hexanoic acid─imidazole (IMID) DES with “tunable hydrophobicity” can be used to extract fatty acids. This protocol did not involve the introduction of additional chemical species, thus better preserving the recyclability of the solvent. In this work, we reproduce the experimentally reported fatty acid extraction and recovery process using the coarse-grained Martini 3 force field. We demonstrate that our HexA-IMID DES simulations are capable of accurately reproducing the phase separation and extraction phenomena and yielding molecular level insights into the process. Additionally, we studied the effect of IL formation on these properties. Our study opens the way to rational design of new extraction protocols with DESs and further establishes the potential role CG MD can have in the screening of new DESs and their properties with comparatively little computational cost. Finally, we demonstrate that when combined with the Martini 3 IL models, we can efficiently study how different extents of reaction toward IL formation affect the system properties, as well as extraction properties.