---
title: "Nanopore-Functionalized Hybrid Lipid-Block Copolymer Membranes Allow Efficient Single-Molecule Sampling and Stable Sensing of Human Serum"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Edo Vreeker, Fabian Grünewald, Nieck Jordy van der Heide, Andrea Bonini, Siewert J. Marrink, Katarzyna (Kasia) Tych, and Giovanni Maglia"         # Paper authors (required)
year: "2025"           # Publication year (required)
publication: "Advanced Materials"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1002/adma.202418462"            # URL of DOI (required)  
materials: "https://advanced.onlinelibrary.wiley.com/doi/full/10.1002/adma.202418462"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Polymers
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Vreeker, E., Grünewald, F., van der Heide, N. J., Bonini, A., Marrink, S. J., Tych, K., & Maglia, G. (2025). Nanopore‐Functionalized Hybrid Lipid‐Block Copolymer Membranes Allow Efficient Single‐Molecule Sampling and Stable Sensing of Human Serum. Advanced Materials, 2418462.

## Abstract

Biological nanopores are powerful tools for single-molecule detection, with promising potential as next-generation biosensors. A major bottleneck in nanopore analysis is the fragility of the supporting lipid membranes, that easily rupture after exposure to biological samples. Membranes comprising PMOXA-PDMS-PMOXA (poly(2-methyloxazoline-b-dimethylsiloxane-b-2-methyloxazoline)) or PBD-PEO (poly(1,2-butadiene)-b-poly(ethylene oxide)) polymers may form robust alternatives, but their suitability for the reconstitution of a broad range of nanopores has not yet been investigated. Here, PBD-PEO membranes are found to be highly robust toward applied voltages and human serum, while providing a poor environment for nanopore reconstitution. However, hybrid membranes containing a similar molar ratio of PBD11PEO8 polymers and diphytanoyl phosphatidylcholine (DPhPC) lipids show the best of both worlds: highly robust membranes suitable for the reconstitution of a wide variety of nanopores. Molecular dynamics simulations reveal that lipids form ≈12 nm domains interspersed by a polymer matrix. Nanopores partition into these lipid nanodomains and sequester lipids, possibly offering the same binding strength as in a native bilayer. Nanopores reconstituted in hybrid membranes yield efficient sampling of biomolecules and enable sensing of high concentrations of human serum. This work thus shows that hybrid membranes functionalized with nanopores allow single-molecule sensing, while forming robust interfaces, resolving an important bottleneck for novel nanopore-based biosensors.