---
title: "Insight into the Self-Assembly Behaviors of Per-and Polyfluoroalkyl Substances Using a Computational Microscope"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Bei Yan, Riccardo Alessandri, Siewert J Marrink, Linda S Lee, and Jinxia Liu"         # Paper authors (required)
year: "2025"           # Publication year (required)
publication: "Environmental Science & Technology Letters"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.estlett.4c01081"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/acs.estlett.4c01081?goto=supporting-info#_i9"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Parametrization
  - Self-assembly
  - Vesicles
  - Small molecules
  - Nanoparticles
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Yan, B., Alessandri, R., Marrink, S. J., Lee, L. S., & Liu, J. (2025). Insight into the Self-Assembly Behaviors of Per-and Polyfluoroalkyl Substances Using a “Computational Microscope”. Environmental Science & Technology Letters, 12(5), 626-631.

## Abstract

Aqueous film-forming foams (AFFFs) have been extensively used for firefighting, contributing to environmental contamination with per- and polyfluoroalkyl substances (PFAS). Most PFAS in AFFFs are fluorosurfactants, known to self-assemble into large supramolecular assemblies in the field of physical chemistry; however, the application of this phenomenon to understanding environmental fate has not been studied. We hypothesize that self-assembled PFAS likely enhance the long-term retention of PFAS in subsurface environments, acting as a continuous source of dissolved PFAS. Thus, characterizing these self-assemblies and understanding their aggregation dynamics are crucial for assessing the fate and transport of PFAS. Despite the utility of molecular dynamics (MD) simulation in studying surfactant behaviors, fluorosurfactants have been underexplored due to the lack of force field parameters. In this study, we developed coarse-grained (CG) force field parameters for fluorosurfactants based on the Martini 3 model and performed CG-MD simulations. These “computational microscope” simulations reveal the self-assembly behavior of selected PFAS, aligning with experimental cryo-transmission electron microscopy observations and providing mechanistic insights. Our work sheds light on the evolution of solvated PFAS self-assemblies over time and space. The CG-MD simulation can particularly address the knowledge gaps for new PFAS that are difficult to explore experimentally due to the lack of chemical standards.