---
title: "RNA phase separation with Martini 3"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Qin Zhang, Mariana Valério, Linus Grünewald, Luís Borges-Araújo, Fabian Grünewald, Shaomeng Wang, Siewert J. Marrink, Yubin Gong, Paulo C. T. de Souza"         # Paper authors (required)
year: "2025"           # Publication year (required)
publication: "chemrxiv"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.26434/chemrxiv-2025-ggcq2"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Pre-print
  - RNA
  - Biomolecular condensates
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Zhang, Q., Valério, M., Grünewald, L., Borges-Araújo, L., Grünewald, F., Wang, S., ... & Telles de Souza, P. C. (2025). RNA phase separation with Martini 3.

## Abstract

RNA–RNA interactions drive the formation of biomolecular condensates via liquid–liquid phase separation (LLPS), but the molecular mechanisms governing this phenomenon remain poorly understood. Here, we employ Martini 3 coarse-grained simulations to investigate phase transitions of G4C2 RNA repeats—sequences implicated in neurodegenerative disorders such as ALS and FTD—across varying salt concentrations. The model captures salt-dependent transitions from condensed to soluble states and suggests that dominant interaction types—Watson–Crick base pairing and G–G interactions—shift with ionic strength. Notably, longer RNA sequences maintain condensed states at salt concentrations that dissolve shorter ones, in line with experimental observations. While the Martini 3 RNA model remains a prototype, our findings demonstrate its capability to reproduce key biophysical features of RNA LLPS, including sequence-length dependence and interaction specificity. This work highlights Martini models as a promising computational framework for studying RNA-rich condensates and provides mechanistic insight into RNA-driven phase behavior, paving the way for future investigations into sequence-dependent effects.