---
title: "Curvature-Induced Sorting of Lipids in Plasma Membrane Tethers"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Svetlana Baoukina, Helgi I. Ingólfsson, Siewert J. Marrink and D. Peter Tieleman"         # Paper authors (required)
year: "2018"           # Publication year (required)
publication: "Advanced Theory and Simulations"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1002/adts.201800034"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Baoukina, S., Ingólfsson, H. I., Marrink, S. J., & Tieleman, D. P. (2018). Curvature‐induced sorting of lipids in plasma membrane tethers. Advanced Theory and Simulations, 1(8), 1800034.

## Abstract

Membrane curvature controls the spatial organization and activity of cells. Lipid sorting in cell membranes can be explained by matching lipid molecular shape to regions of different curvatures. A molecular view of curvature-induced lipid sorting is obtained using coarse-grained molecular dynamics. A model membrane consisting of an asymmetric bilayer of multiple lipid species is simulated. Curvature is induced by pulling a tether, that is, a bilayer nanotube, from a flat membrane. Pulling is performed both from the inner and outer leaflets, corresponding to directions in and out of the cell. Redistribution of different lipid types between the tether and the bilayer is observed, leading to spatial variations in the composition of both leaflets, and, in turn, softening of the tether. Depending on the direction of pulling, the lipid distributions and the tether properties differ. Formation of a tether from the planar membrane thus induces lipid sorting without phase separation.