---
title: "Lipid–Protein Interactions Are Unique Fingerprints for Membrane Proteins"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Valentina Corradi, Eduardo Mendez-Villuendas, Helgi I. Ingólfsson, Ruo-Xu Gu, Iwona Siuda, Manuel N. Melo, Anastassiia Moussatova, Lucien J. DeGagné, Besian I. Sejdiu, Gurpreet Singh, Tsjerk A. Wassenaar, Karelia Delgado Magnero, Siewert J. Marrink, and D. Peter Tieleman"         # Paper authors (required)
year: "2018"           # Publication year (required)
publication: "ACS Central Science"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acscentsci.8b00143"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/abs/10.1021/acscentsci.8b00143"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Corradi, V., Mendez-Villuendas, E., Ingólfsson, H. I., Gu, R. X., Siuda, I., Melo, M. N., ... & Tieleman, D. P. (2018). Lipid–protein interactions are unique fingerprints for membrane proteins. ACS central science, 4(6), 709-717.

## Abstract

Cell membranes contain hundreds of different proteins and lipids in an asymmetric arrangement. Our current understanding of the detailed organization of cell membranes remains rather elusive, because of the challenge to study fluctuating nanoscale assemblies of lipids and proteins with the required spatiotemporal resolution. Here, we use molecular dynamics simulations to characterize the lipid environment of 10 different membrane proteins. To provide a realistic lipid environment, the proteins are embedded in a model plasma membrane, where more than 60 lipid species are represented, asymmetrically distributed between the leaflets. The simulations detail how each protein modulates its local lipid environment in a unique way, through enrichment or depletion of specific lipid components, resulting in thickness and curvature gradients. Our results provide a molecular glimpse of the complexity of lipid–protein interactions, with potentially far-reaching implications for our understanding of the overall organization of real cell membranes.