---
title: "Molecular simulations of self-assembling bio-inspired supramolecular systems and their connection to experiments"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Pim W. J. M. Frederix, Ilias Patmanidis and Siewert J. Marrink"         # Paper authors (required)
year: "2018"           # Publication year (required)
publication: "Chemical Society Reviews"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/C8CS00040A"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Self-assembly
  - Enhanced sampling
  - Multi-scale
  - Materials science
  - Nanoparticles
  - Polymers
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Frederix, P. W., Patmanidis, I., & Marrink, S. J. (2018). Molecular simulations of self-assembling bio-inspired supramolecular systems and their connection to experiments. Chemical Society Reviews, 47(10), 3470-3489.

## Abstract

In bionanotechnology, the field of creating functional materials consisting of bio-inspired molecules, the function and shape of a nanostructure only appear through the assembly of many small molecules together. The large number of building blocks required to define a nanostructure combined with the many degrees of freedom in packing small molecules has long precluded molecular simulations, but recent advances in computational hardware as well as software have made classical simulations available to this strongly expanding field. Here, we review the state of the art in simulations of self-assembling bio-inspired supramolecular systems. We will first discuss progress in force fields, simulation protocols and enhanced sampling techniques using recent examples. Secondly, we will focus on efforts to enable the comparison of experimentally accessible observables and computational results. Experimental quantities that can be measured by microscopy, spectroscopy and scattering can be linked to simulation output either directly or indirectly, via quantum mechanical or semi-empirical techniques. Overall, we aim to provide an overview of the various computational approaches to understand not only the molecular architecture of nanostructures, but also the mechanism of their formation.