---
title: "Transferable MARTINI Model of Poly (ethylene Oxide)"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Fabian Grunewald, Giulia Rossi, Alex H de Vries, Siewert J Marrink, Luca Monticelli"         # Paper authors (required)
year: "2018"           # Publication year (required)
publication: "The Journal of Physical Chemistry B"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jpcb.8b04760"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/abs/10.1021/acs.jpcb.8b04760"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Polymers
  - Parametrization
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Grunewald, F., Rossi, G., De Vries, A. H., Marrink, S. J., & Monticelli, L. (2018). Transferable MARTINI model of poly (ethylene oxide). The journal of physical chemistry B, 122(29), 7436-7449.

## Abstract

Motivated by the deficiencies of the previous MARTINI models of poly(ethylene oxide) (PEO), we present a new model featuring a high degree of transferability. The model is parametrized on (a) a set of 8 free energies of transfer of dimethoxyethane (PEO dimer) from water to solvents of varying polarity; (b) the radius of gyration in water at high dilution; and (c) matching angle and dihedral distributions from atomistic simulations. We demonstrate that our model behaves well in five different areas of application: (1) it produces accurate densities and phase behavior or small PEO oligomers and water mixtures; (2) it yields chain dimensions in good agreement with the experiment in three different solvents (water, diglyme, and benzene) over a broad range of molecular weights (∼1.2 kg/mol to 21 kg/mol); (3) it reproduces qualitatively the structural features of lipid bilayers containing PEGylated lipids in the brush and mushroom regime; (4) it is able to reproduce the phase behavior of several PEO-based nonionic surfactants in water; and (5) it can be combined with the existing MARTINI PS to model PS–PEO block copolymers. Overall, the new PEO model outperforms previous models and features a high degree of transferability.