---
title: "Enhancing Molecular n-Type Doping of Donor–Acceptor Copolymers by Tailoring Side Chains"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Jian Liu, Li Qiu, Riccardo Alessandri, Xinkai Qiu, Giuseppe Portale, JingJin Dong, Wytse Talsma, Gang Ye, Aprizal Akbar Sengrian, Paulo C. T. Souza, Maria Antonietta Loi, Ryan C. Chiechi, Siewert J. Marrink, Jan C. Hummelen, and L. Jan Anton Koster"         # Paper authors (required)
year: "2018"           # Publication year (required)
publication: "Advanced Materials"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1002/adma.201704630"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Materials science
  - Polymers
  - Small molecules
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Liu, J., Qiu, L., Alessandri, R., Qiu, X., Portale, G., Dong, J., ... & Koster, L. J. A. (2018). Enhancing molecular n‐type doping of donor–acceptor copolymers by tailoring side chains. Advanced Materials, 30(7), 1704630.

## Abstract

In this contribution, for the first time, the molecular n-doping of a donor–acceptor (D–A) copolymer achieving 200-fold enhancement of electrical conductivity by rationally tailoring the side chains without changing its D–A backbone is successfully improved. Instead of the traditional alkyl side chains for poly{[N,N′-bis(2-octyldodecyl)-naphthalene-1,4,5,8-bis(dicarboximide)-2,6-diyl](NDI)-alt-5,5′-(2,2′-bithiophene)} (N2200), polar triethylene glycol type side chains is utilized and a high electrical conductivity of 0.17 S cm−1 after doping with (4-(1,3-dimethyl-2,3-dihydro-1H-benzoimidazol-2-yl)phenyl)dimethylamine is achieved, which is the highest reported value for n-type D–A copolymers. Coarse-grained molecular dynamics simulations indicate that the polar side chains can significantly reduce the clustering of dopant molecules and favor the dispersion of the dopant in the host matrix as compared to the traditional alkyl side chains. Accordingly, intimate contact between the host and dopant molecules in the NDI-based copolymer with polar side chains facilitates molecular doping with increased doping efficiency and electrical conductivity. For the first time, a heterogeneous thermoelectric transport model for such a material is proposed, that is the percolation of charge carriers from conducting ordered regions through poorly conductive disordered regions, which provides pointers for further increase in the themoelectric properties of n-type D–A copolymers.