---
title: "Role of Charge and Hydrophobicity in Liprotide Formation: A Molecular Dynamics Study with Experimental Constraints"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Jannik Nedergaard Pedersen, Pim Wilhelmus Johannes Maria Frederix, Jan Skov Pedersen, Siewert Jan Marrink, and Daniel E. Otzen"         # Paper authors (required)
year: "2018"           # Publication year (required)
publication: "ChemBioChem"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1002/cbic.201700496"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Multi-scale
  - Biomolecular condensates
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Nedergaard Pedersen, J., Frederix, P. W. J. M., Skov Pedersen, J., Marrink, S. J., & Otzen, D. E. (2018). Role of charge and hydrophobicity in liprotide formation: A molecular dynamics study with experimental constraints. ChemBioChem, 19(3), 263-271.

## Abstract

Bovine α-lactalbumin (aLA) and oleate (OA) form a complex that has been intensively studied for its tumoricidal activity. Small-angle X-ray scattering (SAXS) has revealed that this complex consists of a lipid core surrounded by partially unfolded protein. We call this type of complex a liprotide. Little is known of the molecular interactions between OA and aLA, and no technique has so far provided any high-resolution structure of a liprotide. Here we have used coarse-grained (CG) molecular dynamics (MD) simulations, isothermal titration calorimetry (ITC) and SAXS to investigate the interactions between aLA and OA during the process of liprotide formation. With ITC we found that the strongest enthalpic interactions occurred at a molar ratio of 12.0±1.4:1 OA/aLA. Liprotides formed between OA and aLA at several OA/aLA ratios in silico were stable both in CG and in all-atom simulations. From the simulated structures we calculated SAXS spectra that show good agreement with experimentally measured patterns of matching liprotides. The simulations showed that aLA assumes a molten globular (MG) state, exposing several hydrophobic patches involved in interactions with OA. Initial binding of aLA to OA occurs in an area of aLA in which a high amount of positive charge is located, and only later do hydrophobic interactions become important. The results reveal how unfolding of aLA to expose hydrophobic residues is important for complex formation between aLA and OA. Our findings suggest a general mechanism for liprotide formation and might explain the ability of a large number of proteins to form liprotides with OA.