---
title: "The N-terminal amphipathic helix of Pex11p self-interacts to induce membrane remodelling during peroxisome fission"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Juanjuan Su, Ann S. Thomas, Tanja Grabietz, Christiane Landgraf, Rudolf Volkmer, Siewert J. Marrink, Chris Williams, and Manuel N. Melo"         # Paper authors (required)
year: "2018"           # Publication year (required)
publication: "Biochimica et Biophysica Acta (BBA)-Biomembranes"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bbamem.2018.02.029"            # URL of DOI (required)  
materials: "https://www.sciencedirect.com/science/article/pii/S0005273618300701#s0120"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Su, J., Thomas, A. S., Grabietz, T., Landgraf, C., Volkmer, R., Marrink, S. J., ... & Melo, M. N. (2018). The N-terminal amphipathic helix of Pex11p self-interacts to induce membrane remodelling during peroxisome fission. Biochimica et Biophysica Acta (BBA)-Biomembranes, 1860(6), 1292-1300.

## Abstract

Pex11p plays a crucial role in peroxisome fission. Previously, it was shown that a conserved N-terminal amphipathic helix in Pex11p, termed Pex11-Amph, was necessary for peroxisomal fission in vivo while in vitro studies revealed that this region alone was sufficient to bring about tubulation of liposomes with a lipid consistency resembling the peroxisomal membrane. However, molecular details of how Pex11-Amph remodels the peroxisomal membrane remain unknown. Here we have combined in silico, in vitro and in vivo approaches to gain insights into the molecular mechanisms underlying Pex11-Amph activity. Using molecular dynamics simulations, we observe that Pex11-Amph peptides form linear aggregates on a model membrane. Furthermore, we identify mutations that disrupted this aggregation in silico, which also abolished the peptide's ability to remodel liposomes in vitro, establishing that Pex11p oligomerisation plays a direct role in membrane remodelling. In vivo studies revealed that these mutations resulted in a strong reduction in Pex11 protein levels, indicating that these residues are important for Pex11p function. Taken together, our data demonstrate the power of combining in silico techniques with experimental approaches to investigate the molecular mechanisms underlying Pex11p-dependent membrane remodelling.