---
title: "Molecular Dynamics of the Association of L-Selectin and FERM Regulated by PIP2"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Fude Sun, Carsten F.E. Schroer, Lida Xu, Huiwei Yin, Siewert J. Marrink, and Shi-Zhong Luo"         # Paper authors (required)
year: "2018"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2018.02.034"            # URL of DOI (required)  
materials: "https://www.sciencedirect.com/science/article/pii/S0006349518302947#app2"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Sun, F., Schroer, C. F., Xu, L., Yin, H., Marrink, S. J., & Luo, S. Z. (2018). Molecular Dynamics of the Association of L-Selectin and FERM Regulated by PIP2. Biophysical journal, 114(8), 1858-1868.

## Abstract

Phosphatidylinositol 4,5-bisphosphate (PIP2) acts as a signaling lipid, mediating membrane trafficking and recruitment of proteins to membranes. A key example is the PIP2-dependent regulation of the adhesion of L-selectin to the cytoskeleton adaptors of the N-terminal subdomain of ezrin-radixin-moesin (FERM). The molecular details of the mediating behavior of multivalent anionic PIP2 lipids in this process, however, remain unclear. Here, we use coarse-grained molecular dynamics simulation to explore the mechanistic details of PIP2 in the transformation, translocation, and association of the FERM/L-selectin complex. We compare membranes of different compositions and find that anionic phospholipids are necessary for both FERM and the cytoplasmic domain of L-selectin to absorb on the membrane surface. The subsequent formation of the FERM/L-selectin complex is strongly favored by the presence of PIP2, which clusters around both proteins and triggers a conformational transition in the cytoplasmic domain of L-selectin. We are able to quantify the effect of PIP2 on the association free energy of the complex by means of a potential of mean force. We conclude that PIP2 behaves as an adhesive agent to enhance the stability of the FERM/L-selectin complex and identify key residues involved. The molecular information revealed in this study highlights the specific role of membrane lipids such as PIP2 in protein translocation and potential signaling.