---
title: "Cholesterol Flip-Flop Impacts Domain Registration in Plasma Membrane Models"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Sebastian Thallmair, Helgi I. Ingólfsson, and Siewert J. Marrink"         # Paper authors (required)
year: "2018"           # Publication year (required)
publication: "The journal of physical chemistry letters"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jpclett.8b01877"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/abs/10.1021/acs.jpclett.8b01877"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Sterols
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Thallmair, S., Ingólfsson, H. I., & Marrink, S. J. (2018). Cholesterol flip-flop impacts domain registration in plasma membrane models. The journal of physical chemistry letters, 9(18), 5527-5533.

## Abstract

The plasma membrane is a highly complex multicomponent system that is central to the functioning of cells. Cholesterol, a key lipid component of the plasma membrane, promotes the formation of nanodomains. These nanodomains are often correlated across the two membrane leaflets, but the underlying physical mechanism remains unclear. Using coarse-grained molecular dynamics simulations, we investigate the influence of cholesterol flip-flop on membrane properties, in particular, the interleaflet coupling of cholesterol-enriched domains. We show that the cholesterol density correlation between the leaflets of an average mammalian plasma membrane is significantly reduced by suppressing interleaflet cholesterol population. Our results suggest an amplifying role of cholesterol in signal transduction across the leaflets.