---
title: "Molecular Mechanism of Lipid Nanodisk Formation by Styrene-Maleic Acid Copolymers"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Minmin Xue, Lisheng Cheng, Ignacio Faustino, Wanlin Guo, and Siewert J. Marrink"         # Paper authors (required)
year: "2018"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2018.06.018"            # URL of DOI (required)  
materials: "https://www.sciencedirect.com/science/article/pii/S0006349518307215#app2"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Self-assembly
  - Polymers
  - Micelles
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Xue, M., Cheng, L., Faustino, I., Guo, W., & Marrink, S. J. (2018). Molecular mechanism of lipid nanodisk formation by styrene-maleic acid copolymers. Biophysical journal, 115(3), 494-502.

## Abstract

Experimental characterization of membrane proteins often requires solubilization. A recent approach is to use styrene-maleic acid (SMA) copolymers to isolate membrane proteins in nanometer-sized membrane disks, or so-called SMA lipid particles (SMALPs). The approach has the advantage of allowing direct extraction of proteins, keeping their native lipid environment. Despite the growing popularity of using SMALPs, the molecular mechanism behind the process remains poorly understood. Here, we unravel the molecular details of the nanodisk formation by using coarse-grained molecular dynamics simulations. We show how SMA copolymers bind to the lipid bilayer interface, driven by the hydrophobic effect. Due to the concerted action of multiple adsorbed copolymers, large membrane defects appear, including small, water-filled pores. The copolymers can stabilize the rim of these pores, leading to pore growth and membrane disruption. Although complete solubilization is not seen on the timescale of our simulations, self-assembly experiments show that small nanodisks are the thermodynamically preferred end state. Our findings shed light on the mechanism of SMALP formation and on their molecular structure. This can be an important step toward the design of optimized extraction tools for membrane protein research.