---
title: Multiscaling
format: html
---

### AdResS simulation of MARTINI solvents
<hr>

These are the systems simulated in [Zavadlav, J., Melo, M. N., Vicente Cunha, A., De Vries, A. H., Marrink, S. J., & Praprotnik, M. (2014). Adaptive resolution simulation of MARTINI solvents. Journal of Chemical Theory and Computation](https://pubs.acs.org/doi/10.1021/ct5001523), using GROMACS.

- [Martini water + bundled SPC](https://martini-library.s3.us-east-2.amazonaws.com/example_applications/multiscaling/bundled.tar): this simulation requires modifications to GROMACS 4.6.5, included in this patch. See the supporting information in the paper for details on the modifications.
- [Butane](https://martini-library.s3.us-east-2.amazonaws.com/example_applications/multiscaling/butane.tar): can be simulated using the standard version of GROMACS (4.6.4 was used in the paper). If the modified GROMACS version is used instead, adress_ex_forcecap should be set to the capping distance (try something between 0.1 and 0.2) instead of the capping magnitude.

The archive for each system contains the respective pre-converged thermodynamic force table.

 