---
title: Other systems
format: html
---
<hr>

### Phytochemicals
<hr>

Phytochemicals Initial structures for the five phytochemicals: capsaicin (cap), curucmin (cur), epigallocatechin gallate (EGCG), genistein (gen), and resveratrol (res); and those five phytochemicals in a POPC bilayer (512 POPC lipids, 6000 CG waters, and 48 phytochemicals each) simulated for 2 μs.

- [cap-CG.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/cap-CG.gro)
- [cur-CG.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/cur-CG.gro)
- [EGCG-CG.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/EGCG-CG.gro)
- [gen-CG.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/gen-CG.gro)
- [res-CG.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/res-CG.gro)
- [POPC-cap-2us.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/POPC-cap-2us.gro)
- [POPC-cur-2us.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/POPC-cur-2us.gro)
- [POPC-EGCG-2us.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/POPC-EGCG-2us.gro)
- [POPC-gen-2us.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/POPC-gen-2us.gro)
- [POPC-res-2us.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/POPC-res-2us.gro)

And the phytochemicals parameter file:

- [martini_v2.0_phytochemicals.itp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/martini_v2.0_phytochemicals.itp)

### Docosane physisorption on graphite from heptane
<hr>

System for simulation of preferred physisorption of long-chain alkane (6 beads, representing docosane) from short-chain alkane (2-bead, representing heptane).

- [sams.top](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/sams.top)
- [sams.mdp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/sams.mdp)
REQUIRES special parameter files!

- [martini_v2.g.itp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/martini_v2.g.itp)
- [martini_v2.0_solvents.itp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/martini_v2.0_solvents.itp)
- [martini_v2.g_graphite.itp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/martini_v2.g_graphite.itp)
- [adsorbant_docosane.itp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/adsorbant_docosane.itp)

Starting conformation contains 18,000 graphite surface particles (5 layers) GRAP, and in total 600 docosane molecules (DOCO) and 16,200 heptane molecules (OCT).

- [start.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/start.gro)

### DNA strand
<hr>

Double stranded DNA, 12 base pair

(provided by Syma Khalid)

- [dna.mdp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dna.mdp)
- [dna.top](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dna.top)
- [dna.itp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dna.itp)
- [dna.pdb](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dna.pdb)
- [dna.vmd](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dna.vmd) (to view the elastic network)

### Voltage sensitive dyes
<hr>

Voltage sensitive dye Di-4-ASPBS bound to a POPC membrane
System size: 1 dye, lipids 128, water 1489

- [dye1.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dye1.gro)
- [dye1.mdp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dye1.mdp)
- [dye1.top](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dye1.top)
- [dye1.ndx](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dye1.ndx)

A charged voltage sensitive dye Di-12P-ASPBS bound to a POPC membrane
System size: 1 dye, 2 sodium counterions, lipids 128, water 1481

- [dye4.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dye4.gro)
- [dye4.mdp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dye4.mdp)
- [dye4.top](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dye4.top)
- [dye4.ndx](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/dye4.ndx)

### Fullerenes
<hr>

Equilibrated at T=310K, constant pressure P=1 bar.
System size: 64 fullerenes,  1152 octane molecules

(provided by Luca Monticelli)

- [fullerene.itp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/fullerene.itp)
- [fullerene.top](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/fullerene.top)
- [fullerenes_in_octane.gro](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/fullerenes_in_octane.gro)
- [fullerene.mdp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/fullerene.mdp)
- [martini_v2.1_CNP.itp](https://cgmartini-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/other_systems/martini_v2.1_CNP.itp)

<hr>