---
title: Solvent systems
format: html
---

<hr>

### Martini solvent boxes
<hr>
Thanks to the contribution of [Sebastian Franco Ulloa](https://www.sebastianfu.com/), we can now provide our users with a small library of pre-equilibrated solvent boxes, ranging from acetamide to trans-octadecane.

Files can be downloaded [here](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/Martini_solvents.zip).

### Salt solution
<hr>
Equilibrated at T=300K, P=1 bar.
System size: sodium 8, chloride 8, water 388.

- [nacl+wat.gro](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/nacl%2Bwat.gro)
- [nacl+wat.mdp](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/nacl%2Bwat.mdp)
- [nacl+wat.top](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/nacl%2Bwat.top)

### Hexadecane slab in water
<hr>

Equilibrated at T=300K, constant area and perpendicular Pz=1 bar.
System size: hexadecane 100, water 400.

- [hexadecane_slab.gro](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/hexadecane_slab.gro)
- [hexadecane_slab.mdp](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/hexadecane_slab.mdp)
- [hexadecane_slab.top](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/hexadecane_slab.top)

### Pure water solvent
<hr>

Equilibrated at T=300K, P=1 bar.
System size: water 2000 (corresponding to 8000 real water molecules).

- [water.gro](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/water.gro)
- [water.mdp](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/water.mdp)
- [water.top](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/water.top)

A box with 1824 polarizable waters, equilibrated at T=300K, P = 1 bar.

- [polarize-water.gro](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/polarize-water.gro)
- [polarize-water.mdp](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/polarize-water.mdp)
- [polarize-water.top](https://martiniff-library.s3.ca-central-1.amazonaws.com/1_Downloads/example_applications/solvent_systems/polarize-water.top)

<hr>
