blank_issues_enabled: true
contact_links:
  - name: Ask a question or propose something
    url: https://github.com/orgs/Martini-Force-Field-Initiative/discussions
    about: >-
      For questions about using the Martini Force Field.