---
title: "Pressure−Area Isotherm of a Lipid Monolayer from Molecular Dynamics Simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Svetlana Baoukina, Luca Monticelli, Siewert J. Marrink, and D. Peter Tieleman"         # Paper authors (required)
year: "2007"           # Publication year (required)
publication: "Langmuir"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/la702286h"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Baoukina, S., Monticelli, L., Marrink, S. J., & Tieleman, D. P. (2007). Pressure− area isotherm of a lipid monolayer from molecular dynamics simulations. Langmuir, 23(25), 12617-12623.

## Abstract

We calculated the pressure−area isotherm of a dipalmitoyl-phosphatidylcholine (DPPC) lipid monolayer from molecular dynamics simulations using a coarse-grained molecular model. We characterized the monolayer structure, geometry, and phases directly from the simulations and compared the calculated isotherm to experiments. The calculated isotherm shows liquid-expanded and liquid-condensed phases and their coexistence plateau. At high pressure, the monolayer surface is rippled; upon further compression, the monolayer undergoes a collapse. We studied the effect of temperature and system size on the isotherm slope and phase coexistence region. Thermodynamic and dynamic properties of the monolayer phases were also investigated.