---
title: "G Protein-Coupled Receptors Self-Assemble in Dynamics Simulations of Model Bilayers"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Xavier Periole, Thomas Huber, Siewert-Jan Marrink, and Thomas P. Sakmar"         # Paper authors (required)
year: "2007"           # Publication year (required)
publication: "Journal of the American Chemical Society"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/ja0706246"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
  - Self-assembly
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Periole, X., Huber, T., Marrink, S. J., & Sakmar, T. P. (2007). G protein-coupled receptors self-assemble in dynamics simulations of model bilayers. Journal of the American Chemical Society, 129(33), 10126-10132.

## Abstract

Many integral membrane proteins assemble to form oligomeric structures in biological membranes. In particular, seven-transmembrane helical G protein-coupled receptors (GPCRs) appear to self-assemble constitutively in membranes, but the mechanism and physiological role of this assembly are unknown. We developed and employed coarse-grain molecular dynamics (CGMD) models to investigate the molecular basis of how the physicochemical properties of the phospholipid bilayer membrane affect self-assembly of visual rhodopsin, a prototypical GPCR. The CGMD method is a mesoscopic simulation technique in which groups of atoms are mapped to particles on the basis of a four-to-one rule. This systematic reduction of the degrees of freedom allows for computationally efficient calculation of the structure and dynamics of molecular assemblies for larger time and length scales than accessible to atomistic models, providing here an unprecedented view of spontaneous protein assembly in biomembranes. Systems with up to 16 rhodopsin molecules at a protein-to-lipid ratio of 1:100 were simulated for time scales of up to 8 μs. The results obtained for four different phospholipid environments showed that localized adaptation of the membrane bilayer to the presence of receptors is reproducibly most pronounced near transmembrane helices 2, 4, and 7. This local membrane deformation appears to be a key factor defining the rate, extent, and orientational preference of protein−protein association. The implications of our findings are discussed within a framework of a generalized mechanism of membrane protein self-assembly.