---
title: "Molecular Dynamics Simulation of the Formation, Structure, and Dynamics of Small Phospholipid Vesicles"
type: "article"
sidebar: false
toc: false
author: "Siewert J. Marrink and Alan E. Mark"
year: "2003"
publication: "Journal of the American Chemical Society"
preprint: ""
doi: "https://doi.org/10.1021/ja0352092"
materials: ""
categories:
  - Vesicles
  - Lipid membranes
  - Phopholipids
  - Journal article
---

## Citation (APA 7)

> Marrink, S. J., & Mark, A. E. (2003). Molecular Dynamics Simulation of the Formation, Structure, and Dynamics of Small Phospholipid Vesicles. Journal of the American Chemical Society, 125(49), 15233–15242. https://doi.org/10.1021/ja0352092

## Abstract

Here, we use coarse grained molecular dynamics (MD) simulations to study the spontaneous aggregation of dipalmitoylphosphatidylcholine (DPPC) lipids into small unilamellar vesicles. We show that the aggregation process occurs on a nanosecond time scale, with bicelles and cuplike vesicles formed at intermediate stages. Formation of hemifused vesicles is also observed at higher lipid concentration. With either 25% dipalmitoylphosphatidylethanolamine (DPPE) or lysoPC mixed into the system, the final stages of the aggregation process occur significantly faster. The structure of the spontaneously formed vesicles is analyzed in detail. Microsecond simulations of isolated vesicles reveal significant differences in the packing of the lipids between the inner and outer monolayers, and between PC, PE, and lysoPC. Due to the small size of the vesicles they remain almost perfectly spherical, undergoing very limited shape fluctuations or bilayer undulations. The lipid lateral diffusion rate is found to be faster in the outer than in the inner monolayer. The water permeability coefficient of the pure DPPC vesicles is of the order of 10-3 cm s-1, in agreement with experimental measurements.