---
title: "Bulk Heterojunction Morphologies with Atomistic Resolution from Coarse-Grain Solvent Evaporation Simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Riccardo Alessandri, Jaakko J. Uusitalo, Alex H. de Vries, Remco W. A. Havenith, and Siewert J. Marrink"         # Paper authors (required)
year: "2017"           # Publication year (required)
publication: "Journal of the American Chemical Society"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jacs.6b11717"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/abs/10.1021/jacs.6b11717"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Polymers
  - Multi-scale
  - Materials science
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Alessandri, R., Uusitalo, J. J., De Vries, A. H., Havenith, R. W., & Marrink, S. J. (2017). Bulk heterojunction morphologies with atomistic resolution from coarse-grain solvent evaporation simulations. Journal of the American Chemical Society, 139(10), 3697-3705.

## Abstract

Control over the morphology of the active layer of bulk heterojunction (BHJ) organic solar cells is paramount to achieve high-efficiency devices. However, no method currently available can predict morphologies for a novel donor–acceptor blend. An approach which allows reaching relevant length scales, retaining chemical specificity, and mimicking experimental fabrication conditions, and which is suited for high-throughput schemes has been proven challenging to find. Here, we propose a method to generate atom-resolved morphologies of BHJs which conforms to these requirements. Coarse-grain (CG) molecular dynamics simulations are employed to simulate the large-scale morphological organization during solution-processing. The use of CG models which retain chemical specificity translates into a direct path to the rational design of donor and acceptor compounds which differ only slightly in chemical nature. Finally, the direct retrieval of fully atomistic detail is possible through backmapping, opening the way for improved quantum mechanical calculations addressing the charge separation mechanism. The method is illustrated for the poly(3-hexyl-thiophene) (P3HT)–phenyl-C61-butyric acid methyl ester (PCBM) mixture, and found to predict morphologies in agreement with experimental data. The effect of drying rate, P3HT molecular weight, and thermal annealing are investigated extensively, resulting in trends mimicking experimental findings. The proposed methodology can help reduce the parameter space which has to be explored before obtaining optimal morphologies not only for BHJ solar cells but also for any other solution-processed soft matter device.