---
title: "Ganglioside-Lipid and Ganglioside-Protein Interactions Revealed by Coarse-Grained and Atomistic Molecular Dynamics Simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Ruo-Xu Gu, Helgi I. Ingólfsson, Alex H. de Vries, Siewert J. Marrink, and D. Peter Tieleman"         # Paper authors (required)
year: "2017"           # Publication year (required)
publication: "The Journal of Physical Chemistry B"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jpcb.6b07142"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/abs/10.1021/acs.jpcb.6b07142"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Multi-scale
  - Parametrization
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Gu, R. X., Ingólfsson, H. I., De Vries, A. H., Marrink, S. J., & Tieleman, D. P. (2017). Ganglioside-lipid and ganglioside-protein interactions revealed by coarse-grained and atomistic molecular dynamics simulations. The Journal of Physical Chemistry B, 121(15), 3262-3275.

## Abstract

Gangliosides are glycolipids in which an oligosaccharide headgroup containing one or more sialic acids is connected to a ceramide. Gangliosides reside in the outer leaflet of the plasma membrane and play a crucial role in various physiological processes such as cell signal transduction and neuronal differentiation by modulating structures and functions of membrane proteins. Because the detailed behavior of gangliosides and protein-ganglioside interactions are poorly known, we investigated the interactions between the gangliosides GM1 and GM3 and the proteins aquaporin (AQP1) and WALP23 using equilibrium molecular dynamics simulations and potential of mean force calculations at both coarse-grained (CG) and atomistic levels. In atomistic simulations, on the basis of the GROMOS force field, ganglioside aggregation appears to be a result of the balance between hydrogen bond interactions and steric hindrance of the headgroups. GM3 clusters are slightly larger and more ordered than GM1 clusters due to the smaller headgroup of GM3. The different structures of GM1 and GM3 clusters from atomistic simulations are not observed at the CG level based on the Martini model, implying a difference in driving forces for ganglioside interactions in atomistic and CG simulations. For protein-ganglioside interactions, in the atomistic simulations, GM1 lipids bind to specific sites on the AQP1 surface, whereas they are depleted from WALP23. In the CG simulations, the ganglioside binding sites on the AQP1 surface are similar, but ganglioside aggregation and protein-ganglioside interactions are more prevalent than in the atomistic simulations. Using the polarizable Martini water model, results were closer to the atomistic simulations. Although experimental data for validation is lacking, we proposed modified Martini parameters for gangliosides to more closely mimic the sizes and structures of ganglioside clusters observed at the atomistic level.