---
title: "CHARMM‐GUI MARTINI Maker for modeling and simulation of complex bacterial membranes with lipopolysaccharides"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Pin‐Chia Hsu, Bart MH Bruininks, Damien Jefferies, Paulo Cesar Telles de Souza, Jumin Lee, Dhilon S Patel, Siewert J Marrink, Yifei Qi, Syma Khalid, Wonpil Im"         # Paper authors (required)
year: "2017"           # Publication year (required)
publication: "Journal of Computational Chemistry"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1002/jcc.24895"            # URL of DOI (required)  
materials: "https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fjcc.24895&file=jcc24895-sup-0001-suppinfo.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Lipid membranes
  - Journal article
  - Phopholipids
  - Vesicles
  - Micelles
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Hsu, P. C., Bruininks, B. M., Jefferies, D., Cesar Telles de Souza, P., Lee, J., Patel, D. S., ... & Im, W. (2017). CHARMM‐GUI Martini Maker for modeling and simulation of complex bacterial membranes with lipopolysaccharides.

## Abstract

A complex cell envelope, composed of a mixture of lipid types including lipopolysaccharides, protects bacteria from the external environment. Clearly, the proteins embedded within the various components of the cell envelope have an intricate relationship with their local environment. Therefore, to obtain meaningful results, molecular simulations need to mimic as far as possible this chemically heterogeneous system. However, setting up such systems for computational studies is far from trivial, and consequently the vast majority of simulations of outer membrane proteins still rely on oversimplified phospholipid membrane models. This work presents an update of CHARMM-GUI Martini Maker for coarse-grained modeling and simulation of complex bacterial membranes with lipopolysaccharides. The qualities of the outer membrane systems generated by Martini Maker are validated by simulating them in bilayer, vesicle, nanodisc, and micelle environments (with and without outer membrane proteins) using the Martini force field. We expect this new feature in Martini Maker to be a useful tool for modeling large, complicated bacterial outer membrane systems in a user-friendly manner.