---
title: "Computational Lipidomics of the Neuronal Plasma Membrane"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Helgi I. Ingólfsson, Timothy S. Carpenter, Harsh Bhatia, Peer-Timo Bremer, Siewert J. Marrink, and Felice C. Lightstone"         # Paper authors (required)
year: "2017"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2017.10.017"            # URL of DOI (required)  
materials: "https://www.sciencedirect.com/science/article/pii/S0006349517311323#app2"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Ingólfsson, H. I., Carpenter, T. S., Bhatia, H., Bremer, P. T., Marrink, S. J., & Lightstone, F. C. (2017). Computational lipidomics of the neuronal plasma membrane. Biophysical journal, 113(10), 2271-2280.

## Abstract

Membrane lipid composition varies greatly within submembrane compartments, different organelle membranes, and also between cells of different cell stage, cell and tissue types, and organisms. Environmental factors (such as diet) also influence membrane composition. The membrane lipid composition is tightly regulated by the cell, maintaining a homeostasis that, if disrupted, can impair cell function and lead to disease. This is especially pronounced in the brain, where defects in lipid regulation are linked to various neurological diseases. The tightly regulated diversity raises questions on how complex changes in composition affect overall bilayer properties, dynamics, and lipid organization of cellular membranes. Here, we utilize recent advances in computational power and molecular dynamics force fields to develop and test a realistically complex human brain plasma membrane (PM) lipid model and extend previous work on an idealized, “average” mammalian PM. The PMs showed both striking similarities, despite significantly different lipid composition, and interesting differences. The main differences in composition (higher cholesterol concentration and increased tail unsaturation in brain PM) appear to have opposite, yet complementary, influences on many bilayer properties. Both mixtures exhibit a range of dynamic lipid lateral inhomogeneities (“domains”). The domains can be small and transient or larger and more persistent and can correlate between the leaflets depending on lipid mixture, Brain or Average, as well as on the extent of bilayer undulations.