---
title: "Alcohol Interactions with Lipid Bilayers"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Tomáš Kondela, Jana Gallová, Thomas Hauß, Jonathan Barnoud, Siewert-J. Marrink and Norbert Kučerka"         # Paper authors (required)
year: "2017"           # Publication year (required)
publication: "Molecules"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.3390/molecules22122078"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Small molecules
  - Solvents
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Kondela, T., Gallová, J., Hauß, T., Barnoud, J., Marrink, S. J., & Kučerka, N. (2017). Alcohol interactions with lipid bilayers. Molecules, 22(12), 2078.

## Abstract

We investigate the structural changes to lipid membrane that ensue from the addition of aliphatic alcohols with various alkyl tail lengths. Small angle neutron diffraction from flat lipid bilayers that are hydrated through water vapor has been employed to eliminate possible artefacts of the membrane curvature and the alcohol’s membrane-water partitioning. We have observed clear changes to membrane structure in both transversal and lateral directions. Most importantly, our results suggest the alteration of the membrane-water interface. The water encroachment has shifted in the way that alcohol loaded bilayers absorbed more water molecules when compared to the neat lipid bilayers. The experimental results have been corroborated by molecular dynamics simulations to reveal further details. Namely, the order parameter profiles have been fruitful in correlating the mechanical model of structural changes to the effect of anesthesia.