---
title: "Design and Properties of Genetically Encoded Probes for Sensing Macromolecular Crowding"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Boqun Liu, Christoffer Åberg, Floris J. van Eerden, Siewert J. Marrink, Bert Poolman, and Arnold J. Boersma"         # Paper authors (required)
year: "2017"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2017.04.004"            # URL of DOI (required)  
materials: "https://www.sciencedirect.com/science/article/pii/S0006349517303910#app2"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Polymers
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Liu, B., Åberg, C., van Eerden, F. J., Marrink, S. J., Poolman, B., & Boersma, A. J. (2017). Design and properties of genetically encoded probes for sensing macromolecular crowding. Biophysical journal, 112(9), 1929-1939.

## Abstract

Cells are highly crowded with proteins and polynucleotides. Any reaction that depends on the available volume can be affected by macromolecular crowding, but the effects of crowding in cells are complex and difficult to track. Here, we present a set of Förster resonance energy transfer (FRET)-based crowding-sensitive probes and investigate the role of the linker design. We investigate the sensors in vitro and in vivo and by molecular dynamics simulations. We find that in vitro all the probes can be compressed by crowding, with a magnitude that increases with the probe size, the crowder concentration, and the crowder size. We capture the role of the linker in a heuristic scaling model, and we find that compression is a function of size of the probe and volume fraction of the crowder. The FRET changes observed in Escherichia coli are more complicated, where FRET-increases and scaling behavior are observed solely with probes that contain the helices in the linker. The probe with the highest sensitivity to crowding in vivo yields the same macromolecular volume fractions as previously obtained from cell dry weight. The collection of new probes provides more detailed readouts on the macromolecular crowding than a single sensor.