---
title: "Stability and dynamics of membrane-spanning DNA nanopores"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Vishal Maingi, Jonathan R. Burns, Jaakko J. Uusitalo, Stefan Howorka, Siewert J. Marrink & Mark S. P. Sansom"         # Paper authors (required)
year: "2017"           # Publication year (required)
publication: "Nature Communications"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/ncomms14784"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/ncomms14784#Sec16"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Multi-scale
  - Enhanced sampling
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Maingi, V., Burns, J. R., Uusitalo, J. J., Howorka, S., Marrink, S. J., & Sansom, M. S. (2017). Stability and dynamics of membrane-spanning DNA nanopores. Nature Communications, 8(1), 14784.

## Abstract

Recently developed DNA-based analogues of membrane proteins have advanced synthetic biology. A fundamental question is how hydrophilic nanostructures reside in the hydrophobic environment of the membrane. Here, we use multiscale molecular dynamics (MD) simulations to explore the structure, stability and dynamics of an archetypical DNA nanotube inserted via a ring of membrane anchors into a phospholipid bilayer. Coarse-grained MD reveals that the lipids reorganize locally to interact closely with the membrane-spanning section of the DNA tube. Steered simulations along the bilayer normal establish the metastable nature of the inserted pore, yielding a force profile with barriers for membrane exit due to the membrane anchors. Atomistic, equilibrium simulations at two salt concentrations confirm the close packing of lipid around of the stably inserted DNA pore and its cation selectivity, while revealing localized structural fluctuations. The wide-ranging and detailed insight informs the design of next-generation DNA pores for synthetic biology or biomedicine.