---
title: "Enhancing doping efficiency by improving host-dopant miscibility for fullerene-based n-type thermoelectrics"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Li Qiu, Jian Liu, Riccardo Alessandri, Xinkai Qiu, Marten Koopmans, Remco W. A. Havenith, Siewert J. Marrink, Ryan C. Chiechi, L. Jan Anton Koster and  Jan C. Hummelen"         # Paper authors (required)
year: "2017"           # Publication year (required)
publication: "Journal of materials chemistry A"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/C7TA06609K"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Materials science
  - Polymers
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Qiu, L., Liu, J., Alessandri, R., Qiu, X., Koopmans, M., Havenith, R. W., ... & Hummelen, J. C. (2017). Enhancing doping efficiency by improving host-dopant miscibility for fullerene-based n-type thermoelectrics. Journal of materials chemistry A, 5(40), 21234-21241.

## Abstract

This paper describes a promising n-type doping system with high performance for thermoelectric applications. By introducing the polar triethylene glycol (TEG) side chain onto both fullerene host (PTEG-1) and dopant (TEG-DMBI) materials, the TEG-DMBI doped PTEG-1 films obtained through solution processing provide a better miscibility compared with films doped with commercially available N-DMBI (bearing a dimethylamino group instead of TEG), as determined by phase imaging AFM (atomic force microscopy) measurements and coarse-grain molecular dynamics simulations, leading to high doping efficiency up to 18% at 20 mol% doping concentration and thus high carrier density and mobility, which are critical to the electrical conductivity. Therefore a record power factor of 19.1 μW m−1 K−2 is obtained with an electrical conductivity of 1.81 S cm−1, one of the highest values reported for solution processable fullerene derivatives as n-type organic materials for thermoelectric applications to date.