---
title: "Exchange pathways of plastoquinone and plastoquinol in the photosystem II complex"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Floris J. Van Eerden, Manuel N. Melo, Pim W. J. M. Frederix, Xavier Periole & Siewert J. Marrink"         # Paper authors (required)
year: "2017"           # Publication year (required)
publication: "Nature Communications"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/ncomms15214"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/ncomms15214#Sec13"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Phopholipids
  - Sterols
  - Cofactors
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Van Eerden, F. J., Melo, M. N., Frederix, P. W., Periole, X., & Marrink, S. J. (2017). Exchange pathways of plastoquinone and plastoquinol in the photosystem II complex. Nature communications, 8(1), 15214.

## Abstract

Plastoquinone (PLQ) acts as an electron carrier between photosystem II (PSII) and the cytochrome b6f complex. To understand how PLQ enters and leaves PSII, here we show results of coarse grained molecular dynamics simulations of PSII embedded in the thylakoid membrane, covering a total simulation time of more than 0.5 ms. The long time scale allows the observation of many spontaneous entries of PLQ into PSII, and the unbinding of plastoquinol (PLQol) from the complex. In addition to the two known channels, we observe a third channel for PLQ/PLQol diffusion between the thylakoid membrane and the PLQ binding sites. Our simulations point to a promiscuous diffusion mechanism in which all three channels function as entry and exit channels. The exchange cavity serves as a PLQ reservoir. Our simulations provide a direct view on the exchange of electron carriers, a key step of the photosynthesis machinery.