---
title: "Prediction of Thylakoid Lipid Binding Sites on Photosystem II"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Floris J. Van Eerden, Manuel N. Melo, Pim W.J.M. Frederix, and Siewert J. Marrink"         # Paper authors (required)
year: "2017"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2017.09.039"            # URL of DOI (required)  
materials: "https://www.sciencedirect.com/science/article/pii/S0006349517311207#app2"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Van Eerden, F. J., Melo, M. N., Frederix, P. W., & Marrink, S. J. (2017). Prediction of thylakoid lipid binding sites on photosystem II. Biophysical journal, 113(12), 2669-2681.

## Abstract

The thylakoid membrane has a unique lipid composition, consisting mostly of galactolipids. These thylakoid lipids have important roles in photosynthesis. Here, we investigate to what extent these lipids bind specifically to the Photosystem II complex. To this end, we performed coarse-grain MD simulations of the Photosystem II complex embedded in a thylakoid membrane with realistic composition. Based on >85 μs simulation time, we find that monogalactosyldiacylglycerol and sulfoquinovosyldiacylglycerol lipids are enriched in the annular shell around the protein, and form distinct binding sites. From the analysis of residue contacts, we conclude that electrostatic interactions play an important role in stabilizing these binding sites. Furthermore, we find that chlorophyll a has a prevalent role in the coordination of the lipids. In addition, we observe lipids to diffuse in and out of the plastoquinone exchange cavities, allowing exchange of cocrystallized lipids with the bulk membrane and suggesting a more open nature of the plastoquinone exchange cavity. Together, our data provide a wealth of information on protein-lipid interactions for a key protein in photosynthesis.