---
title: "Molecular Dynamics of Photosystem II Embedded in the Thylakoid Membrane"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Floris J. van Eerden, Tom van den Berg, Pim W. J. M. Frederix, Djurre H. de Jong, Xavier Periole, and Siewert J. Marrink"         # Paper authors (required)
year: "2017"           # Publication year (required)
publication: "The Journal of Physical Chemistry B"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jpcb.6b06865"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/abs/10.1021/acs.jpcb.6b06865"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Cofactors
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Van Eerden, F. J., Van Den Berg, T., Frederix, P. W., De Jong, D. H., Periole, X., & Marrink, S. J. (2017). Molecular dynamics of photosystem II embedded in the thylakoid membrane. The Journal of Physical Chemistry B, 121(15), 3237-3249.

## Abstract

Photosystem II (PSII) is one of the key protein complexes in photosynthesis. We introduce a coarse grained model of PSII and present the analysis of 60 μs molecular dynamics simulations of PSII in both monomeric and dimeric form, embedded in a thylakoid membrane model that reflects its native lipid composition. We describe in detail the setup of the protein complex and the many natural cofactors and characterize their mobility. Overall we find that the protein subunits and cofactors are more flexible toward the periphery of the complex as well as near the PLQ exchange cavity and at the dimer interface. Of all cofactors, β-carotenes show the highest mobility. Some of the β-carotenes diffuse in and out of the protein complex via the thylakoid membrane. In contrast with the PSII dimer, the monomeric form adopts a tilted conformation in the membrane, with strong interactions between the soluble PsbO subunit and the glycolipid headgroups. Interestingly, the tilted conformation causes buckling of the membrane. Together, our results provide an unprecedented view of PSII dynamics on a microsecond time scale. Our data may be used as basis for the interpretation of experimental data as well as for theoretical models describing exciton energy transfer.