---
title: "The Martini 3 Metabolome"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Christopher Brasnett, Chelsea M. Brown, Linus Grünewald, Jan A. Stevens and Siewert J. Marrink"         # Paper authors (required)
year: "2026"           # Publication year (required)
publication: "bioRxiv"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.64898/2026.03.06.710121"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Pre-print
  - Metabolites
  - Parametrization
  - Small molecules
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Brasnett, C., Brown, C. M., Grünewald, L., Stevens, J. A., & Marrink, S. J. (2026). The Martini 3 Metabolome. bioRxiv, 2026-03.

## Abstract

Metabolites are ubiquitous in all living cells and are essential mediators of biochemical processes, serving either as substrates or as cofactors to enable the reactions. Capturing this diversity in computational workflows is important for allowing realistic simulations of the cytoplasm. Coarse-grained molecular dynamics enables the simulation of large scale systems up to the level of whole-cells, but is limited by the availability of refined parameters for all possible components in the system. In this work, we describe the parameterization of 186 common metabolites found in bacteria and eukaryotes within the framework of the Martini 3 force field. To showcase the behavior of Martini metabolites in a biological setting, we report simulations of protein-ligand binding and membrane permeation. The establishment of a Martini metabolome enables high-throughput simulations of metabolites interacting with other biomolecules, and opens the way for simulations of realistic cellular environments.