---
title: "Martini 3 Coarse-Grain Model For Linear Perfluoroalkyl Substances"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Alessandro Calza, Matteo Calvaresi, Francesco Zerbetto and Siewert J. Marrink"         # Paper authors (required)
year: "2026"           # Publication year (required)
publication: "Journal of Chemical Theory and Computation"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jctc.6c00250"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Materials science
  - Parametrization
  - Multi-scale
  - Micelles
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Calza, A., Calvaresi, M., Zerbetto, F., & Marrink, S. J. (2026). Martini 3 coarse-grain model for linear PerFluoroAlkyl Substances. Journal of Chemical Theory and Computation.

## Abstract

Perfluoroalkyl substances (PFAS) are a family of over seven million chemicals found in a vast number of industrial and consumer applications. Often referred to as the “forever chemicals,” they have gained increasing attention due to their environmental and health implications. The growing awareness and interest in these perfluorinated pollutants demand the exploitation of an integrated approach where the use of computational pipelines can play a major role in the understanding and prediction of their behavior. To this end, we developed an accurate and transferable coarse-grain PFAS model in the framework of the Martini 3 force field. Given the large amount of PFAS already reported, 18 linear perfluorocarboxylic acids and perfluorosulfonic acids of different chain lengths were considered in the parametrization. The model was validated following the standard Martini procedure and complemented with additional studies on self-aggregation and the interaction with graphene, which is a common substrate for sensors and wastewater remediation adsorbents. The results are highly consistent with both all-atom simulations and experimental data, successfully reproducing the key structural and physical properties. We believe that our study opens the way for high-throughput simulations to explore the interaction between PFAS and nanoparticles/(bio)molecules.