---
title: "Molecular Mechanisms of KIT Receptor Dimerization and Oncogenic Activation Revealed by Multiscale Simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Maria Gabriella Chiariello, Akash Deep Biswas, Carmen Gratteri, Ingrid Guarnetti Prandi, Siewert J. Marrink, Andrea Beccari, and Carmine Talarico"         # Paper authors (required)
year: "2026"           # Publication year (required)
publication: "chemRxiv"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.26434/chemrxiv.15002017/v1"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Pre-print
  - Proteins
  - Multi-scale
  - Self-assembly
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Chiariello, M. G., Biswas, A. D., Gratteri, C., Guarnetti Prandi, I., Marrink, S. J., Beccari, A., & Talarico, C. (2026). Molecular Mechanisms of KIT Receptor Dimerization and Oncogenic Activation Revealed by Multiscale Simulations.

## Abstract

The receptor tyrosine kinase KIT is essential for cell proliferation and differentiation, and its aberrant activation contributes to cancers such as acute myeloid leukemia and gastrointestinal stromal tumors. KIT activation normally requires stem cell factor (SCF)-induced dimerization, whereas oncogenic mutations can drive ligand-independent signalling. Here, we employ multiscale molecular dynamics simulations based on the Martini 3 coarse-grained (CG) force field to investigate the dimerization mechanisms of full-length KIT in both wild-type (WT) and oncogenic mutant forms within a realistic membrane environment. For the WT receptor, simulations capture SCF-driven dimerization through a cooperative “zipper-like” mechanism involving sequential domain-domain interactions. In contrast, the T417I, Δ418–419 mutant forms stable dimers spontaneously in the absence of SCF, stabilized by enhanced D5–D5 hydrophobic contacts. Back-mapping and atomistic refinement yielded the first all-atom (AA) structural model of the full-length KIT(T417I, Δ418–419) mutant, consistent with the V-shaped extracellular conformation observed experimentally. This study provides mechanistic insight into KIT activation and establishes a Martini 3 based framework for simulating receptor assembly and guiding the design of antibodies or small molecules that disrupt aberrant dimerization.