---
title: "Oxygen depletion in biomolecular condensates is dominated by macromolecular density"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Ankush Garg, Christopher Brasnett, Siewert J. Marrink, Klaus Koren and Magnus Kjaergaard"         # Paper authors (required)
year: "2026"           # Publication year (required)
publication: "Nature Communications"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s41467-026-69376-2"            # URL of DOI (required)  
materials: "https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-026-69376-2/MediaObjects/41467_2026_69376_MOESM1_ESM.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Biomolecular condensates
  - Self-assembly
  - Coacervate
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Garg, A., Brasnett, C., Marrink, S. J., Koren, K., & Kjaergaard, M. (2026). Oxygen depletion in biomolecular condensates is dominated by macromolecular density. Nature Communications.

## Abstract

Biomolecular condensates are dynamic cellular compartments formed by the self-assembly of proteins and nucleic acids. Many metabolites partition into condensates based on their interactions with the macromolecular constituents; yet, whether gases behave similarly remains unknown. Here, we show that oxygen partitions into protein-based condensates formed by intrinsically disordered repeat proteins with systematically varied sequences. Using microelectrodes, phosphorescence lifetime imaging microscopy, and molecular dynamics simulations, we find that oxygen is partially excluded from the condensate, and its partitioning does not correlate with the condensate hydrophobicity. Instead, oxygen concentration is inversely related to condensate protein density. These results suggest that the prevailing theory of small-molecule partitioning into condensates has to be augmented to consider the concentration of macromolecules as a dominant factor in the absence of interactions between the metabolite and the condensate. Our results suggest that biomolecular condensates can generate a nanoscale oxygen gradient, potentially modulating the local availability of oxygen for biochemical reactions within the cell.