---
title: "Structural and functional implications of phase separation of membrane protein LacY in Escherichia coli"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Dmitrii Linnik, Sumayra Sultanji, Jan A. Stevens, Gea K. Schuurman-Wolters, Rinse de Boer, Christiaan M. Punter, Siewert J. Marrink, Ivan Maslov and Bert Poolman"         # Paper authors (required)
year: "2026"           # Publication year (required)
publication: "Nature Communications"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s41467-026-69951-7"            # URL of DOI (required)  
materials: "https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-026-69951-7/MediaObjects/41467_2026_69951_MOESM1_ESM.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Biomolecular condensates
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Linnik, D., Sultanji, S., Stevens, J. A., Schuurman-Wolters, G. K., De Boer, R., Punter, C. M., ... & Poolman, B. (2026). Structural and functional implications of phase separation of membrane protein LacY in Escherichia coli. Nature Communications.

## Abstract

Liquid-liquid phase-separation (LLPS) controls protein activity and dynamically organizes (macro)molecules in living systems without the need for membrane-bound compartments. Biomolecular condensates of water-soluble proteins have extensively been studied, but little is known about LLPS of membrane proteins. In this work we induce in vivo condensation of lactose permease (LacY), a widely-studied model monomeric inner membrane protein in Escherichia coli, and evaluate how it affects LacY function. We fused LacY with engineered, condensate-forming protein PopTag. We observe major changes in the localization and mobility of LacYPop. Molecular dynamics simulations show how the PopTag domain drives the condensate-like association dynamics of LacYPop through hydrophobic sticker interactions. LacYPop preserves native-level transport activity and outperforms the non-condensed LacY under mild hyperosmotic stress (osmotic upshift). In osmotically stressed cells, membrane-bound biomolecular condensates also reduce deformation of the cytoplasmic membrane. Perturbation experiments suggest that membrane curvature drives the accumulation of LacYPop at the poles of E. coli. Co-condensation of LacY and β-galactosidase LacZ slightly reduces their activity and results in remarkable cellular reorganization of the proteins. Our research shows the localization, dynamics, and function of phase-separated membrane proteins in bacteria and highlights the potential of LLPS for engineering complex metabolic networks in vivo.