---
title: "The physicochemical design, structure and permeability of the JCVI-syn3A minimal cell membrane"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Caterina Presutti, Mert Bozoflu, Joanna Juhaniewicz-Dębińska, Lauren A. Lowe, Naomi Woltinge, Arathi Das, Mart Stuart, Siewert J. Marrink and Bert Poolman"         # Paper authors (required)
year: "2026"           # Publication year (required)
publication: "Research Square"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.21203/rs.3.rs-8843141/v1"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Pre-print
  - Lipid membranes
  - Phospholipids
  - Vesicles
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Presutti, C., Bozoflu, M., Juhaniewicz-Dębińska, J., Lowe, L. A., Woltinge, N., Das, A., ... & Poolman, B. (2026). The physicochemical design, structure and permeability of the JCVI-syn3A minimal cell membrane.

## Abstract

Minimal cells offer a platform to uncover the fundamental physicochemical principles of cellular life. While genomes, proteomes and metabolic networks of cells have been elucidated, the lipidome, which determines the physicochemical identity of the membrane, remains largely unexplored. Yet, the membrane is a central determinant of cellular viability, regulating solute permeability, mechanical stability, and environmental cues. Here, we investigate membranes that recapitulate the lipid composition of the minimal cell JCVI-syn3A, which is distinguished by an unusually high cholesterol content and simple composition. Combining cryo-electron microscopy, Langmuir monolayer experiments, permeability assays, and coarse-grained molecular dynamics simulations, we demonstrate that cholesterol and sphingomyelin act as dominant condensing agents that stabilize the membrane while preserving an ordered yet fluid state. These lipids enhance lipid packing and acyl-chain order, whereas cardiolipin, POPC, and DOPG counterbalance condensation by promoting fluidity and compressibility. Cholesterol–sphingomyelin interactions emerge as a key thermodynamic driver that fine-tunes membrane order, fluidity, and permeability. Remarkably, membranes containing up to 60 mol% of cholesterol remain permeable to water and physiologically relevant osmolytes at rates compatible with growth of JCVI-syn3A. Together, our results define the physicochemical principles underlying minimal cell membranes and reveal how lipid composition enables passive permeation while maintaining membrane integrity.