---
title: "Folded domains impose structural heterogeneity and attenuated dynamics in biomolecular condensates"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Liguo Wang and Siewert J. Marrink"         # Paper authors (required)
year: "2026"           # Publication year (required)
publication: "Nature Communications"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s41467-026-71778-1"            # URL of DOI (required)  
materials: "https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-026-71778-1/MediaObjects/41467_2026_71778_MOESM1_ESM.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Biomolecular condensates
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Wang, L., & Marrink, S. J. (2026). Folded domains impose structural heterogeneity and attenuated dynamics in biomolecular condensates. Nature Communications.

## Abstract

Biomolecular condensates are widely studied using simplified analogues formed by purified low complexity domains (LCDs) or intrinsically disordered regions (IDRs). However, the exclusion of folded domains fails to capture natural molecular complexity and limits their physiological relevance. Here, we performed molecular dynamics simulations to systematically investigate the internal structure of condensates formed by full-length multidomain proteins (MDPs) in comparison to IDR-only systems. In contrast to uniformly expanded conformations observed in IDR-only condensates during tens of microseconds simulation, MDP-based systems exhibit significant heterogeneity. The heterogeneous microenvironment imposed by folded domains results in component-specific coupling and a wide range of conformations sampled by the IDRs. Strikingly, residue interaction specificity remains conserved between the condensed and solution states, even in the presence of MDPs. Finally, both local and global dynamics are attenuated in MDP-based condensates, opposing the heterogeneous retardation and unperturbed local dynamics observed in IDR-only systems. Our findings propose folded domains to act as architectural keystones in natural condensates, and enrich our understanding of their internal structural and dynamic properties.