---
title: "Condensates as Conformation Editors of Disordered Client Proteins"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Liguo Wang and Siewert J. Marrink"         # Paper authors (required)
year: "2026"           # Publication year (required)
publication: "Journal of the American Chemical Society"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jacs.6c00501"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/suppl/10.1021/jacs.6c00501/suppl_file/ja6c00501_si_001.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Biomolecular condensates
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Wang, L., & Marrink, S. J. (2026). Condensates as Conformation Editors of Disordered Client Proteins. Journal of the American Chemical Society.

## Abstract

Biomolecular condensates organize cellular biochemistry not only by passive concentration modulation of molecules but also by potentially remodeling client protein conformations. However, the systematic principles governing such conformational editing are unknown. Here, we use coarse-grained simulations to demonstrate that diverse condensate environments remodel disordered client proteins in a scaffold-specific manner. Additionally, we explore the factors of this remodeling, establishing that the linear patterning of scaffold interaction motifs along sequence (sticker clustering) plays an important role, whereas an increased scaffold chain length primarily slows client dynamics while leaving their sequence-specific intrachain contact patterns largely preserved. This conformational remodeling is mediated by varied and nonuniform client–condensate interaction maps that are not solely encoded by primary sequence grammar but are cooperatively shaped by the emergent condensate architecture. Our work reveals that condensates function as sophisticated regulators of recruited disordered client conformation, with broad implications for cellular regulation and therapeutic intervention.