---
title: "Capturing chemical reactions inside biomolecular condensates with reactive Martini simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Christopher Brasnett, Armin Kiani, Selim Sami, Sijbren Otto & Siewert J. Marrink"         # Paper authors (required)
year: "2024"           # Publication year (required)
publication: "Communications Chemistry"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s42004-024-01234-y"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/s42004-024-01234-y#Sec11"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Biomolecular condensates
  - Small molecules
  - Reactive
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Brasnett, C., Kiani, A., Sami, S. & Marrink, S. J. (2024). Capturing chemical reactions inside biomolecular condensates with reactive Martini simulations. Commun Chem 7, 151.

## Abstract

Biomolecular condensates are phase separated systems that play an important role in the spatio-temporal organisation of cells. Their distinct physico-chemical nature offers a unique environment for chemical reactions to occur. The compartmentalisation of chemical reactions is also believed to be central to the development of early life. To demonstrate how molecular dynamics may be used to capture chemical reactions in condensates, here we perform reactive molecular dynamics simulations using the coarse-grained Martini forcefield. We focus on the formation of rings of benzene-1,3-dithiol inside a synthetic peptide-based condensate, and find that the ring size distribution shifts to larger macrocycles compared to when the reaction takes place in an aqueous environment. Moreover, reaction rates are noticeably increased when the peptides simultaneously undergo phase separation, hinting that condensates may act as chaperones in recruiting molecules to reaction hubs.