---
title: "Martini 3 Coarse-Grained Model for the Cofactors Involved in Photosynthesis"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Maria Gabriella Chiariello, Rubi Zarmiento-Garcia and Siewert-Jan Marrink"         # Paper authors (required)
year: "2024"           # Publication year (required)
publication: "International Journal of Molecular Sciences"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.3390/ijms25147947"            # URL of DOI (required)  
materials: "https://www.mdpi.com/1422-0067/25/14/7947"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Parametrization
  - Metabolites
  - Cofactors
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Chiariello, M. G., Zarmiento-Garcia, R., & Marrink, S. J. (2024). Martini 3 Coarse-Grained Model for the Cofactors Involved in Photosynthesis. International Journal of Molecular Sciences, 25(14), 7947.

## Abstract

As a critical step in advancing the simulation of photosynthetic complexes, we present the Martini 3 coarse-grained (CG) models of key cofactors associated with light harvesting (LHCII) proteins and the photosystem II (PSII) core complex. Our work focuses on the parametrization of beta-carotene, plastoquinone/quinol, violaxanthin, lutein, neoxanthin, chlorophyll A, chlorophyll B, and heme. We derived the CG parameters to match the all-atom reference simulations, while structural and thermodynamic properties of the cofactors were compared to experimental values when available. To further assess the reliability of the parameterization, we tested the behavior of these cofactors within their physiological environments, specifically in a lipid bilayer and bound to photosynthetic complexes. The results demonstrate that our CG models maintain the essential features required for realistic simulations. This work lays the groundwork for detailed simulations of the PSII-LHCII super-complex, providing a robust parameter set for future studies.