---
title: "Nanomechanical footprint of SARS-CoV-2 variants in complex with a potent nanobody by molecular simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Luis F Cofas-Vargas, Gustavo E Olivos-Ramirez, Mateusz Chwastyk, Rodrigo A Moreira, Joseph L Baker, Siewert J Marrink, and Adolfo B Poma"         # Paper authors (required)
year: "2024"           # Publication year (required)
publication: "Nanoscale"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/D4NR02074J"            # URL of DOI (required)  
materials: "https://www.rsc.org/suppdata/d4/nr/d4nr02074j/d4nr02074j1.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Enhanced sampling
  - Multi-scale
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Cofas-Vargas, L. F., Olivos-Ramirez, G. E., Chwastyk, M., Moreira, R. A., Baker, J. L., Marrink, S. J., & Poma, A. B. (2024). Nanomechanical footprint of SARS-CoV-2 variants in complex with a potent nanobody by molecular simulations. Nanoscale, 16(40), 18824-18834.

## Abstract

Rational design of novel antibody therapeutics against viral infections such as coronavirus relies on surface complementarity and high affinity for their effectiveness. Here, we explore an additional property of protein complexes, the intrinsic mechanical stability, in SARS-CoV-2 variants when complexed with a potent antibody. In this study, we utilized a recent implementation of the GōMartini 3 approach to investigate large conformational changes in protein complexes with a focus on the mechanostability of the receptor-binding domain (RBD) from WT, Alpha, Delta, and XBB.1.5 variants in complex with the H11-H4 nanobody. The analysis revealed moderate differences in mechanical stability among these variants. Also, we identified crucial residues in both the RBD and certain protein segments in the nanobody that contribute to this property. By performing pulling simulations and monitoring the presence of specific native and non-native contacts across the protein complex interface, we provided mechanistic insights into the dissociation process. Force-displacement profiles indicate a tensile force clamp mechanism associated with the type of protein complex. Our computational approach not only highlights the key mechanostable interactions that are necessary to maintain overall stability, but it also paves the way for the rational design of potent antibodies that are mechanostable and effective against emergent SARS-CoV-2 variants.