---
title: "Oxygen partitioning into biomolecular condensates is governed by excluded volume"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Ankush Garg, Christopher Brasnett, Siewert J Marrink, Klaus Koren, and Magnus Kjaergaard"         # Paper authors (required)
year: "2024"           # Publication year (required)
publication: "bioRxiv"    # Journal or similar (required)
preprint: "https://www.biorxiv.org/content/10.1101/2024.05.03.592328v1"       # URL to prepint page (optional)  
doi: "https://doi.org/10.1101/2024.05.03.592328"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Pre-print
  - Coacervate
  - Proteins
  - Biomolecular condensates
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Garg, A., Brasnett, C., Marrink, S. J., Koren, K., & Kjaergaard, M. (2024). Oxygen partitioning into biomolecular condensates is governed by excluded volume. bioRxiv, 2024-05.

## Abstract

Biomolecular condensates form through the self-assembly of proteins and nucleic acids to create dynamic compartments in cells. By concentrating specific molecules, condensates establish distinct microenvironments that regulate biochemical reactions in time and space. Macromolecules and metabolites partition into condensates depending on their interactions with the macromolecular constituents, however, the partitioning of gases has not been explored. We investigated oxygen partitioning into condensates formed by intrinsically disordered repeat proteins with systematic sequence variations using phosphorescence lifetime imaging microscopy (PLIM). Unlike other hydrophobic metabolites, oxygen is partially excluded from the condensate with partitioning constants more strongly modulated by changes in protein length than hydrophobicity. For repeat proteins, the dense phase protein concentration drops with chain length resulting in a looser condensate with less excluded volume. We found that oxygen partitioning is anti-correlated with dense phase protein concentration, suggesting that oxygen concentration is mainly determined by the solvent accessible volume. This suggests that oxygen partitioning is determined by the physical organization of the condensates rather than the chemical properties of the scaffold. Molecular dynamics simulations suggest that oxygen does not form strong and specific interactions with the scaffold and is dynamic on the nanosecond timescale. Biomolecular condensates thus result in variation of oxygen concentrations on nanometer length-scales, which can tune the oxygen concentration available for biochemical reactions within the cell.