---
title: "Exploring the Ligand Binding and Conformational Dynamics of the Substrate-Binding Domain 1 of the ABC Transporter GlnPQ"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Mariia Nemchinova, Gea K. Schuurman-Wolters, Jacob J. Whittaker, Valentina Arkhipova, Siewert J. Marrink, Bert Poolman, and Albert Guskov"         # Paper authors (required)
year: "2024"           # Publication year (required)
publication: "The Journal of Physical Chemistry B"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jpcb.4c02662"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/acs.jpcb.4c02662?goto=supporting-info"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Small molecules
  - Metabolites
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Nemchinova, M., Schuurman-Wolters, G. K., Whittaker, J. J., Arkhipova, V., Marrink, S. J., Poolman, B., & Guskov, A. (2024). Exploring the Ligand Binding and Conformational Dynamics of the Substrate-Binding Domain 1 of the ABC Transporter GlnPQ. The Journal of Physical Chemistry B, 128(32), 7822-7832.

## Abstract

The adenosine triphosphate (ATP)-binding cassette (ABC) importer GlnPQ from Lactococcus lactis has two sequential covalently linked substrate-binding domains (SBDs), which capture the substrates and deliver them to the translocon. The two SBDs differ in their ligand specificities, binding affinities and the distance to the transmembrane domain; interestingly, both SBDs can bind their ligands simultaneously without affecting each other. In this work, we studied the binding of ligands to both SBDs using X-ray crystallography and molecular dynamics simulations. We report three high-resolution structures of SBD1, namely, the wild-type SBD1 with bound asparagine or arginine, and E184D SBD1 with glutamine bound. Molecular dynamics (MD) simulations provide a detailed insight into the dynamics associated with open-closed transitions of the SBDs.