---
title: "Vesicle protrusion induced by antimicrobial peptides suggests common carpet mechanism for short antimicrobial peptides"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Peter Park, Danilo Kiyoshi Matsubara, Domenico R Barzotto, Filipe S Lima, Hernan Chaimovich, Siewert Jan Marrink, and Iolanda M Cuccovia"         # Paper authors (required)
year: "2024"           # Publication year (required)
publication: "Scientific Reports"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s41598-024-60601-w"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/s41598-024-60601-w#Sec11"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Vesicles
  - Proteins
  - Lipid membranes
  - Multi-scale
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Park, P., Matsubara, D. K., Barzotto, D. R., Lima, F. S., Chaimovich, H., Marrink, S. J., & Cuccovia, I. M. (2024). Vesicle protrusion induced by antimicrobial peptides suggests common carpet mechanism for short antimicrobial peptides. Scientific Reports, 14(1), 9701.

## Abstract

Short-cationic alpha-helical antimicrobial peptides (SCHAMPs) are promising candidates to combat the growing global threat of antimicrobial resistance. They are short-sequenced, selective against bacteria, and have rapid action by destroying membranes. A full understanding of their mechanism of action will provide key information to design more potent and selective SCHAMPs. Molecular Dynamics (MD) simulations are invaluable tools that provide detailed insights into the peptide-membrane interaction at the atomic- and meso-scale level. We use atomistic and coarse-grained MD to look into the exact steps that four promising SCHAMPs—BP100, Decoralin, Neurokinin-1, and Temporin L—take when they interact with membranes. Following experimental set-ups, we explored the effects of SCHAMPs on anionic membranes and vesicles at multiple peptide concentrations. Our results showed all four peptides shared similar binding steps, initially binding to the membrane through electrostatic interactions and then flipping on their axes, dehydrating, and inserting their hydrophobic moieties into the membrane core. At higher concentrations, fully alpha-helical peptides induced membrane budding and protrusions. Our results suggest the carpet mode of action is fit for the description of SCHAMPs lysis activity and discuss the importance of large hydrophobic residues in SCHAMPs design and activity.