---
title: "Probing the stability and interdomain interactions in the ABC transporter OpuA, using single-molecule optical tweezers"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Lyan van der Sleen, Jan Stevens, Siewert J Marrink, Bert Poolman, and Katarzyna Tych"         # Paper authors (required)
year: "2024"           # Publication year (required)
publication: "Cell Reports"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.celrep.2024.114110"            # URL of DOI (required)  
materials: "https://www.cell.com/cell-reports/fulltext/S2211-1247(24)00438-8#supplementaryMaterial"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Enhanced sampling
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> van der Sleen, L., Stevens, J. A., Marrink, S. J., Poolman, B., & Tych, K. (2024). Probing the stability and interdomain interactions in the ABC transporter OpuA using single-molecule optical tweezers. Cell reports, 43(4).

## Abstract

Transmembrane transporter proteins are essential for maintaining cellular homeostasis and, as such, are key drug targets. Many transmembrane transporter proteins are known to undergo large structural rearrangements during their functional cycles. Despite the wealth of detailed structural and functional data available for these systems, our understanding of their dynamics and, consequently, how they function is generally limited. We introduce an innovative approach that enables us to directly measure the dynamics and stability of interdomain interactions of transmembrane proteins using optical tweezers. Focusing on the osmoregulatory ATP-binding cassette transporter OpuA from Lactococcus lactis, we examine the mechanical properties and potential interactions of its substrate-binding domains. Our measurements are performed in lipid nanodiscs, providing a native-mimicking environment for the transmembrane protein. The technique provides high spatial and temporal resolution and allows us to study the functionally relevant motions and interdomain interactions of individual transmembrane transporter proteins in real time in a lipid bilayer.