---
title: "Structural Aspects of the ROS1 Kinase Domain and Oncogenic Mutations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Juliana F Vilachã, Tsjerk A Wassenaar, and Siewert J Marrink"         # Paper authors (required)
year: "2024"           # Publication year (required)
publication: "Crystals"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.3390/cryst14020106"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Vilachã, J. F., Wassenaar, T. A., & Marrink, S. J. (2024). Structural Aspects of the ROS1 Kinase Domain and Oncogenic Mutations. Crystals, 14(2), 106.

## Abstract

Protein kinases function as pivotal regulators in biological events, governing essential cellular processes through the transfer of phosphate groups from ATP molecules to substrates. Dysregulation of kinase activity is frequently associated with cancer, ocasionally arising from chromosomal translocation events that relocate genes encoding kinases. Fusion proteins resulting from such events, particularly those involving the proto-oncogene tyrosine-protein kinase ROS (ROS1), manifest as constitutively active kinases, emphasizing their role in oncogenesis. Notably, the chromosomal reallocation of the ros1 gene leads to fusion of proteins with the ROS1 kinase domain, implicated in various cancer types. Despite their prevalence, targeted inhibition of these fusion proteins relies on repurposed kinase inhibitors. This review comprehensively surveys experimentally determined ROS1 structures, emphasizing the pivotal role of X-ray crystallography in providing high-quality insights. We delve into the intricate interactions between ROS1 and kinase inhibitors, shedding light on the structural basis for inhibition. Additionally, we explore point mutations identified in patients, employing molecular modeling to elucidate their structural impact on the ROS1 kinase domain. By integrating structural insights with in vitro and in silico data, this review advances our understanding of ROS1 kinase in cancer, offering potential avenues for targeted therapeutic strategies.