---
title: "Hybrid lipid-block copolymer membranes enable stable reconstitution of a wide range of nanopores and robust sampling of serum"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Edo Vreeker, Fabian Grunewald, Nieck van der Heide, Siewert-Jan Marrink, Katarzyna Tych, and Giovanni Maglia"         # Paper authors (required)
year: "2024"           # Publication year (required)
publication: "bioRxiv"    # Journal or similar (required)
preprint: "https://www.biorxiv.org/content/10.1101/2024.05.16.594548v1"       # URL to prepint page (optional)  
doi: "https://doi.org/10.1101/2024.05.16.594548"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Pre-print
  - Polymers
  - Lipid membranes
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Vreeker, E., Grunewald, F., van der Heide, N., Marrink, S. J., Tych, K., & Maglia, G. (2024). Hybrid lipid-block copolymer membranes enable stable reconstitution of a wide range of nanopores and robust sampling of serum. bioRxiv, 2024-05.

## Abstract

Biological nanopores are powerful tools for detecting biomolecules at the single-molecule level, making them appealing as sensors for biological samples. However, the lipid membranes in which nanopores reside can be unstable in the presence of biological fluids. Here, membranes formed with the amphiphilic polymers PMOXA-PDMS-PMOXA and PBD-PEO are tested as potential alternatives for nanopore sensing. We demonstrate that polymer membranes can possess increased stability towards applied potentials and high concentrations of human serum, but that the stable insertion of a wide range of biological nanopores is most often compromised. Alternatively, hybrid polymer-lipid membranes comprising a 1:1 w/w mixture of PBD11PEO8 and DPhPC showed high electrical and biochemical stability while creating a suitable environment for all tested nanopores. Analytes such as proteins, DNA and sugars were efficiently sampled, indicating that in hybrid membranes nanopores showed native-like properties. Molecular dynamics simulations revealed that lipids form ∼12 nm domains interspersed by a polymer matrix. Nanopores partitioned into these lipid nanodomains and sequestered lipids possibly offering the same binding strength as in a native bilayer. This work shows that single-molecule analysis with nanopores in [PBD11PEO8 + DPhPC] membranes is feasible and present stable recordings in the presence of human serum. These results pave the way towards novel nanopore-based biosensors.