---
title: "PhD/Post doc positions"       # Title of the announcement (required)
description: |  # Short description of the announcement (required)
  "Various PhD/post-doc positions available to work on synthetic cells, including purely computational projects in our group!"            
sideber: false  # do not change
toc: false      # do not change
author: "Chelsea Brown (on bahlf of Siewert-Jan Marrink)"     # Author of the announcement (required)
date: "11/11/2024"       # Date of the announcement with format DD/MM/YYYY (required)
image: ""      # path to image file (optional): If not provided, the default image for announcements will be used
---

<!-- 
The text below is just an example. Please replace it with the actual description of the announcement. You can use markdown syntax to format the text.
-->

Building a synthetic cell is one of the greatest scientific and technological challenges of the 21st century. In the framework of a huge national Dutch program ([EVOLF](https://www.evolf.life)) and a European Doctorate network ([ComeInCell](https://www.comeincell.org)), we have 12 PhD/Postdoc positions available for biophysicists, bioengineers, biochemists, and molecular biologist at the [Groningen Biomolecular Sciences and Biotechnology Institute](https://www.rug.nl/research/gbb) of the University of Groningen in the Netherlands.

**Marrink group **

- Position 11: Multiscale modeling of cell division, probing the interplay between lipids and proteins for the rational design of efficient fission of artificial cells. [Further reading](https://doi.org/10.1038/s41467-020-16094-y)
- Position 12: Molecular dynamics simulations of minimal cells, focusing on the properties and organization of the cell envelope. [Further reading](https://doi.org/10.3389/fchem.2023.1106495)
