---
title: "Development of Martini 2.2 parameters for N-glycans: A case study of the HIV-1 Env glycoprotein dynamics"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Srirupa Chakraborty, Kshitij Wagh, S Gnanakaran, Cesar A López"         # Paper authors (required)
year: "2021"           # Publication year (required)
publication: "Glycobiology"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1093/glycob/cwab017"            # URL of DOI (required)  
materials: "https://academic.oup.com/glycob/article/31/7/787/6179202#supplementary-data"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Glycans
  - Proteins
  - Parametrization
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Chakraborty, S., Wagh, K., Gnanakaran, S., & López, C. A. (2021). Development of Martini 2.2 parameters for N-glycans: A case study of the HIV-1 Env glycoprotein dynamics. Glycobiology, 31(7), 787-799.

## Abstract

N-linked glycans are ubiquitous in nature and play key roles in biology. For example, glycosylation of pathogenic proteins is a common immune evasive mechanism, hampering the development of successful vaccines. Due to their chemical variability and complex dynamics, an accurate molecular understanding of glycans is still limited by the lack of effective resolution of current experimental approaches. Here, we have developed and implemented a reductive model based on the popular Martini 2.2 coarse-grained force field for the computational study of N-glycosylation. We used the HIV-1 Env as a direct applied example of a highly glycosylated protein. Our results indicate that the model not only reproduces many observables in very good agreement with a fully atomistic force field but also can be extended to study large amount of glycosylation variants, a fundamental property that can aid in the development of drugs and vaccines.