---
title: "Protocol for Simulations of PEGylated Proteins with Martini 3"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Fabian Grünewald, Peter C Kroon, Paulo CT Souza, Siewert J Marrink"         # Paper authors (required)
year: "2021"           # Publication year (required)
publication: "Structural Genomics: Methods in Molecular Biology"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1007/978-1-0716-0892-0_18"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Book chapter
  - Protocol
  - Proteins
  - Polymers
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Grünewald, F., Kroon, P. C., Souza, P. C., & Marrink, S. J. (2021). Protocol for simulations of PEGylated proteins with martini 3. Structural Genomics: General Applications, 315-335.

## Abstract

Enhancement of proteins by PEGylation is an active area of research. However, the interactions between polymer and protein are far from fully understood. To gain a better insight into these interactions or even make predictions, molecular dynamics (MD) simulations can be applied to study specific protein-polymer systems at molecular level detail. Here we present instructions on how to simulate PEGylated proteins using the latest iteration of the Martini coarse-grained (CG) force-field. CG MD simulations offer near atomistic information and at the same time allow to study complex biological systems over longer time and length scales than fully atomistic-level simulations.