---
title: "Structure of the human signal peptidase complex reveals the determinants for signal peptide cleavage"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "A. Manuel Liaci, Barbara Steigenberger, Paulo Cesar Telles de Souza, Sem Tamara, Mariska Gröllers-Mulderij, Patrick Ogrissek, Siewert J. Marrink, Richard A. Scheltema and Friedrich Förster"         # Paper authors (required)
year: "2021"           # Publication year (required)
publication: "Molecular cell"    # Journal or similar (required)
preprint: "https://www.biorxiv.org/content/10.1101/2020.11.11.378711v1.abstract"       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.molcel.2021.07.031"            # URL of DOI (required)  
materials: "https://www.sciencedirect.com/science/article/pii/S1097276521006006#app2"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Liaci, A. M., Steigenberger, B., de Souza, P. C. T., Tamara, S., Gröllers-Mulderij, M., Ogrissek, P., ... & Förster, F. (2021). Structure of the human signal peptidase complex reveals the determinants for signal peptide cleavage. Molecular cell, 81(19), 3934-3948.

## Abstract

The signal peptidase complex (SPC) is an essential membrane complex in the endoplasmic reticulum (ER), where it removes signal peptides (SPs) from a large variety of secretory pre-proteins with exquisite specificity. Although the determinants of this process have been established empirically, the molecular details of SP recognition and removal remain elusive. Here, we show that the human SPC exists in two functional paralogs with distinct proteolytic subunits. We determined the atomic structures of both paralogs using electron cryo-microscopy and structural proteomics. The active site is formed by a catalytic triad and abuts the ER membrane, where a transmembrane window collectively formed by all subunits locally thins the bilayer. Molecular dynamics simulations indicate that this unique architecture generates specificity for SPs based on the length of their hydrophobic segments.