---
title: "Capturing Membrane Phase Separation by Dual Resolution Molecular Dynamics Simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Yang Liu, Alex H. de Vries, Weria Pezeshkian, and Siewert J. Marrink"         # Paper authors (required)
year: "2021"           # Publication year (required)
publication: "Journal of Chemical Theory and Computation"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jctc.1c00151"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/acs.jctc.1c00151?goto=supporting-info"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Multi-scale
  - Vesicles
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Liu, Y., de Vries, A. H., Pezeshkian, W., & Marrink, S. J. (2021). Capturing membrane phase separation by dual resolution molecular dynamics simulations. Journal of Chemical Theory and Computation, 17(9), 5876-5884.

## Abstract

Understanding the lateral organization in plasma membranes remains an open problem and is of great interest to many researchers. Model membranes consisting of coexisting domains are commonly used as simplified models of plasma membranes. The coarse-grained (CG) Martini force field has successfully captured spontaneous separation of ternary membranes into a liquid-disordered and a liquid-ordered domain. With all-atom (AA) models, however, phase separation is much harder to achieve due to the slow underlying dynamics. To remedy this problem, here, we apply the virtual site (VS) hybrid method on a ternary membrane composed of saturated lipids, unsaturated lipids, and cholesterol to investigate the phase separation. The VS scheme couples the two membrane leaflets at CG and AA resolution. We found that the rapid phase separation reached by the CG leaflet can accelerate and guide this process in the AA leaflet.