---
title: "Asymmetric CorA gating mechanism as observed by molecular dynamics simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Mariia Nemchinova, Josef Melcr, Tsjerk A. Wassenaar, Siewert J. Marrink, and Albert Guskov"         # Paper authors (required)
year: "2021"           # Publication year (required)
publication: "Journal of chemical information and modeling"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jcim.1c00261"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/acs.jcim.1c00261?goto=supporting-info"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Nemchinova, M., Melcr, J., Wassenaar, T. A., Marrink, S. J., & Guskov, A. (2021). Asymmetric CorA gating mechanism as observed by molecular dynamics simulations. Journal of chemical information and modeling, 61(5), 2407-2417.

## Abstract

The CorA family of proteins plays a housekeeping role in the homeostasis of divalent metal ions in many bacteria and archaea as well as in mitochondria of eukaryotes, rendering it an important target to study the mechanisms of divalent transport and regulation across different life domains. Despite numerous studies, the mechanistic details of the channel gating and the transport of the metal ions are still not entirely understood. Here, we use all-atom and coarse-grained molecular dynamics simulations combined with in vitro experiments to investigate the influence of divalent cations on the function of CorA. Simulations reveal pronounced asymmetric movements of monomers that enable the rotation of the α7 helix and the cytoplasmic subdomain with the subsequent formation of new interactions and the opening of the channel. These computational results are functionally validated using site-directed mutagenesis of the intracellular cytoplasmic domain residues and biochemical assays. The obtained results infer a complex network of interactions altering the structure of CorA to allow gating. Furthermore, we attempt to reconcile the existing gating hypotheses for CorA to conclude the mechanism of transport of divalent cations via these proteins.