---
title: "Simulating realistic membrane shapes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Weria Pezeshkian and Siewert J. Marrink"         # Paper authors (required)
year: "2021"           # Publication year (required)
publication: "Current opinion in cell biology"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.ceb.2021.02.009"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Lipid membranes
  - Multi-scale
  - Vesicles
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Pezeshkian, W., & Marrink, S. J. (2021). Simulating realistic membrane shapes. Current opinion in cell biology, 71, 103-111.

## Abstract

Biological membranes exhibit diversity in their shapes and complexity in chemical compositions that are linked to many cellular functions. These two central features of biomembranes have been the subject of numerous simulation studies, using a diverse range of computational techniques. Currently, the field is able to capture this complexity at increasing levels of realism and connect the microscopic view on protein–lipid interactions to cellular morphologies at the level of entire organelles. Here we highlight recent advances in this topic, identify current bottlenecks, and sketch possible ways ahead.