---
title: "Coacervate formation studied by explicit solvent coarse-grain molecular dynamics with the Martini model"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Maria Tsanai, Pim WJM Frederix, Carsten FE Schroer, Paulo CT Souza, Siewert J Marrink"         # Paper authors (required)
year: "2021"           # Publication year (required)
publication: "Chemical Science"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/D1SC00374G"            # URL of DOI (required)  
materials: "https://www.rsc.org/suppdata/d1/sc/d1sc00374g/d1sc00374g3.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Coacervate
  - Biomolecular condensates
  - Proteins
  - Polymers
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Tsanai, M., Frederix, P. W., Schroer, C. F., Souza, P. C., & Marrink, S. J. (2021). Coacervate formation studied by explicit solvent coarse-grain molecular dynamics with the Martini model. Chemical Science, 12(24), 8521-8530.

## Abstract

Complex coacervates are liquid–liquid phase separated systems, typically containing oppositely charged polyelectrolytes. They are widely studied for their functional properties as well as their potential involvement in cellular compartmentalization as biomolecular condensates. Diffusion and partitioning of solutes into a coacervate phase are important to address because their highly dynamic nature is one of their most important functional characteristics in real-world systems, but are difficult to study experimentally or even theoretically without an explicit representation of every molecule in the system. Here, we present an explicit-solvent, molecular dynamics coarse-grain model of complex coacervates, based on the Martini 3.0 force field. We demonstrate the accuracy of the model by reproducing the salt dependent coacervation of poly-lysine and poly-glutamate systems, and show the potential of the model by simulating the partitioning of ions and small nucleotides between the condensate and surrounding solvent phase. Our model paves the way for simulating coacervates and biomolecular condensates in a wide range of conditions, with near-atomic resolution.