---
title: "Martini 3 Coarse-Grained Model for Type III Deep Eutectic Solvents: Thermodynamic, Structural, and Extraction Properties"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Petteri Vainikka, Sebastian Thallmair, Paulo Cesar Telles Souza, Siewert J Marrink"         # Paper authors (required)
year: "2021"           # Publication year (required)
publication: "ACS Sustainable Chemistry & Engineering"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acssuschemeng.1c06521"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/suppl/10.1021/acssuschemeng.1c06521/suppl_file/sc1c06521_si_001.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Solvents
  - Micelles
  - Journal article
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Vainikka, P., Thallmair, S., Souza, P. C. T., & Marrink, S. J. (2021). Martini 3 coarse-grained model for type III deep eutectic solvents: Thermodynamic, structural, and extraction properties. ACS Sustainable Chemistry & Engineering, 9(51), 17338-17350.

## Abstract

Deep eutectic solvents (DESs) are a more environmentally friendly, cost-effective, and recyclable alternative for ionic liquids. Since the number of possible deep eutectic solvents is very large, there are needs for effective methods to predict the physicochemical nature of possible new deep eutectic solvents that are not met by the currently available models. Here, we have built coarse-grained models for a few well-known and actively studied deep eutectic solvents using the recently published Martini 3 force field. Molecular dynamics simulations demonstrate that our models predict the properties of these particular DESs with an acceptable accuracy, and they are capable of capturing known liquid–liquid extraction processes as well as morphological shape changes of surfactant aggregates. Our coarse-grained approach is novel in the study of DESs, opening new possibilities for rapid screening of new DESs and their properties.