---
title: "Bottom-up fabrication of a proteasome–nanopore that unravels and processes single proteins"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Shengli Zhang, Gang Huang, Roderick Corstiaan Abraham Versloot, Bart Marlon Herwig Bruininks, Paulo Cesar Telles de Souza, Siewert-Jan Marrink & Giovanni Maglia"         # Paper authors (required)
year: "2021"           # Publication year (required)
publication: "Nature chemistry"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s41557-021-00824-w"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/s41557-021-00824-w#Sec14"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Zhang, S., Huang, G., Versloot, R. C. A., Bruininks, B. M. H., de Souza, P. C. T., Marrink, S. J., & Maglia, G. (2021). Bottom-up fabrication of a proteasome–nanopore that unravels and processes single proteins. Nature chemistry, 13(12), 1192-1199.

## Abstract

The precise assembly and engineering of molecular machines capable of handling biomolecules play crucial roles in most single-molecule methods. In this work we use components from all three domains of life to fabricate an integrated multiprotein complex that controls the unfolding and threading of individual proteins across a nanopore. This 900 kDa multicomponent device was made in two steps. First, we designed a stable and low-noise β-barrel nanopore sensor by linking the transmembrane region of bacterial protective antigen to a mammalian proteasome activator. An archaeal 20S proteasome was then built into the artificial nanopore to control the unfolding and linearized transport of proteins across the nanopore. This multicomponent molecular machine opens the door to two approaches in single-molecule protein analysis, in which selected substrate proteins are unfolded, fed to into the proteasomal chamber and then addressed either as fragmented peptides or intact polypeptides.