---
title: "Concerted diffusion of lipids in raft-like membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Touko Apajalahti, Perttu Niemelä, Praveen Nedumpully Govindan, Markus S. Miettinen, Emppu Salonen, Siewert-Jan Marrink and Ilpo Vattulainen"         # Paper authors (required)
year: "2010"           # Publication year (required)
publication: "Faraday discussions"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/B901487J"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Multi-scale
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Apajalahti, T., Niemelä, P., Govindan, P. N., Miettinen, M. S., Salonen, E., Marrink, S. J., & Vattulainen, I. (2010). Concerted diffusion of lipids in raft-like membranes. Faraday discussions, 144, 411-430.

## Abstract

Currently, there is no comprehensive model for the dynamics of cellular membranes. The understanding of even the basic dynamic processes, such as lateral diffusion of lipids, is still quite limited. Recent studies of one-component membrane systems have shown that instead of single-particle motions, the lateral diffusion is driven by a more complex, concerted mechanism for lipid diffusion (E. Falck et al., J. Am. Chem. Soc., 2008, 130, 44–45), where a lipid and its neighbors move in unison in terms of loosely defined clusters. In this work, we extend the previous study by considering the concerted lipid diffusion phenomena in many-component raft-like membranes. This nature of diffusion phenomena emerge in all the cases we have considered, including both atom-scale simulations of lateral diffusion within rafts and coarse-grained MARTINI simulations of diffusion in membranes characterized by coexistence of raft and non-raft domains. The data allows us to identify characteristic time scales for the concerted lipid motions, which turn out to range from hundreds of nanoseconds to several microseconds. Further, we characterize typical length scales associated with the correlated lipid diffusion patterns and find them to be about 10 nm, or even larger if weak correlations are taken into account. Finally, the concerted nature of lipid motions is also found in dissipative particle dynamics simulations of lipid membranes, clarifying the role of hydrodynamics (local momentum conservation) in membrane diffusion phenomena.