---
title: "Lateral pressure profiles in lipid monolayers"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Svetlana Baoukina, Siewert J. Marrink and D. Peter Tieleman"         # Paper authors (required)
year: "2010"           # Publication year (required)
publication: "Faraday discussions"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/B905647E"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Solvents
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Baoukina, S., Marrink, S. J., & Tieleman, D. P. (2010). Lateral pressure profiles in lipid monolayers. Faraday discussions, 144, 393-409.

## Abstract

We have used molecular dynamics simulations with coarse-grained and atomistic models to study the lateral pressure profiles in lipid monolayers. We first consider simple oil/air and oil/water interfaces, and then proceed to lipid monolayers at air/water and oil/water interfaces. The results are qualitatively similar in both atomistic and coarse-grained models. The lateral pressure profile in a monolayer is characterized by a headgroup/water pressure-interfacial tension-chain pressure pattern. In contrast to lipid bilayers, the pressure decreases towards the chain free ends. An additional chain/air tension peak is present in monolayers at the air/water interface. Lateral pressure profiles are calculated for monolayers of different lipid composition under varying surface tension. Increasing the surface tension suppresses both pressure peaks and widens the interfacial tension in monolayers at the oil/water interface, and mainly suppresses the chain pressure in monolayers at the air/water interface. In monolayers in the liquid-condensed phase, the pressure peaks split due to ordering. Variation of lipid composition leads to noticeable changes in all regions of the pressure profile at a fixed surface tension.