---
title: "Cholesterol in Bilayers with PUFA Chains: Doping with DMPC or POPC Results in Sterol Reorientation and Membrane-Domain Formation"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Norbert Kučerka, Drew Marquardt, Thad A. Harroun, Mu-Ping Nieh, Stephen R. Wassall, Djurre H. de Jong, Lars V. Schäfer, Siewert J. Marrink, and John Katsaras"         # Paper authors (required)
year: "2010"           # Publication year (required)
publication: "Biochemistry"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/bi100891z"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Sterols
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Kucerka, N., Marquardt, D., Harroun, T. A., Nieh, M. P., Wassall, S. R., De Jong, D. H., ... & Katsaras, J. (2010). Cholesterol in bilayers with PUFA chains: doping with DMPC or POPC results in sterol reorientation and membrane-domain formation. Biochemistry, 49(35), 7485-7493.

## Abstract

Using neutron diffraction Harroun et al. [(2006) Biochemistry 45, 1227−1233; (2008) Biochemistry 47, 7090−7096] carried out studies that unequivocally demonstrated cholesterol preferentially sequestering in the middle of bilayers (i.e., flat orientation) made of lipids with polyunsaturated fatty acids (PUFA), in contrast to its “usual” position where its hydroxyl group locates near the lipid/water interface (i.e., upright orientation). Here we clearly show, using neutron diffraction, cholesterol’s orientational preference in different lipid bilayers. For example, although it requires 50 mol % POPC (16:0−18:1 PC) in DAPC (di20:4 PC) bilayers to cause cholesterol to revert to its upright orientation, only 5 mol % DMPC (di14:0 PC) is needed to achieve the same effect. This result demonstrates not only cholesterol’s affinity for saturated hydrocarbon chains, but also its aversion for PUFAs. Molecular dynamics (MD) simulations performed on similar systems show that in high PUFA content bilayers cholesterol is simultaneously capable of assuming different orientations within a bilayer. Although this result is known from previous MD studies by Marrink et al. [(2008) J. Am. Chem. Soc. 130, 10−11], it has yet to be confirmed experimentally. Importantly, MD simulations predict the formation of DMPC-rich domains, data corroborated by experiment (i.e., 10 mol % DMPC-doped DAPC bilayers), where cholesterol preferentially locates in its upright orientation, while in DMPC-depleted domains cholesterol is found mostly in the bilayer center (i.e., flat orientation). These results lend credence to DMPC’s aversion for PUFAs, supporting the notion that domain formation is primarily driven by lipids.