---
title: "Release of content through mechano-sensitive gates in pressurized liposomes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Martti Louhivuori, H. Jelger Risselada, Erik van der Giessen, and Siewert J. Marrink"         # Paper authors (required)
year: "2010"           # Publication year (required)
publication: "Proceedings of the National Academy of Sciences"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1073/pnas.1001316107"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Solvents
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Louhivuori, M., Risselada, H. J., van der Giessen, E., & Marrink, S. J. (2010). Release of content through mechano-sensitive gates in pressurized liposomes. Proceedings of the National Academy of Sciences, 107(46), 19856-19860.

## Abstract

Mechano-sensitive channels are ubiquitous membrane proteins that activate in response to increasing tension in the lipid membrane. They facilitate a sudden, nonselective release of solutes and water that safeguards the integrity of the cell in hypo- or hyper-osmotic shock conditions. We have simulated the rapid release of content from a pressurized liposome through a particular mechano-sensitive protein channel, MscL, embedded in the liposomal membrane. We show that a single channel is able to relax the liposome, stressed to the point of bursting, in a matter of microseconds. We map the full activation–deactivation cycle of MscL in near-atomic detail and are able to quantify the rapid decrease in liposomal stress as a result of channel activation. This provides a computational tool that opens the way to contribute to the rational design of functional nano-containers.