---
title: "Immobilization of the Plug Domain Inside the SecY Channel Allows Unrestricted Protein Translocation"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Jelger A. Lycklama a Nijeholt, Monica Bulacu, Siewert Jan Marrink, and Arnold J.M. Driessen"         # Paper authors (required)
year: "2010"           # Publication year (required)
publication: "Journal of biological chemistry"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1074/jbc.M110.124636"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> a Nijeholt, J. A. L., Bulacu, M., Marrink, S. J., & Driessen, A. J. (2010). Immobilization of the plug domain inside the SecY channel allows unrestricted protein translocation. Journal of biological chemistry, 285(31), 23747-23754.

## Abstract

The SecYEG complex forms a protein-conducting channel in the inner membrane of Escherichia coli to support the translocation of secretory proteins in their unfolded state. The SecY channel is closed at the periplasmic face of the membrane by a small re-entrance loop that connects transmembrane segment 1 with 2b. This helical domain 2a is termed the plug domain. By the introduction of pairs of cysteines and crosslinkers, the plug domain was immobilized inside the channel and connected to transmembrane segment 10. Translocation was inhibited to various degrees depending on the position and crosslinker spacer length. With one of the crosslinked mutants translocation occurred unrestricted. Biochemical characterization of this mutant as well as molecular dynamics simulations suggest that only a limited movement of the plug domain suffices for translocation.