---
title: "Antimicrobial Peptides Induce Growth of Phosphatidylglycerol Domains in a Model Bacterial Membrane"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Anton A. Polyansky, Rajesh Ramaswamy, Pavel E. Volynsky, Ivo F. Sbalzarini, Siewert J. Marrink, and Roman G. Efremov"         # Paper authors (required)
year: "2010"           # Publication year (required)
publication: "The Journal of Physical Chemistry Letters"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jz101163e"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Polyansky, A. A., Ramaswamy, R., Volynsky, P. E., Sbalzarini, I. F., Marrink, S. J., & Efremov, R. G. (2010). Antimicrobial peptides induce growth of phosphatidylglycerol domains in a model bacterial membrane. The Journal of Physical Chemistry Letters, 1(20), 3108-3111.

## Abstract

We performed microsecond long coarse-grained molecular dynamics simulations to elucidate the lateral structure and domain dynamics of a phosphatidylethanolamine (PE)/phosphatidylglycerol (PG) mixed bilayer (7/3), mimicking the inner membrane of gram-negative bacteria. Specifically, we address the effect of surface bound antimicrobial peptides (AMPs) on the lateral organization of the membrane. We find that, in the absence of the peptides, the minor PG fraction only forms small clusters, but that these clusters grow in size upon binding of the cationic AMPs. The presence of AMPs systematically affects the dynamics and induces long-range order in the structure of PG domains, stabilizing the separation between the two lipid fractions. Our results help in understanding the initial stages of destabilization of cytoplasmic bacterial membranes below the critical peptide concentration necessary for disruption, and provide a possible explanation for the multimodal character of AMP activity.