---
title: "Influence of Hydrophobic Mismatch and Amino Acid Composition on the Lateral Diffusion of Transmembrane Peptides"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Sivaramakrishnan Ramadurai, Andrea Holt, Lars V. Schäfer, Victor V. Krasnikov, Dirk T.S. Rijkers, Siewert J. Marrink, J. Antoinette Killian, and Bert Poolman"         # Paper authors (required)
year: "2010"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2010.05.042"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Ramadurai, S., Holt, A., Schäfer, L. V., Krasnikov, V. V., Rijkers, D. T., Marrink, S. J., ... & Poolman, B. (2010). Influence of hydrophobic mismatch and amino acid composition on the lateral diffusion of transmembrane peptides. Biophysical journal, 99(5), 1447-1454.

## Abstract

We investigated the effect of amino acid composition and hydrophobic length of α-helical transmembrane peptides and the role of electrostatic interactions on the lateral diffusion of the peptides in lipid membranes. Model peptides of varying length and composition, and either tryptophans or lysines as flanking residues, were synthesized. The peptides were labeled with the fluorescent label Alexa Fluor 488 and incorporated into phospholipid bilayers of different hydrophobic thickness and composition. Giant unilamellar vesicles were formed by electroformation, and the lateral diffusion of the transmembrane peptides (and lipids) was determined by fluorescence correlation spectroscopy. In addition, we performed coarse-grained molecular-dynamics simulations of single peptides of different hydrophobic lengths embedded in planar membranes of different thicknesses. Both the experimental and simulation results indicate that lateral diffusion is sensitive to membrane thickness between the peptides and surrounding lipids. We did not observe a difference in the lateral diffusion of the peptides with respect to the presence of tryptophans or lysines as flanking residues. The specific lipid headgroup composition of the membrane has a much less pronounced impact on the diffusion of the peptides than does the hydrophobic thickness.