---
title: "Membrane poration by antimicrobial peptides combining atomistic and coarse-grained descriptions"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Andrzej J. Rzepiela, Durba Sengupta, Nicolae Goga and Siewert J. Marrink"         # Paper authors (required)
year: "2010"           # Publication year (required)
publication: "Faraday discussions"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/B901615E"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Multi-scale
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Rzepiela, A. J., Sengupta, D., Goga, N., & Marrink, S. J. (2010). Membrane poration by antimicrobial peptides combining atomistic and coarse-grained descriptions. Faraday discussions, 144, 431-443.

## Abstract

Antimicrobial peptides (AMPs) comprise a large family of peptides that include small cationic peptides, such as magainins, which permeabilize lipid membranes. Previous atomistic level simulations of magainin-H2 peptides show that they act by forming toroidal transmembrane pores. However, due to the atomistic level of description, these simulations were necessarily limited to small system sizes and sub-microsecond time scales. Here, we study the long-time relaxation properties of these pores by evolving the systems using a coarse-grain (CG) description. The disordered nature and the topology of the atomistic pores are maintained at the CG level. The peptides sample different orientations but at any given time, only a few peptides insert into the pore. Key states observed at the CG level are subsequently back-transformed to the atomistic level using a resolution-transformation protocol. The configurations sampled at the CG level are stable in the atomistic simulation. The effect of helicity on pore stability is investigated at the CG level and we find that partial helicity is required to form stable pores. We also show that the current CG scheme can be used to study spontaneous poration by magainin-H2 peptides. Overall, our simulations provide a multi-scale view of a fundamental biophysical membrane process involving a complex interplay between peptides and lipids.