---
title: "Partitioning of Lipids at Domain Boundaries in Model Membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Lars V. Schäfer and Siewert J. Marrink"         # Paper authors (required)
year: "2010"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2010.08.072"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Schäfer, L. V., & Marrink, S. J. (2010). Partitioning of lipids at domain boundaries in model membranes. Biophysical journal, 99(12), L91-L93.

## Abstract

Line-active molecules (“linactants”) that bind to the boundary interface between different fluid lipid domains in membranes have a strong potential as regulators of the lateral heterogeneity that is important for many biological processes. Here, we use molecular dynamics simulations in combination with a coarse-grain model that retains near-atomic resolution to identify lipid species that can act as linactants in a model membrane that is segregated into two lipid domains of different fluidity. Our simulations predict that certain hybrid saturated/unsaturated chain lipids can bind to the interface and lower the line tension, whereas cone-shaped lysolipids have a less pronounced effect.