---
title: "Lipid-mediated interactions tune the association of glycophorin A helix and its disruptive mutants in membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Durba Sengupta and Siewert J. Marrink"         # Paper authors (required)
year: "2010"           # Publication year (required)
publication: "Physical Chemistry Chemical Physics"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/C0CP00101E"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Self-assembly
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Sengupta, D., & Marrink, S. J. (2010). Lipid-mediated interactions tune the association of glycophorin A helix and its disruptive mutants in membranes. Physical Chemistry Chemical Physics, 12(40), 12987-12996.

## Abstract

The specific and non-specific driving forces of helix association within membranes are still poorly understood. Here, we use coarse-grain molecular dynamics simulations to study the association behavior of glycophorin A and two disruptive mutants, T87F and a triple mutant of the GxxxG motif (G79LG83LG86L), embedded in a lipid membrane. Self-assembly simulations and the association free-energy profile confirm an energetically-favorable dimerized state for both the wild type and the mutants. The reduced association of the mutants compared to the wild type, as observed in experiments, can be justified from comparisons of the free energy profiles. Less-favorable protein–protein interactions as well as disruption of lipid packing around the mutant dimers is responsible for their reduced association. The role of the non-specific “lipid-phobic” contribution appears to be as important as the specific “helix–helix” contribution. However, the differences between the wild type and mutants are subtle and our simulations predict a dimerization state not only for the wild-type glycophorin A, but also for these ‘disruptive’ mutants. Our results highlight the importance of both specific as well as non-specific driving forces in the association of transmembrane helices, and point to the need of more careful interpretation of experimental measurements.