---
title: "Solvent-Exposed Tails as Prestalk Transition States for Membrane Fusion at Low Hydration"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Yuliya G. Smirnova, Siewert-Jan Marrink, Reinhard Lipowsky, and Volker Knecht"         # Paper authors (required)
year: "2010"           # Publication year (required)
publication: "Journal of the American Chemical Society"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/ja910050x"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
  - Vesicles
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Smirnova, Y. G., Marrink, S. J., Lipowsky, R., & Knecht, V. (2010). Solvent-exposed tails as prestalk transition states for membrane fusion at low hydration. Journal of the American Chemical Society, 132(19), 6710-6718.

## Abstract

Membrane fusion is a key step in intracellular trafficking and viral infection. The underlying molecular mechanism is poorly understood. We have used molecular dynamics simulations in conjunction with a coarse grained model to study early metastable and transition states during the fusion of two planar palmitoyl-oleoyl-phosphatidylcholine (POPC) bilayers separated by five waters per lipid in the cis leaflets at zero tension. This system mimics the contact area between two vesicles with large diameters compared to the membrane thickness at conditions where fusion may start in the core of the contact area. At elevated temperatures, the two proximal leaflets become connected via multiple lipid molecules and form a stalklike structure. At room temperature, this structure has a free energy of 3kBT and is separated from the unconnected state by a significant free energy barrier of 20kBT. Stalk formation is initiated by the establishment of a localized hydrophobic contact between the bilayers. This contact is either formed by two partially splayed lipids or a single fully splayed one leading to the formation of a (metastable) splayed lipid bond intermediate. These findings indicate that, for low hydration, early membrane fusion kinetics is not determined by the stalk energy but by the energy of prestalk transition states involving solvent-exposed lipid tails.