---
title: "Role of Lipids in Spheroidal High Density Lipoproteins"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Timo Vuorela, Andrea Catte, Perttu S. Niemelä, Anette Hall, Marja T. Hyvönen, Siewert-Jan Marrink, Mikko Karttunen, and Ilpo Vattulainen"         # Paper authors (required)
year: "2010"           # Publication year (required)
publication: "PLoS Computational Biology"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1371/journal.pcbi.1000964"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Sterols
  - Nanoparticles
  - Drug design
  - Self-assembly
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Vuorela, T., Catte, A., Niemelä, P. S., Hall, A., Hyvönen, M. T., Marrink, S. J., ... & Vattulainen, I. (2010). Role of lipids in spheroidal high density lipoproteins. PLoS computational biology, 6(10), e1000964.

## Abstract

We study the structure and dynamics of spherical high density lipoprotein (HDL) particles through coarse-grained multi-microsecond molecular dynamics simulations. We simulate both a lipid droplet without the apolipoprotein A-I (apoA-I) and the full HDL particle including two apoA-I molecules surrounding the lipid compartment. The present models are the first ones among computational studies where the size and lipid composition of HDL are realistic, corresponding to human serum HDL. We focus on the role of lipids in HDL structure and dynamics. Particular attention is paid to the assembly of lipids and the influence of lipid-protein interactions on HDL properties. We find that the properties of lipids depend significantly on their location in the particle (core, intermediate region, surface). Unlike the hydrophobic core, the intermediate and surface regions are characterized by prominent conformational lipid order. Yet, not only the conformations but also the dynamics of lipids are found to be distinctly different in the different regions of HDL, highlighting the importance of dynamics in considering the functionalization of HDL. The structure of the lipid droplet close to the HDL-water interface is altered by the presence of apoA-Is, with most prominent changes being observed for cholesterol and polar lipids. For cholesterol, slow trafficking between the surface layer and the regimes underneath is observed. The lipid-protein interactions are strongest for cholesterol, in particular its interaction with hydrophobic residues of apoA-I. Our results reveal that not only hydrophobicity but also conformational entropy of the molecules are the driving forces in the formation of HDL structure. The results provide the first detailed structural model for HDL and its dynamics with and without apoA-I, and indicate how the interplay and competition between entropy and detailed interactions may be used in nanoparticle and drug design through self-assembly.