---
title: "Simulation of Domain Formation in DLPC−DSPC Mixed Bilayers"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Roland Faller and Siewert-Jan Marrink"         # Paper authors (required)
year: "2004"           # Publication year (required)
publication: "Langmuir"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/la0492759"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Faller, R., & Marrink, S. J. (2004). Simulation of domain formation in DLPC− DSPC mixed bilayers. Langmuir, 20(18), 7686-7693.

## Abstract

Binary mixtures of two phosphatidylcholines of different chain lengths are simulated in the bilayer state. We find a phase transition between a liquid state and a gel state at all concentrations. This phase transition is characterized by the area per lipid headgroup, the order parameter, and a change in dynamics. At concentrations with a majority of the longer lipid, we find phase separation into a gel and a liquid state in a small temperature window. This leads to a strong dynamic heterogeneity. Experimental phase transition temperatures are reproduced semiquantitatively. We see a clear shift in the phase transition to higher temperatures with increasing concentration of the longer lipid.