---
title: "Molecular View of Hexagonal Phase Formation in Phospholipid Membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Siewert-Jan Marrink and Alan E. Mark"         # Paper authors (required)
year: "2004"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1529/biophysj.104.048710"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Marrink, S. J., & Mark, A. E. (2004). Molecular view of hexagonal phase formation in phospholipid membranes. Biophysical journal, 87(6), 3894-3900.

## Abstract

Important biological processes, such as vesicle fusion or budding, require the cell matrix to undergo a transition from a lamellar to a nonlamellar state. Although equilibrium properties of membranes are amenable to detailed theoretical studies, collective rearrangements involved in phase transitions have thus far only been modeled on a qualitative level. Here, for the first time, the complete transition pathway from a multilamellar to an inverted hexagonal phase is elucidated at near-atomic detail using a recently developed coarse-grained molecular dynamics simulation model. Insight is provided into experimentally inaccessible data such as the molecular structure of the intermediates and the kinetics involved. Starting from multilamellar configurations, the spontaneous formation of stalks between the bilayers is observed on a nanosecond timescale at elevated temperatures or reduced hydration levels. The stalks subsequently elongate in a cooperative manner leading to the formation of an inverted hexagonal phase. The rate of stalk elongation is ∼0.1 nm ns−1. Within a narrow hydration/temperature/composition range the stalks appear stable and rearrange into the rhombohedral phase.