---
title: "Pitfalls of the MARTINI Model"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Riccardo Alessandri, Paulo Cesar Telles de Souza, Sebastian Thallmair, Manuel N Melo, Alex H De Vries, Siewert J Marrink"         # Paper authors (required)
year: "2019"           # Publication year (required)
publication: "Journal of Chemical Theory and Computation"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jctc.9b00473"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/abs/10.1021/acs.jctc.9b00473"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Forcefield
  - Parametrization
  - Solvents
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Alessandri, R., Souza, P. C., Thallmair, S., Melo, M. N., De Vries, A. H., & Marrink, S. J. (2019). Pitfalls of the Martini model. Journal of chemical theory and computation, 15(10), 5448-5460.

## Abstract

The computational and conceptual simplifications realized by coarse-grain (CG) models make them a ubiquitous tool in the current computational modeling landscape. Building block based CG models, such as the Martini model, possess the key advantage of allowing for a broad range of applications without the need to reparametrize the force field each time. However, there are certain inherent limitations to this approach, which we investigate in detail in this work. We first study the consequences of the absence of specific cross Lennard-Jones parameters between different particle sizes. We show that this lack may lead to artificially high free energy barriers in dimerization profiles. We then look at the effect of deviating too far from the standard bonded parameters, both in terms of solute partitioning behavior and solvent properties. Moreover, we show that too weak bonded force constants entail the risk of artificially inducing clustering, which has to be taken into account when designing elastic network models for proteins. These results have implications for the current use of the Martini CG model and provide clear directions for the reparametrization of the Martini model. Moreover, our findings are generally relevant for the parametrization of any other building block based force field.