---
title: "Emerging Diversity in Lipid–Protein Interactions"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Valentina Corradi, Besian I. Sejdiu, Haydee Mesa-Galloso, Haleh Abdizadeh, Sergei Yu. Noskov, Siewert J. Marrink, and D. Peter Tieleman"         # Paper authors (required)
year: "2019"           # Publication year (required)
publication: "Chemical reviews"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.chemrev.8b00451"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Proteins
  - Lipid membranes
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Corradi, V., Sejdiu, B. I., Mesa-Galloso, H., Abdizadeh, H., Noskov, S. Y., Marrink, S. J., & Tieleman, D. P. (2019). Emerging diversity in lipid–protein interactions. Chemical reviews, 119(9), 5775-5848.

## Abstract

Membrane lipids interact with proteins in a variety of ways, ranging from providing a stable membrane environment for proteins to being embedded in to detailed roles in complicated and well-regulated protein functions. Experimental and computational advances are converging in a rapidly expanding research area of lipid–protein interactions. Experimentally, the database of high-resolution membrane protein structures is growing, as are capabilities to identify the complex lipid composition of different membranes, to probe the challenging time and length scales of lipid–protein interactions, and to link lipid–protein interactions to protein function in a variety of proteins. Computationally, more accurate membrane models and more powerful computers now enable a detailed look at lipid–protein interactions and increasing overlap with experimental observations for validation and joint interpretation of simulation and experiment. Here we review papers that use computational approaches to study detailed lipid–protein interactions, together with brief experimental and physiological contexts, aiming at comprehensive coverage of simulation papers in the last five years. Overall, a complex picture of lipid–protein interactions emerges, through a range of mechanisms including modulation of the physical properties of the lipid environment, detailed chemical interactions between lipids and proteins, and key functional roles of very specific lipids binding to well-defined binding sites on proteins. Computationally, despite important limitations, molecular dynamics simulations with current computer power and theoretical models are now in an excellent position to answer detailed questions about lipid–protein interactions.