---
title: "Ceramides bind VDAC2 to trigger mitochondrial apoptosis"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Shashank Dadsena, Svenja Bockelmann, John G. M. Mina, Dina G. Hassan, Sergei Korneev, Guilherme Razzera, Helene Jahn, Patrick Niekamp, Dagmar Müller, Markus Schneider, Fikadu G. Tafesse, Siewert J. Marrink, Manuel N. Melo & Joost C. M. Holthuis"         # Paper authors (required)
year: "2019"           # Publication year (required)
publication: "Nature Communications"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s41467-019-09654-4"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/s41467-019-09654-4#Sec23"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Dadsena, S., Bockelmann, S., Mina, J. G., Hassan, D. G., Korneev, S., Razzera, G., ... & Holthuis, J. C. (2019). Ceramides bind VDAC2 to trigger mitochondrial apoptosis. Nature Communications, 10.

## Abstract

Ceramides draw wide attention as tumor suppressor lipids that act directly on mitochondria to trigger apoptotic cell death. However, molecular details of the underlying mechanism are largely unknown. Using a photoactivatable ceramide probe, we here identify the voltage-dependent anion channels VDAC1 and VDAC2 as mitochondrial ceramide binding proteins. Coarse-grain molecular dynamics simulations reveal that both channels harbor a ceramide binding site on one side of the barrel wall. This site includes a membrane-buried glutamate that mediates direct contact with the ceramide head group. Substitution or chemical modification of this residue abolishes photolabeling of both channels with the ceramide probe. Unlike VDAC1 removal, loss of VDAC2 or replacing its membrane-facing glutamate with glutamine renders human colon cancer cells largely resistant to ceramide-induced apoptosis. Collectively, our data support a role of VDAC2 as direct effector of ceramide-mediated cell death, providing a molecular framework for how ceramides exert their anti-neoplastic activity.