---
title: "Two distinct anionic phospholipid-dependent events involved in SecA-mediated protein translocation"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Sabrina Koch, Marten Exterkate, Cesar A. López, Megha Patro, Siewert J. Marrink and Arnold J.M. Driessen"         # Paper authors (required)
year: "2019"           # Publication year (required)
publication: "Biochimica et Biophysica Acta (BBA)-Biomembranes"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bbamem.2019.183035"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Koch, S., Exterkate, M., López, C. A., Patro, M., Marrink, S. J., & Driessen, A. J. (2019). Two distinct anionic phospholipid-dependent events involved in SecA-mediated protein translocation. Biochimica et Biophysica Acta (BBA)-Biomembranes, 1861(11), 183035.

## Abstract

Protein translocation across the bacterial cytoplasmic membrane is an essential process catalyzed by the Sec translocase, which in its minimal form consists of the protein-conducting channel SecYEG, and the motor ATPase SecA. SecA binds via its positively charged N-terminus to membranes containing anionic phospholipids, leading to a lipid-bound intermediate. This interaction induces a conformational change in SecA, resulting in a high-affinity association with SecYEG, which initiates protein translocation. Here, we examined the effect of anionic lipids on the SecA-SecYEG interaction in more detail, and discovered a second, yet unknown, anionic lipid-dependent event that stimulates protein translocation. Based on molecular dynamics simulations we identified an anionic lipid-enriched region in vicinity of the lateral gate of SecY. Here, the anionic lipid headgroup accesses the lateral gate, thereby stabilizing the pre-open state of the channel. The simulations suggest flip-flop movement of phospholipid along the lateral gate. Electrostatic contribution of the anionic phospholipids at the lateral gate may directly stabilize positively charged residues of the signal sequence of an incoming preprotein. Such a mechanism allows for the correct positioning of the entrant peptide, thereby providing a long-sought explanation for the role of anionic lipids in signal sequence folding during protein translocation.