---
title: "Gangliosides Destabilize Lipid Phase Separation in Multicomponent Membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Yang Liu, Jonathan Barnoud, and Siewert J. Marrink"         # Paper authors (required)
year: "2019"           # Publication year (required)
publication: "Biophysical Journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2019.08.037"            # URL of DOI (required)  
materials: "https://www.sciencedirect.com/science/article/pii/S0006349519307544#app2"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Liu, Y., Barnoud, J., & Marrink, S. J. (2019). Gangliosides destabilize lipid phase separation in multicomponent membranes. Biophysical Journal, 117(7), 1215-1223.

## Abstract

Gangliosides (GMs) form an important class of lipids found in the outer leaflet of the plasma membrane. Typically, they colocalize with cholesterol and sphingomyelin in ordered membrane domains. However, detailed understanding of the lateral organization of GM-rich membranes is still lacking. To gain molecular insight, we performed molecular dynamics simulations of GMs in model membranes composed of coexisting liquid-ordered and liquid-disordered domains. We found that GMs indeed have a preference to partition into the ordered domains. At higher concentrations (>10 mol %), we observed a destabilizing effect of GMs on the phase coexistence. Further simulations with modified GMs show that the structure of the GM headgroup affects the phase separation, whereas the nature of the tail determines the preferential location. Together, our findings provide a molecular basis to understand the lateral organization of GM-rich membranes.