---
title: "Computational Modeling of Realistic Cell Membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Siewert J. Marrink, Valentina Corradi, Paulo C.T. Souza, Helgi I. Ingólfsson, D. Peter Tieleman, and Mark S.P. Sansom"         # Paper authors (required)
year: "2019"           # Publication year (required)
publication: "Chemical Reviews"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.chemrev.8b00460"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Lipid membranes
  - Vesicles
  - Proteins
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Marrink, S. J., Corradi, V., Souza, P. C., Ingolfsson, H. I., Tieleman, D. P., & Sansom, M. S. (2019). Computational modeling of realistic cell membranes. Chemical reviews, 119(9), 6184-6226.

## Abstract

Cell membranes contain a large variety of lipid types and are crowded with proteins, endowing them with the plasticity needed to fulfill their key roles in cell functioning. The compositional complexity of cellular membranes gives rise to a heterogeneous lateral organization, which is still poorly understood. Computational models, in particular molecular dynamics simulations and related techniques, have provided important insight into the organizational principles of cell membranes over the past decades. Now, we are witnessing a transition from simulations of simpler membrane models to multicomponent systems, culminating in realistic models of an increasing variety of cell types and organelles. Here, we review the state of the art in the field of realistic membrane simulations and discuss the current limitations and challenges ahead.