---
title: "Serine Phosphorylation of L-Selectin Regulates ERM Binding, Clustering, and Monocyte Protrusion in Transendothelial Migration"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Abigail Newe, Karolina Rzeniewicz, Melanie König, Carsten F. E. Schroer, Justin Joachim, Angela Rey-Gallardo, Siewert J. Marrink, Jürgen Deka, Maddy Parsons and Aleksandar Ivetic"         # Paper authors (required)
year: "2019"           # Publication year (required)
publication: ""    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.3389/fimmu.2019.02227"            # URL of DOI (required)  
materials: "https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2019.02227/full#h11"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Newe, A., Rzeniewicz, K., König, M., Schroer, C. F., Joachim, J., Rey-Gallardo, A., ... & Ivetic, A. (2019). Serine phosphorylation of L-selectin regulates ERM binding, clustering, and monocyte protrusion in transendothelial migration. Frontiers in Immunology, 10, 2227.

## Abstract

The migration of circulating leukocytes toward damaged tissue is absolutely fundamental to the inflammatory response, and transendothelial migration (TEM) describes the first cellular barrier that is breached in this process. Human CD14+ inflammatory monocytes express L-selectin, bestowing a non-canonical role in invasion during TEM. In vivo evidence supports a role for L-selectin in regulating TEM and chemotaxis, but the intracellular mechanism is poorly understood. The ezrin-radixin-moesin (ERM) proteins anchor transmembrane proteins to the cortical actin-based cytoskeleton and additionally act as signaling adaptors. During TEM, the L-selectin tail within transmigrating pseudopods interacts first with ezrin to transduce signals for protrusion, followed by moesin to drive ectodomain shedding of L-selectin to limit protrusion. Collectively, interaction of L-selectin with ezrin and moesin fine-tunes monocyte protrusive behavior in TEM. Using FLIM/FRET approaches, we show that ERM binding is absolutely required for outside-in L-selectin clustering. The cytoplasmic tail of human L-selectin contains two serine (S) residues at positions 364 and 367, and here we show that they play divergent roles in regulating ERM binding. Phospho-S364 blocks direct interaction with ERM, whereas molecular modeling suggests phospho-S367 likely drives desorption of the L-selectin tail from the inner leaflet of the plasma membrane to potentiate ERM binding. Serine-to-alanine mutagenesis of S367, but not S364, significantly reduced monocyte protrusive behavior in TEM under flow conditions. Our data propose a model whereby L-selectin tail desorption from the inner leaflet of the plasma membrane and ERM binding are two separable steps that collectively regulate protrusive behavior in TEM.