---
title: "A Multi-Scale Approach to Membrane Remodeling Processes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Weria Pezeshkian, Melanie König, Siewert J. Marrink and John H. Ipsen"         # Paper authors (required)
year: "2019"           # Publication year (required)
publication: "Frontiers in molecular biosciences"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.3389/fmolb.2019.00059"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Lipid membranes
  - Multi-scale
  - Vesicles
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Pezeshkian, W., König, M., Marrink, S. J., & Ipsen, J. H. (2019). A multi-scale approach to membrane remodeling processes. Frontiers in molecular biosciences, 6, 59.

## Abstract

We present a multi-scale simulation procedure to describe membrane-related biological processes that span over a wide range of length scales. At macroscopic length-scale, a membrane is described as a flexible thin film modeled by a dynamic triangulated surface with its spatial conformations governed by an elastic energy containing only a few model parameters. An implicit protein model allows us to include complex effects of membrane-protein interactions in the macroscopic description. The gist of this multi-scale approach is a scheme to calibrate the implicit protein model using finer scale simulation techniques e.g., all atom and coarse grain molecular dynamics. We previously used this approach and properly described the formation of membrane tubular invaginations upon binding of B-subunit of Shiga toxin. Here, we provide a perspective of our multi-scale approach, summarizing its main features and sketching possible routes for future development.