---
title: "Nucleation Mechanisms of Self-Assembled Physisorbed Monolayers on Graphite"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Tomasz K. Piskorz, Cristian Gobbo, Siewert J. Marrink, Steven De Feyter, Alex H. de Vries, and Jan H. van Esch"         # Paper authors (required)
year: "2019"           # Publication year (required)
publication: "The Journal of Physical Chemistry C"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jpcc.9b01234"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/abs/10.1021/acs.jpcc.9b01234"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Materials science
  - Small molecules
  - Self-assembly
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Piskorz, T. K., Gobbo, C., Marrink, S. J., De Feyter, S., De Vries, A. H., & Van Esch, J. H. (2019). Nucleation mechanisms of self-assembled physisorbed monolayers on graphite. The Journal of Physical Chemistry C, 123(28), 17510-17520.

## Abstract

Coarse-grained molecular dynamics simulations are employed to obtain a detailed view of the formation of long-range ordered lamellar structures of physisorbed self-assembling long functionalized alkanes on graphite. During the self-assembly, two processes take place: Langmuir preferential adsorption and rearrangement on the surface. The rearrangement starts with nucleation, in which molecules create an ordered domain. The nucleation mechanism is temperature dependent. At lower temperature independent, small and stable nuclei seed the emergence of long-range ordered domains. In contrast, at a higher temperature, molecules adsorb on the surface, and only when a certain level of surface coverage by the adsorbent is reached, the whole structure undergoes a transition from a liquid-like structure to an ordered structure. After this step, relatively slow corrections of the structure take place by Ostwald ripening.