---
title: "An Allosteric Pathway in Copper, Zinc Superoxide Dismutase Unravels the Molecular Mechanism of the G93A Amyotrophic Lateral Sclerosis-Linked Mutation"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Paulo C. T. Souza, Sebastian Thallmair, Siewert J. Marrink, and Raúl Mera-Adasme"         # Paper authors (required)
year: "2019"           # Publication year (required)
publication: "The journal of physical chemistry letters"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/acs.jpclett.9b02868"            # URL of DOI (required)  
materials: "https://pubs.acs.org/doi/10.1021/acs.jpclett.9b02868?goto=supporting-info"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Multi-scale
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Souza, P. C., Thallmair, S., Marrink, S. J., & Mera-Adasme, R. (2019). An allosteric pathway in copper, zinc superoxide dismutase unravels the molecular mechanism of the G93A amyotrophic lateral sclerosis-linked mutation. The journal of physical chemistry letters, 10(24), 7740-7744.

## Abstract

Several different mutations of the protein copper, zinc superoxide dismutase (SOD1) produce the neurodegenerative disorder amyotrophic lateral sclerosis (ALS). The molecular mechanism by which the diverse mutations converge to a similar pathology is currently unknown. The electrostatic loop (EL) of SOD1 is known to be affected in all of the studied ALS-linked mutations of SOD1. In this work, we employ a multiscale simulation approach to show that this perturbation corresponds to an increased probability of the EL detaching from its native position, exposing the metal site of the protein to water. From extensive atomistic and coarse-grained molecular dynamics (MD) simulations, we identify an allosteric pathway that explains the action of the distant G93A mutation on the EL. Finally, we employ quantum mechanics/molecular mechanics MD simulations to show that the opening of the EL decreases the Zn(II) affinity of the protein. As the loss of Zn(II) is at the center of several proposed pathogenic mechanisms in SOD1-linked ALS, the structural effect identified here not only is in agreement with the experimental data but also places the opening of the electrostatic loop as the possible main pathogenic effect for a significant number of ALS-linked SOD1 mutations.