---
title: "Lipid Fingerprints and Cofactor Dynamics of Light Harvesting Complex II in Different Membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Sebastian Thallmair, Petteri A. Vainikka, and Siewert J. Marrink"         # Paper authors (required)
year: "2019"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2019.03.009"            # URL of DOI (required)  
materials: "https://www.sciencedirect.com/science/article/pii/S000634951930195X#app2"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
  - Cofactors
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Thallmair, S., Vainikka, P. A., & Marrink, S. J. (2019). Lipid fingerprints and cofactor dynamics of light-harvesting complex II in different membranes. Biophysical journal, 116(8), 1446-1455.

## Abstract

Plant light-harvesting complex II (LHCII) is the key antenna complex for plant photosynthesis. We present coarse-grained molecular dynamics simulations of monomeric and trimeric LHCII in a realistic thylakoid membrane environment based on the Martini force field. The coarse-grained protein model has been optimized with respect to atomistic reference simulations. Our simulations provide detailed insights in the thylakoid lipid fingerprint of LHCII which compares well with experimental data from membrane protein purification. Comparing the monomer and trimeric LHCII reveals a stabilizing effect of trimerization on the chromophores as well as the protein. Moreover, the average chromophore distance shortens in the trimer leading to stronger excitonic couplings. When changing the native thylakoid environment to a model membrane the protein flexibility remains constant, whereas the chromophore flexibility is reduced. Overall, the presented LHCII model lays the foundation to investigate the μs dynamics of this key antenna protein of plants.