---
title: "SWINGER: a clustering algorithm for concurrent coupling of atomistic and supramolecular liquids"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Julija Zavadlav, Siewert J Marrink, Matej Praprotnik"         # Paper authors (required)
year: "2019"           # Publication year (required)
publication: "Interface focus"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1098/rsfs.2018.0075"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Multi-scale
  - Solvents
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Zavadlav, J., Marrink, S. J., & Praprotnik, M. (2019). SWINGER: a clustering algorithm for concurrent coupling of atomistic and supramolecular liquids. Interface Focus, 9(3), 20180075.

## Abstract

In this contribution, we review recent developments and applications of a dynamic clustering algorithm SWINGER tailored for the multiscale molecular simulations of biomolecular systems. The algorithm on-the-fly redistributes solvent molecules among supramolecular clusters. In particular, we focus on its applications in combination with the adaptive resolution scheme, which concurrently couples atomistic and coarse-grained molecular representations. We showcase the versatility of our multiscale approach on a few applications to biomolecular systems coupling atomistic and supramolecular water models such as the well-established MARTINI and dissipative particle dynamics models and provide an outlook for future work.