---
title: "Molecular Structure of Membrane Tethers"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Svetlana Baoukina, Siewert J. Marrink, and D. Peter Tieleman"         # Paper authors (required)
year: "2012"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2012.03.048"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Baoukina, S., Marrink, S. J., & Tieleman, D. P. (2012). Molecular structure of membrane tethers. Biophysical journal, 102(8), 1866-1871.

## Abstract

Membrane tethers are nanotubes formed by a lipid bilayer. They play important functional roles in cell biology and provide an experimental window on lipid properties. Tethers have been studied extensively in experiments and described by theoretical models, but their molecular structure remains unknown due to their small diameters and dynamic nature. We used molecular dynamics simulations to obtain molecular-level insight into tether formation. Tethers were pulled from single-component lipid bilayers by application of an external force to a lipid patch along the bilayer normal or by lateral compression of a confined bilayer. Tether development under external force proceeded by viscoelastic protrusion followed by viscous lipid flow. Weak forces below a threshold value produced only a protrusion. Larger forces led to a crossover to tether elongation, which was linear at a constant force. Under lateral compression, tethers formed from undulations of unrestrained bilayer area. We characterized in detail the tether structure and its formation process, and obtained the material properties of the membrane. To our knowledge, these results provide the first molecular view of membrane tethers.