---
title: "In Silico Design of Robust Bolalipid Membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Monica Bulacu, Xavier Périole, and Siewert J. Marrink"         # Paper authors (required)
year: "2012"           # Publication year (required)
publication: "Biomacromolecules"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/bm201454j"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Bulacu, M., Périole, X., & Marrink, S. J. (2012). In silico design of robust bolalipid membranes. Biomacromolecules, 13(1), 196-205.

## Abstract

The robustness of microorganisms used in industrial fermentations is essential for the efficiency and yield of the production process. A viable tool to increase the robustness is through engineering of the cell membrane and especially by incorporating lipids from species that survive under harsh conditions. Bolalipids are tetraether lipids found in Archaea bacteria, conferring stability to these bacteria by spanning across the cytoplasmic membrane. Here we report on in silico experiments to characterize and design optimal bolalipid membranes in terms of robustness. We use coarse-grained molecular dynamics simulations to study the structure, dynamics, and stability of membranes composed of model bolalipids, consisting of two dipalmitoylphosphatidylcholine (DPPC) lipids covalently linked together at either one or both tail ends. We find that bolalipid membranes differ substantially from a normal lipid membrane, with an increase in thickness and tail order, an increase in the gel-to-liquid crystalline phase transition temperature, and a decrease in diffusivity of the lipids. By changing the flexibility of the linker between the lipid tails, we furthermore show how the membrane properties can be controlled. A stiffer linker increases the ratio between spanning and looping conformations, rendering the membrane more rigid. Our study may help in designing artificial membranes, with tunable properties, able to function under extreme conditions. As an example, we show that incorporation of bolalipids makes the membrane more tolerant toward butanol.