---
title: "Structural Investigation of MscL Gating Using Experimental Data and Coarse Grained MD Simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Evelyne Deplazes, Martti Louhivuori, Dylan Jayatilaka, Siewert J. Marrink, and Ben Corry"         # Paper authors (required)
year: "2012"           # Publication year (required)
publication: "PLoS Computational Biology"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1371/journal.pcbi.1002683"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Deplazes, E., Louhivuori, M., Jayatilaka, D., Marrink, S. J., & Corry, B. (2012). Structural investigation of MscL gating using experimental data and coarse grained MD simulations.

## Abstract

The mechanosensitive channel of large conductance (MscL) has become a model system in which to understand mechanosensation, a process involved in osmoregulation and many other physiological functions. While a high resolution closed state structure is available, details of the open structure and the gating mechanism remain unknown. In this study we combine coarse grained simulations with restraints from EPR and FRET experiments to study the structural changes involved in gating with much greater level of conformational sampling than has previously been possible. We generated a set of plausible open pore structures that agree well with existing open pore structures and gating models. Most interestingly, we found that membrane thinning induces a kink in the upper part of TM1 that causes an outward motion of the periplasmic loop away from the pore centre. This previously unobserved structural change might present a new mechanism of tension sensing and might be related to a functional role in osmoregulation.