---
title: "Transmembrane helices can induce domain formation in crowded model membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Jan Domański, Siewert J. Marrink, and Lars V. Schäfer"         # Paper authors (required)
year: "2012"           # Publication year (required)
publication: "Biochimica et Biophysica Acta (BBA)-Biomembranes"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bbamem.2011.08.021"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Domański, J., Marrink, S. J., & Schäfer, L. V. (2012). Transmembrane helices can induce domain formation in crowded model membranes. Biochimica et Biophysica Acta (BBA)-Biomembranes, 1818(4), 984-994.

## Abstract

We studied compositionally heterogeneous multi-component model membranes comprised of saturated lipids, unsaturated lipids, cholesterol, and α-helical TM protein models using coarse-grained molecular dynamics simulations. Reducing the mismatch between the length of the saturated and unsaturated lipid tails reduced the driving force for segregation into liquid-ordered (lo) and liquid-disordered (ld) lipid domains. Cholesterol depletion had a similar effect, and binary lipid mixtures without cholesterol did not undergo large-scale phase separation under the simulation conditions. The phase-separating ternary dipalmitoyl-phosphatidylcholine (DPPC)/dilinoleoyl-PC (DLiPC)/cholesterol bilayer was found to segregate into lo and ld domains also in the presence of a high concentration of ΤΜ helices. The ld domain was highly crowded with TM helices (protein-to-lipid ratio ~ 1:5), slowing down lateral diffusion by a factor of 5–10 as compared to the dilute case, with anomalous (sub)-diffusion on the μs time scale. The membrane with the less strongly unsaturated palmitoyl-linoleoyl-PC instead of DLiPC, which in the absence of TM α-helices less strongly deviated from ideal mixing, could be brought closer to a miscibility critical point by introducing a high concentration of TM helices. Finally, the 7-TM protein bacteriorhodopsin was found to partition into the ld domains irrespective of hydrophobic matching. These results show that it is possible to directly study the lateral reorganization of lipids and proteins in compositionally heterogeneous and crowded model biomembranes with coarse-grained molecular dynamics simulations, a step toward simulations of realistic, compositionally complex cellular membranes. This article is part of a Special Issue entitled: Protein Folding in Membranes.