---
title: "Molecular View of the Role of Fusion Peptides in Promoting Positive Membrane Curvature"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Marc Fuhrmans and Siewert J. Marrink"         # Paper authors (required)
year: "2012"           # Publication year (required)
publication: "Journal of the American Chemical Society"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/ja207290b"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Fuhrmans, M., & Marrink, S. J. (2012). Molecular view of the role of fusion peptides in promoting positive membrane curvature. Journal of the American Chemical Society, 134(3), 1543-1552.

## Abstract

Fusion peptides are moderately hydrophobic segments of viral and nonviral membrane fusion proteins that enable these proteins to fuse two closely apposed biological membranes. In vitro assays furthermore show that even isolated fusion peptides alone can support membrane fusion in model systems. In addition, the fusion peptides have a distinct effect on the phase diagram of lipid mixtures. Here, we present molecular dynamics simulations investigating the effect of a particular fusion peptide, the influenza hemagglutinin fusion peptide and some of its mutants, on the lipid phase diagram. We detect a systematic shift toward phases with more positive mean curvature in the presence of the peptides, as well as an occurrence of bicontinuous cubic phases, which indicates a stabilization of Gaussian curvature. The wild-type fusion peptide has a stronger effect on the phase behavior as compared to the mutants, which we relate to its boomerang shape. Our results point to a different role of fusion peptides than hitherto assumed, the stabilization of pores rather than stalks along the fusion pathway.