---
title: "Line-Tension Controlled Mechanism for Influenza Fusion"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Herre Jelger Risselada, Giovanni Marelli, Marc Fuhrmans, Yuliya G. Smirnova, Helmut Grubmüller, Siewert Jan Marrink, and Marcus Müller"         # Paper authors (required)
year: "2012"           # Publication year (required)
publication: "PLoS One"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1371/journal.pone.0038302"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Risselada, H. J., Marelli, G., Fuhrmans, M., Smirnova, Y. G., Grubmüller, H., Marrink, S. J., & Müller, M. (2012). Line-tension controlled mechanism for influenza fusion. PLoS One, 7(6), e38302.

## Abstract

Our molecular simulations reveal that wild-type influenza fusion peptides are able to stabilize a highly fusogenic pre-fusion structure, i.e. a peptide bundle formed by four or more trans-membrane arranged fusion peptides. We rationalize that the lipid rim around such bundle has a non-vanishing rim energy (line-tension), which is essential to (i) stabilize the initial contact point between the fusing bilayers, i.e. the stalk, and (ii) drive its subsequent evolution. Such line-tension controlled fusion event does not proceed along the hypothesized standard stalk-hemifusion pathway. In modeled influenza fusion, single point mutations in the influenza fusion peptide either completely inhibit fusion (mutants G1V and W14A) or, intriguingly, specifically arrest fusion at a hemifusion state (mutant G1S). Our simulations demonstrate that, within a line-tension controlled fusion mechanism, these known point mutations either completely inhibit fusion by impairing the peptide’s ability to stabilize the required peptide bundle (G1V and W14A) or stabilize a persistent bundle that leads to a kinetically trapped hemifusion state (G1S). In addition, our results further suggest that the recently discovered leaky fusion mutant G13A, which is known to facilitate a pronounced leakage of the target membrane prior to lipid mixing, reduces the membrane integrity by forming a ‘super’ bundle. Our simulations offer a new interpretation for a number of experimentally observed features of the fusion reaction mediated by the prototypical fusion protein, influenza hemagglutinin, and might bring new insights into mechanisms of other viral fusion reactions.