---
title: Martini workshop lectures
format: html
---

</br>

### MARTINI WORKSHOP 2017 
(Groningen, The Netherlands)
<hr>

#### Monday, August 21

- Introduction to the Martini model, Siewert Jan Marrink [slides](http://cgmartini.nl/images/stories/WORKSHOP2017/lecture-01.pdf)

- Lipid biophysics with the Martini model, Helgi Ingólfsson [slides](http://cgmartini.nl/images/stories/WORKSHOP2017/lecture-02.pdf)

 

#### Tuesday, August 22

- Martini model for proteins, Alex de Vries [slides](http://cgmartini.nl/images/stories/WORKSHOP2017/lecture-03.pdf)

- Peptide aggregation, Pim Frederix [slides](http://cgmartini.nl/images/stories/WORKSHOP2017/lecture-04.pdf)

- Photosystem II, Floris van Eerden [slides](http://cgmartini.nl/images/stories/WORKSHOP2017/lecture-05.pdf)

 

#### Wednesday, August 23

- TOOLS: martinize, martinate, insane, backward, daft, Tsjerk Wassenaar [slides](http://cgmartini.nl/images/stories/WORKSHOP2017/lecture-06.pdf)

- Advanced parameterization of Martini, Manuel Nuno Melo [slides](http://cgmartini.nl/images/stories/WORKSHOP2017/lecture-08.pdf)

- Multiscaling with Martini, Manuel Nuno Melo [slides](http://cgmartini.nl/images/stories/WORKSHOP2017/lecture-09.pdf)

 

#### Thursday, August 24

- The Martini model for DNA and RNA, Ignacio Faustino Plo [slides](http://cgmartini.nl/images/stories/WORKSHOP2017/lecture-10.pdf)

- Blends for organic photovoltaics, Riccardo Alessandri [slides](http://cgmartini.nl/images/stories/WORKSHOP2017/lecture-11.pdf)

- The future of Martini, Paulo Telles de Souza [slides](http://cgmartini.nl/images/stories/WORKSHOP2017/lecture-12.pdf)


</br>

### MARTINI WORKSHOP 2015 
(Groningen, The Netherlands)
<hr>
 
#### Monday, August 24

- Introduction to coarse-graining, Alex de Vries [slides](http://cgmartini.nl/images/stories/WORKSHOP2015/lecture-01.pdf)

- Introduction to the Martini model, Siewert Jan Marrink [slides](http://cgmartini.nl/images/stories/WORKSHOP2015/lecture-02.pdf)

#### Tuesday, August 25

- Lipid biophysics with the Martini model, Helgi Ingólfsson [slides](http://cgmartini.nl/images/stories/WORKSHOP2015/lecture-03.pdf)

- Martini model for proteins, Alex de Vries [slides](http://cgmartini.nl/images/stories/WORKSHOP2015/lecture-04.pdf)

#### Wednesday, August 26

- TOOLS: martinize, martinate, insane, backward, daft, Tsjerk Wassenaar [slides](http://cgmartini.nl/images/stories/WORKSHOP2015/lecture-05.pdf)

- Martini model for saccharides (includes also other polymers and dna), Siewert Jan Marrink [slides](http://cgmartini.nl/images/stories/WORKSHOP2015/lecture-06.pdf)

#### Thursday, August 27

- Advanced parameterization of Martini, Manuel Nuno Melo [slides](http://cgmartini.nl/images/stories/WORKSHOP2015/lecture-07.pdf)

- Multiscaling with Martini, Manuel Nuno Melo [slides](http://cgmartini.nl/images/stories/WORKSHOP2015/lecture-08.pdf)