---
title: <i class="fa-solid fa-ice-cream"></i> Carbohydrates
format: html
---

<hr>

Martini 2 parameters for some carbohydrates developed by the Martini community over the years are listed below with some usage clarifications and references for further description of these works.

### Martini 2.2 N-Glycans
<hr>

Topologies for Martini 2.2 glycans are available for download [here](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/carbohydrates/PARAMETERS.itp), courtesy of César López Bautista and co-workers. For further background reading, please see:

- **S. Chakraborty,   K. Wagh,   S. Gnanakaran,   C. A. López**. *Development of Martini 2.2 parameters for N-glycans: a case study of the HIV-1 Env glycoprotein dynamics.* Glycobiology, (doi: [10.1093/glycob/cwab017](https://doi.org/10.1093/glycob/cwab017))

### Common mono-/di-saccharides, and amylose.
<hr>

Topologies for Martini 2 mono-/di-saccharides and amylose are available for download [here](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/carbohydrates/martini_v2.0_sugars.itp). For further background reading, please see:

- **C.A. Lopez, A. Rzepiela, A.H. de Vries, L. Dijkhuizen, P.H. Hunenberger, S.J. Marrink**. *The MARTINI coarse-grained force field: Extension to carbohydrates* JCTC, (doi: [10.1021/ct900313w](https://doi.org/10.1021/ct900313w))

### Beta-cyclodextrin, Dimethyl-cyclodextrin and Hydroxypropyl-cyclodextrin
<hr>

Topologies for Martini 2 beta-cyclodextrin, dimethyl-cyclodextrin and hydroxypropyl-cyclodextrin are available for download [here](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/carbohydrates/cyclodextrin.tar). A new bead type must be incorporated for beta cyclodextrin, which is included in the `martini_v2.1_pc.itp` file. Beta cyclodextrin is represented as a dimer, since it is the prevalent type in solution. However it can be easily transformed into a monomer if necessary. For further background reading, please see:

- **López, C. A., de Vries, A. H., & Marrink, S. J.** Computational microscopy of cyclodextrin mediated cholesterol extraction from lipid model membranes. Scientific Reports, (doi: [10.1038/srep02071](http://doi.org/10.1038/srep02071))

<hr>
