---
title: <i class="fa-solid fa-cheese"></i> Lipidome
format: html
---

<hr>

Martini 2 lipid parameters are listed below according to their major categories. For explanation of the lipid naming schema and the Martini 2 lipid parameterization philosophy please see the [Martini 2 lipid details](martini_lipids_details.qmd) page. For further background reading on the Martini 2 lipidome, see:

- **T.A. Wassenaar, H.I. Ingólfsson, R.A. Böckmann, D.P. Tieleman, S.J. Marrink**. *Computational lipidomics with insane: a versatile tool for generating custom membranes for molecular simulations.* JCTC, 11:2144–2155, 2015. [abstract](http://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b00209)

**References to these works can be found in the headers of the corresponding `.itp` files.**

----------------------------------------------------------------------

<style>
        .rotated-image {
            transform: rotate(90deg);
        }
    </style>    

### Phosphatidylcholine (PC)
<hr>

|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|	di-C08:0-C10:0 PC (DTPC)	   | [DTPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dtpc/DTPC-em.gro)   |  [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dtpc/martini_v2.0_DTPC_01.itp)   |  Not available    |
|   di-C12:0-C14:0 PC (DLPC)   |  [DLPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dlpc/DLPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dlpc/martini_v2.0_DLPC_01.itp) | CHARMM: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dlpc/DMPC.charmm36.map) <br> GROMOS: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dlpc/DMPC.gromos.map) |
|   di-C16:0-C18:0 PC (DPPC)   |  [DPPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dppc/DPPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dppc/martini_v2.0_DPPC_01.itp) <br> Alt optimal: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dppc/martini_v2.0_DPPC_01-alt-opt.itp) <br> Alt extensible: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dppc/martini_v2.0_DPPC_01-alt-ext.itp)| CHARMM: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dppc/DPPC.charmm36.map) <br> GROMOS: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dppc/DPPC.gromos.map) <br> AMBER: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dppc/DPPC.amber.map) |
|   di-C20:0-C22:0 PC (DBPC)   |  [DBPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dbpc/DBPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dbpc/martini_v2.0_DBPC_01.itp) | GROMOS: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dbpc/DBPC.gromos-alex.map) |
|   di-C12:1-C14:1 PC (DYPC)   |  [DYPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dypc/DYPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dypc/martini_v2.0_DYPC_01.itp) | Not available |
|   di-C16:1-C18:1 PC (DVPC)   |  [DVPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dvpc/DVPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dvpc/martini_v2.0_DVPC_01.itp) | Not available |
|   di-C16:1-C18:1 PC (DOPC)   |  [DOPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dopc/DOPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dopc/martini_v2.0_DOPC_02.itp) <br> Alt optimal: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dopc/martini_v2.0_DOPC_02-alt-opt.itp) <br> Alt extensible: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dopc/martini_v2.0_DOPC_02-alt-ext.itp)| CHARMM: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dopc/DOPC.charmm36.map) |
|   di-C16:2-C18:2 PC (DIPC)   |  [DIPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dipc/DIPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dipc/martini_v2.0_DIPC_01.itp) | Not available |
|   di-C16:3-C18:3 PC (DFPC)   |  [DFPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dfpc/DFPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dfpc/martini_v2.0_DFPC_01.itp) | Not available |
|   di-C20:1-C22:1 PC (DGPC)   |  [DGPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dgpc/DGPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dgpc/martini_v2.0_DGPC_01.itp) | Not available |
|   di-C20:4-C22:5 PC (DAPC)   |  [DAPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dapc/DAPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dapc/martini_v2.0_DAPC_02.itp) | Not available |
|   di-C24:6-C26:6 PC (DRPC)   |  [DRPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/drpc/DRPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/drpc/martini_v2.0_DRPC_01.itp) | Not available |
|   di-C24:1-C26:1 PC (DNPC)   |  [DNPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dnpc/DNPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/dnpc/martini_v2.0_DNPC_01.itp) | Not available |
|   C12:0/16:0 PC (LPPC)   |  [LPPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/lppc/LPPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/lppc/martini_v2.0_LPPC_01.itp) | Not available |
|   C16:0/18:1 PC (POPC)   |  [POPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/popc/POPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/popc/martini_v2.0_POPC_02.itp) | CHARMM: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/popc/POPC.charmm36.map) <br> GROMOS: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/popc/POPC.gromos-alex.map) |
|   C16:0/20:1 PC (PGPC)   |  [PGPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/pgpc/PGPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/pgpc/martini_v2.0_PGPC_01.itp) | Not available |
|   C16:0/20:2 PC (PEPC)|  [PEPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/pepc/PEPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/pepc/martini_v2.0_PEPC_01.itp) | Not available |
|   C16:0/18:2 PC (PIPC) |  [PIPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/pipc/PIPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/pipc/martini_v2.0_PIPC_01.itp) | Not available |
|   C16:0/20:4 PC (PAPC) |  [PAPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/papc/PAPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/papc/martini_v2.0_PAPC_01.itp) | Not available |
|   C16:0/22:6 PC (PUPC) |  [PUPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/pupc/PUPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/pupc/martini_v2.0_PUPC_01.itp) | Not available |
|   C16:0/24:6 PC (PRPC) |  [PRPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/prpc/PRPC-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pc/prpc/martini_v2.0_PRPC_01.itp) | Not available |

----------------------------------------------------------------------

### Phosphatidylethanolamine (PE)
<hr>

|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|  di-C08:0-C10:0 PE (DTPE)  |  [DTPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dtpe/DTPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dtpe/martini_v2.0_DTPE_01.itp) | Not available |
|  di-C12:0-C14:0 PE (DLPE)  |  [DLPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dlpe/DLPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dlpe/martini_v2.0_DLPE_01.itp) | Not available |
|   di-C16:0-C18:0 PE (DPPE) |  [DPPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dppe/DPPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dppe/martini_v2.0_DPPE_01.itp) | Not available |
|  di-C20:0-C22:0 PE (DBPE)  |  [DBPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dbpe/DBPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dbpe/martini_v2.0_DBPE_01.itp) | Not available |
|  di-C24:0-C26:0 PE (DXPE)  |  [DXPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dxpe/DXPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dxpe/martini_v2.0_DXPE_01.itp) | Not available |
|  di-C12:1-C14:1 PE (DYPE)  |  [DYPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dype/DYPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dype/martini_v2.0_DYPE_01.itp) | Not available |
|  di-C16:1-C18:1 PE (DVPE)  |  [DVPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dvpe/DVPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dvpe/martini_v2.0_DVPE_01.itp) | Not available |
|  di-C16:1-C18:1 PE (DOPE)  |  [DOPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dope/DOPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dope/martini_v2.0_DOPE_02.itp) | Not available |
|  di-C16:2-C18:2 PE (DIPE)  |  [DIPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dipe/DIPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dipe/martini_v2.0_DIPE_01.itp) | Not available |
|  di-C16:3-C18:3 PE (DFPE)  |  [DFPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dfpe/DFPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dfpe/martini_v2.0_DFPE_01.itp) | Not available |
|  di-C20:1-C22:1 PE (DGPE)  |  [DGPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dgpe/DGPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dgpe/martini_v2.0_DGPE_01.itp) | Not available |
|  di-C20:4-C22:5 PE (DAPE)  |  [DAPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dape/DAPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dape/martini_v2.0_DAPE_01.itp) | Not available |
|  di-C20:5-C22:6 PE (DUPE)  |  [DUPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dupe/DUPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dupe/martini_v2.0_DUPE_01.itp) | Not available |
|  di-C24:6-C26:6 PE (DRPE)  |  [DRPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/drpe/DRPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/drpe/martini_v2.0_DRPE_01.itp) | Not available |
|  di-C24:1-C26:1 PE (DNPE)  |  [DNPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dnpe/DNPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/dnpe/martini_v2.0_DNPE_01.itp) | Not available |
|  C12:0/16:0 PE (LPPE)  |  [LPPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/lppe/LPPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/lppe/martini_v2.0_LPPE_01.itp) | Not available |
|  C16:0/18:1 PE (POPE)  |  [POPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/pope/POPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/pope/martini_v2.0_POPE_02.itp) | Not available |
|  C16:0/20:1 PE (PGPE)  |  [PGPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/pgpe/PGPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/pgpe/martini_v2.0_PGPE_01.itp) | Not available |
|  C16:0/20:3 PE (PQPE)  |  [PQPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/pqpe/PQPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/pqpe/martini_v2.0_PQPE_01.itp) | Not available |
|  C16:0/18:2 PE (PIPE)  |  [PIPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/pipe/PIPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/pipe/martini_v2.0_PIPE_01.itp) | Not available |
|  C16:0/20:4 PE (PAPE)  |  [PAPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/pape/PAPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/pape/martini_v2.0_PAPE_01.itp) | Not available |
|  C16:0/22:6 PE (PUPE)  |  [PUPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/pupe/PUPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/pupe/martini_v2.0_PUPE_01.itp) | Not available |
|  C16:0/24:6 PE (PRPE)  |  [PRPE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/prpe/PRPE-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pe/prpe/martini_v2.0_PRPE_01.itp) | Not available |

----------------------------------------------------------------------

### Phosphatidylserine (PS)
<hr>

|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|  di-C08:0-C10:0 PS (DTPS)  |  [DTPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dtps/DTPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dtps/martini_v2.0_DTPS_01.itp) | Not available |
|  di-C12:0-C14:0 PS (DLPS)  |  [DLPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dlps/DLPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dlps/martini_v2.0_DLPS_01.itp) | Not available |
|  di-C16:0-C18:0 PS (DPPS)  |  [DPPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dpps/DPPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dpps/martini_v2.0_DPPS_01.itp) | Not available |
|  di-C20:0-C22:0 PS (DBPS)  |  [DBPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dbps/DBPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dbps/martini_v2.0_DBPS_01.itp) | Not available |
|  di-C24:0-C26:0 PS (DXPS)  |  [DXPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dxps/DXPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dxps/martini_v2.0_DXPS_01.itp) | Not available |
|  di-C12:1-C14:1 PS (DYPS)  |  [DYPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dyps/DYPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dyps/martini_v2.0_DYPS_01.itp) | Not available |
|  di-C16:1-C18:1 PS (DVPS)  |  [DVPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dvps/DVPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dvps/martini_v2.0_DVPS_01.itp) | Not available |
|  di-C16:1-C18:1 PS (DOPS)  |  [DOPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dops/DOPS-em.gro)|    [[itp]]() | Not available |
|  di-C16:2-C18:2 PS (DIPS)  |  [DIPS-em.gro]()|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dops/martini_v2.0_DOPS_02.itp) | Not available |
|  di-C16:3-C18:3 PS (DFPS)  |  [DFPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dfps/DFPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dfps/martini_v2.0_DFPS_01.itp) | Not available |
|  di-C20:1-C22:1 PS (DGPS)  |  [DGPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dgps/DGPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dgps/DGPS-em.gro) | Not available |
|  di-C20:4-C22:5 PS (DAPS)  |  [DAPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/daps/DAPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/daps/martini_v2.0_DAPS_01.itp) | Not available |
|  di-C20:5-C22:6 PS (DUPS)  |  [DUPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dups/DUPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/dups/martini_v2.0_DUPS_01.itp) | Not available |
|  di-C24:6-C26:6 PS (DRPS)  |  [DRPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/drps/DRPS-em.gro)|    [[itp]]() | Not available |
|  di-C24:1-C26:1 PS (DNPS)  |  [DNPS-em.gro]()|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/drps/martini_v2.0_DRPS_01.itp) | Not available |
|  C12:0/16:0 PS (LPPS)  |  [LPPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/lpps/LPPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/lpps/martini_v2.0_LPPS_01.itp) | Not available |
|  C16:0/18:1 PS (POPS) |  [POPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/pops/POPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/pops/martini_v2.0_POPS_02.itp) | Not available |
|  C16:0/20:1 PS (PGPS)  |  [PGPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/pgps/PGPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/pgps/martini_v2.0_PGPS_01.itp) | Not available |
|  C16:0/20:3 PS (PQPS)  |  [PQPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/pqps/PQPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/pqps/martini_v2.0_PQPS_01.itp) | Not available |
|  C16:0/18:2 PS (PIPS)  |  [PIPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/pips/PIPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/pips/martini_v2.0_PIPS_01.itp) | Not available |
|  C16:0/20:4 PS (PAPS)  |  [PAPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/paps/PAPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/paps/martini_v2.0_PAPS_01.itp) | Not available |
|  C16:0/22:6 PS (PUPS)  |  [PUPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/pups/PUPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/pups/martini_v2.0_PUPS_01.itp) | Not available |
|  C16:0/24:6 PS (PRPS)  |  [PRPS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/prps/PRPS-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/ps/prps/martini_v2.0_PRPS_01.itp) | Not available |

----------------------------------------------------------------------

### Phosphatidylglycerol (PG)
<hr>

|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|  di-C08:0-C10:0 PG (DTPG)  |  [DTPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dtpg/DTPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dtpg/martini_v2.0_DTPG_01.itp) | Not available |
|  di-C12:0-C14:0 PG (DLPG)  |  [DLPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dlpg/DLPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dlpg/martini_v2.0_DLPG_01.itp) | Not available |
|  di-C16:0-C18:0 PG (DPPG)  |  [DPPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dppg/DPPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dppg/martini_v2.0_DPPG_01.itp) | CHARMM: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dppg/DPPG.charmm36.map) |
|  di-C20:0-C22:0 PG (DBPG)  |  [DBPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dbpg/DBPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dbpg/martini_v2.0_DBPG_01.itp) | Not available |
|  di-C24:0-C26:0 PG (DXPG)  |  [DXPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dxpg/DXPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dxpg/martini_v2.0_DXPG_01.itp) | Not available |
|  di-C12:1-C14:1 PG (DYPG)  |  [DYPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dypg/DYPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dypg/martini_v2.0_DYPG_01.itp) | Not available |
|  di-C16:1-C18:1 PG (DVPG)  |  [DVPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dvpg/DVPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dvpg/martini_v2.0_DVPG_01.itp) | Not available |
|  di-C16:1-C18:1 PG (DOPG)  |  [DOPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dopg/DOPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dopg/martini_v2.0_DOPG_02.itp) | Not available |
|  di-C16:2-C18:2 PG (DIPG)  |  [DIPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dipg/DIPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dipg/martini_v2.0_DIPG_01.itp) | Not available |
|  di-C16:3-C18:3 PG (DFPG)  |  [DFPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dfpg/DFPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dfpg/DFPG-em.gro) | Not available |
|  di-C20:1-C22:1 PG (DGPG)  |  [DGPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dgpg/DGPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dgpg/martini_v2.0_DGPG_01.itp) | Not available |
|  di-C20:4-C22:5 PG (DAPG)  |  [DAPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dapg/DAPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dapg/martini_v2.0_DAPG_01.itp) | Not available |
|  di-C24:6-C26:6 PG (DRPG)  |  [DRPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/drpg/DRPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/drpg/martini_v2.0_DRPG_01.itp) | Not available |
|  di-C24:1-C26:1 PG (DNPG)  |  [DNPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dnpg/DNPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/dnpg/martini_v2.0_DNPG_01.itp) | Not available |
|  C12:0/16:0 PG (LPPG)      |  [LPPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/lppg/LPPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/lppg/martini_v2.0_LPPG_01.itp) | Not available |
|  C16:0/18:1 PG (POPG)      |  [POPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/popg/POPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/popg/martini_v2.0_POPG_02.itp) | Not available |
|  C16:0/20:1 PG (PGPG)      |  [PGPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/pgpg/PGPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/pgpg/martini_v2.0_PGPG_01.itp) | Not available |
|  C16:0/18:2 PG (PIPG)      |  [PIPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/pipg/PIPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/pipg/martini_v2.0_PIPG_01.itp) | Not available |
|  C16:0/20:4 PG (PAPG)      |  [PAPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/papg/PAPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/papg/martini_v2.0_PAPG_01.itp) | Not available |
|  C16:0/24:6 PG (PRPG)      |  [PRPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/prpg/PRPG-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/prpg/martini_v2.0_PRPG_01.itp) | Not available |
|  C18:1/16:0 PG (OPPG)      |  [OPPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/oppg/OPPG.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/oppg/martini_v2.0_OPPG_01.itp) | Not available |
|  C16:1(3t)/16:0 PG (JPPG)  |  [JPPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/jppg/JPPG.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/jppg/martini_v2.0_JPPG_01.itp) | Not available |
|  C16:1(3t)/18:3 PG (JFPG)  |  [JFPG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/jfpg/JFPG.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pg/jfpg/martini_v2.0_JFPG_01.itp) | Not available |

----------------------------------------------------------------------

### Phosphatidic acid (PA)
<hr>

|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|  di-C08:0-C10:0 PA (DTPA)  |  [DTPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dtpa/DTPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dtpa/martini_v2.0_DTPA_01.itp) | Not available |
|  di-C12:0-C14:0 PA (DLPA)  |  [DLPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dlpa/DLPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dlpa/martini_v2.0_DLPA_01.itp) | Not available |
|  di-C16:0-C18:0 PA (DPPA)  |  [DPPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dppa/DPPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dppa/martini_v2.0_DPPA_01.itp) | Not available |
|  di-C20:0-C22:0 PA (DBPA)  |  [DBPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dbpa/DBPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dbpa/martini_v2.0_DBPA_01.itp) | Not available |
|  di-C24:0-C26:0 PA (DXPA)  |  [DXPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dxpa/DXPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dxpa/martini_v2.0_DXPA_01.itp) | Not available |
|  di-C12:1-C14:1 PA (DYPA)  |  [DYPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dypa/DYPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dypa/martini_v2.0_DYPA_01.itp) | Not available |
|  di-C16:1-C18:1 PA (DVPA)  |  [DVPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dvpa/DVPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dvpa/martini_v2.0_DVPA_01.itp) | Not available |
|  di-C16:1-C18:1 PA (DOPA)  |  [DOPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dopa/DOPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dopa/martini_v2.0_DOPA_01.itp) | Not available |
|  di-C16:2-C18:2 PA (DIPA)  |  [DIPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dipa/DIPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dipa/martini_v2.0_DIPA_01.itp) | Not available |
|  di-C16:3-C18:3 PA (DFPA)  |  [DFPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dfpa/DFPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dfpa/martini_v2.0_DFPA_01.itp) | Not available |
|  di-C20:1-C22:1 PA (DGPA)  |  [DGPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dgpa/DGPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dgpa/martini_v2.0_DGPA_01.itp) | Not available |
|  di-C20:4-C22:5 PA (DAPA)  |  [DAPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dgpa/martini_v2.0_DGPA_01.itp)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dapa/martini_v2.0_DAPA_01.itp) | Not available |
|  di-C24:6-C26:6 PA (DRPA)  |  [DRPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/drpa/DRPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/drpa/martini_v2.0_DRPA_01.itp) | Not available |
|  di-C24:1-C26:1 PA (DNPA)  |  [DNPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dnpa/DNPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/dnpa/martini_v2.0_DNPA_01.itp) | Not available |
|  C12:0/16:0 PA (LPPA)      |  [LPPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/lppa/LPPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/lppa/martini_v2.0_LPPA_01.itp) | Not available |
|  C16:0/18:1 PA (POPA)      |  [POPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/popa/POPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/popa/martini_v2.0_POPA_01.itp) | Not available |
|  C16:0/20:1 PA (PGPA)      |  [PGPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/pgpa/PGPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/pgpa/martini_v2.0_PGPA_01.itp) | Not available |
|  C16:0/18:2 PA (PIPA)      |  [PIPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/pipa/PIPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/pipa/martini_v2.0_PIPA_01.itp) | Not available |
|  C16:0/20:4 PA (PAPA)      |  [PAPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/papa/PAPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/papa/martini_v2.0_PAPA_01.itp) | Not available |
|  C16:0/22:6 PA (PUPA)      |  [PUPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/pupa/PUPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/pupa/martini_v2.0_PUPA_01.itp) | Not available |
|  C16:0/24:6 PA (PRPA)      |  [PRPA-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/prpa/PRPA-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pa/prpa/martini_v2.0_PRPA_01.itp) | Not available |

----------------------------------------------------------------------

### Phosphatidylinositols
<hr>

<center> <h4><span style="color:gray; size=18">Phosphatidylinositol (PI)</span></h4> </center>
|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|    di-C16:0-C18:0 PI (DPPI)    |  [DPPI-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/dppi/DPPI-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/dppi/martini_v2.0_DPPI_01.itp) | Not available |
|    C16:0/18:1 (PVPI)           |  [PVPI-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pvpi/PVPI-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pvpi/martini_v2.0_PVPI_01.itp) | Not available |
|    C16:0/18:1 PI (POPI)        |  [POPI-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/popi/POPI-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/popi/martini_v2.0_POPI_01.itp) | Not available |
|    C16:0/18:2 PI (PIPI)        |  [PIPI-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pipi/PIPI-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pipi/martini_v2.0_PIPI_01.itp) | Not available |
|    C16:0/20:4 PI (PAPI)        |  [PAPI-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/papi/PAPI-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/papi/martini_v2.0_PAPI_01.itp) | Not available |
|    C16:0/22:6 PI (PUPI)        |  [PUPI-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pupi/PUPI-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pupi/martini_v2.0_PUPI_01.itp) | Not available |

<center> <h4><span style="color:gray; size=18">Phosphatidylinositol phosphate (PIP1)</span></h4> </center>
|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|    di-C16:0-C18:0 PIP (DPP1)   |  [DPP1-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/dpp1/DPP1-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/dpp1/martini_v2.0_DPP1_01.itp) | Not available |
|    C16:0/18:1 PIP (PVP1)       |  [PVP1-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pvp1/PVP1-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pvp1/martini_v2.0_PVP1_01.itp) | Not available |
|    C16:0/18:1 PIP (POP1)       |  [POP1-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pop1/POP1-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pop1/martini_v2.0_POP1_01.itp) | Not available |

<center> <h4><span style="color:gray; size=18">Phosphatidylinositol bisphosphate (PIP2)</span></h4> </center>
|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|    di-C16:0-C18:0 PIP2 (DPP2)   |  [DPP2-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/dpp2/DPP2-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/dpp2/martini_v2.0_DPP2_01.itp) | Not available |
|    C16:0/18:1 PIP2 (PVP2)       |  [PVP2-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pvp2/PVP2-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pvp2/martini_v2.0_PVP2_01.itp) | Not available |
|    C16:0/18:1 PIP2 (POP2)       |  [POP2-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pop2/POP2-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pop2/martini_v2.0_POP2_01.itp) | Not available |

<center> <h4><span style="color:gray; size=18">Phosphatidylinositol trisphosphate (PIP3)</span></h4> </center>
|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|    C16:0/18:1 PIP3 (PVP3)|  [PVP3-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pvp3/PVP3-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pvp3/martini_v2.0_PVP3_01.itp) | Not available |
|    C16:0/18:1 PIP3 (POP3) | [POP3-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pop3/POP3-em.gro)|    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/pi/pop3/martini_v2.0_POP3_01.itp) | Not available |

----------------------------------------------------------------------

### Glycerols
<hr>

<center> <h4><span style="color:gray; size=18">Diacylglycerol (DAG)</span></h4> </center>
|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|  C16:0/18:1 DAG (PVDG)  |  [PVDG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/glycerols/pvdg/PVDG-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/glycerols/pvdg/martini_v2.0_PVDG_01.itp) | Not available |
|  C16:0/18:1 DAG (PODG)  |  [PODG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/glycerols/podg/PODG-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/glycerols/podg/martini_v2.0_PODG_01.itp) | Not available |
|  C16:0/18:2 DAG (PIDG)  |  [PIDG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/glycerols/pidg/PIDG-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/glycerols/pidg/martini_v2.0_PIDG_01.itp) | Not available |
|  C16:0/20:4 DAG (PADG)  |  [PADG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/glycerols/padg/PADG-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/glycerols/padg/martini_v2.0_PADG_01.itp) | Not available |
|  C16:0/22:6 DAG (PUDG)  |  [PUDG-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/glycerols/pudg/PUDG-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/glycerols/pudg/martini_v2.0_PUDG_01.itp) | Not available |

<center> <h4><span style="color:gray; size=18">Triacylglycerol (TAG)</span></h4> </center>
|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|  Glyceryl-trioleate  |  Not available    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/glycerols/tog/martini_v2.0_TOG_01.itp) | Not available |

----------------------------------------------------------------------

### Lysophosphatidylcholine (LPC)
<hr>

|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|  C04:0-C06:0 LPC (CPC)  |  [CPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/cpc/CPC-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/cpc/martini_v2.0_CPC_01.itp) | Not available |
|  C08:0-C10:0 LPC (TPC)  |  [TPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/tpc/TPC-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/tpc/martini_v2.0_TPC_01.itp) | Not available |
|  C12:0-C14:0 LPC (LPC)  |  [LPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/lpc/LPC-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/lpc/martini_v2.0_LPC_01.itp) | Not available |
|  C16:0-C18:0 LPC (PPC)  |  [PPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/ppc/PPC-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/ppc/martini_v2.0_PPC_02.itp) | Not available |
|  C16:1-C18:1 LPC (VPC)  |  [VPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/vpc/VPC-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/vpc/martini_v2.0_VPC_01.itp) | Not available |
|  C16:1-C18:1 LPC (OPC)  |  [OPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/opc/OPC-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/opc/martini_v2.0_OPC_01.itp) | Not available |
|  C16:2-C18:2 LPC (IPC)  |  [IPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/ipc/IPC-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/ipc/martini_v2.0_IPC_01.itp) | Not available |
|  C20:4-C22:5 LPC (APC)  |  [APC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/apc/APC-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/apc/martini_v2.0_APC_01.itp) | Not available |
|  C20:5-C22:6 LPC (UPC)  |  [UPC-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/upc/UPC-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/lpc/upc/martini_v2.0_UPC_01.itp) | Not available |

----------------------------------------------------------------------

### Sphingomyelin (SM)
<hr>

|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|  C(d18:1/18:0) SM (DPSM)  |  [DPSM-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/dpsm/DPSM-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/dpsm/martini_v2.0_DPSM_01.itp) | Not available |
|  C(d20:1/20:0) SM (DBSM)  |  [DBSM-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/dbsm/DBSM-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/dbsm/martini_v2.0_DBSM_01.itp) | Not available |
|  C(d24:1/24:0) SM (DXSM)  |  [DXSM-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/dxsm/DXSM-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/dxsm/martini_v2.0_DXSM_01.itp) | Not available |
|  C(d18:1/18:1) SM (PVSM)  |  [PVSM-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/pvsm/PVSM-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/pvsm/martini_v2.0_PVSM_01.itp) | Not available |
|  C(d18:1/18:1) SM (POSM)  |  [POSM-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/posm/POSM-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/posm/martini_v2.0_POSM_01.itp) | Not available |
|  C(d18:1/22:1) SM (PGSM)  |  [PGSM-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/pgsm/PGSM-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/pgsm/martini_v2.0_PGSM_01.itp) | Not available |
|  C(d18:1/24:1) SM (PNSM)  |  [PNSM-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/pnsm/PNSM-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/pnsm/PNSM-em.gro) | Not available |
|  C(d20:1/24:1) SM (BNSM)  |  [BNSM-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/bnsm/BNSM-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/bnsm/BNSM-em.gro) | Not available |
|  C(d24:1/24:1) SM (XNSM)  |  [XNSM-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/xnsm/XNSM-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sm/xnsm/martini_v2.0_XNSM_01.itp) | Not available |

----------------------------------------------------------------------

### Ceramide (CER)
<hr>

|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|  C(d18:1/18:0) CER (DPCE)  |  [DPCE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/cer/dpce/DPCE-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/cer/dpce/martini_v2.0_DPCE_01.itp) | Not available |
|  C(d24:1/24:0) CER (DXCE)  |  [DXCE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/cer/dxce/DXCE-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/cer/dxce/martini_v2.0_DXCE_01.itp) | Not available |
|  C(d18:1/24:1) CER (PNCE)  |  [PNCE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/cer/pnce/PNCE-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/cer/pnce/martini_v2.0_PNCE_01.itp) | Not available |
|  C(d24:1/24:1) CER (XNCE)  |  [XNCE-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/cer/xnce/XNCE-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/cer/xnce/martini_v2.0_XNCE_01.itp) | Not available |

----------------------------------------------------------------------

### Glycosphingolipids
<hr>

<center> <h4><span style="color:gray; size=18">Glucosylceramide (GS)</span></h4> </center>
|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
| C(d16:1/16:0) GS (DPGS)   |  [DPGS-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dpgs/DPGS-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dpgs/martini_v2.0_DPGS_01.itp) | Not available |

<center> <h4><span style="color:gray; size=18">Monosialotetrahexosylganglioside (GM1)</span></h4> </center>
|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
| C(d18:1/18:0) GM1 (DPG1)   |  [DPG1-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dpg1/DPG1-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dpg1/martini_v2.0_DPG1_02.itp) | GROMOS: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dpg1/DPG1.gromos.map) |
| C(d20:1/20:0) GM1 (DBG1)   |  [DBG1-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dbg1/DBG1-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dbg1/martini_v2.0_DBG1_02.itp) | Not available |
| C(d24:1/24:0) GM1 (DXG1)   |  [DXG1-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dxg1/DXG1-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dxg1/martini_v2.0_DXG1_02.itp) | Not available |
| C(d18:1/24:1) GM1 (PNG1)   |  [PNG1-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/png1/PNG1-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/png1/martini_v2.0_PNG1_02.itp) | Not available |
| C(d24:1/24:1) GM1 (XNG1)   |  [XNG1-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/xng1/XNG1-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/xng1/martini_v2.0_XNG1_02.itp) | Not available |

<center> <h4><span style="color:gray; size=18">Monosialodihexosylganglioside (GM3)</span></h4> </center>
|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
| C(d18:1/18:0) GM3 (DPG3)   |  [DPG3-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dpg3/DPG3-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dpg3/martini_v2.0_DPG3_02.itp) | GROMOS: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dpg3/DPG3.gromos.map) |
| C(d20:1/20:0) GM3 (DBG3)   |  [DBG3-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dbg3/DBG3-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dbg3/martini_v2.0_DBG3_02.itp) | Not available |
| C(d24:1/24:0) GM3 (DXG3)   |  [DXG3-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dxg3/DXG3-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/dxg3/martini_v2.0_DXG3_02.itp) | Not available |
| C(d18:1/24:1) GM3 (PNG3)   |  [PNG3-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/png3/PNG3-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/png3/martini_v2.0_PNG3_02.itp) | Not available |
| C(d24:1/24:1) GM3 (XNG3)   |  [XNG3-em.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/xng3/XNG3-em.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gs/xng3/martini_v2.0_XNG3_02.itp) | Not available |

----------------------------------------------------------------------

### Glycoglycerolipids
<hr>

<center> <h4><span style="color:gray; size=18">Monogalactosyl and/or monoglucosyl diacylglycerol (MGDG)</span></h4> </center>
|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
| di-C16:0-C18:0 MGDG (DPMG)   |  Not available    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/dpmg/martini_v2.0_DPMG_02.itp) | Not available |
| C18:1/16:0 MGDG (OPMG)       |  [OPMG.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/opmg/OPMG.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/opmg/martini_v2.0_OPMG_01.itp) | Not available |
| di-C18:3 MGDG (DFMG)         |  [DFMG.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/dfmg/DFMG.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/dfmg/martini_v2.0_DFMG_01.itp) | Not available |
| C18:3/16:0 MGDG (FPMG)       |  [FPMG.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/fpmg/FPMG.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/fpmg/martini_v2.0_FPMG_01.itp) | Not available |

<center> <h4><span style="color:gray; size=18">Sulfoquinovosyl diacylglycerol (SQDG)</span></h4> </center>
|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
| di-C16:0-C18:0 SQDG (DPSG)   |  [DPSG.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/dpsg/DPSG.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/dpsg/martini_v2.0_DPSG_03.itp) | Not available |
| C18:1/16:0 SQDG (OPSG)       |  [OPSG.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/opsg/OPSG.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/opsg/martini_v2.0_OPSG_01.itp) | Not available |
| C18:3/16:0 SQDG (FPSG)	   |  [FPSG.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/fpsg/FPSG.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/fpsg/martini_v2.0_FPSG_01.itp) | Not available |

<center> <h4><span style="color:gray; size=18">Digalactosyl diacylglycerol (DGDG)</span></h4> </center>
|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
| di-C16:0-C18:0 DGDG (DPGG)   |  Not available   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/dpgg/martini_v2.0_DPGG_02.itp) | Not available |
| C18:1/16:0 DGDG (OPGG)       |  [OPGG.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/opgg/OPGG.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/opgg/martini_v2.0_OPGG_01.itp) | Not available |
| di-C18:3 DGDG (DFGG)         |  [DFGG.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/dfgg/DFGG.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/dfgg/martini_v2.0_DFGG_01.itp) | Not available |
| C18:3/16:0 DGDG (FPGG)       |  [FPGG.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/fpgg/FPGG.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/gl/fpgg/martini_v2.0_FPGG_01.itp) | Not available |

----------------------------------------------------------------------

### Sterols
<hr>

|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|   cholesterol      (CHOL)          |  Not available   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sterols/chol/martini_v2.0_CHOL_02.itp) | CHARMM: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sterols/chol/CHOL.charmm36.map) <br> GROMOS: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sterols/chol/CHOL.gromos.map) <br> AMBER: [[map]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sterols/chol/CHOL.amber.map) |
|   cholate        (CHOA)            |  Not available    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sterols/choa/martini_v2.0_CHOA_02.itp) | Not available |
|   cholesteryl oleate  (CHYO)       |  Not available    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sterols/chyo/martini_v2.0_CHYO_02.itp) | Not available |
|   ergosterol      (ERGO)           |  Not available    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sterols/ergo/martini_v2.0_ERGO_01.itp) | Not available |
|   bacteriohopanetetrol    (HBHT)   |  Not available    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sterols/hbht/martini_v2.0_HBHT_01.itp) | Not available |
|   diploptene         (HDPT)        |  Not available    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sterols/hdpt/martini_v2.0_HDPT_01.itp) | Not available |
|   hopane           (HHOP)          |  Not available    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sterols/hhop/martini_v2.0_HHOP_01.itp) | Not available |
|   hopanoid polycyclic group (HOPR) |  Not available    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/sterols/hopr/martini_v2.0_HOPR_01.itp) | Not available |

----------------------------------------------------------------------

### Surfactants
<hr>

|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|  beta-octylglucoside (BOG) |   Not available   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/surfactants/bog/martini_v2.0_BOG_01.itp) | Not available |
|  alkyl-PEG (C12E2)  |  [martini_v2.0_C12E2.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/surfactants/c12e12/martini_v2.0_C12E2.gro)   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/surfactants/c12e12/martini_v2.0_C12E2.itp) | Not available |
|  alkyl-PEG (C12E4)  |  [martini_v2.0_C12E4.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/surfactants/c12e4/martini_v2.0_C12E4.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/surfactants/c12e4/martini_v2.0_C12E4.itp) | Not available |
|  alkyl-PEG (C12E6)  |  [martini_v2.0_C12E6.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/surfactants/c12e6/martini_v2.0_C12E6.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/surfactants/c12e6/martini_v2.0_C12E6.itp) | Not available |
|  dodecylmaltoside (DDM)  |   Not available    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/surfactants/ddm/martini_v2.0_DDM_01.itp) | Not available |
|  dodecylphosphocholine (DPC)  |  Not available     |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/surfactants/dpc/martini_v2.0_DPC_01.itp) | Not available |
|  sodium dodecyl sulfate (SDS)  |   Not available    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/surfactants/sds/martini_v2.0_SDS_01.itp) | Not available |

----------------------------------------------------------------------

### Fatty acids (FA)
<hr>

|         Lipid                    |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
| lauric (C12:0) / myristic (C14:0) acid (LCA)   |   Not available    |    Charged: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/fa/lca/martini_v2.0_LCN_01.itp) <br> Uncharged: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/fa/lca/martini_v2.0_LCA_01.itp)  | Not available |
| palmitic (C16:0) / stearic (C18:0) acid (PCA)  |   Not available    |   Charged: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/fa/pca/martini_v2.0_PCN_01.itp) <br> Uncharged: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/fa/pca/martini_v2.0_PCA_01.itp) | Not available |
| arachidic (C20:0) / behenic (C22:0) acid (BCA)   |   Not available    |    Charged: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/fa/bca/martini_v2.0_BCN_01.itp) <br> Uncharged: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/fa/bca/martini_v2.0_BCA_01.itp)  | Not available |
| lignoceroyl (C24:0) / hexacosanoic (C26:0) acid (XCA)   |   Not available    |    Charged: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/fa/xca/martini_v2.0_XCN_01.itp) <br> Uncharged: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/fa/xca/martini_v2.0_XCA_01.itp)  | Not available |
| arachidonic (C20:4) / docosapentaenoic (C22:5) acid (ACA)   |   Not available    |    Charged: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/fa/aca/martini_v2.0_ACN_01.itp) <br> Uncharged: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/fa/aca/martini_v2.0_ACA_01.itp)  | Not available |
|  docosahexaenoic (C22:6) acid (DHA)  |   Not available    |    Charged: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/fa/dha/martini_v2.0_UCN_01.itp) <br> Uncharged: [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/fa/dha/martini_v2.0_UCA_01.itp)  | Not available |

----------------------------------------------------------------------

### Others
<hr>

|         Lipid            |     Coordinates   |    Topology   |     Mapping      |
|------------------------------|-------------------|-----------------|------------------|
|  cyclic di-DPPC Bolalipid (BOLA)  |  Not available   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/bola/martini_v2.0_BOLA_01.itp) | Not available |
|  acyclic di-DPPC Bolalipid (BOLB) |  Not available   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/bolb/martini_v2.0_BOLB_01.itp) | Not available |
|  cardiolipin (CL) 0-  (CDL0)|   [CDL0.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/cdl0/CDL0.gro)  |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/cdl0/martini_v2.0_CDL0_01.itp) | Not available |
|  cardiolipin (CL) 1- (CDL1) |  [CDL1.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/cdl1/CDL1.gro)   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/cdl1/martini_v2.0_CDL1_01.itp) | Not available |
|  cardiolipin (CL) 2- (CDL2) |  [CDL2.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/cdl2/CDL2.gro)   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/cdl2/martini_v2.0_CDL2_01.itp) | Not available |
|  lipopolysaccharide (LPS) |  [LPS_cg.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/lps/LPS_cg.gro)   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/lps/martini_v2.0_LPS_01.itp) | Not available |
|  lipid A - Bacteroides fragilis (BFRA) |    [Bfragilis.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/bfra/Bfragilis.gro) |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/bfra/Bfragilis_v1.itp) | Not available |
|  lipid A - Bordetella pertussis (BPER) | [Bpertussis.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/bper/Bpertussis.gro)   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/bper/Bpertussis_v1.itp) | Not available |
|  lipid A - Campylobacter jejuni (CJEJ) |  [Cjejuni.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/cjej/Cjejuni.gro)   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/cjej/Cjejuni_v1.itp) | Not available |
|  lipid A - Chlamydia trachomatis (CTRA) |  [Ctrachomatis.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/ctra/Ctrachomatis.gro)   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/ctra/Ctrachomatis_v1.itp) | Not available |
|  lipid A - Helicobacter pylori (HPYL) | [Hpylori.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/hpyl/Hpylori.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/hpyl/Hpylori_v1.itp) | Not available |
|  lipid A - Neisseria meningitidis (NMEN) | [Nmeningitidis.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/nmen/Nmeningitidis.gro)    |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/nmen/Nmeningitidis_v1.itp) | Not available |
|  lipid A - Porphyromonas gingivalis (PGIN) |  [Pgingivalis.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/pgin/Pgingivalis.gro)   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/pgin/Pgingivalis_v1.itp) | Not available |
|  lipid A - Pseudomonas aeruginosa (PARU) |  [Paeruginosa_LPA.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/paru/Paeruginosa_LPA.gro)   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/paru/Paeruginosa_LPA_v1.itp) | Not available |
|  lipid A+core - Pseudomonas aeruginosa (PARC) |  [Paeruginosa_LPC.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/parc/Paeruginosa_LPC.gro)   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/parc/Paeruginosa_LPC_v1.itp) | Not available |
|  lipid A - Salmonella minnesota (SMIN) |   [Sminnesota.gro](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/smin/Sminnesota.gro)  |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/smin/Sminnesota_v1.itp) | Not available |
|  di-C16:0-C18:0 TAP (DPTAP) |  Not available   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/dptap/martini_v2.0_DPTAP_01.itp) | Not available |
|  di-C16:1-C18:1 TAP (DOTAP) |  Not available   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/dotap/martini_v2.0_DOTAP_01.itp) | Not available |
|  di-C16:1-C18:1 TAP (DITAP) |  Not available   |    [[itp]](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/lipidome/others/ditap/martini_v2.0_DITAP_01.itp) | Not available |


----------------------------------------------------------------------

