---
title: <i class="fa-solid fa-section"></i> Others
format: html
---

<hr>

Martini 2 topologies for molecules not fitting in other categories are listed below.

### Voltage-sensitive dyes

----------------------------------------------------------------------

- [martini_v2.0_other.itp](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/others/martini_v2.0_other.itp)

----------------------------------------------------------------------

### Commonly used phytochemicals

----------------------------------------------------------------------

- [martini_v2.0_phytochemicals.itp](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/others/martini_v2.0_phytochemicals.itp)

----------------------------------------------------------------------
 
### Optimal Martini 2 Cholesterol with LINCS
<hr>

*Optimized cholesterol model for Martini 2 to overcome the constraint convergence issues using LINCS.* For further background reading, please see:

- **B. Fábián, S. Thallmair, and Gerhard Hummer**. *Optimal bond constraint topology for molecular dynamics simulations of cholesterol.* J. Chem. Theory Comput., 2023. [DOI: 10.1021/acs.jctc.2c01032](https://doi.org/10.1021/acs.jctc.2c01032) 

----------------------------------------------------------------------

- [martini_v2.0_CHOL_02-optLINCS.itp](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/others/martini_v2.0_CHOL_02-optLINCS.itp)

----------------------------------------------------------------------
  

### Nucleotide Cofactors for Martini 2
<hr>

Thanks to the great work of Filipe Sousa and the Melo team, we can present to you nucleotide cofactors for Martini 2. This work includes topologies for key metabolites and cofactors, such as FAD, FMN, riboflavin, NAD, NADP, ATP, ADP, AMP, and thiamine pyrophosphate, in different oxidation and protonation states as well as smaller molecules derived from them (among others, nicotinamide, adenosine, adenine, ribose, thiamine, and lumiflavin), summing up a total of 79 different molecules.

----------------------------------------------------------------------

- [nucleotides.itp](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/others/nucleotides.itp)

----------------------------------------------------------------------

### PSII cofactors
<hr>

Topologies for the cofactors associated with the Photosystem II. The ZIP-archives contain CG Martini topologies as well as united atom Gromos topologies for: Plastoquinone, Plastoquinol, Ubiquinone, Ubiquinol, *Beta-carotene, Heme b, Chlorophyll A and Pheophytin. Details on the parameterization and behavior of the topologies can be found in:

- **Djurre H. de Jong, Nicoletta Liguori, Tom van den Berg, Clement Arnarez, Xavier Periole, and Siewert J. Marrink**. *Atomistic and Coarse Grain Topologies for the Cofactors Associated with the PhotoSystem II Core Complex.* , J. Phys. Chem. B, 2015, 119 (25), pp 7791–7803.

----------------------------------------------------------------------

- [topologies.zip](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/others/topologies.zip)

----------------------------------------------------------------------

> _The file describing the tabulated angle of Betacarotene does not have the right format. Although it does  produce the right distribution, the dynamics are off. The tabulated potential and the ITP file below do have the right format, produce the right distribution and give better dynamics as compared to the atomistic simulations. Thanks to Floris van Eerden for pointing this out and providing us with the correct files._

----------------------------------------------------------------------

- [BCR_correct.zip](https://martini-library.s3.us-east-2.amazonaws.com/ff_parameters/martini2/others/BCR_correct.zip)

----------------------------------------------------------------------


### DIM (Phthiocerol dimycocerosate) lipids
<hr>

(provided by Matthieu Chavent - [Matthieu.Chavent@ipbs.fr](mailto: Matthieu.Chavent@ipbs.fr))

The coordinates and topological files for the DIM lipids for AMBER and MARTINI as well as  tcl (VMD) scripts and jupyter notebooks used to perform analysis can be accessed via the link:

- [https://github.com/MChavent/DIM_data/tree/master/MD_simulations](https://github.com/MChavent/DIM_data/tree/master/MD_simulations)

The associated paper is available on Biorxiv preprint:   

- [https://www.biorxiv.org/content/10.1101/649541v1](https://www.biorxiv.org/content/10.1101/649541v1)

----------------------------------------------------------------------