---
title: "Protein dynamics and lipid affinity of monomeric, zeaxanthin-binding LHCII in thylakoid membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Fatemeh Azadi-Chegeni, Sebastian Thallmair, Meaghan E. Ward, Giorgio Perin, Siewert J. Marrink, Marc Baldus, Tomas Morosinotto, Anjali Pandit"         # Paper authors (required)
year: "2022"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2021.12.039"            # URL of DOI (required)  
materials: "https://www.sciencedirect.com/science/article/pii/S0006349521039631#app2"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Azadi-Chegeni, F., Thallmair, S., Ward, M. E., Perin, G., Marrink, S. J., Baldus, M., ... & Pandit, A. (2022). Protein dynamics and lipid affinity of monomeric, zeaxanthin-binding LHCII in thylakoid membranes. Biophysical journal, 121(3), 396-409.

## Abstract

The xanthophyll cycle in the antenna of photosynthetic organisms under light stress is one of the most well-known processes in photosynthesis, but its role is not well understood. In the xanthophyll cycle, violaxanthin (Vio) is reversibly transformed to zeaxanthin (Zea) that occupies Vio binding sites of light-harvesting antenna proteins. Higher monomer/trimer ratios of the most abundant light-harvesting protein, the light-harvesting complex II (LHCII), usually occur in Zea accumulating membranes and have been observed in plants after prolonged illumination and during high-light acclimation. We present a combined NMR and coarse-grained simulation study on monomeric LHCII from the npq2 mutant that constitutively binds Zea in the Vio binding pocket. LHCII was isolated from 13C-enriched npq2 Chlamydomonas reinhardtii (Cr) cells and reconstituted in thylakoid lipid membranes. NMR results reveal selective changes in the fold and dynamics of npq2 LHCII compared with the trimeric, wild-type and show that npq2 LHCII contains multiple mono- or digalactosyl diacylglycerol lipids (MGDG and DGDG) that are strongly protein bound. Coarse-grained simulations on npq2 LHCII embedded in a thylakoid lipid membrane agree with these observations. The simulations show that LHCII monomers have more extensive lipid contacts than LHCII trimers and that protein-lipid contacts are influenced by Zea. We propose that both monomerization and Zea binding could have a functional role in modulating membrane fluidity and influence the aggregation and conformational dynamics of LHCII with a likely impact on photoprotection ability.