---
title: "Membrane thickness, lipid phase and sterol type are determining factors in the permeability of membranes to small solutes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Jacopo Frallicciardi, Josef Melcr, Pareskevi Siginou, Siewert J. Marrink & Bert Poolman"         # Paper authors (required)
year: "2022"           # Publication year (required)
publication: "Nature communications"    # Journal or similar (required)
preprint: "https://www.biorxiv.org/content/10.1101/2021.07.16.452599v1"       # URL to prepint page (optional)  
doi: "https://doi.org/10.1038/s41467-022-29272-x"            # URL of DOI (required)  
materials: "https://www.nature.com/articles/s41467-022-29272-x#Sec23"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Phopholipids
  - Solvents
  - Small molecules
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Frallicciardi, J., Melcr, J., Siginou, P., Marrink, S. J., & Poolman, B. (2022). Membrane thickness, lipid phase and sterol type are determining factors in the permeability of membranes to small solutes. Nature communications, 13(1), 1605.

## Abstract

Cell membranes provide a selective semi-permeable barrier to the passive transport of molecules. This property differs greatly between organisms. While the cytoplasmic membrane of bacterial cells is highly permeable for weak acids and glycerol, yeasts can maintain large concentration gradients. Here we show that such differences can arise from the physical state of the plasma membrane. By combining stopped-flow kinetic measurements with molecular dynamics simulations, we performed a systematic analysis of the permeability of a variety of small molecules through synthetic membranes of different lipid composition to obtain detailed molecular insight into the permeation mechanisms. While membrane thickness is an important parameter for the permeability through fluid membranes, the largest differences occur when the membranes transit from the liquid-disordered to liquid-ordered and/or to gel state, which is in agreement with previous work on passive diffusion of water. By comparing our results with in vivo measurements from yeast, we conclude that the yeast membrane exists in a highly ordered and rigid state, which is comparable to synthetic saturated DPPC-sterol membranes.