---
title: "Complex nanoemulsion for vitamin delivery: droplet organization and interaction with skin membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Neila Machado, Bart M. H. Bruininks, Priyanka Singh, Laurita dos Santos, Carine Dal Pizzol, Gustavo de C. Dieamant, Odivania Kruger, Airton A. Martin, Siewert J. Marrink, Paulo C. T. Souza and Priscila P. Favero"         # Paper authors (required)
year: "2022"           # Publication year (required)
publication: "Nanoscale"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/D1NR04610A"            # URL of DOI (required)  
materials: "https://www.rsc.org/suppdata/d1/nr/d1nr04610a/d1nr04610a1.pdf"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Nanoparticles
  - Self-assembly
  - Small molecules
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Machado, N., Bruininks, B. M., Singh, P., Dos Santos, L., Dal Pizzol, C., Dieamant, G. D. C., ... & Favero, P. P. (2022). Complex nanoemulsion for vitamin delivery: droplet organization and interaction with skin membranes. Nanoscale, 14(2), 506-514.

## Abstract

Lipid nanoemulsions are promising nanomaterials for drug delivery applications in food, pharmaceutical and cosmetic industries. Despite the noteworthy commercial interest, little is known about their supramolecular organization, especially about how such multicomponent formulations interact with cell membranes. In the present work, coarse-grained molecular dynamics simulations have been employed to study the self-assembly of a 15-component lipid nanoemulsion droplet containing vitamins A and E for skin delivery. Our results display aspects of the unique “onion-like” agglomeration between the chemical constituents in the different layers of the lipid nanodroplet. Vitamin E molecules are more concentrated in the center of the droplet together with other hydrophobic constituents such as the triglycerides with long tails. On the other hand, vitamin A occupies an intermediate layer between the core and the co-emulsifier surface of the nanodroplet, together with lecithin phospholipids. Coarse-grained molecular dynamics simulations were also performed to provide insight into the first steps involved in absorption and penetration of the nanodroplet through skin membrane models, representing an intracellular (hair follicle infundibulum) and intercellular pathway (stratum corneum) through the skin. Our data provide a first view on the complex organization of commercial nanoemulsion and its interaction with skin membranes. We expect our results to open the way towards the rational design of such nanomaterials.