---
title: "Two cooperative binding sites sensitize PI(4,5)P2 recognition by the tubby domain"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Veronika Thallmair, Lea Schultz, Wencai Zhao, Siewert J. Marrink, Dominik Oliver and Sebastian Thallmair"         # Paper authors (required)
year: "2022"           # Publication year (required)
publication: "Science advances"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://www.science.org/doi/10.1126/sciadv.abp9471"            # URL of DOI (required)  
materials: "https://zenodo.org/records/6587156"      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Phopholipids
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Thallmair, V., Schultz, L., Zhao, W., Marrink, S. J., Oliver, D., & Thallmair, S. (2022). Two cooperative binding sites sensitize PI (4, 5) P2 recognition by the tubby domain. Science advances, 8(36), eabp9471.

## Abstract

Phosphoinositides (PIs) are lipid signaling molecules that operate by recruiting proteins to cellular membranes via PI recognition domains. The dominant PI of the plasma membrane is phosphatidylinositol 4,5-bisphosphate [PI(4,5)P2]. One of only two PI(4,5)P2 recognition domains characterized in detail is the tubby domain. It is essential for targeting proteins into cilia involving reversible membrane association. However, the PI(4,5)P2 binding properties of tubby domains have remained enigmatic. Here, we used coarse-grained molecular dynamics simulations to explore PI(4,5)P2 binding by the prototypic tubby domain. The comparatively low PI(4,5)P2 affinity of the previously described canonical binding site is underpinned in a cooperative manner by a previously unknown, adjacent second binding site. Mutations in the previously unknown site impaired PI(4,5)P2-dependent plasma membrane localization in living cells and PI(4,5)P2 interaction in silico, emphasizing its importance for PI(4,5)P2 affinity. The two-ligand binding mode may serve to sharpen the membrane association-dissociation cycle of tubby-like proteins that underlies delivery of ciliary cargo.