---
title: Lectures
format: html
---

N.B.! Lectures for each day can be downloaded as a bundle, or watched online by following the links.

### September 1st
<hr>

#### Download all talks [here](http://cgmartini.nl/images/stories/workshop2021/lectures/first/lectures_sept_1st.zip).

- Introduction to Martini 3 - Paulo C. T. Souza - [Watch](https://youtu.be/lx8P577COfM) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/first/Introduction_to_Martini3.pdf)

- Novel applications of Martini 3 - Siewert-Jan Marrink - [Watch](https://www.youtube.com/watch?v=A72A9s980BQ) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/first/SJ-martini3-applications.pdf)

- Martini Tools - Tsjerk Wassenaar - [Watch](https://youtu.be/Gvf6W0fBqwg) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/first/Martini-Tools.pdf)

- The MArtini Database (MAD) and web server - Luca Monticelli - [Watch](https://youtu.be/__LDjW2hB5Q) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/first/luca_MAD/MAD_server.pdf)

- The Martini Lipids - Manuel N. Melo - [Watch](https://youtu.be/cMhlpwoDtg8) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/first/manel/MN_Melo_Martini_lipids.pdf)

### September 2nd
<hr>

#### Download all talks [here](http://cgmartini.nl/images/stories/workshop2021/lectures/second/lectures_sep_2nd.zip).

- Martini 3 Small Molecules - Riccardo Alessandri - [Watch](https://www.youtube.com/watch?v=PfgEx72KxVg) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/second/riccardo/2021-09-02_MartiniWorkshop2021_Small_molecules-vFINAL.pdf)

- Bartender - Raul Mera A. - [Watch](https://youtu.be/e6P79G9Z8r4) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/second/Bartender_RMera.pdf)

- Protein models in Martini 3 - Sebastian Thallmair - [Watch](https://youtu.be/KDej6wt7-x8) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/second/M3workshop-01.pdf)

- Protein-small molecule binding with Martini 3 - Paulo C. T. Souza - [Watch](https://www.youtube.com/watch?v=L-d2VVj5ZXo) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/second/Protein_Small_molecule_Binding.pdf)

- Polymer modeling with Martini 3 - Fabian Grünewald - [Watch](https://www.youtube.com/watch?v=SwTT5QY0mgI) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/second/PolyplyWorkshop2021.pdf)

### September 3rd
<hr>

#### Download all talks [here](http://cgmartini.nl/images/stories/workshop2021/lectures/third/lectures_sep_3rd.zip).

- Titratable Martini - Fabian Grünewald - [Watch](https://www.youtube.com/watch?v=G2V_UTccy-Y) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/third/TitratableMartiniWorkshop2021.pdf)

- TS2CG - Weria Pezeshkian - [Watch](https://www.youtube.com/watch?v=iRL8wFIuuqE) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/third/weria_TS2CG.pdf)

- Machine Learning-driven Multiscale Modeling - Helgi I. Ingólfsson - [Watch](https://www.youtube.com/watch?v=n5o9fKeVwuY) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/third/Martini%20workshop%20-%20MuMMI%20-%20Ingolfsson.pdf)

- Lipid-protein interactions - Peter Tieleman - [Watch](https://youtu.be/R3TRYUi7x9o) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/third/Martini-tieleman.pdf)

- ProLint - Besian I. Sejdiu - [Watch](https://www.youtube.com/watch?v=_CYrEYkP--g) [Slides (PDF)](http://cgmartini.nl/images/stories/workshop2021/lectures/third/tieleman/Sejdiu_MartiniWorkshop.pptx.pdf)

