---
title: Tutorials
format: html
---

### 1: Lipid bilayers I — Self-assembly
<hr>

A PDF version of this tutorial is available [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_1/Lipid_bilayers_I_lpara_mnmelo.docx.pdf).

In case of issues, please contact [lpborgesaraujo@tecnico.ulisboa.pt](lpborgesaraujo@tecnico.ulisboa.pt) or [m.n.melo@itqb.unl.pt](m.n.melo@itqb.unl.pt)

### 2: Lipid bilayers II - Complex mixtures using Insane
<hr>

A PDF version of this tutorial is available [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_1/Lipid_bilayers_II_lpara_mnmelo.docx.pdf).

In case of issues, please contact [lpborgesaraujo@tecnico.ulisboa.pt](lpborgesaraujo@tecnico.ulisboa.pt) or [m.n.melo@itqb.unl.pt](m.n.melo@itqb.unl.pt)

### 3: Proteins - Part I: Basic and Martinize 2
<hr>

A PDF version of this tutorial is available [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_2/tutorial_3_protein_part1.pdf). The files required for this tutorial (including worked files) can be downloaded from [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_2/tutorial_protein_part1.zip).

In case of issues, please contact [thallmair@fias.uni-frankfurt.de](thallmair@fias.uni-frankfurt.de) or [paulo.telles-de-souza@ibcp.fr](paulo.telles-de-souza@ibcp.fr)

(if you just landed here, we recommend you follow the [tutorial about lipid bilayers first](#lipid-bilayers-i-—-self-assembly))

### 4: Backward
<hr>

Consult tutorial [here](http://cgmartini.nl/index.php/2021-martini-online-workshop/tutorials/566-4-backward).

In case of issues, please contact [t.a.wassenaar@rug.nl](t.a.wassenaar@rug.nl).


### 5: MAD - MArtini Database
<hr>

Unlike the other tutorials, this one is a demonstration on how to use the MAD server. You can watch it [here](https://youtu.be/fcaSbsaBCLY).

### 6: Parametrization of a new small molecule
<hr>

In case of issues, please contact [alessandri@uchicago.edu](alessandri@uchicago.edu).

This tutorial is available for download [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_7/M3tutorials--parameterizing-a-new-small-molecule.pdf). Required files and worked examples can be downloaded [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_7/files-m3-newsm.zip), and files for Bartender can be obtained [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_7/files-m3-bartender.zip).

### 7: Proteins Part II – TM proteins and Protein complexes
<hr>

A PDF version of this tutorial is available [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_6/tutorial_7_protein_part2.pdf).  The files required for this tutorial (including worked files) can be downloaded from [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_6/tutorial_proteins_part2.zip).

In case of issues, please contact [paulo.telles-de-souza@ibcp.fr](paulo.telles-de-souza@ibcp.fr).

(if you just landed here, we recommend you follow the tutorials about Lipid bilayers, [Part I](#lipid-bilayers-i-—-self-assembly) and [Part II](#lipid-bilayers-ii---complex-mixtures-using-insane), and also the [Proteins Part I](#proteins---part-i-basic-and-martinize-2) first)

### 8: Protein-small molecule binding
<hr>

In case of issues, please contact [paulo.telles-de-souza@ibcp.fr](paulo.telles-de-souza@ibcp.fr).

A PDF version of this tutorial is available [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_4/tutorial_protein_small_molecule_binding.pdf). The files required for this tutorial can be downloaded from [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_4/tutorial_small_molecule-protein_binding.zip).

### 9: Polyply
<hr>

Consult tutorial [here](http://cgmartini.nl/index.php/2021-martini-online-workshop/tutorials/559-8-polyply).

In case of issues, please contact [f.grunewald@rug.nl](f.grunewald@rug.nl).

### 10: TS2CG
<hr>

Note: A PDF version of this tutorial is available [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_9/TS2CG%20tut.pdf).

In case of issues, please contact [w.pezeshkian@rug.nl](w.pezeshkian@rug.nl) or [m.konig@rug.nl](m.konig@rug.nl)

### 11: Running Martini simulation with ddcMD
<hr>

Note: Input data for this tutorial can be downloaded [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_10/ddcMD-Martini-tautorial.tar.gz). A PDF version of this tutorial is available [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_10/ddcMD%20martini%20tutorials-v2.pdf).

In case of issues, please contact [ingolfsson1@llnl.gov](ingolfsson1@llnl.gov)

(if you just landed here, we recommend you follow the [tutorial about lipid bilayers first](#lipid-bilayers-i-—-self-assembly))

### 12: Titratable Martini
<hr>

This tutorial is available for download [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_11/titratable_tutorial.pdf), and the required files can be downloaded [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_11/titratable_martini_tutorial_files.zip).

Tutorial written by Selim Sami and Fabian Grünewald. In case of issues, please contact [s.sami@rug.nl](s.sami@rug.nl) or [f.grunewald@rug.nl](f.grunewald@rug.nl)

### 13: prolintpy - Automate the analysis and visualization of protein-lipid interactions.
<hr>

A (outdated) pdf version of this tutorial can be downloaded [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_12/prolintpy_TielemanLab.pdf)!

In case of issues, please contact [besian.sejdiu@stjude.org](besian.sejdiu@stjude.org) or [tieleman@ucalgary.ca](tieleman@ucalgary.ca)

### 14: Dual resolution membrane tutorial
<hr>

A pdf version of this tutorial can be downloaded [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_13/Dual%20resolution%20membrane%20tutorial.pdf), and the required files are available [here](http://cgmartini.nl/images/stories/workshop2021/tutorials/tutorial_13/vs_membrane_tutorial.zip).

In case of issues, please contact [y.liu@rug.nl](y.liu@rug.nl)