---
title: Membrane buckling artefact
subtitle: Must-read for those who simulate membrane systems.
description: |
  Membrane deformations under the action of a semi-isotropically coupled barostat. 
sidebar: false
toc: false
author: Daniel Ramirez
date: "09/25/2023"
---

In MD simulations using the GROMACS package with default Martini parameters, the group of Hummer found large membranes to deform under the action of a semi-isotropically coupled barostat. As the primary cause, they identified overly short outer cutoffs and infrequent neighbor list updates that result in missed long-range attractive Lennard-Jones interactions. Small but systematic imbalances in the apparent pressure tensor then induce unphysical asymmetric box deformations that crumple the membrane. Guidelines are presented to avoid these artefacts, including estimates for appropriate values for the outer cutoff r_l and the number of time steps nstlist between neighbor list updates.

Must-read for those who simulate membrane systems. For details, see the paper from [Kim et al. in chemRxiv](https://chemrxiv.org/engage/chemrxiv/article-details/64b55faeb053dad33a692084).