<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ProLint2: Analysis of lipid-protein interactions – Martini Force Field Initiative</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../">
<link href="../../../../images/favicon.png" rel="icon" type="image/png">
<script src="../../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap-69fe911abf326d3c3f52f7dd89351358.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../../../../site_libs/quarto-contrib/iconify-2.1.0/iconify-icon.min.js"></script>
<link href="../../../../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
      const quotes = [
          "<i>Shaken, not stirred.</i> - James Bond",
          "<i>He was white and shaken, like a dry martini.</i> - P. G. Wodehouse",      
          "<i>I think people think we're all sipping martinis by the pool.</i> - Maria Menounos",
          "<i>Why don't you get out of that wet coat and into a dry martini?</i> - Robert Benchley",
          "<i>Really, can anyone drink several martinis at lunch?</i> - Christine Baranski",
          "<i>Zen martini: A martini with no vermouth at all. And no gin, either.</i> - P.J. O'Rourke",
          "<i>I never go jogging, it makes me spill my martini.</i> - George Burns",
          "<i>Martinis are the only American invention as perfect as a sonnet.</i> - H. L. Mencken",
          "<i>He knows just how I like my martini: full of alcohol.</i> - Homer Simpson",
          "<i>Happiness is: finding olives in your martini when you're hungry.</i> - Johnny Carson",
          "<i>If it wasn't for the olives in his martinis he'd starve to death.</i> - Milton Berle",
        ];
      const randomIndex = Math.floor(Math.random() * quotes.length);
      const randomQuote = quotes[randomIndex];

      const footerLeft = document.querySelector('.footer-left');
      if (footerLeft) {
          footerLeft.innerHTML = randomQuote;
      }
    });
</script>


<link rel="stylesheet" href="../../../../styles.css">
<meta property="og:title" content="ProLint2: Analysis of lipid-protein interactions – Martini Force Field Initiative">
<meta property="og:description" content="">
<meta property="og:image" content="https://cgmartini.nl/docs/tutorials/Martini3/ProLint/fig1.png">
<meta property="og:site_name" content="Martini Force Field Initiative">
<meta property="og:image:height" content="160">
<meta property="og:image:width" content="1368">
<meta name="twitter:title" content="ProLint2: Analysis of lipid-protein interactions – Martini Force Field Initiative">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://cgmartini.nl/docs/tutorials/Martini3/ProLint/fig1.png">
<meta name="twitter:image-height" content="160">
<meta name="twitter:image-width" content="1368">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../../images/martini.gif" alt="martini logo" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../index.html"> <i class="bi bi-house-fill" role="img">
</i> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../../../docs/tutorials/index.html" aria-current="page"> <i class="bi bi-mortarboard-fill" role="img">
</i> 
<span class="menu-text">Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../docs/downloads/index.html"> <i class="bi bi-download" role="img">
</i> 
<span class="menu-text">Downloads</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../docs/publications/index.html"> <i class="bi bi-newspaper" role="img">
</i> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../docs/announcements/index.html"> 
<span class="menu-text"><i class="fa-solid fa-bullhorn" aria-label="bullhorn"></i> Announcements</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../docs/contact/index.html"> 
<span class="menu-text"><i class="fa-regular fa-address-book" aria-label="address-book"></i> Contact</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-fa-circle-info--help" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text"><i class="fa-solid fa-circle-info" aria-label="circle-info"></i> Help</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-fa-circle-info--help">    
        <li>
    <a class="dropdown-item" href="https://github.com/orgs/Martini-Force-Field-Initiative/discussions"><i class="bi bi-chat-right-text" role="img">
</i> 
 <span class="dropdown-text">Discussion Board</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/orgs/Martini-Force-Field-Initiative/discussions"><i class="bi bi-bug" role="img">
</i> 
 <span class="dropdown-text">Report an Issue</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../docs/faq/index.html"><i class="bi bi-question-circle" role="img">
</i> 
 <span class="dropdown-text">FAQs</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://x.com/cg_martini" title="Martini Twitter" class="quarto-navigation-tool px-1" aria-label="Martini Twitter"><i class="bi bi-twitter"></i></a>
    <a href="https://github.com/Martini-Force-Field-Initiative" title="Martini GitHub" class="quarto-navigation-tool px-1" aria-label="Martini GitHub"><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">ProLint2: Analysis of lipid-protein interactions</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/tutorials/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><b>Summary</b></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/tutorials/Martini3/lectures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🎓 Martini Lectures</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/tutorials/Martini3/tutorials.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🛠️ Hands-on Tutorials</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../docs/tutorials/Legacy/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🕸️ Legacy Material</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#recommended-installation" id="toc-recommended-installation" class="nav-link" data-scroll-target="#recommended-installation">Recommended Installation</a></li>
  <li><a href="#prolint2-workflow" id="toc-prolint2-workflow" class="nav-link" data-scroll-target="#prolint2-workflow">ProLint2 Workflow</a></li>
  <li><a href="#creating-a-universe-and-analyzing-system-composition" id="toc-creating-a-universe-and-analyzing-system-composition" class="nav-link" data-scroll-target="#creating-a-universe-and-analyzing-system-composition">Creating a Universe and analyzing system composition</a></li>
  <li><a href="#contact-based-metrics" id="toc-contact-based-metrics" class="nav-link" data-scroll-target="#contact-based-metrics">Contact-based metrics</a></li>
  <li><a href="#visualization" id="toc-visualization" class="nav-link" data-scroll-target="#visualization">Visualization</a></li>
  <li><a href="#advanced-applications" id="toc-advanced-applications" class="nav-link" data-scroll-target="#advanced-applications">Advanced applications</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  <li><a href="#tools-and-scripts-used-in-this-tutorial" id="toc-tools-and-scripts-used-in-this-tutorial" class="nav-link" data-scroll-target="#tools-and-scripts-used-in-this-tutorial">Tools and scripts used in this tutorial</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ProLint2: Analysis of lipid-protein interactions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<hr>
In case of issues, please contact <a href="mailto:%20daniel.ramirezecheme@ucalgary.ca">daniel.ramirezecheme@ucalgary.ca</a> or <a href="mailto:%20tieleman@ucalgary.ca">tieleman@ucalgary.ca</a>.
<hr>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<ul>
<li><a href="#introduction"><code>Introduction</code></a></li>
<li><a href="#recommended-installation"><code>Recommended installation</code></a></li>
<li><a href="#prolint2-workflow"><code>ProLint2 Workflow (Universe &gt; Contacts &gt; Metrics &gt; Plotters)</code></a></li>
<li><a href="#creating-a-universe-and-analyzing-system-composition"><code>Creating a Universe and analyzing system composition</code></a></li>
<li><a href="#contact-based-metrics"><code>Contact-based metrics</code></a></li>
<li><a href="#visualization"><code>Visualization</code></a></li>
<li><a href="#advanced-applications"><code>Advanced applications</code></a></li>
<li><a href="#conclusions"><code>Conclusions</code></a></li>
<li><a href="#tools-and-scripts-used-in-this-tutorial"><code>Tools and scripts used in this tutorial</code></a></li>
<li><a href="#references"><code>References</code></a></li>
</ul>
</section>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<hr>
<p><code>ProLint2</code> is an open-source Python library for the automated analysis and visualization of lipid-protein interactions in molecular dynamics (MD) simulations of multicomponent membrane systems at atomistic or coarse-grained (CG) resolutions. It constitutes an update to the original <code>ProLintpy</code> library <sup><a href="#references">[1]</a></sup> that significantly improves computational efficiency and versatility <sup><a href="#references">[2]</a></sup>.</p>
<p>For many years, proteins were the primary focus in studies of biological membranes, with lipids largely regarded as mere solvents for hydrophobic proteins. However, in recent years, the complexity of the lipid environment has gained recognition. The role of lipids in membrane protein functions can be described as (i) specific, when lipids directly bind to the protein surface, affecting the protein’s activity and/or stability, (ii) non-specific, when the physical properties of membranes, such as surface tension, thickness, curvature, and fluidity, influence protein function, or (iii) a combination of both. Selecting an accurate membrane model is crucial for drawing biologically relevant conclusions about the lipid-protein interplay in the system of interest.</p>
<p>This tutorial will focus on the use of <code>ProLint2</code> for the analysis and visualization of specific lipid-protein interactions in a Martini simulation of the G-protein-gated inwardly rectifying potassium channel (GIRK). The system features a single GIRK copy within a lipid model composed of (POPE:1|POPS:1|CHOL:1), which mimics the inner leaflet of neuronal and cardiac cell membranes, where GIRK channels are physiologically active. Te purposes of these analyses is to highlight the capabilities of <code>ProLint2</code> to analyze lipid-protein interactions, providing you with the basis for their application to any other membrane-protein MD system.</p>
<p>A Jupyter notebook to follow this tutorial can be accessed <a href="https://cgmartini-library.s3.ca-central-1.amazonaws.com/0_Tutorials/m3_tutorials/ProLint/ProLint_Tutorial.ipynb">here</a>.</p>
</section>
<section id="recommended-installation" class="level3">
<h3 class="anchored" data-anchor-id="recommended-installation">Recommended Installation</h3>
<hr>
<p>To avoid conflicts with other Python packages, we recommend creating a dedicated environment for <code>ProLint2</code> using <code>conda</code>. You can do this by running the following commands in your terminal:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">conda</span> create <span class="at">-n</span> prolint2 python=3.10 jupyter</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">conda</span> activate prolint2</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> <span class="at">-m</span> pip install prolint2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>ProLint2</code> relies on <code>MDAnalysis</code> to read input data files, which makes it compatible with all the most popular MD engines, including GROMACS, CHARMM, NAMD, LAMMPS, and OpenMM. <code>MDAnalysis</code> is a powerful Python library designed for analyzing MD trajectories. If you’re not familiar with it, we strongly encourage you to consult the <a href="https://docs.mdanalysis.org/stable/index.html"><code>MDAnalysis</code> documentation</a> for an overview of its features, supported file formats, and usage examples.</p>
</div>
</div>
</section>
<section id="prolint2-workflow" class="level3">
<h3 class="anchored" data-anchor-id="prolint2-workflow">ProLint2 Workflow</h3>
<p><code>ProLint2</code> simplifies the analysis of lipid-protein interactions by breaking it down into four sequential steps, which aligns with the four main components of the library:</p>
<p><img src="fig1.png" class="img-fluid"></p>
<section id="universe" class="level4">
<h4 class="anchored" data-anchor-id="universe"><strong>• Universe</strong></h4>
<p>Once you load your trajectory files with <code>ProLint2</code> it will automatically create a modified <code>MDAnalysis</code> Universe that keeps all the functionalities of any <code>MDAnalysis</code> Universe, but adds an extra set of methods and attributes that are specific for the analysis of membrane protein systems. These are based on the automatic categorization of residues into two essential components (database and query), as shown below:</p>
<p><img src="fig2.png" class="img-fluid"></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This automation eliminates the need for manual removal of irrelevant residues, including water or ions.</p>
</div>
</div>
</section>
<section id="contacts" class="level4">
<h4 class="anchored" data-anchor-id="contacts"><strong>• Contacts</strong></h4>
<p>The next step in the sequence involves the creation of <code>ProLint2</code> Contacts instances, which keep track of the interactions between all the lipid and protein residues in the system. <code>ProLint2</code> uses a distance-based approach to define contacts, which means that for every frame the algorithm checks whether a lipid molecule and a protein residue interact by verifying whether at least one atom from each group is within a defined distance cutoff. The default cutoff in <code>ProLint2</code> is 7 Angstroms, which excludes weaker, less relevant interactions while capturing strong and meaningful ones. However, this parameter can be customized to meet any specific requirement. This step is the most time-consuming, and the total processing time will vary depending on the size of the system and the number of frames in the trajectory.</p>
</section>
<section id="metrics" class="level4">
<h4 class="anchored" data-anchor-id="metrics"><strong>• Metrics</strong></h4>
<p><code>ProLint2</code> Metrics provides a tool to explore lipid-protein interactions at the residue-lipid type level of detail, which is not explicitly available in the Contacts objects. Default metrics such as SumMetric, MaxMetric, and MeanMetric provide insights into the strength and specificity of interactions with different lipid types in the system. Additionally, users can create custom metrics to mold the analysis to their specific requirements.</p>
</section>
<section id="plotters" class="level4">
<h4 class="anchored" data-anchor-id="plotters"><strong>• Plotters</strong></h4>
<p>Finally, <code>ProLint2</code>’s Plotters provide a systematic way to visually reveal relevant interactions. Identifying important lipid types using exploratory Plotters and density plots is recommended as the first step, followed by a detailed examination of specific interactions. This approach optimizes the analysis workflow, and ensures a thorough exploration of the local lipid environment around proteins.</p>
</section>
</section>
<section id="creating-a-universe-and-analyzing-system-composition" class="level3">
<h3 class="anchored" data-anchor-id="creating-a-universe-and-analyzing-system-composition">Creating a Universe and analyzing system composition</h3>
<hr>
<p>We will start by creating a <code>ProLint2</code> Universe, using the GIRK sample dataset already included in the library:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prolint2 <span class="im">import</span> Universe</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prolint2.sampledata <span class="im">import</span> GIRKDataSample</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>GIRK <span class="op">=</span> GIRKDataSample()</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>pl_u <span class="op">=</span> Universe(GIRK.coordinates, GIRK.trajectory)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This sample data consist of the last 5 us of a 40-us-long Martini simulation of the GIRK system described in the <a href="#introduction">introduction</a>. For purposes of keeping the dataset light enough for the tutorial, snapshots were saved every 4 nanoseconds so that we had a total of only 1250 frames in our trajectory:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Trajectory data for GIRK starting at </span><span class="sc">{</span>pl_u<span class="sc">.</span>trajectory[<span class="dv">0</span>]<span class="sc">.</span>time<span class="op">/</span><span class="dv">1000000</span><span class="sc">:.0f}</span><span class="ss"> us and ending at </span><span class="sc">{</span>pl_u<span class="sc">.</span>trajectory[<span class="op">-</span><span class="dv">1</span>]<span class="sc">.</span>time<span class="op">/</span><span class="dv">1000000</span><span class="sc">:.0f}</span><span class="ss"> us, sampled every </span><span class="sc">{</span>pl_u<span class="sc">.</span>trajectory<span class="sc">.</span>dt<span class="op">/</span><span class="dv">1000</span><span class="sc">:.0f}</span><span class="ss"> ns."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="output"><code>Trajectory data for GIRK starting at 35 us and ending at 40 us, sampled every 4 ns.</code></pre>
<p>When the system was loaded, <code>Prolint2</code> automatically identified the protein and lipid components in the system, which can be accessed as:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>pl_u.query, pl_u.database</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="output"><code>(&lt;ProLint Wrapper for &lt;AtomGroup with 2956 atoms&gt;&gt;,
 &lt;ProLint Wrapper for &lt;AtomGroup with 20864 atoms&gt;&gt;)</code></pre>
<p>Notice how both the <code>query</code> and <code>database</code> are ProLint wrappers around the <code>MDAnalysis</code> AtomGroups. This means that you get to keep all the functionalities of <code>MDAnalysis</code> AtomGroups, but you can also use additional <code>ProLint2</code>-specific functions, such as making changes to the <code>query</code> and <code>database</code> AtomGroups or accessing information to simplify the exploration of the system composition, as follows:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Membrane lipid composition is </span><span class="sc">{</span><span class="bu">dict</span>(pl_u.database.resname_counts)<span class="sc">}</span><span class="ss">."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="output"><code>Membrane lipid composition is {'POPE': 652, 'POPS': 652, 'CHOL': 652}.</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"First five residues of the protein are: </span><span class="sc">{</span>pl_u<span class="sc">.</span>query<span class="sc">.</span>get_resnames([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>], out<span class="op">=</span><span class="bu">dict</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="output"><code>First five residues of the protein are: {1: 'ARG', 2: 'GLN', 3: 'ARG', 4: 'TYR', 5: 'MET'}</code></pre>
<section id="modifying-the-query-and-database-atomgroups" class="level4">
<h4 class="anchored" data-anchor-id="modifying-the-query-and-database-atomgroups">Modifying the query and database AtomGroups</h4>
<hr>
<p><code>ProLint2</code>’s automation for identifying protein and lipid components in the system relies entirely on residue names. For the query group (proteins), it automatically detects all standard and modified amino acids using the same criteria as in <code>MDAnalysis.Universe.select_atoms("protein")</code>. For the database group (membrane), it identifies lipid molecules based on their residue names, provided these names are part of a list of the most common lipid types defined by default in the <code>ProLint2</code> configuration. However, if your system uses different residue names or if you wish to focus your analysis on specific residues, you can easily adjust the query and database groups accordingly.</p>
<p>To add a custom lipid type to the database group, you can use the <code>add()</code> method and reassign the database group as follows:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>pl_u.database <span class="op">=</span> pl_u.database.add(<span class="st">"LIPX"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>This will add the LIPX lipid type to the database group. Please notice we are using the residue name “LIPX” here as an example of a custom lipid type, but you can use any residue name that is relevant to your system. As LIPX is not part of the GIRK system, it will not add anything in this case. This can be checked by running <code>pl_u.database.resname_counts</code> again.</p>
</div>
</div>
<p>To remove a residue from the query group, you can use the <code>remove()</code> method and reassign the query group as follows:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>pl_u.query <span class="op">=</span> pl_u.query.remove(<span class="st">"ARG"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of arginine residues: </span><span class="sc">{</span>pl_u<span class="sc">.</span>query<span class="sc">.</span>resname_counts[<span class="st">'ARG'</span>]<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="output"><code>Number of arginine residues: 0</code></pre>
<p>To add the ARG residues back to the query group in this case, we can use the <code>add()</code> method:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>pl_u.query <span class="op">=</span> pl_u.query.add(<span class="st">"ARG"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of arginine residues: </span><span class="sc">{</span>pl_u<span class="sc">.</span>query<span class="sc">.</span>resname_counts[<span class="st">'ARG'</span>]<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="output"><code>Number of arginine residues: 64</code></pre>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Given the efficiency of ProLint2 for contacts calculations even in large systems, it is not recommended to remove residues from either the query or database groups unless you have a specific reason to do so. Focusing on certain residues can be done later in the analysis, when you are ready to explore specific interactions.</p>
</div>
</div>
</section>
<section id="prolint2s-units-and-normalizers" class="level4">
<h4 class="anchored" data-anchor-id="prolint2s-units-and-normalizers">ProLint2’s units and normalizers</h4>
<hr>
<p>ProLint2 offers a set of time units and normalizers to facilitate the interpretation of the results. There parameters can be set at the Universe level, as follows:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>pl_u.params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="output"><code>{'units': 'us',
 'normalizer': 'time_fraction',
 'unit_conversion_factor': 1e-06,
 'norm_factor': 0.0008}</code></pre>
<p>Here is a list of each parameter and its meaning:</p>
<ul>
<li><code>units</code>: this is the time unit we want to display the results in.</li>
<li><code>normalizer</code>: this is how we want to normalize the results. <code>ProLint2</code> supports three types of normalization:
<ul>
<li><code>counts</code>: Display the raw counts (i.e., count of frame numbers)</li>
<li><code>actual_time</code>: Normalize by the true simulation -&gt; (dt/unit_conversion_factor)</li>
<li><code>time_fraction</code>: normalize by the total time of the simulation and divide by the total time of the simulation (i.e., numbers represent fractions of time spent in contact)</li>
</ul></li>
<li><code>unit_conversion_factor</code>: this is the conversion factor to convert the raw counts to the desired unit.</li>
<li><code>norm_factor</code>: this is the normalization factor that is updated based on the normalization type. For example, if the normalization type is <code>time_fraction</code>, then this factor is <code>dt / totaltime</code>.</li>
</ul>
<p>These parameters can be modified by setting the <code>Universe.units</code> and <code>Universe.normalizer</code> attributes, as follows:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>pl_u.units <span class="op">=</span> <span class="st">"ns"</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>pl_u.params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="output"><code>{'units': 'ns',
 'normalizer': 'time_fraction',
 'unit_conversion_factor': 0.001,
 'norm_factor': 0.0008
}</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>pl_u.normalize_by <span class="op">=</span> <span class="st">"actual_time"</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>pl_u.params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="output"><code>{'units': 'ns',
 'normalizer': 'actual_time',
 'unit_conversion_factor': 0.001,
 'norm_factor': 4.0
}</code></pre>
</section>
</section>
<section id="contact-based-metrics" class="level3">
<h3 class="anchored" data-anchor-id="contact-based-metrics">Contact-based metrics</h3>
<hr>
<p>Computing the contacts is the cornerstone in the <code>ProLint2</code> workflow, as it provides the basis for all subsequent analyses. To create a Contacts instance, you can use the <code>compute_contacts()</code> method included in the Universe. You can define any distance cutoff for defining contacts, otherwise it will use 7 Angstroms by default. Here is how to create a Contacts instance for the GIRK system:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>pl_c <span class="op">=</span> pl_u.compute_contacts(cutoff<span class="op">=</span><span class="fl">7.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Contacts information is stored in two main attributes: <code>pl_c.contacts</code> and <code>pl_c.contact_frames</code>, with structures: <code>{Query_ResID: {Database_ResType: [Contact_Windows]}}</code> and <code>{Query_ResID: {Database_ResID: [Frame_Numbers]}}</code> respectively. The contact windows are defined as the time intervals in which a contact is established between a lipid and a protein residue, while the frame numbers are the corresponding frame numbers in the trajectory. The output of these attributes is shown below for demonstration purposes, but <code>ProLint2</code> is designed to help you explore this information in a more user-friendly way, as we will see in the next sections.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>pl_c.contacts[<span class="dv">14</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="output"><code>defaultdict(list,
            {'POPE': [np.float64(4.0),
              np.float64(4.0),
              np.float64(8.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(8.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(8.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(4.0),
              np.float64(8.0),
...
              np.float64(8.0),
              np.float64(4.0),
              np.float64(16.0),
              np.float64(4.0),
              np.float64(4.0)]})</code></pre>
<p>The output above can be interpreted as follows: for residue 14, there are several contact windows with POPE lipids, each lasting 4 ns, 4 ns, 8 ns, and so on. In contrast, it has only two contact windows with POPS lipids, both lasting 4 ns (equivalent to 1 frame in the trajectory). This information is provided for all protein residues in the system that have at least one contact with any lipid type.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>pl_c.contact_frames[<span class="dv">14</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre class="output"><code>defaultdict(list,
            {np.int64(2527): [0,
              15,
              20,
              21,
              25,
              35,
              38,
              47,
              49,
              65,
              197,
              246,
              251,
              291,
              323],
             np.int64(2760): [0, 2],
             np.int64(2800): [2, 7, 8, 13, 18, 20, 21, 22, 24, 27, 33, 57],
             np.int64(2506): [10, 11],
             np.int64(2888): [11,
              13,
              15,
              19,
              353,
              355,
...
              1240,
              1241],
             np.int64(2776): [1228, 1244],
             np.int64(2347): [1236],
             np.int64(2480): [1239, 1240, 1250]})</code></pre>
<p>The output above can be understood as follows: protein residue 14 interacts with lipid residue 2527 in frames 0, 15, 20, and so on; it only interacts with lipid residue 2760 in frames 0 and 2, and with lipid residue 2800 in frames 2, 7, 8, and so forth. This information is provided for all protein residues in the system that have at least one contact with any lipid molecule. While ProLint2 facilitates easy exploration of this data, you can always access the raw data in these attributes if you wish to conduct any other type of analysis.</p>
<p>We will now proceed to the next step in the ProLint2 workflow, which involves creating metrics based on the contacts we have just computed. Metrics serve as a means to quantify the various interaction patterns between lipids and protein residues within the system. Given the highly dynamic nature of lipids, these interactions can be transient, depending on the affinity, meaning they can be quickly established and replaced by another lipid molecule, or persistent, indicating they can last for an extended period. Additionally, the specificity of the interaction can be high, meaning it is established with a specific lipid type, or low, meaning it can occur with any lipid type. ProLint2 offers a set of default metrics:</p>
<ul>
<li><strong>MaxMetric</strong>: This metric finds the longest contact window between each residue and each lipid type. If this metric is high for a certain residue-lipid_type combination, that interaction is likely to have high affinity.</li>
<li><strong>MeanMetric</strong>: This metric calculates the average duration of contact windows between each residue and each lipid type. If this metric is high for a certain residue-lipid_type combination, that interaction is likely to be of high affinity and can be considered specific or not depending on the total fraction of time the contact is maintained.</li>
<li><strong>SumMetric</strong>: This metric counts the sum over all the contact windows between each residue and each lipid type. The interpretation of this metric can only be done in the context of the membrane lipid composition, as the more representative the lipid type is in the system, the more likely it is that the interaction happens by chance. For example, if a residue has a high SumMetric with a lipid type that is very abundant in the system, it is likely that the interaction is not specific, but rather a consequence of the high concentration of that lipid type in the system. On the other hand, if a residue has a high SumMetric with a lipid type that is not abundant in the system, it is likely that the interaction is specific. In addition, the SumMetric results can be contaminated by the fact that more than one lipid of the same type can be in contact with the same residue simultaneously, which can lead to values that are higher than the total simulation length.</li>
</ul>
<p>To use the default metrics, you can use the <code>compute_metrics()</code> method included in the Contacts objects:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prolint2.metrics.metrics <span class="im">import</span> Metric, MeanMetric, SumMetric, MaxMetric</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>metric_instances_list <span class="op">=</span> [MeanMetric(), SumMetric(), MaxMetric()]</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>metric_instance <span class="op">=</span> Metric(pl_c, metric_instances_list) </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>contacts_out <span class="op">=</span> metric_instance.compute() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="visualization" class="level3">
<h3 class="anchored" data-anchor-id="visualization">Visualization</h3>
<hr>
<p>Prolint2 provides a set of Plotters to visualize results of lipid-protein interactions at different levels of detail:</p>
<p><img src="fig3.png" class="img-fluid"></p>
<p>We recommend using the Plotters in a systematic way, starting with exploratory Plotters to identify relevant lipid types and metrics, followed by a detailed examination of specific interactions. This approach optimizes the analysis workflow and ensures a thorough exploration of the local lipid environment.</p>
<section id="exploratory-point-distribution-plotter" class="level4">
<h4 class="anchored" data-anchor-id="exploratory-point-distribution-plotter">Exploratory Point Distribution Plotter</h4>
<hr>
<div class="sourceCode" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prolint2.plotting.multiples <span class="im">import</span> MultiplePointDistribution</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>MPD <span class="op">=</span> MultiplePointDistribution(pl_u, contacts_out)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>MPD.create_plot()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig4.png" class="img-fluid figure-img"></p>
<figcaption>Exploratory Point Distribution Plot: Columns show the different lipid types, and the rows represent different metrics. On each individual plot x-axis represents the protein residues and the y-axis represents the metric values.</figcaption>
</figure>
</div>
<p>The peaks displayed in the plot above highlight the regions of the protein that are directly exposed to the membrane, while the areas between the peaks represent fragments of the protein forming the internal core. This analysis revealed that interactions with POPE appear to be less relevant, as the metric values are lower than those of other lipids with similar representativeness in the system. On the other hand, it shows specific interactions with CHOL and POPS that merit further exploration, corresponding to the notably high MeanMetric values observed for certain residues. For this tutorial, we have decided to use normalized lipid density profiles and logo plots to analyze the interactions with POPS lipids.</p>
</section>
<section id="normalized-lipid-density-plotter" class="level4">
<h4 class="anchored" data-anchor-id="normalized-lipid-density-plotter">Normalized Lipid Density Plotter</h4>
<hr>
<div class="sourceCode" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prolint2.plotting <span class="im">import</span> DensityMap</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>Dens <span class="op">=</span> DensityMap(pl_u, fig_size<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">6</span>))</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>Dens.create_plot(lipid_type<span class="op">=</span><span class="st">'POPS'</span>, interpolation<span class="op">=</span><span class="st">'nearest'</span>, cmap<span class="op">=</span><span class="st">'viridis'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="fig5.png" class="img-fluid"></p>
</section>
<section id="sequence-logo-plotter" class="level4">
<h4 class="anchored" data-anchor-id="sequence-logo-plotter">Sequence Logo Plotter</h4>
<hr>
<div class="sourceCode" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prolint2.plotting <span class="im">import</span> LogoResidues</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>LR <span class="op">=</span> LogoResidues(pl_u, contacts_out)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>LR.create_plot(lipid_type<span class="op">=</span><span class="st">'POPS'</span>, metric_name<span class="op">=</span><span class="st">'MeanMetric'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="fig6.png" class="img-fluid"></p>
<p>From this, we can identify three residues with high MeanMetric values with POPS: Val354, Lys461, and Lys467. The figure below illustrates that these residues are closely situated within the protein structure, forming a potential binding site for POPS.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig7.jpeg" class="img-fluid figure-img"></p>
<figcaption>Surface representation of the GIRK protein. In red are Lys361 and Lys367, and in blue is Val354. Picture generated through VMD.</figcaption>
</figure>
</div>
<p>The specificity of this interaction is anticipated due to the positively charged lysine side chain, which can engage in electrostatic interactions with the negatively charged headgroup of POPS. To further investigate this interaction, we can use an Interaction Heatmap Plotter to visualize the contact pattern at the atom-atom level of detail. For these analyses, we must first identify the POPS molecule that most frequently interacts with one of these residues, let’s choose Lys461. We can get this information by using the get_lipid_contact_durations() function, which provides a dataframe listing the lipid molecule IDs sorted by their total contact frequencies.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prolint2.plotting.utils <span class="im">import</span> get_lipid_contact_durations</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>get_lipid_contact_durations(pl_u, pl_c, <span class="st">'POPS'</span>, residue_id<span class="op">=</span><span class="dv">461</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="fig8.png" class="img-fluid"></p>
</section>
<section id="interaction-heatmap-plotter" class="level4">
<h4 class="anchored" data-anchor-id="interaction-heatmap-plotter">Interaction Heatmap Plotter</h4>
<hr>
<p>From this, we can identify a POPS molecule with ID 2329 that exhibits the highest contact frequency with residue 461. With this information, we can now create an Interaction Heatmap Plotter, as follows:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prolint2.plotting <span class="im">import</span> InteractionHeatMap</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>IHM <span class="op">=</span> InteractionHeatMap(pl_u, pl_c)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>IHM.create_plot(residue_id<span class="op">=</span><span class="dv">461</span>, lipid_id<span class="op">=</span><span class="dv">2622</span>, palette<span class="op">=</span><span class="st">'Reds'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="fig9.png" class="img-fluid"></p>
<p>As expected, the interaction occurs mostly between the headgroup of POPS and the positively charged second bead of the lysine side chain. To look deeper at the evolution of this specific interaction as a function of time, we can use the TwoPointDistanceEvolution Plotter:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prolint2.plotting <span class="im">import</span> TwoPointDistanceEvolution</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>TPD <span class="op">=</span> TwoPointDistanceEvolution(pl_u)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>TPD.create_plot(lipid_id <span class="op">=</span> <span class="dv">2622</span>, lipid_atomname<span class="op">=</span><span class="st">'PO4'</span>, residue_id <span class="op">=</span> <span class="dv">461</span>, residue_atomname<span class="op">=</span><span class="st">'SC2'</span>, unit <span class="op">=</span> <span class="st">'frame'</span>, smooth_line <span class="op">=</span> <span class="va">True</span>, n_points <span class="op">=</span> <span class="dv">250</span>, useOffset <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="fig10.png" class="img-fluid"></p>
<p>This plots confirms the expected short distance (below the 7-Angstrom cutoff) between the phosphate bead of POPS 2622 and the second bead of the side chain of Lys461 throughout the entire simulation.</p>
</section>
</section>
<section id="advanced-applications" class="level3">
<h3 class="anchored" data-anchor-id="advanced-applications">Advanced applications</h3>
<hr>
<p>For more advanced application, please refer to the following sources:</p>
<ul>
<li>Zhekova, H. R., Echemendía, D. P. R., Sejdiu, B. I., Pushkin, A., Tieleman, D. P., &amp; Kurtz, I. (2024). Molecular dynamics simulations of lipid-protein interactions in SLC4 proteins. Biophysical Journal, 123(12), 1705–1721. https://doi.org/10.1016/j.bpj.2024.05.013</li>
<li>Cino, E. A., Ramirez-Echemendia, D. P., Hu, S., &amp; Tieleman, D. P. (2024). Analyzing lipid distributions and curvature in molecular dynamics simulations of complex membranes. In Methods in Enzymology. Academic Press. https://doi.org/10.1016/bs.mie.2024.03.014</li>
</ul>
</section>
<section id="conclusions" class="level3">
<h3 class="anchored" data-anchor-id="conclusions">Conclusions</h3>
<hr>
<p>In this tutorial, we have showcased the capabilities of <code>ProLint2</code> for the analysis and visualization of lipid-protein interactions using as example a Martini simulation of the GIRK system. We have seen how to create a <code>ProLint2</code> Universe, compute contacts, and analyze lipid-protein interactions using different metrics and levels of detail. The goal is to provide you with the basis for you to start exploring lipid-protein interactions in your own systems, using the incredible versatility of <code>ProLint2</code>. Please do not hesitate to reach out to the authors if you have any questions or suggestions for improvements.</p>
</section>
<section id="tools-and-scripts-used-in-this-tutorial" class="level3">
<h3 class="anchored" data-anchor-id="tools-and-scripts-used-in-this-tutorial">Tools and scripts used in this tutorial</h3>
<hr>
<p>The source code is available here: <a href="https://github.com/ProLint/prolint2">https://github.com/ProLint/prolint2</a>. The documentation is available here: <a href="https://prolint2.readthedocs.io/en/latest/">https://prolint2.readthedocs.io/en/latest/</a>.</p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<hr>
<p>[1] Besian I Sejdiu, D Peter Tieleman, ProLint: a web-based framework for the automated data analysis and visualization of lipid–protein interactions, Nucleic Acids Research, Volume 49, Issue W1, 2 July 2021, Pages W544–W550, https://doi.org/10.1093/nar/gkab409</p>
<p>[2] Ramirez-Echemendia, Daniel P., et al.&nbsp;“ProLint v. 2: An Optimized Tool for the Analysis and Visualization of Lipid-Protein Interactions.” Biophysical Journal, vol.&nbsp;123, no. 3, 2024, p.&nbsp;372a.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/cgmartini\.nl");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<div class="footer-left">

</div>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/cg_martini">
      <i class="bi bi-twitter" role="img" aria-label="Martini Twitter">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../../docs/faq/index.html">
<p><iconify-icon inline="true" role="img" icon="hugeicons:help-circle" style="font-size: 1.25em;" aria-label="FAQs" title="FAQs"></iconify-icon></p>
</a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Martini-Force-Field-Initiative">
      <i class="bi bi-github" role="img" aria-label="Martini GitHub">
</i> 
    </a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
<div class="footer-right">
© 2025 Martini Force Field Initiative <img src="https://cgmartini-library.s3.ca-central-1.amazonaws.com/icon.png" alt="Icon">
</div>
</div>
  </div>
</footer>
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
      const quotes = [
          "<i>Shaken, not stirred.</i> - James Bond",
          "<i>He was white and shaken, like a dry martini.</i> - P. G. Wodehouse",      
          "<i>I think people think we're all sipping martinis by the pool.</i> - Maria Menounos",
          "<i>Why don't you get out of that wet coat and into a dry martini?</i> - Robert Benchley",
          "<i>Really, can anyone drink several martinis at lunch?</i> - Christine Baranski",
          "<i>Zen martini: A martini with no vermouth at all. And no gin, either.</i> - P.J. O'Rourke",
          "<i>I never go jogging, it makes me spill my martini.</i> - George Burns",
          "<i>Martinis are the only American invention as perfect as a sonnet.</i> - H. L. Mencken",
          "<i>He knows just how I like my martini: full of alcohol.</i> - Homer Simpson",
          "<i>Happiness is: finding olives in your martini when you're hungry.</i> - Johnny Carson",
          "<i>If it wasn't for the olives in his martinis he'd starve to death.</i> - Milton Berle",
        ];
      const randomIndex = Math.floor(Math.random() * quotes.length);
      const randomQuote = quotes[randomIndex];

      const footerLeft = document.querySelector('.footer-left');
      if (footerLeft) {
          footerLeft.innerHTML = randomQuote;
      }
    });
</script>
<script src="../../../../js/sidebar-close.js"></script> 




</body></html>