---
title: "The effect of aliphatic alcohols on fluid bilayers in unilamellar DOPC vesicles — A small-angle neutron scattering and molecular dynamics study"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "M. Klacsová, M. Bulacu, N. Kučerka, D. Uhríková, J. Teixeira, S.J. Marrink, and P. Balgavý"         # Paper authors (required)
year: "2011"           # Publication year (required)
publication: "Biochimica et Biophysica Acta (BBA)-Biomembranes"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bbamem.2011.04.010"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Small molecules
  - Phopholipids
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Klacsová, M., Bulacu, M., Kučerka, N., Uhríková, D., Teixeira, J., Marrink, S. J., & Balgavý, P. (2011). The effect of aliphatic alcohols on fluid bilayers in unilamellar DOPC vesicles—A small-angle neutron scattering and molecular dynamics study. Biochimica et Biophysica Acta (BBA)-Biomembranes, 1808(9), 2136-2146.

## Abstract

Small-angle neutron scattering and coarse-grained molecular dynamics simulations have been used to determine the structural parameters (bilayer thickness D, polar region thickness DH, interfacial lateral area of the unit cell AUC and alcohol partial interfacial area ACnOH) of fluid dioleoylphosphatidylcholine:dioleoylphosphatidylserine (PCPS, DOPC:DOPS = 24.7 mol:mol) bilayers in extruded unilamellar vesicles with incorporated aliphatic alcohols (CnOH, n = 8–18 is the even number of carbons in alkyl chain). External 2H2O/H2O contrast variation experiments revealed that DH decreases as a function of alkyl chain length and CnOH:PCPS molar ratio. Using measurements at single 100% 2H2O contrast we found that (i) D decreases with CnOH:PCPS molar ratio and increases with CnOH chain length (at 0.4 molar ratio); (ii) AUC significantly increases already in the presence of shortest CnOH studied (at 0.4 molar ratio), further increase is observed with longer CnOHs and at higher molar ratios; (iii) ACnOH of alcohol molecules in PCPS bilayer increases linearly with the alkyl chain length, ACnOH obtained for CnOHs with n ≤ 10 corresponds to ACnOH ≤ 20Å2 — a value specific for the crystalline or solid rotator phase of alkanes. All these structural modifications induced by studied CnOHs were reproduced in MD simulations. The computational results give an accurate description of the alcohol effects at the molecular level, explaining the experimental data. The anomaly in ACnOH is discussed via the “umbrella” effect described for cholesterol.