---
title: "Lipid Acrobatics in the Membrane Fusion Arena"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Albert J. Markvoort, and Siewert J. Marrink"         # Paper authors (required)
year: "2011"           # Publication year (required)
publication: "Current Topics in Membranes"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/B978-0-12-385891-7.00011-8"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Review
  - Lipid membranes
  - Vesicles
  - Micelles
  - Proteins
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Markvoort, A. J., & Marrink, S. J. (2011). Lipid acrobatics in the membrane fusion arena. Current Topics in Membranes, 68, 259-294.

## Abstract

This chapter describes the recent contribution of computer simulation approaches to unravel the molecular details of membrane fusion. Over the past decade, fusion between apposed membranes and vesicles has been studied using a large variety of simulation methods and systems. Despite the variety in techniques, some generic fusion pathways emerge that predict a more complex picture beyond the traditional stalk–pore pathway. Indeed the traditional pathway is confirmed in particle-based simulations, but, in addition, alternative pathways are observed in which stalks expand linearly rather than radially, leading to inverted-micellar or asymmetric hemifusion intermediates. The fusion and fission of membranes is an essential process in cell biophysics, occurring during exo- and endocytosis, intracellular trafficking and enveloped virus infection. Membrane fusion is also important in a range of biomedical applications, such as in gene or drug delivery. A wide range of regulatory protein complexes exists in vivo. Because of the wide variety and complexity of fusion protein arrays, the molecular picture of protein-mediated fusion and fission is largely unclear.