---
title: "Low density lipoprotein: structure, dynamics, and interactions of apoB-100 with lipids"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Teemu Murtola, Timo A. Vuorela, Marja T. Hyvönen, Siewert-Jan Marrink, Mikko Karttunenf and Ilpo Vattulainen"         # Paper authors (required)
year: "2011"           # Publication year (required)
publication: "Soft Matter"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1039/C1SM05367A"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Lipid membranes
  - Sterols
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Murtola, T., Vuorela, T. A., Hyvönen, M. T., Marrink, S. J., Karttunen, M., & Vattulainen, I. (2011). Low density lipoprotein: structure, dynamics, and interactions of apoB-100 with lipids. Soft Matter, 7(18), 8135-8141.

## Abstract

Low-density lipoprotein (LDL) transports cholesterol in the bloodstream and plays an important role in the development of cardiovascular diseases, in particular atherosclerosis. Despite its importance to health, the structure of LDL is not known in detail. This is worrying since the lack of LDL's structural information makes it more difficult to understand its function. In this work, we have combined experimental and theoretical data to construct LDL models comprised of the apoB-100 protein wrapped around a lipid droplet of about 20 nm in size. The models are considered by near-atomistic multi-microsecond simulations to unravel structural as well as dynamical properties of LDL, with particular attention paid to lipids and their interactions with the protein. We find that the distribution and the ordering of the lipids in the LDL particle are rather complex. The previously proposed 2- and 3-layer models turn out to be inadequate to describe the properties of the lipid droplet. At the surface of LDL, apoB-100 is found to interact favorably with cholesterol and its esters. The interactions of apoB-100 with core molecules, in particular cholesteryl esters, are rather frequent and arise from hydrophobic amino acids interacting with the ring of cholesteryl esters, and also in part from the rather loose packing of lipids at the surface of the lipoparticle. The loose packing may foster the function of transfer proteins, which transport lipids between lipoproteins. Finally, the comparison of the several apoB-100 models in our study suggests that the properties of lipids in LDL are rather insensitive to the conformation of apoB-100. Altogether, the findings pave the way for further studies of LDL to better understand the central steps in the emergence of atherosclerosis.