---
title: "Protein Shape Change Has a Major Effect on the Gating Energy of a Mechanosensitive Channel"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "O.H. Samuli Ollila, Martti Louhivuori, Siewert J. Marrink, and Ilpo Vattulainen"         # Paper authors (required)
year: "2011"           # Publication year (required)
publication: "Biophysical journal"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1016/j.bpj.2011.02.027"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Phopholipids
  - Lipid membranes
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Ollila, O. S., Louhivuori, M., Marrink, S. J., & Vattulainen, I. (2011). Protein shape change has a major effect on the gating energy of a mechanosensitive channel. Biophysical journal, 100(7), 1651-1659.

## Abstract

Increasing experimental evidence has shown that membrane protein functionality depends on molecular composition of cell membranes. However, the origin of this dependence is not fully understood. It is reasonable to assume that specific lipid-protein interactions are important, yet more generic effects due to mechanical properties of lipid bilayers likely play a significant role too. Previously it has been demonstrated using models for elastic properties of membranes and lateral pressure profiles of lipid bilayers that the mechanical properties of a lipid bilayer can contribute as much as ∼10 kBT to the free energy difference associated with a change in protein conformational state. Here, we extend those previous approaches to a more realistic model for a large mechanosensitive channel (MscL). We use molecular dynamics together with the MARTINI model to simulate the open and closed states of MscL embedded in a DOPC bilayer. We introduce a procedure to calculate the mechanical energy change in the channel gating using a three-dimensional pressure distribution inside a membrane, computed from the molecular dynamics simulations. We decompose the mechanical energy to terms associated with area dilation and shape contribution. Our results highlight that the lateral pressure profile of a lipid bilayer together with the shape change in gating can induce a contribution of ∼30 kBT on the gating energy of MscL. This contribution arises largely from the interfacial tension between hydrophobic and hydrophilic regions in a lipid bilayer.