---
title: "Lipid packing drives the segregation of transmembrane helices into disordered lipid domains in model membranes"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Lars V. Schäfer, Djurre H. de Jong, Andrea Holt, Andrzej J. Rzepiela, Alex H. de Vries, Bert Poolman, J. Antoinette Killian, and Siewert J. Marrink"         # Paper authors (required)
year: "2011"           # Publication year (required)
publication: "Proceedings of the National Academy of Sciences"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1073/pnas.1009362108"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Lipid membranes
  - Proteins
  - Enhanced sampling
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Schäfer, L. V., de Jong, D. H., Holt, A., Rzepiela, A. J., de Vries, A. H., Poolman, B., ... & Marrink, S. J. (2011). Lipid packing drives the segregation of transmembrane helices into disordered lipid domains in model membranes. Proceedings of the National Academy of Sciences, 108(4), 1343-1348.

## Abstract

Cell membranes are comprised of multicomponent lipid and protein mixtures that exhibit a complex partitioning behavior. Regions of structural and compositional heterogeneity play a major role in the sorting and self-assembly of proteins, and their clustering into higher-order oligomers. Here, we use computer simulations and optical microscopy to study the sorting of transmembrane helices into the liquid-disordered domains of phase-separated model membranes, irrespective of peptide–lipid hydrophobic mismatch. Free energy calculations show that the enthalpic contribution due to the packing of the lipids drives the lateral sorting of the helices. Hydrophobic mismatch regulates the clustering into either small dynamic or large static aggregates. These results reveal important molecular driving forces for the lateral organization and self-assembly of transmembrane helices in heterogeneous model membranes, with implications for the formation of functional protein complexes in real cells.