---
title: "Protofibrillar Assembly Toward the Formation of Amyloid Fibrils"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Jesper Sørensen, Xavier Periole, Katrine K. Skeby, Siewert-J. Marrink, and Birgit Schiøtt"         # Paper authors (required)
year: "2011"           # Publication year (required)
publication: "The Journal of Physical Chemistry Letters"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/jz2010094"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Proteins
  - Self-assembly
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Sørensen, J., Periole, X., Skeby, K. K., Marrink, S. J., & Schiøtt, B. (2011). Protofibrillar assembly toward the formation of amyloid fibrils. The Journal of Physical Chemistry Letters, 2(19), 2385-2390.

## Abstract

The formation and growth of amyloid fibrils was investigated using coarse-grained molecular dynamics simulations. In particular, we studied the assembly of amylin(20–29) peptides, preassembled into protofibril fragments. The systems consisted of 27 protofibril fragments initially distributed onto a regular cubic grid with random orientation. Their association was followed on the μs time scale. At 300 K, it was observed that, while the assemblies formed are mainly disordered, there was an apparent preference for the fragments to associate such that an elongation of the structures predominates over their lateral extension. Increasing the temperature in the simulations resulted in an increase of the contact surfaces and allowed for rearrangement within the prefibrillar aggregates over longer time scales. The preferential elongation-like growth mechanism observed at 300 K was not persistent at higher temperatures indicative of a shift in growth pathway, congruent with experimental observations that changing growth conditions alters the morphology of the fibrils.