---
title: "Sphere-to-Rod Transitions of Nonionic Surfactant Micelles in Aqueous Solution Modeled by Molecular Dynamics Simulations"          # Paper title (required)
type: "article"    # do not change
sidebar: false     # do not change
toc: false         # do not change
author: "Maria Velinova, Durba Sengupta, Alia V. Tadjer, and Siewert-Jan Marrink"         # Paper authors (required)
year: "2011"           # Publication year (required)
publication: "Langmuir"    # Journal or similar (required)
preprint: ""       # URL to prepint page (optional)  
doi: "https://doi.org/10.1021/la203055t"            # URL of DOI (required)  
materials: ""      # URL to suplementary info (optional)
categories:        # (required) these keywords will create tags for further filtering. 
  - Journal article
  - Micelles
  - Drug design
  - Self-assembly
  - Parametrization
---

<!-- 
The info below is just an example. 

Both fields are required and they have to be replaced with the respective info for each paper. 

Please notice the `> ` symbol before the citation, it gives it additional styling.  
-->

## Citation (APA 7)      

> Velinova, M., Sengupta, D., Tadjer, A. V., & Marrink, S. J. (2011). Sphere-to-rod transitions of nonionic surfactant micelles in aqueous solution modeled by molecular dynamics simulations. Langmuir, 27(23), 14071-14077.

## Abstract

Control of the size and agglomeration of micellar systems is important for pharmaceutical applications such as drug delivery. Although shape-related transitions in surfactant solutions are studied experimentally, their molecular mechanisms are still not well understood. In this study, we use coarse-grained molecular dynamics simulations to describe micellar assemblies of pentaethylene glycol monododecyl ether (C12E5) in aqueous solution at different concentrations. The obtained size and aggregation numbers of the aggregates formed are in very good agreement with the available experimental data. Importantly, increase of the concentration leads to a second critical micelle concentration where a transition to rod-like aggregates is observed. This transition is quantified in terms of shape anisotropy, together with a detailed structural analysis of the micelles as a function of aggregation number.